### ISSUE TITLE
bug: Migrating gamedb to MySQL fails

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#1010]
**Describe the bug**
The migration was failing a lot, and I'm not sure how to describe it, I just know that when I looked at the database in mysql, it was empty, I'm going to paste all the prints and important things I said in discord, I'm reporting why they asked since it needs pr to correction

**Version Encountered**
0.7.0.126

**To Reproduce**
1 - starting clean game
![image](https://user-images.githubusercontent.com/63019821/139666522-991c68f2-ec03-4970-baff-017e3d42d83e.png)
2 - making 2 db on mysql
![image](https://user-images.githubusercontent.com/63019821/139666564-1935c2c8-fc4f-4e20-a85d-eb02b8ff1c68.png)
3 - Migrating
![image](https://user-images.githubusercontent.com/63019821/139666591-ecf1b0c9-70c0-4a86-b27a-56ee31f24d4b.png)
4 - See error
![image](https://user-images.githubusercontent.com/63019821/139666623-e603e4dd-33b6-47a1-a09d-a09f0d24e6af.png)

**Expected behavior**
Migrate

**Screenshots**
**Logs**
2021-10-30 16:54:20.852 [Error] GAMEDB: 20102 - Failed executing DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
ALTER TABLE Items ADD CooldownGroup longtext NOT NULL DEFAULT '';

**Operating System:**
Windows, Mac, Or Linux

**Additional context**
Sometimes doesn't give any error
![image](https://user-images.githubusercontent.com/63019821/139666747-48818512-d81e-4ab1-8cd9-cfc27dc074ad.png)
But config is not changed
![image](https://user-images.githubusercontent.com/63019821/139666782-03e75068-e8a9-4d98-a944-cc65e6c031cd.png)
and data is not copied although all tables are created
![image](https://user-images.githubusercontent.com/63019821/139666927-2bf2caf2-f7a4-47f6-b7f1-6aedc5c77a2c.png)

**Comment by Arufonsu** [comment]
> 2021-10-30 16:54:20.852 [Error] GAMEDB: 20102 - Failed executing DbCommand (2ms) [Parameters=[], CommandType='Text', CommandTimeout='30']
> ALTER TABLE Items ADD CooldownGroup longtext NOT NULL DEFAULT '';

This is from the game db, which is not recommended to be migrate to mysql. The current workaround is to migrate the game db to MariaDB, but this isn't a solution to the issue itself.

Not sure if this is intended either (do we need a default value here?), but in order to fix this issue, we have to change the migration file where CooldownGroup is added to the game database, by removing it's default values, a good example on how could we fix this can be seen here: #708 

Regards ~
