### ISSUE TITLE
Guild Sync variables

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#1012]
**Is your feature request related to a problem? Please describe.**
We can synchronize the variable of everyone who is in the party, the same could happen for everyone who is in the same guild.

**Describe the solution you'd like**
Var sync for everyone who is in the same guild.

**Additional context**
Nice feature!

**Comment by Arufonsu** [comment]
sync what?
guild members? where to? what for?
there's already a way to retrieve guild members, and it's actually always updated when u call it, i've tested this myself when working with the overhead information settings PR.

**Comment by Cheshire92** [comment]
I would say an easier and better solution would be JCs proposed changes for guild variables.

https://github.com/AscensionGameDev/Intersect-Engine/pull/777

**Comment by WeylonSantana** [comment]
> I would say an easier and better solution would be JCs proposed changes for guild variables.
> 
> #777

I thought guild variables would be something private, a guy made a post on the forum one day asking for help to pay and whoever helped would have the source too, I didn't think it would go to the official

**Comment by jcsnider** [comment]
Someone funded the work, but it was always meant to be public. It just hasn't been tested very well yet.

**Comment by WeylonSantana** [comment]
> Someone funded the work, but it was always meant to be public. It just hasn't been tested very well yet.

If it is for the public, will it serve as a solution to this issue? If yes, I can close

**Comment by jcsnider** [comment]
Yes
