### ISSUE TITLE
Musics of the map, stopts when sound starts

### ISSUE THREAD

**Issue by ThousandX** [AscensionGameDev/Intersect-Engine#102]
**Describe the bug**
It seems to me that the sound of the interface or even in the spells or any other sound from the client, conflicts with the songs

**Version Encountered**
0.6.2.402 (Last DEV pull)

**To Reproduce**
Enter the city where the music plays, use some magic with sound or hover over the game interface

**Screenshots**
[Video Link](http://www.theceltos.com.br/Client.exe 2020.04.06 - 16.16.56.10.mp4)
**Operating System:**
Windows 10 PRO

**Comment by BrunoWrier** [comment]
me to, if i teleport to a map, the song just stop forever

**Comment by jcsnider** [comment]
Resolution depends on #116
