### ISSUE TITLE
Players cannot select Target when admin hidden nearby.

### ISSUE THREAD

**Issue by dudevelopement** [AscensionGameDev/Intersect-Engine#1025]
**Describe the bug**
Some players have reported to me, that when I'm close to hiding, they can't select any targets on the screen.

**Version Encountered**
0.7.0

**To Reproduce**
1 - Create an event that hides your /de character for example.
2 - Go up close to a player on a map, in case it was tested on a map with Active PvP.
3 - See the player trying to select target, without success. you can do this with 2 accounts.

**Expected behavior**
The player could focus on the targets that are visible without any problem.

**Screenshots**
No sorry

**Logs**
No

**Operating System:**
Windows

**Additional context**
Sorry for my English, I used the translator.

**Comment by Cheshire92** [comment]
I believe this was fixed in the development branch, but the change hasn't been moved to prerelease yet.

**Comment by dudevelopement** [comment]
Oh sorry, I tried to apply your change in the version I have, but I noticed that the en.IsHidden function doesn't exist, so I couldn't apply it to test if it was really resolved.

Thanks

**Comment by Arufonsu** [comment]
Closing this since #900 should have solved this already. 
Don't worry for now, as these changes from the dev branch will eventually reach out the prerelease builds.
