### ISSUE TITLE
Monster acts strange after leaving hiding skill

### ISSUE THREAD

**Issue by dudevelopement** [AscensionGameDev/Intersect-Engine#1027]
**Describe the bug**
After making a monster that casts a spell that makes it invisible (Stealth) when the spell's effect wears off, the monster stays still like a fool.

**Version Encountered**
0.7.0

**To Reproduce**
1 - Creates any monster.
2 - Create a spell that will leave you in hidden mode.
3 - Make the monster use this spell.
4 - Wait for the monster to become visible again.
5 - See the dumbass stopped

**Expected behavior**
I didn't get to see if the monster attacks you in stealth mode, but when it comes out of invisibility it doesn't attack you, it just stands still, until you kill it.
My expectation is that he would return to attacking you normally.

**Screenshots**

**Logs**
If there are error logs please attach them below.

**Operating System:**
Windows

**Additional context**

**Comment by WeylonSantana** [comment]
Unable to reproduce, a monster that uses invisibility continues its normal behavior

returns to spawn location when player flees (if configured)
continues (or returns) aggression if the player returns
continues to attack
continues to move randomly

I will close, if you want to reopen, send a video reproducing this bug in a clean version of the intersect
