### ISSUE TITLE
[GWEN] Sounds played through the Gwen pipeline (clickedsound, hoversound, etc) get prematurely Garbage Collected

### ISSUE THREAD

**Issue by AlexVild** [AscensionGameDev/Intersect-Engine#1031]
**Describe the bug**
The interface JSON files allow a user to sometimes attach sounds to UI events, such as clicking a button. However, playing these sounds is bugged - a user who changes a sound to something of sufficient length may realize that their sound is getting cutoff before the sound is finished.

The THEORY:
This is because when a sound is played through Gwen (through `Control/Base.cs`), we do not hold any sort of reference to the sound instance we create. As a result, the .NET GC cleans up this sound instance before the sound is actually finished playing, which triggers the Destructor of a MonogameSoundInstance to fire; prematurely disposing the Mono SoundEffectInstance.

**Version Encountered**

Prerelease - 0.7

**To Reproduce**
1. Replace some UI sound (clickedsound on a button, for example) with some much longer .wav
2. Continually click the button in-client, and you will notice the sound getting cutoff at random intervals.

**Expected behavior**
A sound that is placed on a UI element should play to completion, non-looping.

**Operating System:**
Windows

**Comment by Arufonsu** [comment]
This short video previews how to reproduce the current issue:
Sounds that are placed on a UI element don't always fully play to completion.

https://user-images.githubusercontent.com/17498701/153782590-9f54a6b5-3076-4655-addb-248c80e43e59.mp4
