### ISSUE TITLE
Map Sounds do not take server tile size in to account

### ISSUE THREAD

**Issue by AlexVild** [AscensionGameDev/Intersect-Engine#1036]
**Describe the bug**
You can change tile size via the server config. For the most part, the rest of the engine handles this change properly - however, map sounds (both the attribute, and sounds played via animations) do NOT - they always assume a tile size of 32x32.

**Version Encountered**

**To Reproduce**
1. Place a map sound attribute somewhere in your world, and set the tile range to some number.
2. Stand on the outer range of that number in-client, and you'll very faintly hear the map sound
3. Change tile size to 64x64 in server config json, and reboot the server.
4. The sound will no longer be audible in-client

**Expected behavior**
Sound distance should be calculated based on how many tiles away something is, and tiles have dynamic sizes, so the calculation needs to be dynamic.

**Comment by Cheshire92** [comment]
Issue comes from this place: https://github.com/AscensionGameDev/Intersect-Engine/blob/2a1d2fc0b1056ba816bf49fd3b5c2d9985f832c8/Intersect.Client/Core/Sounds/MapSound.cs#L133

There's two 16s in there which should be tile width and height / 2.
And a single 32f which should probably be (float)Math.Max(Width, Height)

**Comment by lodicolo** [comment]
Merged PR
