### ISSUE TITLE
bug: map editor scroll bars issue when tile size is bigger than default

### ISSUE THREAD

**Issue by AlexVild** [AscensionGameDev/Intersect-Engine#1037]
**Describe the bug**
The map editor has vertical and horizontal scroll bars on either side of it that allow a user without a mousewheel to scroll around a map while editing.

The maximum scroll distances of these scroll bars is not big enough, however, to allow a user to scroll an entire map when a user has modified their default tile size to be anything bigger than the default of 32x32

**Version Encountered**

Prerelease 7.0+

**To Reproduce**
1. Make a full-size map in the map editor
2. Change tile size in server config json to something bigger than 32x32
3. Upon reboot, you will notice the scroll bars do not allow for scrolling the whole map. The middle mouse button or WASD keys must be use instead.

**Expected behavior**
I should always be able to use the scroll bars of the map editor to navigate a map.

**Screenshots**
![example](https://user-images.githubusercontent.com/8580915/148252663-858e9cc3-23cc-44c5-a5fc-2ab32df672f3.png)

Here you can see that I am fully scrolled as far as the bars allow me - but I have not yet reached the map boundary.

**Comment by lodicolo** [comment]
With the WinForms editor deprecated this is probably never getting fixed so I am closing this.

If someone actually decides to fix this, feel free to re-open this once you open a PR.
