### ISSUE TITLE
Add a Auction House System

### ISSUE THREAD

**Issue by Shadowcoffee** [AscensionGameDev/Intersect-Engine#1042]
The engine already has a trading system, but its very small and both players have to be online. A auction system could make it that a game could run a global economy very quickly and it can be used to make a economy based MMO which is one of the most common feature in many MMO games.

The player should be able to config the auction house on and off. There should be a event that can open up the auction house. The player can blacklist and whitelist what can be sold and set a global economy.

**Additional context**

**Comment by Cheshire92** [comment]
I don't believe this will ever happen, the implementation is fairly game dependant and it's a very expensive feature to create and maintain for future versions.

I reckon this will have to be relegated to plugins once those are mature enough.

**Comment by Shadowcoffee** [comment]
Ok!

**Comment by Arufonsu** [comment]
This is a very complex and specific game feature request (i've personally played very few MMOs with economies around auction systems, so i can't really say with confidence that this is a very "common" thing in MMOs), in the other hand, is not a bad idea, but like ches says, is probably not a good moment for such a feature right now.

Closing this for now, may be re-opened if this topic is ever touched again.
