### ISSUE TITLE
bug: location picker does not work with non-32x32 tile sizes

### ISSUE THREAD

**Issue by AlexVild** [AscensionGameDev/Intersect-Engine#1053]
**Describe the bug**
When constructing an event command that leverages the "On/Around location" editor, the editor does not handle mouse clicks correctly. It seems to misplace where the mouse input is coming from.

**Version Encountered**

B7

**To Reproduce**
1. Create a "Spawn NPC" event
2. Choose "On/Around entity"
3. Try to click a square in the corresponding UI. You will see it does not line up with where your mouse is.

**Expected behavior**
When I click on a square in the UI, I want it to respond properly to my mouse position.

**Screenshots**
![image](https://user-images.githubusercontent.com/8580915/151401058-6a5e8944-679a-4544-af7e-c85ccdd8ca20.png)

**Operating System:**
Windows

**Comment by Meddy13** [comment]
If your sprites are not 32 x 32 this creates a bug

**Comment by Meddy13** [comment]
If your boxes are not 32x32 this creates a bug

**Comment by WeylonSantana** [comment]
I don't think I understand this, whenever I click it selects the right square, be it here
![image](https://user-images.githubusercontent.com/63019821/174691846-55fdd903-e870-468e-87f8-b8423b58e420.png)
or here
![image](https://user-images.githubusercontent.com/63019821/174691881-9e331ced-2c99-436f-9171-574df59aa704.png)

**Comment by Arufonsu** [comment]
![imagen](https://user-images.githubusercontent.com/17498701/177059125-958445f1-8a17-48d2-96fc-18abd9c85977.png)
verified issue👍🏽
