### ISSUE TITLE
bug: Editor's Tile Preview does not properly update when deleting NPC Spawns

### ISSUE THREAD

**Issue by AlexVild** [AscensionGameDev/Intersect-Engine#1054]
**Describe the bug**
When removing NPCs with declared spawns, the map preview in the editor will not update the spawn locations if one of those spawns is deleted, unless you update the tile preview.

**Version Encountered**

B7

**To Reproduce**
1. Create an NPC Spawn on some map in the editor with a declared spawn
2. Delete your new NPC Spawn - but leave your mouse in the layer editor
3. Move the mouse to the tile preview, and you'll _then_ see the spawn icon disappear.

**Expected behavior**
When I remove an NPC with a declared spawn, I want to see that spawn icon disappear from the map preview.

**Operating System:**
Windows

**Comment by Arufonsu** [comment]
I've managed to reproduce this issue 👍🏽

**Comment by lodicolo** [comment]
Fixed in 0.7.1.20
