### ISSUE TITLE
feature: ability to highlight selected NPC spawns

### ISSUE THREAD

**Issue by AlexVild** [AscensionGameDev/Intersect-Engine#1055]
**Is your feature request related to a problem? Please describe.**
When dealing with a map in which you have multiple declared NPC Spawns, it is difficult to tell which one you have selected if you want to modify it's properties/position.

**Describe the solution you'd like**
Change the "spawnicon.png" render color if you have selected the NPC Spawn that corresponds with the map preview's displaying of the icon.

**Comment by lodicolo** [comment]
This should be a tooltip like the attribute tooltip feature I implemented in #1397

**Comment by WeylonSantana** [comment]
This should have for the lights too

**Comment by Arufonsu** [comment]
> This should be a tooltip like the attribute tooltip feature I implemented in #1397

would something similar to that could happen as you select NPCs from the list? 🤔
