### ISSUE TITLE
Moderators can Ban Administrators

### ISSUE THREAD

**Issue by AlexVild** [AscensionGameDev/Intersect-Engine#1061]
**Describe the bug**
Moderators can ban admins. This seems like a flaw in design.

**Version Encountered**

0.7.x

**To Reproduce**
1. Be a moderator
2. Select an admin and ban them

**Expected behavior**
A moderator should be told "You don't have permission to do that" or something

**Comment by WeylonSantana** [comment]
was there for years and no one ever noticed lol
