### ISSUE TITLE
Pulling items out of the bank invalidates the inventory stack limit in favor of the bank stack limit

### ISSUE THREAD

**Issue by AlexVild** [AscensionGameDev/Intersect-Engine#1062]
**Describe the bug**
If some item has a different bank stack limit than its inventory stack limit, a player can withdraw an amount > the inventory stack limit from the bank, and the stack in their inventory will reflect that of the bank's limit - allowing players to have more of an item than allowed in their inventory.

This does not appear to work if the item has an inventory stack limit of 1 - then it seems to function okay.

**Version Encountered**

0.7.x

**To Reproduce**
1. Create an item, with a bank stack limit of 10,000 and an inventory limit of 1,000
2. Place 10,000 of the item in your bank, so that the bank contains a stack of 10,000
3.  Withdraw 10,000 of this item.
4. You will now have a stack of 10,000 in your inventory.

**Expected behavior**
On withdraw, we should have:
1. Checked to see how many slots are required for 10,000 of the item. In this case, 10
2. Checked to see if the player had the space for such a withdraw.
3. If so, give them 10 stacks of 1,000 each.
4. Else, tell them they can not perform this action.

**Comment by Arufonsu** [comment]
just reproduced this issue, i can confirm that this is currently happening, since the required slots and stacks aren't properly checked, if not at all 👍🏽
