### ISSUE TITLE
Picking up a stackable item with a full inventory containg a full stack of the item and a not-full stack will not put the item in the inventory

### ISSUE THREAD

**Issue by AlexVild** [AscensionGameDev/Intersect-Engine#1063]
**Describe the bug**
The "Inventory is Full" message fires prematurely, at first failure to place in stack.

**Version Encountered**

0.7.x

**To Reproduce**
1. Get a full stack of some item, say 100 arrows.
2. Get another stack of the same item, but leave room for more. Say, 10 arrows.
3. Fill up your inventory
4. Find a MapItem of the same type as the stackable item, and go to loot it
5. You will get a message complaining your inventory is full
6. Swap the positions of the full stack and the non-full stack, so that the non-full stack comes before
7. You will now be able to pick up the item

**Expected behavior**
When we pick up a stackable item, we should exhaust ALL possible stacks before determining the inventory is full.

**Screenshots**
![image](https://user-images.githubusercontent.com/8580915/153014360-db6806e6-d8da-4f61-b4df-083fd7a12b0f.png)

Note the inventory - i have a full stack (beyond full, but that's a separate issue) of arrows, and another non-full stack, but I can't pick up the stack on the map (see chat log)

**Comment by Arufonsu** [comment]
Just reproduced this issue 👍🏽 it is indeed not trying with all possible stacks before determining that the inventory "is full".

https://user-images.githubusercontent.com/17498701/153777717-7fea6b22-b75e-406a-a11f-ca9530117eee.mp4

https://user-images.githubusercontent.com/17498701/153777719-42fabd60-e0a1-4e90-9b4f-ff9d69fefb66.mp4
