### ISSUE TITLE
Assigning Stat Points is based on your stat points with gear equipped, not your base stats.

### ISSUE THREAD

**Issue by AlexVild** [AscensionGameDev/Intersect-Engine#1064]
**Describe the bug**
When you level and have points to spend, you are assigning points based on your _calculated_ stats, with gear, and not your base stats.

This allows you to either:
- Equip gear that lowers a stat, then pump points into that stat to get PAST stat limits
- Equip gear that raises a stat, and not be allowed to put points into some stat until you unequip the gear.

**Version Encountered**

0.7x

**To Reproduce**
1. Equip some equipment that raises your stats to the limit or beyond
2. Level up
3. Try to assign points to the stat - you will not be able to
4. Unequip the gear
5. You can now assign the points

**Expected behavior**
Spending points should be based on your _base_ stats, not your calculated stats.

**Comment by Arufonsu** [comment]
Just gave it a try with a clean dev branch build and i couldn't _fully_ reproduce this.
buut, there is indeed a visual glitch/behavior that should be corrected, the + button shouldn't show up if we equip something and we already reached the maximum possible base stat, somehow, equipping items will allow this to happen, but i couldn't make it for the + button to actually raise the base stat past it's own limit, hopefully someone else around can try to reproduce this and collaborate on this one (i'm probably missing something?)

**Comment by AlexVild** [comment]
This was a problem in my fork - I foolishly never tested to see if it was in Dev
