### ISSUE TITLE
Damage over Times are not actually unique to the caster

### ISSUE THREAD

**Issue by AlexVild** [AscensionGameDev/Intersect-Engine#1065]
**Describe the bug**
Damage over times have strange behavior where they can be applied multiple times, stacking the _effect_ rather than the duration.

**Version Encountered**

0.7.x

**To Reproduce**
1. Create a projectile with a big animation, that causes a DoT. Make it move slowly and cover a wide array of space
2. Log in as another player, and have the original player cast this DoT. As this player, move around in the spawned projectiles
3. You will have these DoT stack tremendously.

**Expected behavior**
DoTs when acquired from an attacker who has already placed a DoT should NOT cause the DoT to deal a new set of damage - rather, it should just reset the DoTs timer. Effectively, it should clear the old DoT, and create a new one, for each attacking entitythat has triggered a DoT on some affected entity.

**Screenshots**
You can see this happen here:
https://www.youtube.com/watch?v=V1SAyvcjPUM

**Additional context**
I think this is the offending code (from the end of `Entity#TryAttackSpell`):

```cs
if (spellBase.Combat.HoTDoT)
{
    var doTFound = false;
    foreach (var dot in target.CachedDots)
    {
        if (dot.SpellBase.Id == spellBase.Id && dot.Target == this)
        {
            doTFound = true;
        }
    }

    if (doTFound == false) //no duplicate DoT/HoT spells.
    {
        new DoT(this, spellBase.Id, target);
    }
}
```

Most suspiciously, note that we check that the _TARGET_ is equivalent to `this` (the attacking entity. I believe that that line should read:

```cs
if (dot.SpellBase.Id == spellBase.Id && dot.Attacker == this)
```

**Comment by Arufonsu** [comment]
#1078 solved this issue 👍🏽
