### ISSUE TITLE
Stats rollback

### ISSUE THREAD

**Issue by xXEsiXx** [AscensionGameDev/Intersect-Engine#1070]
**Describe the bug**
The defense stats are getting reset after adding a big amount of stats points to it, and the used up stat point are lost. This problem has happened 2 or 3 times out of the blue, which is making it hard to reproduce.

**Version Encountered**
Version 0.1.0.126 prerelease 

**To Reproduce**
1. Go to character info
2. Click on the plusses for putting points in the defense
3. After putting a lot on the defense stats there may be a chance that the stats will be reset back to 12 and the stats that were used will be lost forever

**Expected behavior**
The stats were supposed to stay put in the defense and to not reset 

**Screenshots**
![image](https://user-images.githubusercontent.com/99421317/153459645-93302ae2-daad-4fde-8c87-f08fd7418cc5.png)

**Logs**
No errors

**Operating System:**
Windows

**Additional context**

**Comment by dudevelopement** [comment]
Same here

**Comment by WeylonSantana** [comment]
![image](https://user-images.githubusercontent.com/63019821/174692051-71727c38-26be-43ca-b9b3-61cf040ec658.png)
I can't reproduce, I added 200 points manually in defense, and it didn't return

The way to reproduce may not be correct, could you give more details or record this on video?

**Comment by Arufonsu** [comment]
Same, i've been unable to reproduce this one, like @WeylonSantana pointed out, more info on how to exactly reproduce this may be required. If anyone happens to have more accurate steps on how to reproduce this, feel free to comment this out and we will see what we can do by re-opening the issue.
