### ISSUE TITLE
Step Forward/Backwards Not Working

### ISSUE THREAD

**Issue by jessidion** [AscensionGameDev/Intersect-Engine#1087]
**Describe the bug**
Step Forward/Backwards move routes simply do not work and will hold the player in place indefinitely instead.

**Version Encountered**
0.7.0.129

**To Reproduce**
1. Make an event with a move route
2: The Move Route must be "step backwards or step forward"
3: Your character will be held like a "hold player" and won't step back/forward at all

**Expected behavior**
Step forward/backward

**Screenshots**

**Logs**
If there are error logs please attach them below.

**Operating System:**
Windows 10

**Additional context**
Similar post was made last year on this..: https://www.ascensiongamedev.com/topic/6196-step-backwardforward-command-for-player-not-working/?do=findComment&comment=52622

**Comment by AlexVild** [comment]
Can confirm this bug

**Comment by Cheshire92** [comment]
Fixed the merge of #1099 in development.
Will eventually trickle down to prerelease, if you need it right now I suggest basing your build off of development.
