### ISSUE TITLE
Effects And Durations Not Showing

### ISSUE THREAD

**Issue by jessidion** [AscensionGameDev/Intersect-Engine#1092]
**Describe the bug**
Basically the effects do not show under the spell's description window.

**Version Encountered**

0.7.0.129

**To Reproduce**
1. Make a spell
2. Give it a stat buff effect
3. Make it last awhile
4. See issue

**Expected behavior**
Show which stats are being buffed/debuffed and by how much.

**Screenshots**
https://www.ascensiongamedev.com/resources/filehost/c0dd232a400be8edd003d11e4e4872fa.jpg

**Logs**
If there are error logs please attach them below.

**Operating System:**
Windows 10

**Additional context**
Same issue mentioned in these:
https://github.com/AscensionGameDev/Intersect-Engine/issues/520
https://github.com/AscensionGameDev/Intersect-Engine/issues/550

**Comment by Arufonsu** [comment]
> 
> **Additional context** Same issue mentioned in these: 520 550

Your said it yourself:
This issue is a duplicate since the lack of info for spells on tooltips has already been mentioned on the original reports. 
Please avoid opening duplicate reports, closing this one now.

**Comment by jessidion** [comment]
The original reports are Closed. Asking to confirm it has been fixed. It’s still having the issue. Closing this will make the issue not addressed.
