### ISSUE TITLE
msbuild error of current development branch (IntersectBuildingAssemblyFile == empty)

### ISSUE THREAD

**Issue by char32** [AscensionGameDev/Intersect-Engine#1122]
**Describe the bug**
The current development branch does not build with msbuild (linux version of Microsofts msbuild, if that matters) because the IntersectBuildingAssemblyFile is empty in the Intersect.Network project.
I made a git bisect and up to commit 3d77407c134d5d06615e87b2f037e3ffdf41fc21 everything is fine. Starting with that commit the error occurs.

**Version Encountered**
SHA1: 3d77407c134d5d06615e87b2f037e3ffdf41fc21 or later on branch development

**To Reproduce**
git clean -xfd
nuget restore
msbuild Intersect.sln

**Expected behavior**
Build should pass

**Logs**
"/home/char32/Intersect-Engine/Intersect.sln" (default target) (1) ->
"/home/char32/Intersect-Engine/Intersect.Server/Intersect.Server.csproj" (default target) (8) ->
"/home/char32/Intersect-Engine/Intersect.Server.Framework/Intersect.Server.Framework.csproj" (default target) (9:2) ->
(CoreCompile target) -> 
  Plugins/Helpers/IServerLifecycleHelper.cs(9,22): warning CA1040: Avoid empty interfaces [/home/char32/Intersect-Engine/Intersect.Server.Framework/Intersect.Server.Framework.csproj]

"/home/char32/Intersect-Engine/Intersect.sln" (default target) (1) ->
"/home/char32/Intersect-Engine/Intersect.Client/Intersect.Client.csproj" (default target) (4) ->
"/home/char32/Intersect-Engine/Intersect.Network/Intersect.Network.csproj" (default target) (6:2) ->
(GenerateNetworkKeys target) -> 
  /home/char32/Intersect-Engine/targets/Intersect.Building.KeyGeneration.msbuild(10,62): error MSB4022: The result "" of evaluating the value "$(IntersectBuildingAssemblyFile)" of the "AssemblyFile" attribute in element <UsingTask> is not valid. [/home/char32/Intersect-Engine/Intersect.Network/Intersect.Network.csproj]
  /home/char32/Intersect-Engine/targets/Intersect.Building.KeyGeneration.msbuild(10,62): error MSB4022: The result "" of evaluating the value "$(IntersectBuildingAssemblyFile)" of the "AssemblyFile" attribute in element <UsingTask> is not valid. [/home/char32/Intersect-Engine/Intersect.Network/Intersect.Network.csproj]
  /home/char32/Intersect-Engine/Intersect.Network/Intersect.Network.csproj(48,5): error MSB3073: The command "msbuild ../targets/Intersect.Building.KeyGeneration.msbuild /property:KeySize=4096 /property:GenerateEachBuild= /property:OutputDirectory= /property:IntersectBuildingAssemblyFile=" exited with code 1.

    2154 Warning(s)
    3 Error(s)

**Operating System:**
Linux + mono + msbuild

**Additional context**
It seems that Intersect.Network cannot see the definition of IntersectBuildingAssemblyFile in Directory.build.props.
But I am not sure if an include there is the right way.

**Comment by lodicolo** [comment]
@char32 Case-sensitive file names :)

**Comment by char32** [comment]
@lodicolo Ooh ... did not see that :-) Thanks for the fix! Branch development builds fine again on mono/msbuild
