### ISSUE TITLE
bug: Player Light will sometimes flicker to black for a frame

### ISSUE THREAD

**Issue by AlexVild** [AscensionGameDev/Intersect-Engine#1152]
**Describe the bug**
The player's light will sometimes flicker to black, causing a horrid flashing effect if in a dark room.

**Version Encountered**

Development

**To Reproduce**
1. Create a indoor space with a light value of 0
2. Make the player's light have an intensity of 255
3. In the client, do stuff in the room. Seems to happen to me most often while attacking.
4. Your player light will occasionally flicker.

**Expected behavior**

**Screenshots**
[Here is a video of the bug in action](https://www.ascensiongamedev.com/resources/filehost/804cd7fa6a4c114eb8157b3337235b14.mp4)

And here's a screenshot of what a bad frame looks like:
![image](https://user-images.githubusercontent.com/8580915/160258347-ddcce8e7-a891-4b87-8969-0b8081c8fb7c.png)

**Logs**
If there are error logs please attach them below.

**Operating System:**
Windows, Mac, Or Linux

**Additional context**
This bug is caused by our light intensity value sometimes being calculated as something greater than 255.0, which, since this value is essentially an alpha, causes an overflow issue that effectively sets the light texture's alpha back to 0.

**Comment by Arufonsu** [comment]
ohh nice ! 👍🏽
