### ISSUE TITLE
Authors.md updates

### ISSUE THREAD

**Issue by lodicolo** [AscensionGameDev/Intersect-Engine#1158]
@jburditt @Magehernan @AisenGaming @RedBandana @celojevic 

All of you need to add yourselves how you would prefer to be listed to AUTHORS.md in the `main-authors-md` branch under "Contributors" in alphabetical order please.

Sorry it took this long to discover you all weren't listed.

**Comment by RedBandana** [comment]
Job done @lodicolo, thanks I was not expecting this 👍
Keep up the great job with Intersect 👏👏

**Comment by helenatodev** [comment]
Im Back! Nice work

**Comment by Arufonsu** [comment]
@WeylonSantana  ~

**Comment by lodicolo** [comment]
Due to lack of responses I did the best I could to add everyone when moving 0.7.1-beta to the `main` branch.
