### ISSUE TITLE
feature: Add a Check Slot Condition

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#1189]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to check if the slot is equipped with an item.

**Describe the solution you'd like**
Add condition that checks if slot has item equipped, regardless of item, inside the menu check if the item is equipped

**Additional context**

**Comment by Arufonsu** [comment]
do you mean to add this check as a feature for the event editor?

**Comment by WeylonSantana** [comment]
Yeah
