### ISSUE TITLE
bug: inventory display does not refresh when items are dropped

### ISSUE THREAD

**Issue by goulcode** [AscensionGameDev/Intersect-Engine#1192]
**Found bug**
When you drop any items from inventory, it does not disappear. When you reopen the client, the item that had been dropped leaves inventory.

Often the client crashes in different moments.

(I uploaded an video to youtube showing the bugs)

**Version:** 0.7.1.1-beta-prerelease (v0.7.1.1) - Latest Prerelease Build! (Nightly)

**To Reproduce**
1. Pick up any item in inventory
2. Right click on it
3. Choose "Drop item"
4. The item still in inventory

**Expected behavior**
The item will still in inventory, and client probably crash at any time.

**Vídeo**
[Youtube Vídeo](https://youtu.be/1lcdVBpkqZ8) (I uploaded video as unlisted)

**Logs**
errors-Intersect Client: https://www.ascensiongamedev.com/resources/filehost/fe99f0a20ab5223e06b5ca7940264999.log
Intersect Client-2022_04_06-15_57_51_486: https://www.ascensiongamedev.com/resources/filehost/d5723110dd0f09efb69568b0a82fd260.log

**Operating System:**
Windows 11

**Comment by lodicolo** [comment]
The crash is unrelated to the inventory display bug, opening a separate bug.
