### ISSUE TITLE
bug: Change player item with variable method

### ISSUE THREAD

**Issue by Gorgaki** [AscensionGameDev/Intersect-Engine#1202]
**Describe the bug**
In event in Change player item with variable method does not save the variable global (not test with others).
When I return to the event the selected variable is the first player variable.

**Version Encountered**
v0.7.1.2

**To Reproduce**
1. Go to event
2. Click on Change player item 
3. Take item with variable method

**Screenshots**
![image](https://user-images.githubusercontent.com/83343437/162676489-1deccba3-4f34-4b0a-891e-7abe42c58793.png)

**Operating System:**
Windows

**Comment by WeylonSantana** [comment]
Delivering items with variable value is not working.
@Arufonsu can you confirm for me?
