### ISSUE TITLE
bug: can't properly click/hover on quest and crafting lists.

### ISSUE THREAD

**Issue by dudevelopement** [AscensionGameDev/Intersect-Engine#1207]
**Describe the bug**
I noticed that in the BETA version 0.7.1.3 the quest and crafting system seems to be impossible to click on the name of the quest or craft in order to actually work the mission.

**Version Encountered**
0.7.1.3

**To Reproduce**
- Open the quest menu / Craft item list.
- Try clicking / hovering on the quest name / craftable item.
- See the error. (The highlight will not show up, and you cannot click into the quest when hovering on the name's font).

**Screenshots**
![b31f4b9ebbc0e0e2d199923621ae42bf](https://user-images.githubusercontent.com/64770171/169928434-e9170900-2e93-4d03-a1ed-8e6b440bbb8d.gif)

**Expected behavior**
- As you hover over the quest name's font or craft item name's font, we should be able to click on them and properly see the hovering effect taking place. 

**Operating System:**
Windows

**Comment by Uyarrr** [comment]
I have same issue as well.

**Comment by Arufonsu** [comment]
managed to reproduce it, so i can confirm that this is indeed happening.
cleaned up a bit the format of this issue report and changed the title so it's more accurate to the issue itself.

**Comment by Arufonsu** [comment]
managed to reproduce it, so i can confirm that this is indeed happening.
cleaned up a bit the format of this issue report and changed the title so it's more accurate to the issue itself.

also, just to clarify, the .gif used in this report is a contribution made by [Gokwol](https://github.com/Gokwol) in the duplicated report #1265  👍🏽
