### ISSUE TITLE
Projectile Spawn Delay

### ISSUE THREAD

**Issue by RecoStar** [AscensionGameDev/Intersect-Engine#121]
**Describe the bug**
Projectiles "Spawn Delay" does not seem to be working. Whatever value is put into field the animation spawns straight away. Tested on a modified version of source and a vanilia development build.

**Version Encountered**
Version: 0.6.2.408

**To Reproduce**
1. Create a new project and apply spawn delay
2. Use projectile in game
3. Modify projectile spawn delay - Nothing happens

**Expected behavior**
A delay before animation of projectile is spawn onscreen.

**Screenshots**
None

**Logs**
None

**Operating System:**
Windows 10

**Additional context**

**Comment by jcsnider** [comment]
Hey @RecoStar 

So spawn delay only applies when your projectile is setup to fire multiple waves:
![projectiles](https://www.ascensiongamedev.com/resources/filehost/80fb76818f56197a045452e24b3d3ebd.png)

It seems to be working as intended in 0.6.2.408:
![spawndelay](https://www.ascensiongamedev.com/resources/filehost/44e85a6907d6bbe42bf2f418b0487c50.gif)


If it's not working like that for you can you please share a screenshot of your projectile config and a gif or video of how it's acting like I have above?

Thanks!

**Comment by RecoStar** [comment]
Ah right, didnt know that sorry. Tested and works as intended. Thanks JC
