### ISSUE TITLE
bug: Entity Inspector Flickering/Not Opening

### ISSUE THREAD

**Issue by TheBearWannabe** [AscensionGameDev/Intersect-Engine#1221]
**Describe the bug**
When clicking on an event with an event inspector text, the window flickers and does not appear correctly.

**Version Encountered**
Intersect Engine 0.7.1.5-beta-prerelease

**To Reproduce**
1. Create a new event, add a sprite, and navigate to "Entity Inspector Options"
2. Under Entity Inspector Options, un-check "Disable Inspector" and add some sort of text to the description box. Save event.
3. Launch game and click on event
4. Inspector will flicker and disappear, and the event is unable to be targeted. 

**Expected behavior**
Normally, if the Disable Inspector box is un-checked the player can click on the event and display whatever text that had been added, along with displaying an image (if there was one added as well) 

**Logs**
No error logs

**Operating System:**
Win 11

**Additional context**
I'm hoping this isn't something unique to my own game files, but I have re-added fresh JSON files just in case it was something on my side.

**Comment by lodicolo** [comment]
Can you please record this behavior?

**Comment by Arufonsu** [comment]
just managed to reproduce this (v0.7.1.8-beta-prerelease)

https://user-images.githubusercontent.com/17498701/164945003-d06eb886-6e8f-404c-afe8-820fcf163edd.mp4
