### ISSUE TITLE
bug: Events have 0 Level on their name

### ISSUE THREAD

**Issue by Uyarrr** [AscensionGameDev/Intersect-Engine#1231]
**Describe the bug**
Events have 0 Level on their name
**Version Encountered**
v0.7.1.9

**To Reproduce**
1. Enable "ShowLevelByName": true  for NPC's from server config.
2. Place an event to the map.
3. Enter to the client, check it's name.

**Expected behavior**
It should not show any level like npcs for events.

**Screenshots**
![image](https://user-images.githubusercontent.com/63975845/165822576-460b1139-5bcf-4aab-a0db-9f36d5a703fa.png)

**Comment by lodicolo** [comment]
Will be in 0.7.1.11
