### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by Uyarrr** [AscensionGameDev/Intersect-Engine#1232]
**Describe the bug**

**Version Encountered**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
If there are error logs please attach them below.

**Operating System:**
Windows, Mac, Or Linux

**Additional context**

**Comment by Arufonsu** [comment]
this shouldn't be closed as completed, so i'm closing it down as not planned due to lack of information.
