### ISSUE TITLE
bug: idle,cast,weapon,shoot not changing spritesheet anymore as intended. No change to player or paperdoll

### ISSUE THREAD

**Issue by Kaziie** [AscensionGameDev/Intersect-Engine#1235]
**Describe the bug**
idle,cast,weapon,shoot not changing spritesheet anymore like it used to.  I just upgraded from 7.10 or something, to prerelease version 7.1.9 and my character uses his normal sprite sheet just fine, but it doesn't display the correct spritesheets for each individual actions anymore as far as shoot,cast,weapon and idle (i dont use idle frames but i assumes its affected as well). Casting makes my player stand still, while attacking and shooting use the normal sprite sheet as it would if there was no _idle,_weapon, etc, present. 
Before i upgraded it all worked as intended.

**Version Encountered**
7.1.9

**To Reproduce**
Use any character with paperdoll elements that are assigned sprite sheets for  shoot,cast,weapon, and or idle character animation. It will not work as intended.

**Expected behavior**
Using _idle.png,_weapon.png, etc, at the end of alternate image files will select them for the animation used if the name before the _ is the same. It has worked well in previous versions but doesn't seem to now. 

**Screenshots**

**Logs**
If there are error logs please attach them below.

**Operating System:**
Windows, Mac, Or Linux

**Additional context**

**Comment by lodicolo** [comment]
Fixed in 0.7.1.13
