### ISSUE TITLE
feature: "No NPCs of Type X On Map" condition

### ISSUE THREAD

**Issue by AlexVild** [AscensionGameDev/Intersect-Engine#1240]
**Is your feature request related to a problem? Please describe.**
A simple addition that could be used to mix-up encounters is extending the "No NPCs On Map" condition, by adding a new condition called "No NPCs Of Type On Map". This would allow you to create a boss that, say, could not be attacked unless its minions were dealt with.

**Describe the solution you'd like**
A new condition, "No NPCs of Type On Map", that allows you to select an NPC and, if none of that NPC exist on the map the event is being ran on, returns true.

**Comment by lodicolo** [comment]
Fixed in 0.7.1.13
