### ISSUE TITLE
feature: Second Type of Block for Map Editor to Block Players while not Block Projectiles

### ISSUE THREAD

**Issue by Uyarrr** [AscensionGameDev/Intersect-Engine#1251]
**Is your feature request related to a problem? Please describe.**
If you have a detailed map with lots of blocks around for such as small rocks, projectiles are useless. Because you don't want projectiles to bypass walls but you want them to bypass small objects. You can think it like barricades.

**Describe the solution you'd like**
Second type of block that allows projectiles bypass while players cannot. So developers can put that kind of block to single height blocks such as small rocks etc. It will make projectile system much more useful.

**Comment by Arufonsu** [comment]
This issue has already been mentioned at #990
Altho the proposed solution is not exactly the same one.
@AlexVild  / @Cheshire92  any thoughs ?
