### ISSUE TITLE
Music Looping 2secs...

### ISSUE THREAD

**Issue by ThousandX** [AscensionGameDev/Intersect-Engine#126]
**Describe the bug**
The music both in the city and even in the main menu, is looping for about 2 seconds.

**Version Encountered**
0.6.2.0 (Last DEV Pull with New MOno)

**To Reproduce**
Idk, maybe playing the game and will bug sometime

**Expected behavior**
No musica looping :(

**Operating System:**
Windows 10

**Comment by ThousandX** [comment]
Video 

https://drive.google.com/file/d/1cu41nV1V771w2oyjwt6nv5dQXpYbotP3/view?usp=sharing

**Comment by jcsnider** [comment]
#126 will fix this...
