### ISSUE TITLE
bug: Client Crash When i die

### ISSUE THREAD

**Issue by dudevelopement** [AscensionGameDev/Intersect-Engine#1260]
**Describe the bug**
My game crashes when I'm killed by an npc, it doesn't always happen.

Version Encountered
0.7.1.16

**To Reproduce**
1. Target on any monster
2. Teleport to other map.

**Logs**
`2022-05-20 18:22:42.913 [Error] NullReferenceException: Referência de objeto não definida para uma instância de um objeto.
    Stack:    em Intersect.Client.Entities.Player.Update()
   em Intersect.Client.Core.Main.ProcessGame()
   em Intersect.Client.Core.Main.Update(TimeSpan deltaTime)
   em Intersect.Client.MonoGame.IntersectGame.Update(GameTime gameTime)
   em Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   em Microsoft.Xna.Framework.Game.Tick()
   em Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   em Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   em Intersect.Client.MonoGame.IntersectGame.MonoGameRunner.Start(IClientContext context, Action postStartupAction)
   em Intersect.Client.Core.ClientContext.InternalStart()
   em Intersect.Core.ApplicationContext`2.Start(Boolean lockUntilShutdown)
`

**Operating System:**
Windows, Mac, Or Linux

**Comment by WeylonSantana** [comment]
I couldn't reproduce it, can you reproduce this bug in a clean version? Maybe upload a video to show it better?
https://www.ascensiongamedev.com/resources/filehost/4261735b256f8ee665172f16405ac8c7.mp4

**Comment by dudevelopement** [comment]
can close this, i cant reproduce any more idk why

**Comment by dudevelopement** [comment]
#1224 is causing the problem when the player dies he marks the line 257
foundEntity = TargetBox.MyEntity.MapInstance.Entities.FirstOrDefault(entity => entity.Id == TargetIndex) as Entity;

**Comment by dudevelopement** [comment]
Another way to reproduce the BUG.

Select a monster, leave it marked on the target.
Change map.
see the error

**Comment by dudevelopement** [comment]
This is a possible fix for that

`
            if (TargetBox != null)
            {
                TargetBox.Update();
            }
            else if (this == Globals.Me && TargetBox == null && Interface.Interface.GameUi != null)
            {
                // If for WHATEVER reason the box hasn't been created, create it.
                TargetBox = new EntityBox(Interface.Interface.GameUi.GameCanvas, EntityTypes.Player, null);
                TargetBox.Hide();
            }

`

And working for me, the target box works, no crashes and inspect of npcs are working too

**Comment by lodicolo** [comment]
> This is a possible fix for that
> 
> ```cs
>             if (TargetBox != null)
>             {
>                 TargetBox.Update();
>             }
>             else if (this == Globals.Me && TargetBox == null && Interface.Interface.GameUi != null)
>             {
>                 // If for WHATEVER reason the box hasn't been created, create it.
>                 TargetBox = new EntityBox(Interface.Interface.GameUi.GameCanvas, EntityTypes.Player, null);
>                 TargetBox.Hide();
>             }
> ```
> 
> And working for me, the target box works, no crashes and inspect of npcs are working too

From my understanding this code reverts #943 (fix for #900), and is incorrect.

A correct solution would addressing the NullReferenceException in the following code:
```csharp
TargetBox.MyEntity.MapInstance.Entities.FirstOrDefault(entity => entity.Id == TargetIndex) as Entity;
```

which if I had to guess would be adding null-conditional (`?.`) operators:
```csharp
TargetBox.MyEntity?.MapInstance?.Entities.FirstOrDefault(entity => entity.Id == TargetIndex) as Entity;
```

You can test to see if that resolves your issue and someone can open a PR (not me).

**Comment by dudevelopement** [comment]
Ok, this change fixed the issue!
Thanks Panda!

**Comment by Arufonsu** [comment]
#1262 fixed this issue 👍🏽
