### ISSUE TITLE
bug: Crash on edit empty show image event command

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#1261]
**Describe the bug**
Having no images in the images folder, and set to show image, without having selected an image, when editing the event command without image defined, the editor crashes.

**Version Encountered**
0.7.1.116

**To Reproduce**
1. Don't have images in the images folder
2. Create a command event to show images and press ok
3. try to edit right after returning to event page

**Expected behavior**
not crash

**Screenshots**

**Logs**
2022-05-20 20:36:00.767 [Error] ArgumentNullException: Valor não pode ser nulo.
Nome do parâmetro: value
    Stack:    em System.Windows.Forms.ComboBox.ObjectCollection.IndexOf(Object value)
   em Intersect.Editor.Forms.Editors.Events.Event_Commands.EventCommand_ShowPicture..ctor(ShowPictureCommand refCommand, FrmEvent editor)
   em Intersect.Editor.Forms.Editors.Events.FrmEvent.OpenEditCommand(EventCommand command)
   em Intersect.Editor.Forms.Editors.Events.FrmEvent.btnEdit_Click(Object sender, EventArgs e)
   em System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   em System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   em System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   em System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   em System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   em System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   em System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   em System.Windows.Forms.Control.WndProc(Message& m)
   em System.Windows.Forms.ToolStrip.WndProc(Message& m)
   em System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   em System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

--------------------------------------------------------------------------------

**Operating System:**
Windows

**Additional context**
Found this bug try to reproduce the previous bug

**Comment by Arufonsu** [comment]
just gave this a try and managed to reproduce this issue 👍🏽

**Comment by lodicolo** [comment]
Fixed in 0.7.1.20
