### ISSUE TITLE
bug: when using the interact/attack hotkey (E by default) and hovering over a part of the UI, it does not do the action

### ISSUE THREAD

**Issue by Gokwol** [AscensionGameDev/Intersect-Engine#1266]
**Describe the bug**
When you hover over an item and other UI items, including spells, buttons, etc. you cannot do the interact/attack hotkey action (E by default).

**Version Encountered**

0.7.1.17

**To Reproduce**
1. Go to ANY part of the UI with your cursor
2. Attempt to use the interact / attack key (E by default)
3. See error

**Expected behavior**
When you press E, no matter where your cursor is, it should complete the interact / attack action. For example, if I am attacking and trying to click on potions, or my cursor happens to be placed on a piece of UI, it should complete the action when I press E.

**Screenshots**
![221266658dca661ac2ba25232f06a75f](https://user-images.githubusercontent.com/64770171/169929199-81710357-8746-4a4a-ad7c-5f41ad35772e.gif)

**Logs**
If there are error logs please attach them below.

**Operating System:**
Windows

**Additional context**
It is ALL UI elements, not just clickable buttons.

**Comment by Cheshire92** [comment]
This brings up an interesting point of discussion however; what if I want to have UI action keybinds? If the game ones are always favoured over UI related stuff it's eventually going to cause a similar problem the other way around.

**Comment by Gokwol** [comment]
> This brings up an interesting point of discussion however; what if I want to have UI action keybinds? If the game ones are always favoured over UI related stuff it's eventually going to cause a similar problem the other way around.

My only problem, is it would make sense if [E] (in this case) would do something when clicking on the UI, but it does not. For example, if E and LMB worked the same, that would make sense, if I went into a menu and double tapped E to equip something, then fine, but the problem is it doesn't do anything when hovering over the UI, so if I leave my mouse cursor hanging in say the chat box and run up to an enemy expecting to attack it, then I realize my E doesn't do anything, I'm gunna be confused (as a player who knows nothing about UI or game controls - and was taught in the tutorial or something to press E to attack / interact).

So it should probably be decided now whether that's a good idea or not.

**Comment by Arufonsu** [comment]
hmm yeah, i've realized about this, basically the E key will trigger attacks/actions only if you first attack with the left click 😩 
at least, i can confirm this to be happening for a while now.

**Comment by Arufonsu** [comment]
Note: #1207 is probably related
