### ISSUE TITLE
bug: selected character's equipment not properly rendered in main menu

### ISSUE THREAD

**Issue by xXEsiXx** [AscensionGameDev/Intersect-Engine#1279]
**Describe the bug**
If you have multiple characters in selection, about 2 character for example and one has equipped weapon and armor and the second has nothing equipped, in the character selection the first character items will show in the second character. Its not a dupping problem just a visual problem 

**Version Encountered**
V0.7.1.020
**To Reproduce**
1. Create 2 characters
2. One have him to equip different armor and weapons and the second none 
3. Go to character selection 
4. switch characters and you will see the problem

**Expected behavior**
The first character equipment be on the second character

**Screenshots**
![image](https://user-images.githubusercontent.com/99421317/173610835-f2a072f1-a5eb-4599-bc2e-81ad95b24a76.png)
![image](https://user-images.githubusercontent.com/99421317/173610948-ec3750fc-91a3-4b83-a5bc-c27834e6cca3.png)
![image](https://user-images.githubusercontent.com/99421317/173611068-0c6282cd-b931-4025-a679-a39d8fedacf3.png)

**Logs**
If there are error logs please attach them below.

**Operating System:**
Windows

**Additional context**

**Comment by Arufonsu** [comment]
Just reproduced this issue 👍🏽
