### ISSUE TITLE
Some players are unable to log in.

### ISSUE THREAD

**Issue by ThousandX** [AscensionGameDev/Intersect-Engine#129]
**Describe the bug**
After I returned from MYSQL to SQLITE, some players are unable to login, as it gives this error. failed to load the account, please try again later.
When I return to the MYSQL system, that player is able to open his account, but on SQLITE the bug comes back.

**Version Encountered**
0.6.2.0 (LAST DEV PULL)

**To Reproduce**
Migrating from MYSQL to SQLITE, some accounts do not work.

**Expected behavior**
That I didn't have this error when using SQLITE

**Operating System:**
Windows 10

**Comment by jcsnider** [comment]
I need the username of a user with this problem.

**Comment by ThousandX** [comment]
Login: pertubadu

**Comment by jcsnider** [comment]
Ask him to try logging in with a capital P:
Pertubadu
