### ISSUE TITLE
bug: "Warp to" admin commands

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#1294]
**Describe the bug**
When using any admin command - warp to - one of the players disappears, while still on the map

**Version Encountered**
0.7.1.22

**To Reproduce**
1. Log in 2 account
2. Use any command "warp to"
3. See error

**Expected behavior**
That the expected effect is performed correctly

**Screenshots**
https://www.ascensiongamedev.com/resources/filehost/ca59113fdd1b878c1e178df9f0a623eb.mp4

**Logs**
If there are error logs please attach them below.

**Operating System:**
Windows

**Additional context**

**Comment by dudevelopement** [comment]
this bug also happens when you teleport to the next map, using an NPC, you can do the test, one of the players is invisible, the other is not. This bug does not only happen when teleporting using admin command, but in the entire teleport function.
