### ISSUE TITLE
bug: Player disappears when teleported via event

### ISSUE THREAD

**Issue by dudevelopement** [AscensionGameDev/Intersect-Engine#1296]
**Describe the bug**
One of the players becomes completely invisible to the other when teleporting to another nearby map.

**Version Encountered**
0.7.1.22

**To Reproduce**
1 - Create 1 NPC that will teleport the player to 1 map above.
2 - Have 2 players logged in.
3 - The first player, Use the npc to have him teleport you to the map above.
4 - The second player, Use the npc to make him teleport you to the map above.
5 - See the error.... The first player will be able to see the second player on the new map, but the second player will not be able to see it.

**Expected behavior**
Both players could see each other

**Operating System:**
Windows, Mac, Or Linux

**Comment by SilverShardOnline** [comment]
This is happening to me as well (Build: 0.7.1.39)
Using an event to warp player over to the next map (connected), will make the player disappear visually for the other player.
This only happened with 1 of the players.
