### ISSUE TITLE
bug: Create a new map, changes class spawn

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#1297]
**Describe the bug**
Create a new map, changes class spawn

**Version Encountered**
0.7.1.22

**To Reproduce**
1. Create a new map
2. Check class editor
3. See error

**Expected behavior**
Not change class spawn

**Screenshots**

https://user-images.githubusercontent.com/1476550/192125455-dfd91e54-f587-4e1d-9099-4afbf29b7f2f.mp4

**Logs**
If there are error logs please attach them below.

**Operating System:**
Windows

**Additional context**

**Comment by lodicolo** [comment]
I definitely see the error (in the video) but I am unable to reproduce locally even with a clean DB.

Looking at the code that can even modify that field, I do not see anything that can cause it.

Please try reproducing on the latest the next time you get the chance @WeylonSantana

**Comment by WeylonSantana** [comment]
I can't reproduce it in a recent version either, I don't know what change was made at that time that caused that, but now it seems fixed
