### ISSUE TITLE
bug: Players glitch when traversing a map

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#1298]
**Describe the bug**

**Version Encountered**
0.7.1.22

**To Reproduce**
1. Log in with 2 accounts
2. Walk between 2 maps
3. See error

**Expected behavior**
Not glitch

**Screenshots**
https://www.ascensiongamedev.com/resources/filehost/3f0162f4d46cb007c396deac5e064e6b.mp4
[start from 3:00]

**Logs**
If there are error logs please attach them below.

**Operating System:**
Windows

**Additional context**

**Comment by Arufonsu** [comment]
verified (wtf 😆 )
