### ISSUE TITLE
bug: Empty folders causes strange behavior on selectors

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#1299]
**Describe the bug**
When all folders containing files are empty (entities, animations, items, spells, etc), the selection combobox acts strangely, showing an empty option in addition to none, in some editors, clicking on the empty option causes the editor to crash (e.g. item and animation editor), in other editors the editor does not crash, but allows choosing the empty option which is also an error

**Version Encountered**
0.7.1.22

**To Reproduce**
1. Make folders containing files empty
2. Make new game objects
3. Try select some graphic

**Expected behavior**
Not Crash or show the empty option

**Screenshots**
![image](https://user-images.githubusercontent.com/63019821/174814647-2a532515-096c-42f4-850c-44f02ee18bf1.png)

**Logs**
[errors-Intersect Editor.log](https://github.com/AscensionGameDev/Intersect-Engine/files/8950664/errors-Intersect.Editor.log)

**Operating System:**
Windows

**Additional context**

**Comment by Arufonsu** [comment]
Issue is happening due to changes i did over to GetSmartSortedTextureNames at #1264
Opened a PR that undid that ^ and yet, maintains the expected behaviour and prevents any sort of crash around comboxes.
