### ISSUE TITLE
bug: attack animations runs after blocking

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#1300]
**Describe the bug**
When the sprite has custom attack sprites (attack, weapon or shoot), this animation is played after blocking.

**Version Encountered**
0.7.1.22

**To Reproduce**
1. Make extra sprite animation
2. Equip a shield and release
3. After release de block button see error

**Expected behavior**
Do not run attack animation, if not attacking

**Screenshots**
https://www.ascensiongamedev.com/resources/filehost/04fa0e69f0facca18722f5342a14343b.mp4

**Logs**
If there are error logs please attach them below.

**Operating System:**
Windows

**Additional context**

**Comment by Arufonsu** [comment]
reproduced thus, verified ; similar outcome to the issue's video report 👍🏽
