### ISSUE TITLE
bug: Set Graphic not working

### ISSUE THREAD

**Issue by GabrielTadachi** [AscensionGameDev/Intersect-Engine#1308]
**Describe the bug**
Set graphic is not actually setting the graphic that I say to set.

**Version Encountered**
Last Prerelease

**To Reproduce**
1. Create an event and click on Set Move Route
2. Click to Change Graphic and select the sprite you want
3. Save Event and try it. The sprite will not change

**Expected behavior**
On interacting with the event, the graphic should change, as it changed in previous versions.

**Screenshots**
Output after Move Route:
![image](https://user-images.githubusercontent.com/25730747/175134772-62e45890-0104-4e44-938a-6a302020f9fd.png)

Event configuration:
![image](https://user-images.githubusercontent.com/25730747/175134865-9c42dad0-679c-4621-b953-fb934cbde26a.png)
![image](https://user-images.githubusercontent.com/25730747/175134824-99e59e81-00f9-4b55-bf8c-ca697d34987b.png)
![image](https://user-images.githubusercontent.com/25730747/175136200-f96e0300-be49-4f5a-8e07-987f15493b9b.png)

**Logs**
If there are error logs please attach them below.

**Operating System:**
Windows, Mac, Or Linux

**Additional context**

**Comment by WeylonSantana** [comment]
I confirm, it's a bug
