### ISSUE TITLE
feature: event effect: fade in, fade out 

### ISSUE THREAD

**Issue by darkkriteus** [AscensionGameDev/Intersect-Engine#1321]
Good afternoon, I think it would be interesting to add a visual effect in teleports and events. for example instead of simply teleporting from map to map just by blinking the image, it would be interesting to add the fade out or fade in effect, in the event editor. would make it better, or for example you create a sleep event, then add the fade out, to make it more realistic.

**Comment by WeylonSantana** [comment]
Sure, thank you @blinkuz, its a duplicate.
