### ISSUE TITLE
bug: deleted items inside bags take up space and cannot be withdrawn

### ISSUE THREAD

**Issue by jcsnider** [AscensionGameDev/Intersect-Engine#1335]
### Description

When items which are stored in bags get deleted from the editor they become 'ghosts' which continue to take up the bag slots despite nothing being there. The slot is taken and cannot be reused whatsoever.

![img](https://www.ascensiongamedev.com/resources/filehost/b939d47c522609b1f4c7151e37f76354.png)

### Steps to Reproduce

1. Add items to bag.
2. Delete item from editor which is inside bag.
3. Try to store items in that slot.

### Version with bug

v7.1.22

### Last version that worked well

Unknown

### Affected platforms

Windows, macOS, Linux

### Did you find any workaround?

N/A

### Relevant log output

```shell
N/A
```

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by Arufonsu** [comment]
Reproduced this issue report (verified) 👍🏽
