### ISSUE TITLE
bug: possible rollback for editor accounts

### ISSUE THREAD

**Issue by jcsnider** [AscensionGameDev/Intersect-Engine#1339]
### Description

I have personally seen rollbacks on my editor account characters and others have reported the same. It seems like a solution is to edit and play on separate accounts.

Best guess is that the editor is keeping the player data from when it initially logs in, and then that is saved on logout.

### Steps to Reproduce

1. Edit the game
2. Play the game
3. Logout of client
4. At some point later logout of the editor
5. You might see your characters revert.. although I believe this is rare.

### Version with bug

v7.1.22

### Last version that worked well

Unknown

### Affected platforms

Windows, macOS, Linux

### Did you find any workaround?

I added a condition in the client logout function to never save editors.. seemed to have worked.

### Relevant log output

```shell
N/A
```

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by lodicolo** [comment]
Re-open if this still occurs after #1340
