### ISSUE TITLE
bug: Slowing down the program after using the "Re-Download All Previews" function.

### ISSUE THREAD

**Issue by Zwloki** [AscensionGameDev/Intersect-Engine#1356]
### Description

When using the map editor after using the "Re-Download All Previews" function to refresh the map view, the program slows down. After using this function, editing the map layout becomes problematic (read: slow)

### Steps to Reproduce

1. Map editing
2. Using Re-Download All Previews.
3. Slowing down

### Version with bug

0.7.0.140-beta

### Last version that worked well

Unknown

### Affected platforms

Windows

### Did you find any workaround?

Re-open editor

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by lodicolo** [comment]
@Zwloki How many maps do you have roughly when you are doing this? And does speed improve after restarting the editor?

**Comment by lodicolo** [comment]
Closing for lack of information, if the questions above are answered this can be reopened.
