### ISSUE TITLE
bug: Not using "Strings#FormatQuantityAbbreviated" in the trade window

### ISSUE THREAD

**Issue by AlexVild** [AscensionGameDev/Intersect-Engine#1395]
### Description

The trade window displays item quantities without using the client's `Strings#FormatQuantityAbbreviated` method, which results in gross looking UI:

![image](https://user-images.githubusercontent.com/8580915/180048208-085f1a88-da25-452c-844c-c7e0f0d427ce.png)

### Steps to Reproduce

1. Trade an item with quantity > 1000
2. See that there is no "k" (by default) placed afterward

### Version with bug

7.1.22

### Last version that worked well

Never

### Affected platforms

I was *not* able test on other platforms

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by Arufonsu** [comment]
Verified 👍🏽 

![image](https://user-images.githubusercontent.com/17498701/187243779-b6253ea6-b8c7-46e8-93d5-21dfc121031c.png)


![image](https://user-images.githubusercontent.com/17498701/187243732-a91b62d0-b81a-454c-9f20-573c95beb722.png)
