### ISSUE TITLE
Time spawn doesn't work properly

### ISSUE THREAD

**Issue by naziozeno** [AscensionGameDev/Intersect-Engine#1406]
### Description

The spawn time dont works as can be.
If you leave the area what a boss or any other npc is, after 1 min they will be there again, dont matter how much time you put (at my case, 1h or 1.800,000 ms.)

### Steps to Reproduce

1 - Create a monster with high respawn time
2 - create a map and put the monster there. (normal map, no instanced)
3 - create an event to teleport to this map in another different map.
4 - kill the monster and leave the map for 1 min
5 -  teleport again and it will be there!

### Version with bug

Latest version 0.7.1.35

### Last version that worked well

Before instance system;

### Affected platforms

Windows

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by WeylonSantana** [comment]
I can confirm


https://www.ascensiongamedev.com/resources/filehost/cb87953f3c125361981c28804f9fb2e1.mp4

**Comment by Arufonsu** [comment]
a little reminder for this issue, which I hope will help anyone who tries to address it:

![image](https://user-images.githubusercontent.com/17498701/187302475-e1698acc-0bd7-4946-8b4b-f3685ad578f0.png)
