### ISSUE TITLE
bug: Package update

### ISSUE THREAD

**Issue by Gorgaki** [AscensionGameDev/Intersect-Engine#1413]
### Description

When I use the Package update, the editor crashes

### Steps to Reproduce

Run the Package update.

### Version with bug

V 0.7.1.35

### Last version that worked well

v0.7.0.38

### Affected platforms

Windows

### Relevant log output

```shell
--------------------------------------------------------------------------------
2022-08-08 15:20:01.825 [Error] FormatException: Le format de la chaîne d'entrée est incorrect.
    Stack:    à System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   à System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   à System.Convert.ToInt32(String value)
   à Intersect.Editor.Forms.FrmMain.packAssets(String rootDirectory)
   à Intersect.Editor.Forms.FrmMain.<>c__DisplayClass118_0.<PackageUpdate>b__1()
   à System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   à System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   à System.Threading.ThreadHelper.ThreadStart()


--------------------------------------------------------------------------------
```

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by WeylonSantana** [comment]
This is not a bug
![image](https://user-images.githubusercontent.com/63019821/192121622-f80d2469-0585-401e-956a-5d82e1cd22c1.png)

Is working until current version (0.7.1.51)
![image](https://user-images.githubusercontent.com/63019821/192121645-a889400b-83b4-42c4-b2b7-03c550cf1444.png)
![image](https://user-images.githubusercontent.com/63019821/192121646-1aff806a-406a-4f37-88ae-9fc1c3f9efd3.png)

but it will still remain open as the client shouldn't crash in this situation
