### ISSUE TITLE
bug: NPC vs NPC combat results in all loot being dropped 100%.

### ISSUE THREAD

**Issue by SilverShardOnline** [AscensionGameDev/Intersect-Engine#1416]
### Description

When NPC vs NPC Combat Hostility is enabled, and an NPC kills another NPC - all items on the loot table are dropped 100% of the time regardless of drop rates set.

### Steps to Reproduce

1. Make 2 NPCs and add each other to the NPC vs NPC combat list.
2. Enable NPC vs NPC combat checkbox
3. Enable aggressive behavior on at least 1 NPC.
4. Add items to loot table at any % under 100% (lower is better for testing)
5. Place NPCs next to each other and let one die.
6. Results in all loot being dropped.

Expected Behavior: Loot dropped is based on NPCs item loot drop % as in previous versions.

### Version with bug

 0.7.1.39 (Main)

### Last version that worked well

 0.7.0.134 (Stable)

### Affected platforms

Windows, macOS

### Did you find any workaround?

No workaround.

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by WeylonSantana** [comment]
This bug does not happen in the recent version (current 0.7.1.51)

https://user-images.githubusercontent.com/63019821/192122273-50401d07-115b-45f7-bd09-06386fd70d41.mp4
