### ISSUE TITLE
feature: setting to toggle UI's EXP bar value to % (With Decimals)

### ISSUE THREAD

**Issue by naziozeno** [AscensionGameDev/Intersect-Engine#1431]
### Description

A way to change the exp string for % at the client config, with a way to put how much zeros needed (decimals).

Example:
Old method: current EXP / EXP to next level  ( 1 / 100000 )
New method: % exp ( 0,0000%)

### Intended Use-Case

Many players like me, dont like the astronomic numbers after lv up, with % at current exp is less stressing,

### Duplicate Check

- [X] This feature request is not a duplicate to the best of my knowledge.

**Comment by Arufonsu** [comment]
I'll give this feat request a try during the upcoming weekend 👌🏽

**Comment by Arufonsu** [comment]
I'll give this feat request a try during the upcoming weekend 👌🏽 

Self reminder:
Make it configurable though booleans at the in game settings > interface
