### ISSUE TITLE
bug: Status not showing correctly on client when 0

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#1457]
### Description

If in the editor we put all statuses as 0 like this in class editor
![image](https://user-images.githubusercontent.com/63019821/191621580-a4b7684a-c679-45ac-bc31-6e423f9bebed.png)
on client will show this
![image](https://user-images.githubusercontent.com/63019821/191621708-7514fb5f-1768-4a5b-9dac-a793f8758d09.png)

### Steps to Reproduce

Put all status 0 on class editor and see on client.

### Version with bug

v7.1.22

### Last version that worked well

Unknown

### Affected platforms

Windows

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by lodicolo** [comment]
![image](https://user-images.githubusercontent.com/1476550/192130088-127d7660-d749-4969-9466-786ef48f3ea6.png)

This is not a bug. The minimum evaluated stat value is 1, no matter the actual value set by the class or stored in the DB.

You can see the comment here: https://github.com/AscensionGameDev/Intersect-Engine/blob/4d826bda5a1c2923d287cb8265912e2229ab1871/Intersect.Server/Entities/Combat/Stat.cs#L63
