### ISSUE TITLE
bug: resources not downloading correctly when upgrading to 0.7.1.49

### ISSUE THREAD

**Issue by NikoCummings** [AscensionGameDev/Intersect-Engine#1459]
### Description

Hello, I upgraded from an outdated version of intersect to 0.7.1.49 and am seeing some strange rendering errors in the settings menu.
![1920](https://user-images.githubusercontent.com/10820240/191874074-b8806b4b-39f9-40a6-b737-27cef3939e60.png)

### Steps to Reproduce

1. Upgrade from an older version
2. Run the client and open the settings menu from the main menu or in game

### Version with bug

0.7.1.49

### Last version that worked well

an older version

### Affected platforms

Windows

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by lodicolo** [comment]
I do not see anything in the screenshot that appears to me as though something downloaded incorrectly.

I have no idea what you expected to be seeing, and you don't state how what is shown differs from what is expected.

Closing for lack of details.
