### ISSUE TITLE
Commands when accepting a mission do not work.

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#146]
**Describe the bug**
I realized that not long ago. I hope it is a bug and not another mistake of mine.
Basically when a player finishes a mission, I offer a new one. When I offer the player a mission and he accepts, the command on accepting mission is not executed.

It worked on older versions, but it stopped working on the latest versions. I don't remember which version stopped working.
In the images below I put the command "show text" and it did not execute.
I also tried "showing images" and "running a common event", and it didn't work.

I'm currently using 0.6.1.253

**To Reproduce**
Offer the mission. Showing offer window.
Execute a command when the player accepts.

**Expected behavior**
When you accept the mission, a command has to be executed.
**Screenshots**
![image](https://user-images.githubusercontent.com/63019821/79284321-afea9c00-7e90-11ea-9a6c-d7c5edc63e03.png)
![image](https://user-images.githubusercontent.com/63019821/79284336-bb3dc780-7e90-11ea-84c7-47e524bff09f.png)
![image](https://user-images.githubusercontent.com/63019821/79284352-c4c72f80-7e90-11ea-9418-0a4d201024fb.png)

**Operating System:**
Windows 7 64x.

**Comment by jcsnider** [comment]
@WeylonSantana please also share the spawn/execution conditions for that page.

**Comment by WeylonSantana** [comment]
![image](https://user-images.githubusercontent.com/63019821/79331676-f0c6cd00-7ef1-11ea-9b79-d4510dcb636c.png)
In map I have:
![image](https://user-images.githubusercontent.com/63019821/79331848-36839580-7ef2-11ea-9c70-5718edbc0c53.png)

Second page, to check the mission
![image](https://user-images.githubusercontent.com/63019821/79331948-5b780880-7ef2-11ea-9cca-30b09ba5a528.png)

**Comment by WeylonSantana** [comment]
Apparently another mistake of mine again. So I come to apologize.

The script just read the part of offering the mission. As the event that started the common event is the map event, when accepting the mission it moves to page 2 immediately, stopping the common event, so it doesn't do what's there after accepting a mission.

Solution, put all the existing conditions on one page.
Event in map
![image](https://user-images.githubusercontent.com/63019821/79336433-1d7ee280-7efa-11ea-988e-5128b73a6ed3.png)
![image](https://user-images.githubusercontent.com/63019821/79336472-3091b280-7efa-11ea-9da7-71d7183af050.png)

Commom event page 1
![image](https://user-images.githubusercontent.com/63019821/79336582-5fa82400-7efa-11ea-8d8a-9e77b74d720a.png)
Commom event page 2
![image](https://user-images.githubusercontent.com/63019821/79336632-78b0d500-7efa-11ea-8d0e-96df116bf7d3.png)
