### ISSUE TITLE
enhancement: Copy / paste Map properties 

### ISSUE THREAD

**Issue by NikoCummings** [AscensionGameDev/Intersect-Engine#1461]
### Description

I use a lot of effects on my maps. alpha color channels, fogs, weather, darkness/lighting. It would be great to be able to copy and paste map properties from map to map.

### Intended Use-Case

This would speed up the flow of designing large amounts of maps wich will use the same effects to create a seamless-looking area of your map/world.

### Duplicate Check

- [X] This enhancement idea is not a duplicate to the best of my knowledge.

**Comment by WeylonSantana** [comment]
Before checking the checkbox "This /feature/bug/enhancement idea is not a duplicate to the best of my knowledge.", we ask that you really verify that it is not a duplicate, or if the feature/enhancement has not already been partially created so you can add more information.

Searching for keywords, could have found (if any)
![image](https://user-images.githubusercontent.com/63019821/192093534-de0943cb-f66b-459c-a8f1-d251057f3f6b.png)
I'm closing it as a duplicate of #1277.
