### ISSUE TITLE
bug: My Resolution not available in 0.7.1.49

### ISSUE THREAD

**Issue by NikoCummings** [AscensionGameDev/Intersect-Engine#1462]
### Description

Prior to me upgrading to beta version 0.7.1.49 my screen resolution 1920x1080 was always available and was what i used to test/play my client. I didn't change any monitor display setting on my monitors. I upgraded and now the screen resolution is no longer available to choose and there is no sidebar in the drop-down to scroll up or down. I do use 2 monitors but did so fine prior to the upgrade. I checked my display settings and both monitors are still set to 1920x1080. I tried rebooting my computer, selecting different resolutions, and disabling one monitor. None of these actions resolved the issue.

### Steps to Reproduce

1. login to the client
2. check to see if any resolutions that are available to your monitor are missing.

### Version with bug

0.7.1.49

### Last version that worked well

old

### Affected platforms

Windows

### Did you find any workaround?

no

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by Arufonsu** [comment]
Related:
![image](https://user-images.githubusercontent.com/17498701/192097260-6fdd96d1-9f08-4fb3-862d-d4888d211d38.png)

Despite the fact that it works with 100% scale, there's def some issue happening here with different scaling situations on windows.
