### ISSUE TITLE
feature: ability to play sounds within the animation editor

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#149]
**Is your feature request related to a problem? Please describe.**
I believe that a good improvement in the quality of life when creating games with the intersect, would be in the animation editor.
Animations where we put sounds, in addition to the animation being executed in the editor, the sound of it should also be played. This could help us to synchronize sound and animation. For all the animations in my game, for example, I had to watch animation being played, while in the background, with an open media player, I was trying to sound by sound, to find what best fit.

**Describe the solution you'd like**
When an animation is played, its sound is also in the editor to facilitate synchronization.

PS: I tried to put it in the category as an enhancement, it was a bug, I didn't understand.

**Comment by Azurebeats** [comment]
I've got this to work, but I'm running into some weird ''what if's'' here.

Since both animation layers never play in sync, do we just play the sound at the first frame of both animation layers as a preview? Would cause some awkwardness when you try and play both layers at once, since the sound (and the animation itself) never sync up.

**Comment by WeylonSantana** [comment]
@Azurebeats sorry to delay responding, I didn't see your comment here Are the animation of the top and bottom layer not sync in the same animation? Strange, I use several animations using both sides of the animation (low layer and up layer) and when I put play on 2, they stay synchronized. But I understood your point, many animations do not even use both sides, generally many use the up layer, few use the low layer and even less both.

the beginning of the sound, I believe,
would start when the player pressed play when the framecount is greater than 0.

if the editor knows when a play animation button is playing, then if the creator pressed the other play animation it would not play the sound again.

then it is, when the play animation is pressed the editor is in a state of "running animation along with the sound", and when the other is pressed it is in the state of "running animation". Whatever is pressed first gets the sound, while if the second is pressed when the first tbm is playing, it does not play sound.

the sound would start at the beginning of the frames and cut off when it reaches the end of the frames. unless the creator ticks the box to continue after the animation ends.

I do not know if this is logical or rational for you, or if it is possible or if it is something of my imagination, but I hope it has given some kind of light on something haha.
