### ISSUE TITLE
LIST OF BUGS

### ISSUE THREAD

**Issue by kielleds** [AscensionGameDev/Intersect-Engine#150]
hello jc
I found some bugs on the intersect that I think you can solve with some ease.

LIST OF BUGS
1 ° - There are no limits in the group
In my tests I managed to add 10 members to the group. and in the window they show only 4. it would be right to have a limit.
[group bug example](https://cdn.discordapp.com/attachments/555929528426299412/700416269295288320/unknown.png)

2 ° - The second bug is related to the states area. It does not seem to wrap the line correctly when you activate x buffs / x debuff. in my tests I activated 11 effects and the same bug on the screen.
[status bug example](https://cdn.discordapp.com/attachments/555929528426299412/699326402486337616/unknown.png)

3 ° - In the list of friends there is no way to remove friends, since the selection does not work correctly. When hovering the mouse the handle effect is activated several times showing even more the bug.
NOTE: This bug cannot be demonstrated with an image. Test please.

**Comment by jcsnider** [comment]
Marking as invalid due to the [template not being followed](https://www.ascensiongamedev.com/resources/filehost/ee70ffd6cbb4533aa1dd13bbe792f10a.png) and because of multiple bugs in a single issue. We need 1 bug per issue so it can be discussed and linked properly to the PRs that solve them.
