### ISSUE TITLE
Entity Animations List going infinitely

### ISSUE THREAD

**Issue by rhathaway86** [AscensionGameDev/Intersect-Engine#155]
**Describe the bug**
From testing my own code I noticed in a print to console that Entity Animations List keeps going up and never decreases. Is this intended?

**Version Encountered**

**To Reproduce**
Check Entity Animations.count

**Expected behavior**
Shouldn't the list reset to 0 when no animations present?

**Screenshots**

**Logs**
If there are error logs please attach them below.

**Operating System:**
Windows, Mac, Or Linux

**Additional context**

**Comment by lodicolo** [comment]
@rhathaway86

Check the settings on the animations to verify that it's not just animations that aren't supposed to be removed (as opposed to a real leak).

Animations with `InfiniteLoop == true` or that are listed in `EquipmentAnimations` don't get removed.

**Comment by rhathaway86** [comment]
Yeah, just confirmed. Animations I am using are not infinite loop, and not for equipment.
https://ascensiongamedev.com/resources/filehost/0ca7378534d25c4e0caacd2addd0704d.gif
