### ISSUE TITLE
Cant Upgrade the Version from 0.6.0.151 to 0.6.1.253

### ISSUE THREAD

**Issue by Uyarrr** [AscensionGameDev/Intersect-Engine#156]
**Describe the bug**

**Version Encountered**
Upgrading from 0.6.0.151 to 0.6.1.253

**To Reproduce**
I tried upgrade, patch and even new downloads. All of them results same. Im replacing required files (client editor and server) after when I open my server it asks me to if I want to migrate or not. I'm typing READY, migration starts but it fails and shutdown.

**Screenshots**
![image](https://user-images.githubusercontent.com/63975845/79697209-1fde9500-828a-11ea-9224-ebc695d33066.png)
![image](https://user-images.githubusercontent.com/63975845/79697277-79df5a80-828a-11ea-942f-ed97ff267bbd.png)

**Logs**
I putted log to screenshot.

**Operating System:**
Windows 10

**Comment by lodicolo** [comment]
Your reproduction steps are not consistent with the screenshots you are providing.

Your logs indicate that either the port was already assigned to a device, or the UPnP NAT device was not found.

Please follow lontivero's instructions in [Open.NAT Issue 41](https://github.com/lontivero/Open.NAT/issues/41) and provide that information here.

Until further information is provided, this doesn't appear to a valid Intersect bug.

See also:
https://github.com/lontivero/Open.NAT/issues/34
https://github.com/lontivero/Open.NAT/issues/41

**Comment by Uyarrr** [comment]
Hello even if I made my game accessible to public. It's still same results. It gives error 718: conflictinmappingentry and server is going to shut down.
[errors-Intersect Server.log](https://github.com/AscensionGameDev/Intersect-Engine/files/4502709/errors-Intersect.Server.log)
![image](https://user-images.githubusercontent.com/63975845/79740393-46dbac00-8308-11ea-893c-74d76ee02cb8.png)

**Comment by lodicolo** [comment]
@Uyarrr I asked you to follow lontivero's instructions if we are going to try to help you.

This is an Open.NAT crash not an Intersect one.

**Comment by jcsnider** [comment]
Or just disable UPnP in the Server/resources/config.json

**Comment by Uyarrr** [comment]
It works when I disable it from config.
