### ISSUE TITLE
Can't Buy Stackable Items for 0

### ISSUE THREAD

**Issue by SilverShardOnline** [AscensionGameDev/Intersect-Engine#1568]
### Description

Setting a stackable item to 0 cost in a shop will result in not being able to buy the item.

Note: When trying to buy the item a -2147483648 value is applied initially.

### Steps to Reproduce

1. Create a Shop
2. Create a stackable item and set its buy cost to 0.
3. Try to purchase the item.

### Version with bug

Version 0.7.1.53

### Last version that worked well

Version 0.7.1.39 (I believe)

### Affected platforms

Windows, I was *not* able test on other platforms

### Did you find any workaround?

No.

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by lodicolo** [comment]
Fix is currently building in 0.7.1.55
