### ISSUE TITLE
bug: Crafting Failure Rate 0% still activates fails

### ISSUE THREAD

**Issue by SilverShardOnline** [AscensionGameDev/Intersect-Engine#1569]
### Description

Crafting Failure Rate is set to 0% (has not been touched on any item)
Crafting can still randomly fail. 
It does not happen very often, but I have tested on 2 separate items and happened once in maybe 50 crafts.

### Steps to Reproduce

1. Set an items Craft Failure Rate to 0%.
2. Craft Item repeatedly to get a Crafting Failure message. 
3. 
![craftfail  bug](https://user-images.githubusercontent.com/110916959/192308998-22094351-c43d-4ca4-b409-2b09edf30aa9.png)

### Version with bug

Version 0.7.1.53

### Last version that worked well

Unknown

### Affected platforms

Windows, I was *not* able test on other platforms

### Did you find any workaround?

No.

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by WeylonSantana** [comment]
I tested and this happens
