### ISSUE TITLE
bug: Server Lock Up on Common Event party trigger via NPC Death

### ISSUE THREAD

**Issue by SilverShardOnline** [AscensionGameDev/Intersect-Engine#1584]
### Description

Server locks up when in a Party with at least 1 other player, after killing an NPC that has a Common Event trigger set for 'onDeath for Party Members'.  (This lock up does not occur when just a single player kills, or if the event is set to only be triggered 'by the killer')

After the lock up, nothing loads, players cant log back in, and server needs a force shutdown.

_Lock up can be shown in the video._: https://youtu.be/WzkBA9Xp3d4

### Steps to Reproduce

1. Create common event to trigger on **NPC death** for **Party Members**
2. Join party with another player
3. Kill NPC with death trigger

### Version with bug

v0.7.1.39 - v0.7.1.057

### Last version that worked well

Was not in prior to 7.1

### Affected platforms

Windows, macOS

### Did you find any workaround?

Disabled Mobs triggering common events on death for party members

### Relevant log output

```shell
```

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by lodicolo** [comment]
Video is not available (why was this posted on YouTube instead of just uploading it to GitHub?).

Instructions are incomplete, unable to reproduce based on provided instructions.
