### ISSUE TITLE
enhancement: Ability to use Guild Variables with Input Variable + Guild Event Text Variables

### ISSUE THREAD

**Issue by RecoStar** [AscensionGameDev/Intersect-Engine#1593]
### Description

The ability to do a "input Variable" on guild variables.

As well as Event Text Variables for Guild Variables.

With this ability more functionality would come from the event system.

### Intended Use-Case

Allow changing of guild variables via player input. Such as a guild message of the day, which a guild leader would enter via an input variable. With this a need to Event Text Variables on guild variables would be required.

Many other uses can come of this. 

I have plenty of needs for my game for this enhancement, but I believe this would be beneficial to the engine and community.

### Duplicate Check

- [X] This enhancement idea is not a duplicate to the best of my knowledge.

**Comment by lodicolo** [comment]
Enhancements and feature requests are supposed to be opened as discussions first unless you are also opening your own PR.

https://github.com/AscensionGameDev/Intersect-Engine/discussions/1559
