### ISSUE TITLE
enhancement: Add 'Target-Self' hotkey

### ISSUE THREAD

**Issue by SilverShardOnline** [AscensionGameDev/Intersect-Engine#1594]
### Description

When trying to cast on yourself, the only option is to mouse over and click on your character.

Adding a 'self-target' key would be a great QoL enhancement. 

### Intended Use-Case

Almost all MMOs have self-target keys for casting target-able spells (especially heals) and would be beneficial for most games.

### Duplicate Check

- [X] This enhancement idea is not a duplicate to the best of my knowledge.

**Comment by lodicolo** [comment]
Enhancements and feature requests are supposed to be opened as discussions first unless you are also opening your own PR.

https://github.com/AscensionGameDev/Intersect-Engine/discussions/1559
