### ISSUE TITLE
You cannot create the update within the editor folder, the update would include itself!

### ISSUE THREAD

**Issue by yanisssch** [AscensionGameDev/Intersect-Engine#161]
**Describe the bug**
I have two folders on my desktop, one with the "Client&Server" and another called "Update", if I update and i put this update on my "Update" folder, the editor gives me this error message "You cannot create the update within the editor folder, the update would include itself! " while the folder is not the same as that of the publisher and they are not in the same folder and well separated

**Version Encountered**

0.6.2.0 AutoUpdater Branche

**To Reproduce**
1: Put Client&Editor and if the server you want the server in the same folder on desktop
2: Create a folder with the name you want (ex: Update) on desktop too
3: Turn on server etc....
4: Create an Package Update on Editor
5: Select the "Update" Folder on desktop
6: It will give this error

**Screenshots**
(Sorry i have a too bad internet connexion to make a video)

**Logs**
No logs when this errer happen

**Operating System:**
Windows 8.1 and tested on 10

**Additional context**
I think the editor check the first base of the directory so the desktop is the same folder of Client&Editor folder and Update Folder (I'm not sure i do only php & java not C# xD)

**Comment by jcsnider** [comment]
The PR now includes a fix for this, thanks!
