### ISSUE TITLE
bug: Client/Editor crash when server not online

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#1640]
### Description

It's not in all situations, maybe it's happen only when the ip doesn't result in a connection anywhere or whatever, When this error happens, neither the client nor the editor does not open, it crashes before opening, it should show a better error, like opening and saying that the server is offline, I don't know in what situation it happens, but there it is

### Steps to Reproduce

maybe connect to an ip that doesn't exist, I don't know well

### Version with bug

v7.1.79

### Last version that worked well

Unknown

### Affected platforms

Windows

### Relevant log output

```shell
2022-10-22 02:41:28.617 [Error] NetException: Could not resolve host
    Stack:    em Lidgren.Network.NetPeer.GetNetEndPoint(String host, Int32 port) na C:\Users\primero\git\agd\lidgren-network-gen3\Lidgren.Network\NetPeer.cs:linha 279
   em Lidgren.Network.NetPeer.Connect(String host, Int32 port, NetOutgoingMessage hailMessage) na C:\Users\primero\git\agd\lidgren-network-gen3\Lidgren.Network\NetPeer.cs:linha 295
   em Intersect.Network.Lidgren.LidgrenInterface.Connect()
   em Intersect.Network.Lidgren.LidgrenInterface.Start()
   em Intersect.Network.AbstractNetwork.<>c.<StartInterfaces>b__54_0(INetworkLayerInterface networkLayerInterface)
   em System.Collections.Generic.List`1.ForEach(Action`1 action)
   em Intersect.Network.AbstractNetwork.StartInterfaces()
   em Intersect.Network.ClientNetwork.Connect()
   em Intersect.Client.MonoGame.Network.MonoSocket.Connect(String host, Int32 port)
   em Intersect.Client.Networking.Network.TryConnect()
   em Intersect.Client.Networking.Network.InitNetwork(IClientContext context)
   em Intersect.Client.Core.Main.Start(IClientContext context)
   em Intersect.Client.MonoGame.IntersectGame.IntersectInit()
   em Intersect.Client.MonoGame.IntersectGame.Update(GameTime gameTime)
   em Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   em Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   em Intersect.Client.MonoGame.IntersectGame.MonoGameRunner.Start(IClientContext context, Action postStartupAction)
   em Intersect.Client.Core.ClientContext.InternalStart()
   em Intersect.Core.ApplicationContext`2.Start(Boolean lockUntilShutdown)
```

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by Arufonsu** [comment]
been trying to reproduce this today with no success on reproducing so far, by doing the following:

- using a wrong IP addresses
- localhost with offline server
- localhost with online -> and shutting down the server

**Comment by Arufonsu** [comment]
> There's definitely an unhandled error here

Considering that there's more than just a single situation where it happens, then yes, you are right. 
As soon as someone manages to document how to reproduce the issue, it should get easier for us to tackle it down.
