### ISSUE TITLE
bug: Transform Effect changes Sprite while Casting

### ISSUE THREAD

**Issue by SilverShardOnline** [AscensionGameDev/Intersect-Engine#1649]
### Description

When a Player is under a 'Transform' spell, then casts another spell (longer then 0ms) -the player will appear as their base character (naked) while under casting animation.

Attacking / Shooting / Idle animations are NOT effected.

_adding a  " _casting "  sprite sheet did not have any effect._

https://youtu.be/DiLdEG5EEfA

### Steps to Reproduce

1. Create Transform spell that lasts 30 seconds+
2. Create another spell with casting time of 1 second+
3. Use transform spell, then the 2nd spell to see the bug happen.

### Version with bug

7.1.74

### Last version that worked well

Unknown

### Affected platforms

Windows, macOS

### Did you find any workaround?

No

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by Arufonsu** [comment]
Tested and verified, will submit a PR that fixes this behavior in a bit.
