### ISSUE TITLE
bug: Context menu does not close after window closes

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#1651]
### Description

title

### Steps to Reproduce

1 - open the inventory
2 - open context menu (secondary on some item)
3 - press ESC
4 - the window closes but the menu does not

ps: if you click on the function (like drop) it will still work even with closed inventory

### Version with bug

0.7.1.81

### Last version that worked well

Unknown

### Affected platforms

Windows

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by Arufonsu** [comment]
Reproduced the issue, also, I've got a possible approach to fix this behavior real quick.
i will check out the other cases where context menus are used as well and open a PR

https://user-images.githubusercontent.com/17498701/199542100-29851a57-d845-48e2-8968-46ca97f0713b.mp4
