### ISSUE TITLE
bug: fog takes too long to render

### ISSUE THREAD

**Issue by ZerinSad** [AscensionGameDev/Intersect-Engine#1652]
### Description

About the fog bug that happens when you come to a new map and the fog waits 2min to appear in the screen, it should be 1sec or less, i mean, this feature from the engine makes total difference to some projects, makes part of the beauty of the game. The time for the fog appear seems to change from computer to computer eng. In previous versions of intersect this do not happened here, have started on this one.

### Steps to Reproduce

1. come to a new map
2. wait for the fog

### Version with bug

0.7.1.63

### Last version that worked well

0.7.1.24

### Affected platforms

Windows

### Did you find any workaround?

No

### Relevant log output

```shell
Don't have
```

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by Arufonsu** [comment]
Thanks for reporting this problem, as I mentioned on the forums, we have encountered this problem before, but it was not as noticeable as you mention in your report as to how long it takes to show up. Could you record a video showing how long it takes on your end? This is a critical problem if it's having major consequences on the low-end hardware you mention in the forum, and it's a bug we need to address anyway. Again, thanks for reporting. 👍🏽 

_pd:_ considering the nature of the report (more evident on low end hardware) could you also tell us the specs of the device you use with intersect (only if you want to) it _might_ be useful for whoever wants to solve this problem voluntarily.

**Comment by WeylonSantana** [comment]
@Arufonsu I tested his game (which is online), the first time it took 1 minute for the fog to appear on my computer, the second time it took 2 minutes for the fog to appear, I timed it

**Comment by Arufonsu** [comment]
> @Arufonsu I tested his game (which is online), the first time it took 1 minute for the fog to appear on my computer, the second time it took 2 minutes for the fog to appear, I timed it

i see, well there's indeed been an issue with this for a while, i guess that is hard to notice in my desktop side but i can still, see a small delay on my end, which is still undesired and not pretty to see...

**Comment by SilverShardOnline** [comment]
I have the same issue - takes about a minute to load on a decent PC. 
To note, this bug is also appearing in the editor itself (on initial loading)
