### ISSUE TITLE
bug: Invisible sprite when moving

### ISSUE THREAD

**Issue by Gorgaki** [AscensionGameDev/Intersect-Engine#1655]
### Description

When you attack while moving, the character becomes invisible during the attack.
[2022-11-07 07-00-47.zip](https://github.com/AscensionGameDev/Intersect-Engine/files/9948586/2022-11-07.07-00-47.zip)

### Steps to Reproduce

.

### Version with bug

v 0.7.1.81

### Last version that worked well

.

### Affected platforms

Windows

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by Arufonsu** [comment]
1.- Duplicated of #1086 
2.- Invalid format for steps to reproduce and last version that worked well
![imagen](https://user-images.githubusercontent.com/17498701/200331353-d7934172-e76f-496c-b2ff-0e7c2de3b31c.png)

3.- Thus: closing this as duplicated, invalid and not planned, please refer to https://github.com/AscensionGameDev/Intersect-Engine/issues/1086#issuecomment-1283264008 for more information.
