### ISSUE TITLE
enhancement: CharacterWindow should show up even with 1 max character

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#1666]
### Description

To give those games that have (or will have) only one maximum character the ability to delete and create characters, and not log out and log in mandatory.

### Intended Use-Case

In addition to the case mentioned above, it helps in the debugging of those who make custom modifications without necessarily having to increase the number of characters to be able to delete and create characters.

### Duplicate Check

- [X] This enhancement idea is not a duplicate to the best of my knowledge.

**Comment by Arufonsu** [comment]
[See this PR comment/review](https://github.com/AscensionGameDev/Intersect-Engine/pull/1667#pullrequestreview-1187269121)
It might require you to change some details within this enhancement request.

**Comment by Arufonsu** [comment]
Proposed an [alternative PR here](https://github.com/AscensionGameDev/Intersect-Engine/pull/1668), which is based on [my comment/review around the first proposed PR](https://github.com/AscensionGameDev/Intersect-Engine/pull/1667#pullrequestreview-1187269121)
