### ISSUE TITLE
bug: spells do not correctly shoot their last ammunition

### ISSUE THREAD

**Issue by GarozoneISE** [AscensionGameDev/Intersect-Engine#1683]
### Description

Hey, It's me again, and I don't know again and again if my report is good but I report this : 

- When a player uses a spell that has an "Ammunition Requirements", if the player uses his spell with exactly the required number of items, then the spell executes but without animation, and consuming the ammunition. 

This happens no matter how much ammo is required, all you need to do is have exactly the number requested and cast the spell then the bug appears.

Link Video : https://youtu.be/VPM22Nf8b60 

### Steps to Reproduce

Step 1 : Make an animation
Step 2 : Create a projectile with animation + Ammunition Requirements with "x" number (1,2,3,4..)
Step 3 : Create a spell with this projectile
Step 4 : Use the skill with the exact amount of Ammunition and the bug is here 

### Version with bug

v0.7.1.088

### Last version that worked well

Unknow

### Affected platforms

Windows

### Did you find any workaround?

Just have more than the Ammunition Requirements and it's good, the spell work

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by Arufonsu** [comment]
Tested and verified:


https://user-images.githubusercontent.com/17498701/206912343-1b49c1e3-e80f-4e66-96b6-376a60164f68.mp4


PS: this is not an issue with weapons that use ammo, but an issue **that only involves spells that use ammo**

**Comment by Arufonsu** [comment]
Made some progress on this today,  we also have some duplicated logic, and projectiles being removed before we actually cast spells with them:

https://github.com/AscensionGameDev/Intersect-Engine/assets/17498701/ca7e1663-867d-4424-8a3a-e227f8a2982b
