### ISSUE TITLE
Add Death attribute to the editor

### ISSUE THREAD

**Issue by yanisssch** [AscensionGameDev/Intersect-Engine#169]
**Describe the solution you'd like**
It would be great to add a Death attribute like when someone walk on a block which have a death attribute he will die, this can be use when you want to avoid player to go on a place or go out of the map or maybe if someone walk on the lava it can be more realistic this is really simple but it can help to some things ^^

**Additional context**
I made a working version of the engine with Death Attribute: https://github.com/yanisssch/Intersect-Engine-With-Death-Attribute i make 2 hours to made it (i'm so bad on c# xD)

**Comment by yanisssch** [comment]
I Update the fork because i forget to add the DeathPacket compile x) now you can build the client/server and editor without errors x)

Also i precompiled the Client & Editor and server for people want to had this feature without build on visual here the link: https://www.mediafire.com/file/oui2v10hboz5rcy/Intersect_Client__%26_Editor_%26_Server_With_Death_Attribute.zip/file

**Comment by WeylonSantana** [comment]
Closing this cause a better implementation idea can be found at #909, if #909 is ever implemented, this feature request would also complete.
