### ISSUE TITLE
feature: Party Enhancements

### ISSUE THREAD

**Issue by Uyarrr** [AscensionGameDev/Intersect-Engine#1690]
### Description

As written in topic, these ideas will increase functionality and support of Party for devs a lot.

New Integer: Player Party Size: How many players in the party right now.
Condition: Check Party Size. (Ex: Party size is equal or greater than 2, or like less than 5.)
Condition: Party Power (Ex: Check if player is Leader/Member of Party.)
Party Sync Events: Events that trigger for whole party. (Ex: Warp Player, when one player touches a button, it will warp all players there. Lots of possibilities.)

New Variable Category: Party Variables (Any variables that shares with full party. I saw something called Instanced Variables but I think this is better way to do that. Sometimes you don't want instances but you still want to have party variables.)

### Intended Use-Case

I found these will be extremely useful in situations like, example I want to make two different places that requires different amount of players. Check Party power is really useful when you want an event that can be only triggered by leader. Instancing already has that but again, sometimes you do not want an instance.

### Duplicate Check

- [X] This feature request is not a duplicate to the best of my knowledge.

**Comment by lodicolo** [comment]
Please open this as a discussion.

https://github.com/AscensionGameDev/Intersect-Engine/discussions/1559

**Comment by Arufonsu** [comment]
FYI -> https://github.com/AscensionGameDev/Intersect-Engine/discussions/1693
