### ISSUE TITLE
enhancement: Toggle On/Off Quest Log Categories.

### ISSUE THREAD

**Issue by Uyarrr** [AscensionGameDev/Intersect-Engine#1691]
### Description

As written in topic, toggling on/off Quest Log categories like folders will make it better.

### Intended Use-Case

Imagine having 40+ quests with different categories.

### Duplicate Check

- [X] This enhancement idea is not a duplicate to the best of my knowledge.

**Comment by lodicolo** [comment]
Please open this as a discussion.

See https://github.com/AscensionGameDev/Intersect-Engine/discussions/1559 for more information.
