### ISSUE TITLE
bug: Death by Event (-HP) does not trigger /respawn Events

### ISSUE THREAD

**Issue by SilverShardOnline** [AscensionGameDev/Intersect-Engine#1712]
### Description

If a player dies when having their vitals deducted by an event, Common Events with /respawn do not trigger.

Izakt reported this on Discord as well in v0.7.1.94 

### Steps to Reproduce

1. Create/Use a character with under 100 HP
2.  Create a /Respawn Common Event that sends a message "This Should Display"
3. Create an event that sets a players vitals -100 (set to passable) then walk over it.
4. No message is displayed/event triggered.

### Version with bug

v0.7.1.88

### Last version that worked well

unknown but probably always there.

### Affected platforms

Windows, macOS

### Did you find any workaround?

No.

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by WeylonSantana** [comment]
Tested on 0.7.2.20, the bug does not exist, I will close it for now, if you manage to take better reproduction steps, maybe with video, we can reopen
