### ISSUE TITLE
bug:  events are unable to remove bounded spells

### ISSUE THREAD

**Issue by SilverShardOnline** [AscensionGameDev/Intersect-Engine#1715]
### Description

After the feature: 'Bound Spell' was added, it did not take into consideration a way for an admin to trigger an event to remove that spell.

Common Events should have the ability/option to Remove Spell when it's marked as 'Bound'. 
This is logical as you you can Remove a Bound Item in this manner, and should function the same for spells.

### Steps to Reproduce

1. Make spell and check the 'Bound' box
2. Make a common event to take away that spell from a player
3. Function doesn't execute.

### Version with bug

v0.7.1.88

### Last version that worked well

Always like this

### Affected platforms

Windows, macOS

### Did you find any workaround?

No.

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by Arufonsu** [comment]
bounded skills aren't meant to be removed, they are bounded to the player after all, at least, this is the intended behavior **so is not a bug** - in the other hand, event should be able to remove them from players, since bounded spells should be un-removable **only** by players ; but from what can be seen in the code side, this wasn't the intended behavior (it seems) ; this could be more likely an enhancement request, since the feature is currently working as expected ❓

**Comment by SilverShardOnline** [comment]
My comment would be that you are able to removed Bound Items from a player. 
It is inconsistent to not be able to remove a Bound spell in the same manner.
As well, without it it makes the 'Bound' feature on spells extremely limited and not easily fixable through administrative means.

**Comment by Arufonsu** [comment]
> My comment would be that you are able to removed Bound Items from a player. It is inconsistent to not be able to remove a Bound spell in the same manner. As well, without it it makes the 'Bound' feature on spells extremely limited and not easily fixable through administrative means.

Well, this makes sense, restored the bug label even though this is not technically a bug, but it could indeed have some QoL change for sure 👍🏽

**Comment by NikoCummings** [comment]
I too would love to see this added as well, so you can make class-specific skills that upgrade when you reach a certain level. Remove the bound spell and add a new bound spell which is the upgraded spell.
