### ISSUE TITLE
bug: Removing/Changing position of Lights [L] in editor doesn't function correctly

### ISSUE THREAD

**Issue by SilverShardOnline** [AscensionGameDev/Intersect-Engine#1716]
### Description

I'm not sure which update this bug took place (my bad for not reporting sooner) but sometime in 7.1

Editing a map with Lights already placed, will cause the incorrect light to be deleted/moved.
This bug also happens when moving lights - both on single/multi layer edits.

It actually looks like it's also duplicating the light tile as well:
https://user-images.githubusercontent.com/110916959/215350302-55c9b03c-fe5c-47b5-8c30-7b979366a9aa.mp4

### Steps to Reproduce

1. Add light to map via editor
2. save map
3. Try to update those lights

### Version with bug

v0.7.1.88

### Last version that worked well

Bug was introduced sometime in 7.1 I believe.  A few months back at least.

### Affected platforms

Windows, macOS

### Did you find any workaround?

no

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by Richy1111** [comment]
Happens to me on a current, 7.1.117

**Comment by LunamOdium** [comment]
Same

**Comment by delpu** [comment]
I have the same problem on latest build
