### ISSUE TITLE
bug: _cast paperdoll sprites not rendering

### ISSUE THREAD

**Issue by Orinorii** [AscensionGameDev/Intersect-Engine#1721]
### Description

I've spent the last few days troubleshooting what could be causing this, but _cast paperdoll images just simply don't work for me in the base engine atm. _attack, _shoot, and _idle work fine but when casting a spell it just plays the entirety of the default walking animation. No modifications have been made and I have confirmed that everything is configured correctly.

### Steps to Reproduce

1. Create a spell
2. Create a paperdoll with a _cast suffix
3. Cast the spell

### Version with bug

Current

### Last version that worked well

N/A

### Affected platforms

Windows

### Did you find any workaround?

No

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by Arufonsu** [comment]
Related:

https://github.com/AscensionGameDev/Intersect-Engine/blob/387d22f7c3b0aab8c4cca5907f174c1db33f38a4/Intersect.Client/Entities/Entity.cs#L1097-L1104
