### ISSUE TITLE
bug: clipped fog when walking through maps 

### ISSUE THREAD

**Issue by NikoCummings** [AscensionGameDev/Intersect-Engine#1726]
### Description

Fogs are getting a straight edge cut off/clipping when you sometimes transition from maps. This happens even when you use the same fogs and effects from map to map. You expect this to keep looping repeating instead of having a hard edge where the fog stops. Here's a video of the issue: https://s3.us-east-2.amazonaws.com/ascensiongamedev/filehost/f6a46375b0fce9fef415ffccd5660000.mp4

### Steps to Reproduce

Create 6 maps in a straight line
add some fog and effects
make sure they are identical on all 6 maps
load the client and run through the six maps
notice the "clipping"

### Version with bug

0.7.1.92

### Last version that worked well

unkown

### Affected platforms

Windows

### Did you find any workaround?

No.

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by Arufonsu** [comment]
Oh, forgot to undo my attempt to reduce the amount of fog when i was trying to fix it's behavior. I will open a pull request to revert the changes and bring back the former values to prevent this from happening again.
