### ISSUE TITLE
bug: Crafting Station UI: Ingredients not listed.

### ISSUE THREAD

**Issue by HangryGerbil** [AscensionGameDev/Intersect-Engine#1728]
### Description

When creating a craft that has more than one required ingredient the UI in the Crafting Station is only showing 1 ingredient to players under the required section. So a player can't see the other ingredients needed to craft an item. I did a fresh install of 0.7.1.101 Beta and reproduced the bug in the attached video. 
https://youtu.be/9-bPq1eQ70o

### Steps to Reproduce

1. Create at least 3 items. One Item to be a craft and 2 items to be the ingredients.
2. Create a Craft for the item you want crafted and add the 2 ingredients to its ingredient list.
3. Crate a Crafting Table and add the item to be crafted to its list.
4. Add an event to open a crafting station for the crafting table you just created.
5. Save in the editor and swap over to the client. Trigger the event for the crafting station.
6. You will see your item to be crafted however only the last ingredient it the items ingredient list will show in the UI. 

### Version with bug

0.7.1.101 Beta

### Last version that worked well

Unknown

### Affected platforms

Windows

### Did you find any workaround?

No, I have not found a work around. I would assume there is an issue with the loop that is listing each of the ingredients for the Crafting Station UI. I am new to programming though so had trouble trying to locate an issue. 

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by Arufonsu** [comment]
Probably related to this bug:

https://github.com/AscensionGameDev/Intersect-Engine/commit/3abbc2d7f34ddc85065778a393e658dc7d142a65#diff-ad8657225ca17fc60146b68c20777fbe1ee2b81ad4eb0aac41e7883434fcb91c

https://github.com/AscensionGameDev/Intersect-Engine/commit/3abbc2d7f34ddc85065778a393e658dc7d142a65#diff-65d1297ef1b66fc4b334853af5764ec187848c980cc9a0dbbaa6ef2c23efd89e

**Comment by Arufonsu** [comment]
Thanks for reporting this issue, in addition to a possible (and tested to be working) fix (#1729), i've shared over a minor [QoL enhancement for the craft window ingredients here](https://github.com/AscensionGameDev/Intersect-Assets/pull/38)
