### ISSUE TITLE
bug: 'Ghosting' Target Box after entity death

### ISSUE THREAD

**Issue by SilverShardOnline** [AscensionGameDev/Intersect-Engine#1730]
### Description

Targeting an NPC, then killing it will make the target box appear 'ghosted' when trying to target another NPC (if there are no other NPCs to target)

Targeting a new NPC will clear the ghosting target box.

Video: https://youtu.be/7H-Yc1CGyls

### Steps to Reproduce

1. Make a map with 1 NPC
2. Target NPC, then kill it.
3. Try to target when there are no targets.

### Version with bug

v0.7.1.88

### Last version that worked well

Unknown

### Affected platforms

Windows

### Did you find any workaround?

no

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by Arufonsu** [comment]
0:25 -> is this what you mean by 'ghosting' targetbox (?)

![Screenshot_20230226_231938](https://user-images.githubusercontent.com/17498701/221456932-d4142c38-1949-457a-9cf7-33d44efcb35a.png)

**Comment by WeylonSantana** [comment]
i tested, is true
