### ISSUE TITLE
Introduce PM button instead of double-click-to-PM in Friends List

### ISSUE THREAD

**Issue by ghost** [AscensionGameDev/Intersect-Engine#174]
**Describe the bug**
I noticed that to activate /pm in the chat we must double click on the friend's name in the friends tab, however it doesn't always work.

**Version Encountered**
0.6.2.0 (LAST DEV PULL)

**To Reproduce**
Clicking on the friend's name sometimes doesn't work, it only works if you keep clicking and moving the mouse at the same time

**Expected behavior**
Give 2 clicks and work.

**Operating System:**
Windows 10

**Comment by lodicolo** [comment]
Questionably a bug.

Double click is poor UX design, correct solution is to introduce a PM button that requires a single click.

**Comment by lodicolo** [comment]
Restored issue.

**Comment by jcsnider** [comment]
It never required double click.. due to another bug fixed by #328 the list was always refreshing so you just had to click a lot for it to ever possibly work.
