### ISSUE TITLE
Target selection using mouse is difficult

### ISSUE THREAD

**Issue by ghost** [AscensionGameDev/Intersect-Engine#175]
**Describe the bug**
I noticed that to select the target with the mouse it is very difficult, it does not always work, maybe it is with the npc walking or target walking is more difficult, but it is very strange

**Version Encountered**
0.6.2.0

**To Reproduce**
Going into combat with the target and trying to select with the mouse, I know that TAB exists as a shortcut, but if you have more targets it gets complicated. It should be easier to select the target with the mouse i...

**Expected behavior**
Some way to more easily select the target with the mouse, may not always be able to select the target.

**Operating System:**
Windows 10

**Comment by lodicolo** [comment]
Per the description this doesn't have enough information to be considered a bug, and fits an enhancement better (functionality exists and works but is difficult to use).

**Comment by lodicolo** [comment]
Restoring bug.
