### ISSUE TITLE
Server is not saving the database

### ISSUE THREAD

**Issue by ghost** [AscensionGameDev/Intersect-Engine#176]
**Describe the bug**
I noticed that every time I shut down the server by typing * exit * on the console, some players went back 1 level. it seems to me that this function is not saving the database.

**Version Encountered**
0.6.2.0

**To Reproduce**
Leave the server online, guys playing upando, if you turn off the server right after someone level up, that level will come back when the server starts again

**Expected behavior**
A safe way to save the server whenever it is closed.

**Operating System:**
Windows 10

**Comment by ThousandX** [comment]
This bug is killing me... Using SQLITE every server shutdown, its dont save the player level

**Comment by lodicolo** [comment]
Duplicate of #120
