### ISSUE TITLE
bug: Player can't attack while moving when AllowCombatMovement = False

### ISSUE THREAD

**Issue by SilverShardOnline** [AscensionGameDev/Intersect-Engine#1760]
### Description

Walking then pressing the attack key will cause the player to show attack/shoot animation without playing the sound or performing the attack action.

This only occurs when Server Config is set to AllowCombatMovement = False

https://user-images.githubusercontent.com/110916959/224115932-d9407668-74b6-48e8-a03c-ba66098f2e01.mp4

### Steps to Reproduce

1. Confiq server to AllowCombatMovement = False
2. Hold a walking direction key
3. Press attack key while walking

### Version with bug

v7.1.115

### Last version that worked well

v7.1.115

### Affected platforms

Windows

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by WeylonSantana** [comment]
the option name is AllowCombatMovement
if true, then you **can** attack and walk
if false, then you **can't** attack and walk
I don't understand what's up? the point would be that the animations should not be shown?

**Comment by jessidion** [comment]
Um, this is intended, you literally set Combat Movement to false

**Comment by SilverShardOnline** [comment]
**I did not explain this well.**

The bug happens when you have "AllowCombatMovement" = False (Player should NOT be able to attack while moving)
The animation of attacking will still play, and will play if the player is moving (neither should happen)

The actual attack does not happen though - ONLY the attack animation (no sound is played)

In the video posted: 
> First attacks are standing still (and everything is correct)
> The following attacks are moving (you can see the animation play without sound or the arrow being fired)

I don't use this option, so it's not important to be personally, but is a bug none the less.
