### ISSUE TITLE
Ghost of offline players not removed from map

### ISSUE THREAD

**Issue by ghost** [AscensionGameDev/Intersect-Engine#177]
**Describe the bug**
Player are offline and showing on the game :D

**Version Encountered**
0.6.2.0 (LAST DEV PULL)

**To Reproduce**
N/A

**Screenshots**
![Screenshot 11](https://user-images.githubusercontent.com/21990960/80256899-1a9c9400-8656-11ea-928f-503ab2f513b8.png)

**Operating System:**
Windows 10

**Comment by lodicolo** [comment]
@jcsnider Players appear to get stuck in the game when they disconnect in combat, I think these are related.

**Comment by lodicolo** [comment]
Restoring bug.

**Comment by jcsnider** [comment]
Can't repo. Potentially caused by a rouge mod or something. Going to close until a better report becomes available if this is actually a base engine problem.
