### ISSUE TITLE
Allow clipboard access in chat

### ISSUE THREAD

**Issue by ghost** [AscensionGameDev/Intersect-Engine#178]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Allow users to use the clipboard in chat.

**Comment by lodicolo** [comment]
Restored issue.

**Comment by Azurebeats** [comment]
Does anyone have an idea as to how to support this?
The easiest way I can find would be https://github.com/CopyText/TextCopy

Problem with that, is that it needs a Linux dependancy. (xclip)
Not sure if that's something we're willing to burn our hands on?

**Comment by Azurebeats** [comment]
Some testing done with that library, and you can try/catch the xclip dependancy and throw an error with it on your own terms, so no hard crashes.

Sadly, the lib simply seems to lock up the entire application waiting for the command to finish.. when it never does, even on the Async version.

**Comment by Azurebeats** [comment]
Even more testing done, the library works on anything that DOES NOT use Wayland, but X11.
Anything non-X11 will simply hang the application until the user manually copies something from a different application.
Have not been able to resolve or work around this using anything yet.

**Comment by jcsnider** [comment]
In the client we already have an OS check for dependency export.. maybe we use the TextCopy library but if the OS is Unix and the UName isn't Darwin (OSX) then we just set a flag to disable copy/paste on that platform?

https://github.com/AscensionGameDev/Intersect-Engine/blob/a384580f78e40665613550d60a60f2b0fbec25a0/Intersect.Client/Program.cs#L134-L143

**Comment by Azurebeats** [comment]
Hmm, that might work. So a global value that holds an enum like Platform.Linux, Platform.MacOsx, Platform.Windows.

Could be reused for future platform specific code as wwll. If we do it as such.

**Comment by Azurebeats** [comment]
Okay, so I ended up writing this.. Since alternatives just wouldn't work: https://gist.github.com/Azurebeats/4eab7a0317f0edbd2156ccaf5780d3ed

Still need to test this on Mac and a non-Wayland desktop, but it works on Windows and Ubuntu so far.

**Comment by Azurebeats** [comment]
Resolved with #340 and #341
