### ISSUE TITLE
enhancement: trigger cooldown timer when equiping/unequiping items for event commands

### ISSUE THREAD

**Issue by LunamOdium** [AscensionGameDev/Intersect-Engine#1789]
### Description

When you have an equipment item with a cooldown timer and equip it via an event command(instead of equiping it from inventory), it does not initiate the cooldown timer.

### Steps to Reproduce

1. Create an equipment item with a cooldown(30000ms to give yourself plenty of time to see it)
2. Create an event with the Equip/Unequip Item Command to equip the new item
3. Observe that the cooldown timer is NOT active.

### Version with bug

7.1.116

### Last version that worked well

Unknown

### Affected platforms

Windows, I was *not* able test on other platforms

### Did you find any workaround?

I did not find any sort of workaround.

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by Arufonsu** [comment]
The question with this one is: _Do we really need / want cooldown timers when Equiping/Unequiping via events?_

I don't know if i would call this a "bug" either 🤔 cooldown timers already exists for the regular gameplay/input of players, this sounds more like we would need to _**enhance** events to allow cooldown timers when Equiping/Unequiping_
