### ISSUE TITLE
bug: 'Learn x spell' option is hardcoded for spell items within the inventory context menu

### ISSUE THREAD

**Issue by PyroTech03** [AscensionGameDev/Intersect-Engine#1803]
### Description

When an item setup to cast a spell effect, the right-click menu still displays "Learn Spell" instead of option to use the item. Clicking to learn still uses the item as intended, so seems like just a UI issue. 

### Steps to Reproduce

Create spell
Create item using spell
Right-click item

### Version with bug

Main

### Last version that worked well

Unknown

### Affected platforms

Windows, I was *not* able test on other platforms

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by Arufonsu** [comment]
Thanks for reporting, i've identified where the issue is at and i'll submit a simple change that fixes this behavior so we can alternate between "learn x spell" and "cast x spell" when corresponding 👍🏽
