### ISSUE TITLE
bug: The conditional branch 'Has item' is broke

### ISSUE THREAD

**Issue by Gibier1** [AscensionGameDev/Intersect-Engine#1815]
### Description

The conditional branch 'Has item' with the variable option is broke and don't select the right variable.

### Steps to Reproduce

create a conditional branch wit h 'Has item' and select and variable option. 

### Version with bug

7.2.14

### Last version that worked well

Unknown 

### Affected platforms

Windows, I was *not* able test on other platforms

### Did you find any workaround?

Random test the variable until it give you the right one xD

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by SilverShardOnline** [comment]
This bug appears in 7.1.119.
Looks like it will select the incorrect variable from the list instead of the one you select.

I.e. I choose "Has Item" with variable "Variable A" and it will appear as if I selected "Variable M" instead.
