### ISSUE TITLE
bug: strained estrangement movement in front of the collision

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#1824]
### Description

As the title says, the movement is weird

### Steps to Reproduce

Make a straight line with the collision block
keep pressing left, down, left, down constantly or vice versa
see the bug

https://github.com/AscensionGameDev/Intersect-Engine/assets/1476550/9d825fba-b8d2-421f-93e8-be5fe6296dcc

I would expect smooth movement or something similar

### Version with bug

v7.2.18

### Last version that worked well

Unknown

### Affected platforms

Windows

### Did you find any workaround?

nops

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by Arufonsu** [comment]
i'm unable to see the video nor reproduce 😢

**Comment by Arufonsu** [comment]
related: https://github.com/AscensionGameDev/Intersect-Engine/issues/1763

**Comment by lodicolo** [comment]
Combining into #1763, also replaced the video with one with the audio stripped.
