### ISSUE TITLE
bug: issue with projectile diagonal directions

### ISSUE THREAD

**Issue by Orinorii** [AscensionGameDev/Intersect-Engine#1827]
### Description

Something in the last couple updates seems to have broken projectiles. They no longer fire in the configured direction when fired by NPCs. 

https://www.ascensiongamedev.com/resources/filehost/351d1d8297852da08c717ae4eeedb95e.png

### Steps to Reproduce

1. Make Projectile
2. Assign it to NPC
3. Watch projectile not work properly

### Version with bug

Current

### Last version that worked well

Don't know exact patch, a few a go though

### Affected platforms

Windows

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by Orinorii** [comment]
To update this, I found the specific issue, the back two diagonal tiles in the projectile editor are actually reversed, so theyre shooting backwards. This can be worked around until a fix is applied

**Comment by Arufonsu** [comment]
Tested and reproduced, looking into this right now 👍🏽
