### ISSUE TITLE
Bug in the cast frame in projectile spells (Intersect 6.2)

### ISSUE THREAD

**Issue by Kaizos** [AscensionGameDev/Intersect-Engine#183]
**Describe the bug**
magic frame is buggy, if you choose magic as projectile, instead of activating the cast frame, activate the shoot frame, I believe that the system recognizes the projectile magic as shoot

sorry for my English

**Version Encountered**
Intersect Engine v6.2

**To Reproduce**
Just use a projectile spell, not for cast frame, but for frame shoot

**Expected behavior**
Not
**Screenshots**

**Logs**
If there are error logs please attach them below.
I don't think the need

**Operating System:**
Windows 7

**Additional context**
As there are spells that use a bow, I believe that there would have to be an option to select the type of cast, being able to use for example the cast weapon as a physical skill
Thanks

**Comment by jcsnider** [comment]
This is intended. If you are 'shooting' anything whether it be from an item or spell we intentionally show the 'shoot' animation.

**Comment by alloin** [comment]
@Kaizos cheap fix: https://i.imgur.com/8DCy97T.png

**Comment by Kaizos** [comment]
thanks
