### ISSUE TITLE
Give and take item enhancements

### ISSUE THREAD

**Issue by da-rulez** [AscensionGameDev/Intersect-Engine#185]
**Is your feature request related to a problem? Please describe.**

Right now you need several extra event systems to handle giving and taking multiple items. The system could do with some extra functionality to make this event command a bit more flexible. 

For example: If you want to give 3 different items, you need to check if the player has at least 3 inventory spaces free before you can go on with the event. 

**Describe the solution you'd like**

An extra event command: 

Has at least X open inventory slots. X is set by dev and the event would continue based on wether or not this check failed or succeeded.

Give item command toggle: 

Drop items on floor. -> Would drop the items on the floor if the player received more items than can be held. 

Add another Take / Give Item option:

Max item -> Would take or give as many items as possible. If the player has 10 potions, the event command would take 10. If the player has 5 potions, the event would take only 5. Giving works the same, but would need some check so it won't crash by trying to give too many of a stackable item.

**Comment by Azurebeats** [comment]
This was merged into development yesterday but didn't automatically close the issue.
