### ISSUE TITLE
More waits.

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#186]
**Is your feature request related to a problem?**
Nop

**Describe the solution you'd like**
I believe it would be great, if there were these 3 commands in the "etc" area where there is only "wait ..."
There could be
"Wait for animation to complete"
"Wait for the sound to complete"
"Wait for bgm completion"

I use a lot, for example, playing sound effects (birds singing during the day). And I use that as a common autorun event. Then I have to put a wait command and then put the exact amount of time of the song in milliseconds, so that it will play 1 time and wait for it to run out before playing again. This surpasses the map properties, so that I can play a sound only in the morning, when the birds sing.

For animation it would be the same. It is something that I would like very much, but I don't use, mainly for cutscene. But I can't use it because my computer's performance is poor, the animation renders slower than faster computers. An animation that would be 1 second for me does not last 1 second on powerful computers, so without being able to guess the exact duration of the animations, my hands are tied because there is no command to execute another command only after the animation is played.

These commands that I mentioned above could work in the same way as "wait for route completion" when we use the "define route" command. A command that only works if an animation was executed before it, a sound was executed through a command.

**Comment by Azurebeats** [comment]
I doubt the event system would have a way to hook into most of this without some weird changes, as the server doesn't keep track of this at all.

**Comment by jcsnider** [comment]
Yeah, there's no way for the server to know how long a song is, or sound. It could technically calculate an animation time.. I guess.. but that isn't something I'm interested in adding.

**Comment by WeylonSantana** [comment]
I understood.
