### ISSUE TITLE
feature: Add Fullscreen shortcut

### ISSUE THREAD

**Issue by BrindiWanko** [AscensionGameDev/Intersect-Engine#1868]
### Description

Hello,
I have an Idea, why not Add an Fullscreen buttons on the game juste in top right on the game ?
Because i think the actually option IS hidden on many menu
Regards,

### Intended Use-Case

Add an buttons when the player click the game switch to fullscreen or windows screen

### Duplicate Check

- [X] This feature request is not a duplicate to the best of my knowledge.

**Comment by lodicolo** [comment]
I won't add (yet another) UI button that isn't going to be regularly interacted with, but since many games offer a keyboard shortcut to to this I made a keyboard shortcut to enable this win #1873
