### ISSUE TITLE
Can drop bags with item in it when storing an equipped item

### ISSUE THREAD

**Issue by Azurebeats** [AscensionGameDev/Intersect-Engine#191]
**Describe the bug**
After storing an item you had equipped into a bag, the bag can be dropped.

**Version Encountered**
0.6.2.416

**To Reproduce**
1. Equip an item.
2. Store the equipped item into a bag without unequipping it.
3. Drop the bag, and see that you can (sometimes).

It doesn't always let me do this either, but something DBhandler.GetBag seems to return null when one definitely exists, thus skipping over the check to see if the bag is full.

Also noticed that sometimes the ItemId is just not filled in on bags I'm trying to drop to the map.
Oddly enough I can't reproduce this with any other item type.. Or haven't yet at least.

**Expected behavior**
You should **NOT** be able to drop a bag containing items.

**Screenshots**
![Preview](https://s3.us-east-2.amazonaws.com/ascensiongamedev/filehost/91b01157204be4a119c722efca2e3c68.gif)

**Comment by lodicolo** [comment]
This should be fixed.
