### ISSUE TITLE
bug:  projectile freezing when there are no players on map, resume moving when players return

### ISSUE THREAD

**Issue by Richy1111** [AscensionGameDev/Intersect-Engine#1912]
### Description

Weylon — Today at 3:06 PM
lol
[3:07 PM]
What happens is, if there are no players on the map, everything "freezes", when the players return, it continues where it left off
[3:07 PM]
"freezes" because there is only processing where there is a player
[3:08 PM]
map update() does not execute if there is no player on the map

I myself could not reproduce the projectile freezing because I made a VERY slow projectile. MAX Long animation timer makes it look like it's not moving.

At 100 seconds. It still processes when I leave a connected map, it gets removed when I warp out and warp back in, it stays processing when I walk out of the map rendering grid and walk back into it.

### Steps to Reproduce

1. Weylon knows better than I do at this point.

### Version with bug

7.2.59

### Last version that worked well

Unknown

### Affected platforms

Windows

### Did you find any workaround?

Stop making animation timers with MAX Long settings lol.

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by Arufonsu** [comment]
There's been a lot of updates, upgrades and behavior fixes for projectiles lately and there's been no other user able to reproduce this too, please feel free to reopen the issue if this happens again, if you can provide a video showing the unwanted behavior, even better!
