### ISSUE TITLE
bug: API Guild Variables endpoint don't work

### ISSUE THREAD

**Issue by Thomasfds** [AscensionGameDev/Intersect-Engine#1925]
### Description

I try to use guild endpoint from API (it's on my local computer) :

[Route("{guildId:guid}/variables")] => Real data : http://localhost:5400/api/v1/guilds/f955611d-333e-4f2b-9997-aa3de8e2cd9e/variables

And server return only : [] ?

![image](https://github.com/AscensionGameDev/Intersect-Engine/assets/48243771/7f4bd65c-2556-470a-a6fe-ef6d5d770524)

As you can see from the VS Studio 
![image](https://github.com/AscensionGameDev/Intersect-Engine/assets/48243771/1332270a-360c-4522-830c-733dcfb6abab)

### Steps to Reproduce

1. Enable API on your Server
2. Create Guild Variables
3. Request endpoint for get all guilds variables

### Version with bug

v7.2.64

### Last version that worked well

Unknow

### Affected platforms

Windows

### Did you find any workaround?

No, and from what i see on the code in Github all is good in this way..

### Relevant log output

```shell
No log for this error found.
```

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by lodicolo** [comment]
Unable to reproduce on [v0.8.0-beta.28](https://github.com/AscensionGameDev/Intersect-Engine/releases/tag/v0.8.0-beta.28).

If you are still able to reproduce this, please provide definite proof that the guild in question actually has variables in the database. If there are no variables in the database, it doesn't have any and the array _should_ be empty.

Once you have that additional supporting evidence on the latest version of Intersect please re-open this (don't re-open this if you can't reproduce it on the latest, we don't have enough developers to support multiple versions).
