### ISSUE TITLE
bug: Typo on Event Command "Set Variable" 

### ISSUE THREAD

**Issue by PyroTech03** [AscensionGameDev/Intersect-Engine#1926]
### Description

![Intersect_Editor_FL7o05bdvp](https://github.com/AscensionGameDev/Intersect-Engine/assets/13249558/42f808c7-fdea-4e5c-9322-ddd13a23bbae)
Double instance of "Global Variable" value.  Second should be "Guild Variable".

### Steps to Reproduce

1. Open event editor
2. Add Set Variable command.
3. Use any operator on an integer variable.

### Version with bug

7.2.0

### Last version that worked well

Unknown

### Affected platforms

Windows

### Did you find any workaround?

Functionally it still works as intended.

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by Arufonsu** [comment]
hmm unable to reproduce

**Comment by Arufonsu** [comment]
hmm, unable to reproduce:
![imagen](https://github.com/AscensionGameDev/Intersect-Engine/assets/17498701/f98ea75e-184c-446f-86ff-3518dff3168d)

this was probably fixed back then and you are using an outdated localization file, try to delete your editor_strings.json file, it should look like after reloading the editor (which will make it so the editor re-created and updated file):
![imagen](https://github.com/AscensionGameDev/Intersect-Engine/assets/17498701/46068b6b-849f-42fe-b930-dba760b2591e)

**Comment by PyroTech03** [comment]
Yea, mines likely not updated. Thanks!
