### ISSUE TITLE
bug: Problem with Zooming out

### ISSUE THREAD

**Issue by NikoCummings** [AscensionGameDev/Intersect-Engine#1933]
### Description

When  you zoom out, the maps on either side of the screen are not always loading unless you walk closer to trigger the engine to load them. I'm running on 1920x1080, 32x32 tiles, map size in the server config is 26 tiles by 32 tiles which I believe is the default.
![20231006-2055476220](https://github.com/AscensionGameDev/Intersect-Engine/assets/10820240/9be64b4e-8062-43c9-9ff5-c05fb3bd23c0)
![20231006-2050356230](https://github.com/AscensionGameDev/Intersect-Engine/assets/10820240/69a91214-5012-460d-a759-e318e489e4d5)

### Steps to Reproduce

zoom out
notice the maps not loading

### Version with bug

0.7.2.0

### Last version that worked well

before zoom feature

### Affected platforms

Windows

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by lodicolo** [comment]
We never got sufficient information on this in Discord and it's not possible to zoom out when on 32x32 tiles.
