### ISSUE TITLE
enhancement: make server runnable as a service or in docker without screen

### ISSUE THREAD

**Issue by lodicolo** [AscensionGameDev/Intersect-Engine#1935]
### Description

When running headless without screen, the lack of stdin translates to a `null` return when trying to read the console input.

This is a shortcut to shutdown the server like `exit`, and immediately shuts the server down as soon as it polls for input.

### Intended Use-Case

Allowing headless running without `screen` as a Linux service (e.g. systemd unit) or Docker service

### Duplicate Check

- [X] This enhancement idea is not a duplicate to the best of my knowledge.

**Comment by Arufonsu** [comment]
This is from some tests i did back then in 7.2 (around May ish):

```dockerfile
FROM mono:latest

EXPOSE localhost:5400:5400/udp

ENV HOME /root
ENV USER root
ENV APP_DIR $HOME/intersect-server

USER $USER:$USER
ADD ./Intersect.Server/bin/Release/net462 $APP_DIR

WORKDIR $APP_DIR

RUN set -eux \
    && chown -R "$USER:$USER" "$APP_DIR" \
    && apt-get update && apt-get upgrade -y

VOLUME ${APP_DIR}/resources/
VOLUME ${APP_DIR}/logs/

ENV LD_LIBRARY_PATH=.

CMD ["/usr/bin/mono", "/root/intersect-server/Intersect Server.exe"]
```

![imagen](https://github.com/AscensionGameDev/Intersect-Engine/assets/17498701/42293ce5-d9fb-4edd-80c9-7e7fdd0939b9)

![imagen](https://github.com/AscensionGameDev/Intersect-Engine/assets/17498701/6e390028-0ebd-4f81-bb62-15d0e3ac301e)

**Comment by lodicolo** [comment]
Uh... this already exists. It's existed since 0.6-beta (https://github.com/AscensionGameDev/Intersect-Engine/commit/01e65972c57d6525ba2a8d4be9b29ee9770a633b). :joy: 

![image](https://github.com/AscensionGameDev/Intersect-Engine/assets/1476550/15dfa256-f529-4d48-8e44-c9dcd5344885)

Just use `--no-console`.
