### ISSUE TITLE
bug: The computed authentication tag did not match the input authentication tag.

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#1968]
### Discussed in https://github.com/AscensionGameDev/Intersect-Engine/discussions/1967

<div type='discussions-op-text'>

<sup>Originally posted by **EspectroW94** October 15, 2023</sup>
I really don't know what this error means, but I'm leaving it here in case something is wrong, it can be corrected.

![Captura de pantalla 2023-10-15 182457](https://github.com/AscensionGameDev/Intersect-Engine/assets/127634629/e153cbf6-1130-4b02-9e73-082747a1747e)
</div>

**Comment by lodicolo** [comment]
This was moved to a diagnostic last week
