### ISSUE TITLE
bug: Wrong selection position on the events page?

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#1969]
### Description

seems positioned a little higher
![image](https://github.com/AscensionGameDev/Intersect-Engine/assets/63019821/3e11a7ba-f944-4c76-98b2-e6189265a314)

### Steps to Reproduce

open event editor

### Version with bug

0.8.0.14

### Last version that worked well

Unknown

### Affected platforms

Windows

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by Richy1111** [comment]
The save/cancel buttons are hidden under the task bar at a 1366x768 resolution. This can hinder users that have older displays that can't go higher than 768px.

![ApplicationFrameHost_DK0gchRB6O](https://github.com/AscensionGameDev/Intersect-Engine/assets/72468758/3fb70c0d-4b1f-45e8-83c9-8dd70b1a6603)
![Nv2jcbtDnV](https://github.com/AscensionGameDev/Intersect-Engine/assets/72468758/b589d798-e58b-46f0-a38b-c1a628aabd03)

**Comment by WeylonSantana** [comment]
It is worth mentioning that the size of the windows were not modified, but it seems that in the transition from b7 to b8 they apparently "zoomed"?

**Comment by Richy1111** [comment]
Yeah, editor sizes were fine on 0.7.2.65. The transition to B8 somehow mutated them lol.
