### ISSUE TITLE
Party bug/Crash

### ISSUE THREAD

**Issue by Crovax40** [AscensionGameDev/Intersect-Engine#197]
hello the problem In game when we do not make a Party between player it works, but when we start to make a Party between player is that click on the Party icon the game crashes and we leave the game

**Comment by Crovax40** [comment]
the problem comes multi class except the aspiring all my other class crash when clicking on Party

**Comment by Azurebeats** [comment]
You should probably follow the template given to you when reporting this issue .

And maybe try to show what you mean? I'm not 100% sure I follow.

**Comment by jcsnider** [comment]
Template not followed. No logs or any real information to go off of. Closing this.
