### ISSUE TITLE
bug: we can move items from the other player's offer area

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#1970]
### Description

![image](https://github.com/AscensionGameDev/Intersect-Engine/assets/63019821/b930158e-3a2a-4177-8687-cdaa43e0e30c)

It's a strange behavior, we weren't able to move it to another area, just ours, the item returns to its original place, but it's better to prevent the drag from starting

### Steps to Reproduce

start trademove items from the other player's area

### Version with bug

0.8.0.14

### Last version that worked well

Unknown

### Affected platforms

Windows

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by Arufonsu** [comment]
we can't actually do anything in "our offering side" by dragging either, so dragging should be disabled on both ends
