### ISSUE TITLE
NPC's ignore spell requirements for Global Variable

### ISSUE THREAD

**Issue by da-rulez** [AscensionGameDev/Intersect-Engine#198]
**Describe the bug**

NPC's can cast a spell even though the Global Variable requirement is not met. Haven't tested for players or for other spell casting requirements

**Version Encountered**
0.6.1.252

**To Reproduce**
1. Make GV, set to 1
2. Make spell
3. Set spell casting requirement to GV = 2
4. Give spell to NPC
5. Watch NPC cast the spell even though GV =/= 2

**Expected behavior**

I expect NPC's to not ignore requirements

**Operating System:**
Windows

**Comment by Azurebeats** [comment]
Events aren't handled for anything but players.
So I'd imagine that's why they bypass checks like this as well.

Not sure if that can be considered a bug?

**Comment by jcsnider** [comment]
Had to dive into the code to confirm, but there are no code paths to check condition lists for non-players. So the condition lists should not apply or work for npcs making this, for now, not a bug.
