### ISSUE TITLE
bug: blackscreen with version 0.8.0

### ISSUE THREAD

**Issue by tarumes** [AscensionGameDev/Intersect-Engine#1982]
![grafik](https://github.com/AscensionGameDev/Intersect-Engine/assets/4124273/f970768c-58e0-403e-b289-8b27ce3526fa)
### Description

after creating an account when i try to login with client
just a black window

tested on windows, ubuntu, ~~steamdeck~~

last working version 0.7.2-beta.65

### Steps to Reproduce
A:
clean install
download 0.8.0-beta.xx version
start server
start client
create account
try to login

B:
also happen if you update last working version 0.7.2-beta.65 to any 0.8.0-beta.xx

### Version with bug

0.8.0-beta.1 to 0.8.0-beta.24

### Last version that worked well

0.7.2-beta.65

### Affected platforms

Windows, Linux

### Did you find any workaround?

no

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by theceltos** [comment]
Have you already checked if there are any tiles on the map, or image, try filling the map with a standard tile from the intersect?

**Comment by tarumes** [comment]
yes thats what i tired too painting everything with grass
when its done with a 0.8.0-beta.xx client/server the screen is still black
even UI cant be used/viewed

**Comment by lodicolo** [comment]
@tarumes

1. On Windows do you have both an integrated Intel Graphics and a dedicated AMD/Nvidia GPU?
2. On Linux:
  1. For just the "Linux" one, same question -- iGPU and a dedicated GPU?
  2. For both "Linux" and Steamdeck, which executable are you running? You should *not* be running an .exe
  
Linux (in particular Steamdeck) I would expect to work since I am running an Arch-based distro myself as my daily driver OS and everything works without any black screens.

**Comment by tarumes** [comment]
Intel HD Graphics 530 on windows and Linux (dualboot)
and yes i used the correct binarys for windows and linux ^^

**Comment by lodicolo** [comment]
@tarumes Do you not have a dedicated GPU, only Intel Graphics?

We already know from people who have both Intel HD Graphics 630 _and_ an RTX 3050 mobile chip that if they force Intersect to run on the RTX 3050 that it works, and it's only broken on the Intel HD Graphics.

Intel HD Graphics 530 may also be subject to a bad driver but I can't confirm if this is the case.

I do not know about Steamdeck though, I don't have one.

**Comment by tarumes** [comment]
you cant plugin a GPU into a laptop/thinclient that easy so no i have no way to upgrade the gpu

**Comment by lodicolo** [comment]
> you cant plugin a GPU into a laptop/thinclient that easy so no i have no way to upgrade the gpu

No, but many laptops come with both an integrated GPU and a dedicated GPU.

> steamdeck now magically works after updating it to beta branch

From the crash I saw on Steamdeck, SDL is failing to load GL functions. Not sure why, haven't managed to debug it.

When you say beta branch, do you mean the beta branch for the Steamdeck OS?

**Comment by lodicolo** [comment]
@tarumes Please try [v0.8.0-beta.37](https://github.com/AscensionGameDev/Intersect-Engine/releases/tag/v0.8.0-beta.37) on your Steamdeck.

**Comment by tarumes** [comment]
fixed in
https://github.com/AscensionGameDev/Intersect-Engine/releases/tag/v0.8.0-beta.36
for windows Intel GPU
and steamdeck also works

**Comment by lodicolo** [comment]
@tarumes I wonder if the Intel HD Graphics 530 driver was misreporting the multisampling it could handle (so it didn't crash immediately like Steamdeck) and so it blackscreened instead.
