### ISSUE TITLE
Getting Client Crash when in party and click Party Icon

### ISSUE THREAD

**Issue by AriusII** [AscensionGameDev/Intersect-Engine#199]
**Describe the bug**
Cause JC is super beautifull. no i'm kidding.

When you are on party ( 2+ ) and you click Party/Group Icon for Showing Group Menu getting :

**Version Encountered**
6.2.415 to 6.2.417

**To Reproduce**
Click on party icon when on party and HAVE FUN LOL

**Expected behavior**
Click = Crash

**Screenshots**

**Logs**
2020-05-06 18:53:45.244 [Error] 
  Message: La valeur était trop grande ou trop petite pour un Int32.
    Stack:    à System.Convert.ToInt32(Double value)
   à Intersect.Client.Interface.Game.PartyWindow.Update()
   à Intersect.Client.Interface.Game.Menu.Update(Boolean updateQuestLog)
   à Intersect.Client.Interface.Game.GameInterface.Draw()
   à Intersect.Client.Interface.Interface.DrawGui()
   à Intersect.Client.Core.Graphics.Render()
   à Intersect.Client.MonoGame.IntersectGame.Draw(GameTime gameTime)
   à Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime)
   à Microsoft.Xna.Framework.Game.Tick()
   à Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   à Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)

--------------------------------------------------------------------------------

->  Message: La valeur était trop grande ou trop petite pour un Int32.
Message: The value was too large or too small for an Int32.

**Operating System:**
Windows

**Additional context**

**Comment by jcsnider** [comment]
Any chance of recreating this bug with the .pdb files present that were compiled with that client?

The pdb files allow the logs to display error line numbers and may help in resolving.

**Comment by AriusII** [comment]
So I don't have download source or make anychange on it.

I downlaod the source ( 6.1 ? ) and compile with PDB ? right ?

**Comment by jcsnider** [comment]
When you compile the source.. or when you download a version from AGD there will be an Intersect Client.exe and Intersect Client.pdb file. Those two need to be named as such as in the same folder when running the client.

In theory you shouldn't have to compile, the official downloads will also have the error.

**Comment by AriusII** [comment]
I have : open the pdb with VS, attack to arcadia, and now it's saying me ' PartyWindows.cs '

**Comment by AriusII** [comment]
![image](https://user-images.githubusercontent.com/35581726/81326437-1df23f80-909a-11ea-8f20-7cb75dbe17c8.png)

**Comment by AriusII** [comment]
mMpBar[i]
                                .SetTextureRect(
                                    0, 0, Convert.ToInt32(mMpBar[i].Texture.GetWidth() * ratioMp),
                                    mMpBar[i].Texture.GetHeight()
                                );

**Comment by AriusII** [comment]
Ok found when this happen,

When your Character have 0 mana, it's making crash.
Change class with 0 mana to 1, tested and worked;

But I have creat a class when you hit you get Fury(~mana) so you start at 0.

**Comment by Azurebeats** [comment]
Found where it happens, we're dividing by zero and getting a NaN instead of a number.

Working on making a fix that functions like it does on the entity window now.
