### ISSUE TITLE
feature: additional options for item stats

### ISSUE THREAD

**Issue by AriusII** [AscensionGameDev/Intersect-Engine#200]
HEYLLOW it's arius <3 !
I would like to know if it's possible to add specifique settings about Stats for items.

**Is your feature request related to a problem? Please describe.**
The actual item editor settings can't allow a rand stat for specific Type , we can only put fix stats on items and that all. Us only choice it's a All Random stats ranges and this can put non wanted values ( cf : negative)
Like if I want make an item(armor)
defence : [5] - [8]
speed [-5] - [3]
( cf: I put Rand stats like 10, i can get -15 in speed and I don't want it.)

**Describe the solution you'd like**
Why in stats we cannot have a second choice ( textbox ) of stats
or
Having a Check box, for displaying the range choice, and get by default a Fix one.
Attack : [MIN] | [MAX] (..)
MIN could be the fix value, and let empty MAX for no range valuew
Exemple : 
Armor with defence : 
[MIN] - [MAX]
[50] - [75]
you can have defence  min 50 <-> 75 max
if armor with defence : 
[MIN] - [MAX]
[50] - []
Defence stat is fix and 50 is not gived by rand.

Final Point  with this we can having a random stats between thoses values.

**Comment by Uyarrr** [comment]
Yes, right now it's pretty useless tbh.

**Comment by WeylonSantana** [comment]
I fully support this idea, because check this out:
![image](https://user-images.githubusercontent.com/63019821/164734321-33283e65-5e6a-4d22-a9d2-3097f6d10691.png)

**Comment by WeylonSantana** [comment]
![image](https://user-images.githubusercontent.com/63019821/188699836-5404da21-aee2-4685-b2f8-8b2950101b98.png)
