### ISSUE TITLE
bug: Map stops rendering after walking for a while to any direction

### ISSUE THREAD

**Issue by hyzilion** [AscensionGameDev/Intersect-Engine#2027]
### Description

The world stops rendering at some point in-game. 

in-game:
![1231](https://github.com/AscensionGameDev/Intersect-Engine/assets/71110977/2f459c18-2c65-4e5e-9816-25d70cacaf9f)

on the engine:
![on engine](https://github.com/AscensionGameDev/Intersect-Engine/assets/71110977/f829afdb-e634-4e40-860b-cf52333c2cf5)

### Steps to Reproduce

1. Open the game
2. Walk to any direction for about 15-20 tiles
3. The map abruptly ends on a black screen and you can't walk any further

### Version with bug

0.8.0-beta.59

### Last version that worked well

Unknown

### Affected platforms

Windows

### Did you find any workaround?

No

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by theceltos** [comment]
Same here
![20231104-2039138990](https://github.com/AscensionGameDev/Intersect-Engine/assets/73917614/a8bebb3c-1395-48c1-a19c-5b04aaeddc8e)
![20231104-2039166060](https://github.com/AscensionGameDev/Intersect-Engine/assets/73917614/46330d05-8e69-4b2a-9f08-ecc9a17f9715)

**Comment by iceicebabyy** [comment]
too
![image (1)](https://github.com/AscensionGameDev/Intersect-Engine/assets/99568543/3e0467df-9312-4492-aa3e-04d1d1549d7f)
![image](https://github.com/AscensionGameDev/Intersect-Engine/assets/99568543/5d7867bb-6de8-41ed-b546-781fc883c8a0)
