### ISSUE TITLE
bug: SocketReceiveThread with array out of bounds exception

### ISSUE THREAD

**Issue by EspectroW94** [AscensionGameDev/Intersect-Engine#2041]
### Description

As far as I know, this doesn't really affect the gameplay, but if it can be solved I'll leave it here.

I currently have the version 0.8.0.61 but I saw that happens from the 0.8.0.60. I don't remember very well if it happened in the one I had before that.

I leave a screenshot of the console

![Captura de pantalla 2023-11-06 220319](https://github.com/AscensionGameDev/Intersect-Engine/assets/127634629/abcc9dc3-2032-4a83-a7d4-22697b79ac8d)

### Steps to Reproduce

1. log in
2.  ̶L̶o̶g̶ ̶o̶u̶t̶  Close the client

### Version with bug

0.8.0.61

### Last version that worked well

Unknow

### Affected platforms

Windows, I was *not* able test on other platforms

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by PyroTech03** [comment]
I am getting similar console outputs on build 61 as well.

**Comment by theceltos** [comment]
Same here...

**Comment by AudioSwamp** [comment]
Same here!
