### ISSUE TITLE
enhancement: shield spells do not scale with scaling stat, only give flat amount

### ISSUE THREAD

**Issue by Mcadams** [AscensionGameDev/Intersect-Engine#2118]
### Description

Giving a spell the "Shield" bonus effect will only make the shield as strong as the base amount, the shield does not scale with a scaling stat like other abilities do.

https://streamable.com/m32fpo

### Steps to Reproduce

1. Make a shield spell with a scaling stat and scaling amount
2. Cast the spell
3. The shield only applies the base amount of the spell, no scaling at all

### Version with bug

v.8.0.111

### Last version that worked well

Unknown

### Affected platforms

Windows

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by theceltos** [comment]
This bug really exists, and it would be great if it were fixed.

**Comment by WeylonSantana** [comment]
This is not a bug, is a enhacement resquest, the actual behavior is how it is supposed to be, because all effects also dont scale on anything

**Comment by theceltos** [comment]
AH yes, true, but as this magic would support the character or group, it should be scalable.
