### ISSUE TITLE
bug: Client connectivity status is not updated in real time in client side

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#2129]
### Description

https://github.com/AscensionGameDev/Intersect-Engine/assets/63019821/fada8439-2b09-4382-9ecc-5a28e29a084a

### Steps to Reproduce

close the server with the client open

### Version with bug

v0.8.0.119

### Last version that worked well

Unknown

### Affected platforms

Windows

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by lodicolo** [comment]
Not a bug, it pings every 15 seconds so as to not DDoS the server if a ton of people are just sitting on the login screen.
