### ISSUE TITLE
bug: redo settings window and fix guild info labels

### ISSUE THREAD

**Issue by lodicolo** [AscensionGameDev/Intersect-Engine#2141]
### Description

The settings window needs to  be redone with a proper window, and when it does it should be updated to have enough space for the `Show guild overhead information` and `Show guild overhead HP bar` labels to be changed to `Show guild member overhead information` and `Show guild member overhead HP bar`.

### Steps to Reproduce

N/A

### Version with bug

0.8-beta

### Last version that worked well

None

### Affected platforms

Windows, macOS, Linux

### Did you find any workaround?

If you restyle the settings window you can change the label, this is tracking fixing the defaults. Changing the label can't be done without it being cut off.

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by Arufonsu** [comment]
This has already been partially covered by #2252
https://github.com/AscensionGameDev/Intersect-Assets/pull/49 should fully fix this issue

**Comment by Arufonsu** [comment]
solved by #2252  and  https://github.com/AscensionGameDev/Intersect-Assets/pull/49
