### ISSUE TITLE
bug: xp bonus status on items does not work

### ISSUE THREAD

**Issue by theceltos** [AscensionGameDev/Intersect-Engine#2147]
### Description

As the title says, when setting a percentage of XP gain for an equippable item, it has no effect.

### Steps to Reproduce

Create an equipable item
Add XP bonus effect, ex 10%
Kill a monster.
You will not receive XP with a 10% bonus

### Version with bug

0.8.0.0

### Last version that worked well

Unknown

### Affected platforms

Windows, I was *not* able test on other platforms

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by TimtyG** [comment]
@theceltos I can't reproduce this on 0.8.0.114

**Comment by theceltos** [comment]
I managed to fix it, it was a bug that only happened to me, after my own modification in XP hehehe
