### ISSUE TITLE
bug: Equippable items do not show statistics.

### ISSUE THREAD

**Issue by cydyn** [AscensionGameDev/Intersect-Engine#2150]
### Description

Equipable items such as weapons or shields do not show statistics such as attack, defense, speed, etc. in the crafting window.

The bug occurred some time ago in version 0.7.2.

### Steps to Reproduce

1. Create a crafting scheme so that the final item is an equippable item
2. The equippable item must have these attack and defense stats
3. Once we have crafting ready, the game will not show its statistics in this window

### Version with bug

0.8.126

### Last version that worked well

0.8.0.0

### Affected platforms

Windows, Linux

### Did you find any workaround?

No.

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by cydyn** [comment]
https://github.com/AscensionGameDev/Intersect-Engine/issues/1987

Here the issue last time.

**Comment by cydyn** [comment]
To get around the problem in crafting, just add points in the statranges.
One is enough

**Comment by cydyn** [comment]
I discovered something.
If we add statranges to an item, save it in the editor, and then delete these points, the crafting window shows what statistics the item will have, but from - to. So 5/5
However, you have to do this with every item you want to put in crafting so that the statistics show up.
![Zrzut ekranu 2024-01-07 190307](https://github.com/AscensionGameDev/Intersect-Engine/assets/144380768/a680bbaf-194c-40fe-982e-d50dc4b1a619)

**Comment by EspectroW94** [comment]
Yes, it is indeed presenting this problem again.

**Comment by EspectroW94** [comment]
can't it be solved yet? Although it is not something that directly affects the gameplay, it does mean that when creating an item the statistics cannot be compared since it does not show them.

**Comment by cydyn** [comment]
@EspectroW94 They show. Add 1 point to the item in the new statistics window, save everything and go back to the item editor and delete these points. I think I explained how to get around it

**Comment by EspectroW94** [comment]
@cydyn I apologize, my native language is not English and perhaps I am not translating correctly, I do not understand very well what you mean by "Add 1 point to the item in the new statistics window" you could add some screenshots? Thanks in advance.

**Comment by cydyn** [comment]
@EspectroW94 
![Zrzut ekranu 2024-03-06 205411](https://github.com/AscensionGameDev/Intersect-Engine/assets/144380768/2a226a40-6bae-4a6c-96b3-be4cb980ff07)
For your item, add 1 point here.
Save everything, and delete these points.
Then you will be shown all statistics, even if it is 0.
It then also shows it like this: 5 to 5.
If you don't use random statistics, I recommend simply removing the second number from the client strings.

**Comment by cydyn** [comment]
@EspectroW94 
![Zrzut ekranu 2024-03-06 205827](https://github.com/AscensionGameDev/Intersect-Engine/assets/144380768/734983e7-ccbe-40e0-875d-2bd50d3b4fa8)

**Comment by EspectroW94** [comment]
@cydyn I see. I'll try it tonight, it still seems to me that it's still an error that shows the values ​​at 0, right?

But as long as it works, its fine for me. thank you so much.

**Comment by cydyn** [comment]
@EspectroW94 
After adding statranges, they are somehow connected to the constant statistics. The only error is showing 0, but when we add the values ​​0 to 5 in the statrange, it should also show 0. It's hard for me to explain, but it doesn't bother me, and it's better that it works than not at all.
