### ISSUE TITLE
bug: map cache issues when saving new maps

### ISSUE THREAD

**Issue by H0L0R** [AscensionGameDev/Intersect-Engine#2152]
### Description

If you create a map to the **left** or **up** from an existing map, they begin rendering wrong and glitching. For some reason 2 maps begin layering up on top of each other

how it sould be 
![image](https://github.com/AscensionGameDev/Intersect-Engine/assets/50377566/317f9ffe-f5f7-49f8-9331-c6608b8bc261)

how it is
![image](https://github.com/AscensionGameDev/Intersect-Engine/assets/50377566/bd8c42a8-e2c2-4203-82fa-8451b0a20f0b)

Also, when creating a map down from an existing one, camera doesn't move down to it, when you approaching it, but when you step on this map, it's all fixed, until you return on the first one.

### Steps to Reproduce

1. Create any unconnected map
2. Create a map on the left or up from an existing one

### Version with bug

0.8.0.126

### Last version that worked well

Unknown

### Affected platforms

I was *not* able test on other platforms

### Did you find any workaround?

Maps that are on the right from an existing one works perfectly fine and if you delete maps on top and on the left bag is disappeared.

### Relevant log output

```shell
When you logout, client says that connection to the server is lost, this is what logs said

2024-01-18 20:47:34.196 [Error] NotSupportedException: Unsupported localization type for Mapping.InstanceTypes: Intersect.Localization.LocaleDictionary`2[[Intersect.Enums.MapInstanceType, Intersect Core, Version=0.8.0.126, Culture=neutral, PublicKeyToken=null],[Intersect.Localization.LocalizedString, Intersect Core, Version=0.8.0.126, Culture=neutral, PublicKeyToken=null]]
```

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by H0L0R** [comment]
https://youtu.be/0rgHhlnrW8Y 

here is a video for better understanding

**Comment by AlexVild** [comment]
Here is what's happening:

[This pull request](https://github.com/AscensionGameDev/Intersect-Engine/pull/2101/files#diff-44230b27fb5b784cfc2c929bfab8d980d7b3835460bdcb203e3098036185938e) introduced logic for the client to better cache its maps, which in turn allows for a performance boost on the client.

However, it introduced a bug where the cache can get out of sync with the server's map grids. Essentially, if you add a map to the left of a map located at `[0,0]` with ID 123, while logged into that map with a client, the server/editor will now update that map's grid coordinates to `[1,0]`, BUT, the client will persist thinking that mapId 123 is located at `[0,0]`, which causes a plethora of problems on the client.

It's worth noting however that the database is sound, and the editor is okay. **This is a client-sided problem, albeit a severe one**.

To reproduce this bug:

1) Map editor. Make a map.
2) Log in, go to that map
3) Map editor. Make a map joining to the left of OR above your previous map
4) The client will freak out, and you will not have the correct map grid
5) No amount of client restarts will fix this. Restart the server.
6) On _first login_, the issue will persist
7) On the _next login_, the client will finally display properly

In theory, clearing the client's map cache (located at `AppData/Roaming/.intersect/<game executable name>/<server connection>/` or `~/.local/share/.intersect/<game executable name>/<server connection>/` on Linux) should fix this issue without the need for a server restart.

**Comment by cydyn** [comment]
I will add from myself. To fix the problem, at least temporarily, so that other players do not see this bug, just after resetting the server, use the admin account to completely render the map with your character (Teleport), and reset the server again. I checked with testers and no one had a problem then. So you need to remember to do this after adding the map on the left or top side.
