### ISSUE TITLE
bug : bank deposits equipped items without unequipping them

### ISSUE THREAD

**Issue by cydyn** [AscensionGameDev/Intersect-Engine#2155]
### Description

The problem is that when we have two non-stackable items, such as equipment, if we want to hide one of them, an input box appears asking how many items we want to hide.
The maximum number is immediately marked and we can put it in the bank. (using shift it immediately shifts both non-stackable ones)
If we have an equipped item and the other one is not equipped, and we click either using the contextbox or shift to hide the unequipped item, it will move both of them.
And now, if we take out another item, regardless of whether we meet the conditions to equip it or whether it is an item that cannot be equipped, it is equipped in the slot where we previously had the item (and now we don't have it because it is in the bank). .

The next problem is that it imposes HP and MP and ExtraBuffy on this item, so you can have over 100% MP or HP and you can equip things that you shouldn't.

After leaving and entering the server, these items may disappear, but not always, which may mean that, for example, we put armor on our heads that will give us higher stats than a helmet.

I am attaching videos

### Steps to Reproduce

1. Create 2 different equipable items in the editor.
2. Go to the customer and give yourself 2 pieces of one item and 1 piece of the other.
3. Go to the bank.
4. Wear the item you have 2.
5. Hide the item of which you have 1 piece (The other one)
6. Use the bank in the contextmenu or use shift or double-click on the item you have 2 and which is not equipped and hide it in the bank this way. (Hide the maximum amount if the inputbox appears)
7. When the items you had two pieces of are hidden, cash out the item you put in the bank earlier with the single one.
8. BUG: this item should be in the slot where you previously had the item equipped.

### Version with bug

0.8.127

### Last version that worked well

I dont know

### Affected platforms

Windows

### Did you find any workaround?

I will send a PR soon

https://github.com/AscensionGameDev/Intersect-Engine/assets/144380768/e1f7182c-9869-4422-a54d-721df731f6fb

https://github.com/AscensionGameDev/Intersect-Engine/assets/144380768/34bd39e7-ccba-4932-9a59-1c3042561d22

![Zrzut_ekranu_88](https://github.com/AscensionGameDev/Intersect-Engine/assets/144380768/c20be11a-e429-4c6e-bb6c-52e86ff04ea7)

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by Arufonsu** [comment]
Tried to reproduce everything and the issue is basically about equipped items not being unequipped before we take them out of the inventory into the bank, which triggers this funky behavior with stats.
