### ISSUE TITLE
enhancement: Show tip about attributes via press of a button 

### ISSUE THREAD

**Issue by H0L0R** [AscensionGameDev/Intersect-Engine#2158]
### Description

![image-13](https://github.com/AscensionGameDev/Intersect-Engine/assets/50377566/c0bbe661-11ab-43b4-ae84-f2564d970961)
Hide this tip about any attributes and show it when you press ALT

### Intended Use-Case

Show this tip is unnecessary and very impractical in case of especially block attribute, where is nothing relevant to show and drawing with this attribute is problematic. 

### Duplicate Check

- [X] This enhancement idea is not a duplicate to the best of my knowledge.

**Comment by lodicolo** [comment]
This should have been a discussion first to see if the community agrees with such a change.
