### ISSUE TITLE
bug: EquipmentOnHitTriggers when shooting projectiles

### ISSUE THREAD

**Issue by cydyn** [AscensionGameDev/Intersect-Engine#2226]
### Description

Weapons with the projectile setting do not use or incorrectly use the onhit event when this option is added.
PS: I give video in discord. I cant here, file too big

### Steps to Reproduce

1. Make a weapon with a projectile and a spell or anything on commonevent onhit.
2. Use it.
3. Make a weapon with extra attack effect and add this common event.
4. The gun works.
5. The projectile weapon will also work even if there is no event because it inherits from the previous one

### Version with bug

Latest

### Last version that worked well

Unknown

### Affected platforms

Windows, Linux

### Did you find any workaround?

No

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by Arufonsu** [comment]
Thanks to @PyroTech03 for explaining me this further:

![image](https://github.com/AscensionGameDev/Intersect-Engine/assets/17498701/a78b2aa5-f5ad-4189-ba03-79040959c38a)

so.. ie:
weapon A triggers event A
weapon B triggers event B

when switching around weapons, i'm now unable to trigger event A no matter what at some point
![image](https://github.com/AscensionGameDev/Intersect-Engine/assets/17498701/ef31a120-0b7e-4745-8d3e-5501e3a801c1) ![image](https://github.com/AscensionGameDev/Intersect-Engine/assets/17498701/891b6236-9b0e-4a16-b3a1-3b200a79fcf3) ![image](https://github.com/AscensionGameDev/Intersect-Engine/assets/17498701/cc7ff0d7-f241-4343-bda7-530b31c2aa32)
