### ISSUE TITLE
enhancement: Adding an editor build for linux

### ISSUE THREAD

**Issue by LarsZauberer** [AscensionGameDev/Intersect-Engine#2249]
### Description

Currently there is only the Server and the Client Application in the full Linux release package included. It would be quite nice to also include the Editor Application in the Linux release package.

### Intended Use-Case

This would enable full game development on Linux with the engine.

### Duplicate Check

- [X] This enhancement idea is not a duplicate to the best of my knowledge.

**Comment by Arufonsu** [comment]
I understand the frustration! The absence of Linux support for the editor is indeed a limitation. Implementing this would not be an enhancement; rather, it would need creating an entirely new feature: this would be a substantial undertaking, especially considering the need to rewrite the entire editor 🙁. While it’s not on our current milestone, I appreciate your suggestion. Let’s hope we can eventually bid farewell to WinForms 😆 for now, I'll have to close this one (not a valid _enhancement_ request, it should be a _feature_ request instead and, it should be first [discussed ](https://github.com/AscensionGameDev/Intersect-Engine/discussions) along with the community and see if anyone is willing to give this a go).

Regards

**Comment by LarsZauberer** [comment]
Thanks for the quick response. I hoped that it might be just some tweaks in the .NET configuration to get it working on Linux but it seems this is not the case. It probably makes more sense to prioritize different feature requests rather than this. It is already quite a progress that we have a native Linux Server and Client.
