### ISSUE TITLE
bug: Disconnection error message when returning to the main menu.

### ISSUE THREAD

**Issue by Litorals** [AscensionGameDev/Intersect-Engine#2251]
### Description

Disconnection error message appears every time you enter the Login or Register account section and you return (without logging or create an account) to the main screen.

### Steps to Reproduce

1- Run Server.
2 - Run Client.
3 - Enter the Login section or create an account.
4 - Return to the main menu.

The client will display a disconnection error.
![error](https://github.com/AscensionGameDev/Intersect-Engine/assets/132066040/cba1596b-d4c6-4bd0-87c5-ff1d1d8d27ec)

### Version with bug

v0.8.0-beta.156

### Last version that worked well

0.7.1.120

### Affected platforms

Windows, I was *not* able test on other platforms

### Did you find any workaround?

No

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by theceltos** [comment]
Same here

**Comment by Litorals** [comment]
I tried this again and the same problem continues, the steps to reproduce the bug are the same. Thanks.
