### ISSUE TITLE
Spell target type 'Single Target (Includes Self)' does not cast on self

### ISSUE THREAD

**Issue by Guite-Emortal** [AscensionGameDev/Intersect-Engine#227]
**Describe the bug**
I made a buff spell with the target type set to 'Single Target (Includes Self)' This applied as intended to my party member but not applied to myself the caster when selected as target.
- I also tested with a HoT spell just before submitting to see if it was user error. The HoT did not apply to selected caster either.

**Version Encountered**

0.6.2.419

**To Reproduce**
1. Make a Spell (Mine gives a 30sec buff +10 Atk) and set target type to 'Single Target (Includes self)'
2. Learn spell in-game
3. Select yourself and cast spell
4. See that no buff is applied

**Expected behavior**
A buff timer should appear below the player HP/MP/EXP Window, but does not.

**Operating System:**
Windows

**Comment by Azurebeats** [comment]
Unable to reproduce, can you provide an example spell?

(spell settings)[https://s3.us-east-2.amazonaws.com/ascensiongamedev/filehost/40f73b41ce63dcb40c16756fcfd430c8.png]

**Comment by Azurebeats** [comment]
I can't reproduce this, can you provide an example spell?
(Also make sure the damage is set to a negative so it heals!)

**Comment by Guite-Emortal** [comment]
This is the demo spell I have been working with
![Spell prnt scrn](https://user-images.githubusercontent.com/16596977/82159661-b3cd5d80-9844-11ea-8ac5-5b081eca11ec.png)

**Comment by Azurebeats** [comment]
Try setting it to friendly.

**Comment by Guite-Emortal** [comment]
That was it.
