### ISSUE TITLE
bug: projectiles disappear next to resources and blocks (visual bug)

### ISSUE THREAD

**Issue by cydyn** [AscensionGameDev/Intersect-Engine#2279]
### Description

If the player is turned towards the block/resource or runs towards it, when we aim and shoot at the enemy behind us with guided missiles, the missiles disappear.
(Video on the bugs discord channel)

### Steps to Reproduce

1. Turn towards the wall
2. Mark the enemy behind you and shoot
3. The bullet disappears

### Version with bug

Latest

### Last version that worked well

0.8.166

### Affected platforms

Windows, Linux

### Did you find any workaround?

No

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by Arufonsu** [comment]
Fixed by #2281
