### ISSUE TITLE
bug: projectiles do not ignore who launched

### ISSUE THREAD

**Issue by cydyn** [AscensionGameDev/Intersect-Engine#2280]
### Description

When a projectile is directed and we set the aim to our character, the projectile does not appear at all.

### Steps to Reproduce

1. Create a weapon with projectile
2. Select your character and fire the guided missile

### Version with bug

https://github.com/AscensionGameDev/Intersect-Engine/assets/144380768/88c47385-40fe-4cb2-bc66-f915da4c62dc

latest

### Last version that worked well

0.8.166

### Affected platforms

Windows, Linux

### Did you find any workaround?

no

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by Arufonsu** [comment]
Fixed by #2281
