### ISSUE TITLE
bug: Projectile disappears but hits

### ISSUE THREAD

**Issue by cydyn** [AscensionGameDev/Intersect-Engine#2284]
### Description

The shot hits the opponent but the projectile is not visible.
This doesn't happen on all sides.

(PS: This is checked after adding PR #2283 and #2281)

[Westerre 2024-06-14 12-58-47.zip](https://github.com/user-attachments/files/15837162/Westerre.2024-06-14.12-58-47.zip)
Here Video

### Steps to Reproduce

1. Set block and set npc just like in the recording
2. Shoot projectiles and you'll see the error

### Version with bug

Latest and PR

### Last version that worked well

0.8.166

### Affected platforms

Windows, Linux

### Did you find any workaround?

No

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by WeylonSantana** [comment]
As it happened that you said that you made mistakes doing the merges prematurely, I'm going to close this report as invalid, let's follow things chronologically
1 - the pr will be merged
2 - you can test in a clean version not compiled by you, by downloading from our releases area
3 - reopen this if you still have the bug

I will also test again only when I finish

**Comment by cydyn** [comment]
@WeylonSantana I checked and the code matches the clean intersect with these changes. Check it yourself and I will wait until the changes are available and test it again

**Comment by Arufonsu** [comment]
> @WeylonSantana I checked and the code matches the clean intersect with these changes. Check it yourself and I will wait until the changes are available and test it again

This is still an invalid issue report, please follow what @WeylonSantana said the next time that you decide to file a bug report, even if your code "matches" the base engine, it is still an invalid way to file a bug report, regards.
