### ISSUE TITLE
bug: Item Event Triggers Only Trigger Once

### ISSUE THREAD

**Issue by RecoStar** [AscensionGameDev/Intersect-Engine#2285]
### Description

An item "Event Trigger" will only trigger once if you pick up or drop multiple items.

Event trigger for both "On Pickup" and "On Drop" do not trigger when picking up or dropping multiple items.

### Steps to Reproduce

Create and Item
Create a event that gives 100 experience to player and call it "EXP Gain"
Create an item
Set event trigger "On Pickup" to the event "EXP Gain".
Pick Up multiple items at once and event will only trigger once, instead of per item. 

Same for "On Drop", will only trigger once if dropping more than one item.

### Version with bug

0.8.0.170

### Last version that worked well

Unknown

### Affected platforms

Windows

### Did you find any workaround?

No

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by WeylonSantana** [comment]
have you checked the run in parallel tickbox?

**Comment by RecoStar** [comment]
Ah ok, didnt have that checked. 

So with Parallel enabled, "On Pickup" works fine, but "On Drop" does not.

**Comment by WeylonSantana** [comment]
sorry, missclick
how on drop dont work? what are u trying to trigger with on drop?

**Comment by Arufonsu** [comment]
> sorry, missclick how on drop dont work? what are u trying to trigger with on drop?

If On Drop has issues for OP even with parallel events, then please, open an issue regarding that.

Closing this since is not an issue
