### ISSUE TITLE
bug: server closes when attacking entity with projectile

### ISSUE THREAD

**Issue by theceltos** [AscensionGameDev/Intersect-Engine#2287]
### Description

When trying to kill a monster using a projectile, the server closes by itself.
If the monster dies with just 1 hit, nothing happens, but if you don't kill it in the first hit, the server dies.

### Steps to Reproduce

1 - Select any monster that has more health than you can take damage from.
2 - Throw a projectile at this monster.
3 - Watch the server die.

### Version with bug

0.8.0.0 after pr #2281

### Last version that worked well

Before #2281

### Affected platforms

Windows, I was *not* able test on other platforms

### Relevant log output

```shell
2024-06-16 01:35:38.599 [Error] Received unhandled exception from System.Threading.Thread: Index was outside the bounds of the array.

--------------------------------------------------------------------------------
2024-06-16 01:35:38.610 [Error] IndexOutOfRangeException: Index was outside the bounds of the array.
    Stack:    at Intersect.Server.Entities.Projectile.CheckForCollision(ProjectileSpawn spawn) in D:\The Celtos Game\Engine\Intersect-Engine\Intersect.Server.Core\Entities\Projectile.cs:line 345
   at Intersect.Server.Entities.Projectile.ProcessFragments(List`1 projDeaths, List`1 spawnDeaths) in D:\The Celtos Game\Engine\Intersect-Engine\Intersect.Server.Core\Entities\Projectile.cs:line 268
   at Intersect.Server.Maps.MapInstance.UpdateProjectiles(Int64 timeMs) in D:\The Celtos Game\Engine\Intersect-Engine\Intersect.Server.Core\Maps\MapInstance.cs:line 1383
   at Intersect.Server.Maps.MapInstance.Update(Int64 timeMs) in D:\The Celtos Game\Engine\Intersect-Engine\Intersect.Server.Core\Maps\MapInstance.cs:line 281
   at Intersect.Server.Core.LogicService.LogicThread.UpdateMap(MapInstance mapInstance, Boolean onlyProjectiles) in D:\The Celtos Game\Engine\Intersect-Engine\Intersect.Server.Core\Core\LogicService.LogicThread.cs:line 403


--------------------------------------------------------------------------------
```

### Duplicate Bug Check

- [x] This bug report is not a duplicate to the best of my knowledge.

**Comment by WeylonSantana** [comment]
`Select any monster that has more health than you can take damage from.`
you say like this? - https://www.ascensiongamedev.com/resources/filehost/9a68339599c4b8be5a5996df097f7062.mp4

**Comment by theceltos** [comment]
in fact the first 5 tests were just trying to kill a monster and the other tests I did the bug didn't occur, I'm trying to see the effective way to reproduce the bug

**Comment by theceltos** [comment]
I recorded this video, I know it doesn't help much, but it seems to happen randomly or when the projectile dies
https://youtu.be/ZoEX28J9aK0

**Comment by Arufonsu** [comment]
> I recorded this video, I know it doesn't help much, but it seems to happen randomly or when the projectile dies https://youtu.be/ZoEX28J9aK0

![image](https://github.com/AscensionGameDev/Intersect-Engine/assets/17498701/6150e700-d76a-4e99-ab12-2c398a259c4d)

😥  ...

**Comment by cydyn** [comment]
@WeylonSantana Celtos is not the only one with this error. I think two other people have described this problem on the Bugs channel and it is exactly the same.

**Comment by AlefMichel** [comment]
I don't know if it will help, but apparently the server crashes when the NPC changes maps.
I did the test 4 times and it happens when the NPC changes maps.

There it shows Version 0.8.0.172 but it is actually Versio

https://github.com/AscensionGameDev/Intersect-Engine/assets/128094550/db8b23cd-13d9-480c-9b0c-836a67dae667

n 0.8.0.174.

**Comment by cydyn** [comment]
I also experienced this server crash. This happens when we shoot at an NPC and the NPC moves through the map. Usually it takes two. Although not always. I don't know exactly how to explain reproductions, but the guy above gave a good video
