### ISSUE TITLE
bug: Projectile passes through NPCs.

### ISSUE THREAD

**Issue by AlefMichel** [AscensionGameDev/Intersect-Engine#2291]
### Description

When you are exactly diagonal to an NPC on another map, the projectile passes through the NPC without taking damage, and sometimes another NPC receives the damage.

https://github.com/AscensionGameDev/Intersect-Engine/assets/128094550/7a6f713a-86f9-4e7f-b78a-41a0e4dbc562

### Steps to Reproduce

Create a projectile.
Stand on another map exactly diagonally from an NPC on another map and shoot.

### Version with bug

0.8.0.174

### Last version that worked well

none

### Affected platforms

Windows

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by cydyn** [comment]
I don't know how to fix it. There must be someone more experienced here. Shooting along the map's diagonals means that there is no collision, although the projectile flies correctly towards the opponent but does not hit him.

**Comment by Arufonsu** [comment]
please, give us your projectile settings so we can attempt to reproduce this
