### ISSUE TITLE
Function to unequip item in events.

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#231]
**Is your feature request related to a problem? Please describe.**
We can check when the player is equipped with x item. When the player is not equipped with x item. We can equip item. Why not unequip?

**Describe the solution you'd like**
I believe that this should be related to the command "change items", there should be "give item," take items " " equip items "unequip items".

It doesn't matter where, but it's a specific feature useful for all games, 2 questions can be raised such as:

1 - If the player does not have the item equipped to be able to unequip?
R: so, failure message
2 - if the inventory is full?
R: there are two ways, do not unequip with a failure message or unequip by dropping the item on the floor.

there may be more questions, but that's what I think for now.

**Comment by Azurebeats** [comment]
I find it hard to go along with this being useful for all games as I fail to see a use for this right now?

Feel free to convince me though.

**Comment by WeylonSantana** [comment]
@Azurebeats I tried to think of plausible and useful reasons and collected some.

1 - Many games will use punishment when dying, this topic was much debated among creators and the topic "losing XP when dying" has always been the most desired. Some may already make players lose level when dying, in these situations, items that use the level as a requirement (for example) remained equipped in the inventory even after the player did not have the level to use this item, so at that point the unequiping item would come to handy when we check if the player’s level matches the item’s level. The same works for status, since losing a level also causes status points to be lost.
2 - I saw people who use pet / mount systems (or intend to use them) but get stuck in the problem of paperdolls, unequipping the item would come in handy to help when equipping this mount that would make a transformation in the sprite and keep any item unequipped while the player had pet / mount. I also saw one about making the character swim, and changing the sprite there, and paperdolls could get in the way, could also be useful in that situation.
3 - For control purposes, prevent the player from entering a certain place with a certain item, such as an arena, event, dungeon and such and keep him unequipped.
4 - Some creators use class changes that reset characters, the use of which can come to use there (but it would be item 1 of this list) but another context only.
5 - for this: https://www.ascensiongamedev.com/topic/4773-tutorial-unequip-item/
(simply by facilitating something that would be more difficult for events)

I couldn't think of more or many, because only going through the need do we see how necessary it is, my need is in item 1. The rest just observed where it would be useful seeing other projects out there. if I convinced you then it would be good, if I didn't convince you then you can close.

**Comment by WeylonSantana** [comment]
An additional comment. The command need not be "unequip item x". perhaps the "unequip slot x" was also viable and better. So we could unequip any item in the "weapon" slot or in the "shield" slot or any other of the 5 available or when we create it.

**Comment by Azurebeats** [comment]
That all still sounds incredibly niche and most sounds like it should be handled in code instead for a decent system.

**Comment by WeylonSantana** [comment]
@Azurebeats Okay then, if there is not much usability you can close or discard this topic. So you don't accumulate so many feature requests around here.

**Comment by Azurebeats** [comment]
I'm not closing it, because there's more people than me that get to have opinions on this. 😅

Maybe someone else does consider it a worthy addition.

**Comment by WeylonSantana** [comment]
@jcsnider @Cheshire92 @lodicolo  you can close this topic since the function has already been added to the intersect.
