### ISSUE TITLE
bug: ZDimension does not allow you to activate the event map

### ISSUE THREAD

**Issue by theceltos** [AscensionGameDev/Intersect-Engine#2317]
### Description

ZDimension does not allow you to activate the event map or kill a monster.

### Steps to Reproduce

1 - Have the player enter Level 2 of the ZDimension.
2 - Try to activate an event on the map with your character. How to attack the event to activate it.  
3 - See the bug.

### Version with bug

idk

### Last version that worked well

Maybe before homing projectiles?

### Affected platforms

Windows, I was *not* able test on other platforms

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by Arufonsu** [comment]
> 1 - Have the player enter Level 2 of the ZDimension.
> 2 - Try to activate an event on the map with your character. How to attack the event to activate it.
> 3 - See the bug.

please, fix your grammar so we can understand your issue.

> Maybe before homing projectiles?

And provide an accurate version where this last worked so we can properly compare

**Comment by Arufonsu** [comment]
![image](https://github.com/AscensionGameDev/Intersect-Engine/assets/17498701/14c01b66-4ac1-4167-a313-2185ec1416aa) ![image](https://github.com/AscensionGameDev/Intersect-Engine/assets/17498701/141a0c95-b8ba-4bbe-9cb5-9ed24e7f0a28)

Unable to reproduce with the provided information at [v0.8.0-beta.187](https://github.com/AscensionGameDev/Intersect-Engine/releases/tag/v0.8.0-beta.187)

https://github.com/AscensionGameDev/Intersect-Engine/assets/17498701/d447a9d2-6894-4734-8cd4-53b1528cd3d3

**Comment by Arufonsu** [comment]
> or kill a monster.

also, if you are in a different ZDimension level than entities, *of course that you will be unable to hit entities in different ZDimension levels, i invite you to read again how ZDimensions supposed to work*

**Comment by theceltos** [comment]
1 - Are you equipped with a bow or any weapon that throws projectiles when using it?
2 - Is the monster within the same ZDimension level as you?

The bug happens to the monster within the same square as you

**Comment by WeylonSantana** [comment]
Why are you talking about monsters when your report talks about events? Another point, events don't have Z (but they should, we have to support it one day), so you can't interact with events with different Z, I'll look in the better code to see if it's really possible or not

**Comment by theceltos** [comment]
> Why are you talking about monsters when your report talks about events? Another point, events don't have Z (but they should, we have to support it one day), so you can't interact with events with different Z, I'll look in the better code to see if it's really possible or not

Weylon, if you read it, you'll see that I also mentioned that this bug happened with a monster inside the square. I will record a video to better demonstrate the bug.

**Comment by WeylonSantana** [comment]
> > Why are you talking about monsters when your report talks about events? Another point, events don't have Z (but they should, we have to support it one day), so you can't interact with events with different Z, I'll look in the better code to see if it's really possible or not
> 
> Weylon, if you read it, you'll see that I also mentioned that this bug happened with a monster inside the square. I will record a video to better demonstrate the bug.

I saw a quote but that doesn't make the whole report about projectile vs npc, look at things from my point of view
1 - you make a report saying that there is no way to activate events
2 - in the reproduction steps you talk about trying to use events (step 2 and 3)
ok, our role is to test and find out if it is a bug
3 - aru ​​tested and there is no bug about activating events
4 - do you talk about attacking monsters with projectiles?
Do you understand what doesn’t make sense in the scope of this report?

if the main point here is about not being able to activate events (in the title and in the reproduction steps) just stick to that

So we go back to the point of not being able to attack the monsters, create another report for them with video, monsters and events are treated differently on the server and on the client (I have no idea why yet, they are all entities), in this new report test monsters like
1 - create a monster that spawns outside of a gateway area 1 or 2
2 - make the monster follow you and try to attack with projectiles
We hope this works, as the monster and the player were teleported to the same level in the z dimension.

1 - now try to place the monster spawn within the area
2 - move the player into the area (being taken to level 1), try to attack the monster
We hope here that the attack does not happen, as only the player was taken to level 1-2 by the gateway
