### ISSUE TITLE
Add an "on click" event trigger

### ISSUE THREAD

**Issue by Superspyi** [AscensionGameDev/Intersect-Engine#233]
**Is your feature request related to a problem? Please describe.**
If I set a shop NPC/Event behind a counter a user has to walk up to the counter and I have to have either an action button or collision / player touch event trigger to open a shop.

**Describe the solution you'd like**
If an NPC had an "on click" event trigger then I could have a player walk into the shop, click on the shopkeeper and it will go through that event to open up the shop.

**Additional context**

**Comment by WeylonSantana** [comment]
But Already has, is the "action button" trigger.

**Comment by Azurebeats** [comment]
This feels like a very specific feature for one or two use cases. Not seeing the real benefit here.

**Comment by Superspyi** [comment]
Understandable.  It is a pretty specific feature with the shopkeeper being the only real use case.  Closing.
