### ISSUE TITLE
 Consumables recharge time

### ISSUE THREAD

**Issue by Moscano** [AscensionGameDev/Intersect-Engine#234]
**Is your feature request related to a problem? Please describe.**

I have a suggestion about the consumable's recharge time, in my game there are several types of foods. For example, in 2 seconds, I have about 5 types, one that fills 60 mana, another that fills 120 mana and another that fills 180 mana. When I use commode X, the recharge time only applies to food X, the other foods I can use, so the recharge time of 2 seconds is useless. Well, I can use all 5 foods in 1 second.

**Describe the solution you'd like**

You could select the consumables that will enter the recharge time at the same time.

**Additional context**

https://gyazo.com/31684d069130a19a5b027aac44f6b061

https://gyazo.com/304204fb8070200c92dc595c92f50af6

https://prnt.sc/snpb9r

**Comment by Moscano** [comment]
I put more images / gif

**Comment by ThousandX** [comment]
Yes, it makes the game much more balanced.
I think a Global Cooldown System would do it.
Each time you use 1 consumable or magic, the shortcut tab would have an X cooldown to use any other type of item on the shortcut.

**Comment by BabyLoves** [comment]
I guess... A cooldown system based on group of items. Example:
Consumable Item Heal HP
Consumable Item Heal MP

When i use consumable item heal hp... All of the consumable item hp rest a cooldown

**Comment by Azurebeats** [comment]
Could add configurable groups to the config you can assign items to to go on cooldown with together?

**Comment by Spectreye** [comment]
Would it be applicable to magic too ? Actually you can launch all your spell at a time (Can be dreadfull depending of what spell you make)

**Comment by Azurebeats** [comment]
I have been playing with the idea of a configurable global cooldown and for the cooldown groups to apply to spells as well. But haven't gotten around to it yet.
