### ISSUE TITLE
 Various magic animations.

### ISSUE THREAD

**Issue by Moscano** [AscensionGameDev/Intersect-Engine#240]
**Is your feature request related to a problem? Please describe.**

When you use the same spell multiple times, multiple animations appear.
https://gyazo.com/9e8b0707bb3e616ef4364c724d501ba2

**Describe the solution you'd like**

I have a suggestion about using the same magic more than once and showing the animation only once.

**Additional context**

**Comment by Azurebeats** [comment]
I'd say that is intended behaviour?
Not really seeing the issue here

**Comment by Moscano** [comment]
It's not a problem, I think using 3 times the same spell and appearing 3 animations of the same spell is a little strange.

When you use the spell once.
https://gyazo.com/8d9878b8732659eb9c371d143a5114b1

When you use the same spell multiple times, multiple animations appear.
https://gyazo.com/9e8b0707bb3e616ef4364c724d501ba2

**Comment by seethingword** [comment]
That's intended from what I understand

**Comment by Azurebeats** [comment]
Not really an issue or enhancement, but personal preference. 

Imagine this is more so something you'd want for your game and not general use.
