### ISSUE TITLE
bug: NPC dialogue cannot progress when Typewriter option is disabled

### ISSUE THREAD

**Issue by dhmello** [AscensionGameDev/Intersect-Engine#2425]
### Description

When the Typewriter option is disabled in the game's settings, dialogue with NPCs that involve response options becomes unresponsive, preventing the player from advancing.

### Steps to Reproduce

1. Disable the "**Typewriter Text**" option in the settings menu.

2. Interact with any NPC that has dialogue with response options.

3. Observe that the dialogue cannot progress.

### Version with bug

v0.8.0-beta.242

### Last version that worked well

Unknown

### Affected platforms

Windows, macOS, Linux

### Duplicate Bug Check

- [X] This bug report is not a duplicate to the best of my knowledge.

**Comment by lodicolo** [comment]
@dhmello I am not able to reproduce this based on the provided instructions.

Please create a clean gamedb and playerdb that has this issue and please provide both of them as well as the client's config.json.

**Comment by dhmello** [comment]
@lodicolo i get the fix #2436 , and now the bugs has gone.
