### ISSUE TITLE
bug: Items cannot be stored in the bank

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#2431]
### Discussed in https://github.com/AscensionGameDev/Intersect-Engine/discussions/2430

<div type='discussions-op-text'>

<sup>Originally posted by **EspectroW94** December 25, 2024</sup>
Items cannot be stored in the bank

video:

https://github.com/user-attachments/assets/31934854-751b-48dd-beb2-f747078370e3

</div>

**Comment by lodicolo** [comment]
I'm not able to reproduce this, please use the stock assets to create a clean gamedb and playerdb that has this issue so I can debug it @EspectroW94

**Comment by EspectroW94** [comment]
@lodicolo Literal creates a new game, creates a stackable item, puts an event that opens the bank and deposits the items. Nothing special needs to be done.

version 8.245

**Comment by lodicolo** [comment]
> @lodicolo Literal creates a new game, creates a stackable item, puts an event that opens the bank and deposits the items. Nothing special needs to be done.
> 
> version 8.245

@EspectroW94 I have this exact setup, and the stackables are able to bank without issue, and **I'm not able to reproduce this** (and neither can Aru).

Please recreate the issue in a clean game and player DB and then share both of them so I can try to debug with a setup that is known to not work.

**Comment by EspectroW94** [comment]
I recorded the whole process and left the files. I don't know how else I can help.

video: https://youtu.be/1CZQ3WTnPso

files: https://drive.google.com/file/d/1upNJvoz1Oql6HSjtHLbHyqKixMCeTLKr/view?usp=sharing

**Comment by lodicolo** [comment]
@EspectroW94 That helped, the key appears to be a new user because the bank slot list is empty by default.
