### ISSUE TITLE
feature: target partymates through the party window

### ISSUE THREAD

**Issue by ghost** [AscensionGameDev/Intersect-Engine#244]
**Is your feature request related to a problem? Please describe.**
I was talking to a colleague, and we noticed that the system of selecting the friend during a battle in a lot of mobs is complicated for a support to be able to heal a group member,
then we came to a suggestion that could be a standard on the engine. To be able to select the FRIEND when in a Party, through the party window, clicking on the player's nick in the party window, selecting his friend and healing him, even in the same of many mobs.
This would make life easier for the healers / support group. Currently using the TAB KEY or even trying to use the mouse click, support gameplay is complicated.
Thank you, and it would be really cool if you put this as a standard for the engine, because I think that all projects could use the benefit.

**Comment by lodicolo** [comment]
Restored issue.

**Comment by jcsnider** [comment]
Clicking on a player in the friends list will start a PM to them right now meaning we will need the designated PM and Remove icons before proceeding with this.

Also as a note, I recently added much better targeting logic to the engine, so overall this shouldn't be as bad anymore.

**Comment by Arufonsu** [comment]
Double checked this one feat request, realized that @AlexVild already resolved by with #2086
