### ISSUE TITLE
Update client icon to use transparent background

### ISSUE THREAD

**Issue by jcsnider** [AscensionGameDev/Intersect-Engine#245]
**Is your feature request related to a problem? Please describe.**
The Intersect icon doesn't look great on Windows in the taskbar due to the black background...
[Ref 1](https://www.ascensiongamedev.com/resources/filehost/9aee1048aa04913b346350631c588bbe.png)

**Describe the solution you'd like**
According to Dog in the AGD discord MonoGame/Intersect would work with a bmp icon that has a transparency layer (24 + 1?). That's new to me but seems easy enough to generate with Gimp and replace. No rush but something we should touch up on :)

**Comment by lodicolo** [comment]
Fixed in #285
