### ISSUE TITLE
Mouse hover over an item on the map would show quantity and name

### ISSUE THREAD

**Issue by Superspyi** [AscensionGameDev/Intersect-Engine#246]
**Is your feature request related to a problem? Please describe.**
It would be nice when you hover over an item in game that it would show the amount of the item and then the item name.  

**Describe the solution you'd like**
Add some sort of feature that allows a mouse hover over an item to show the quantity and the name.  Would probably be similar to the same way mouse hover on player, npc, or event will show the brackets around them.  Example of what it would say - 300 Gold - 2 Health Potion - Snake Rattle

**Additional context**
![mouse hover item](https://user-images.githubusercontent.com/64320948/83817962-11aad380-a694-11ea-9513-b0f00dfeb9f0.png)

**Comment by Azurebeats** [comment]
Curious what if situation, what do you propose would happen if there's more than one item on the map in one location?

Only show the top item? Show them all?

**Comment by ThousandX** [comment]
I think I could report in this format if more than one type of item
**First Line: Gold
Second line: ...**

or

**First Line: Gold
Second: x others ...**

**Comment by Superspyi** [comment]
I've only seen it implemented as the top item shows the name on hover.  But the idea of having a separate line for each item doesn't seem to bad.  My only worry is with more than 2-3 items it could definitely start to look messy.  Maybe just the top item is the way to go.  Or maybe something toggleable in a config file or something.

**Comment by Azurebeats** [comment]
Not exactly done yet, but I've got a start.

![image](https://s3.us-east-2.amazonaws.com/ascensiongamedev/filehost/410adbb7c83bdd6fb16dd05968043216.png)

Currently this kind of chaos ensues when there's multiple items next to eachother though.

![image2](https://s3.us-east-2.amazonaws.com/ascensiongamedev/filehost/06f177fe510826e88395914f1adb3b5a.png)

**Comment by Richy1111** [comment]
Oh jeez I was about to propose to just have it show the first item until picked up, but now that idea sounds bad if there's no order. :(.

**Comment by Azurebeats** [comment]
Fixed the rendering order just now, and got the mouseover logic to work.

![image](https://s3.us-east-2.amazonaws.com/ascensiongamedev/filehost/9d825057053a2948feb33995345f939b.gif)
