### ISSUE TITLE
TryBumpEvent broken on maps edges in relation to player.

### ISSUE THREAD

**Issue by rhathaway86** [AscensionGameDev/Intersect-Engine#247]
**Describe the bug**
The TryBumpEvent "Bump" for event function activation does not work when placed on the edge of a map boundary and player bumps the event from another map.

**Fix**
I'd send a pull request, but this is a small fix and I don't want to unload all my current changes on my fork to address.

Inside Player.cs on Intersect.Server
TryBumpEvent is referencing the player MapId with capital M and should be pointed to the function passed lowercase mapId. Make sure you get all instances of this value in the lines below.

**Version Encountered**
Current.

**To Reproduce**
Place an event on map edge and try to use bump on it from other map.

**Expected behavior**
Bump should work.

**Screenshots**
Not needed.

**Logs**
Not needed.

**Operating System:**
Windows

**Additional context**
No.

**Comment by ThousandX** [comment]
This is because it is a local event, or map event, it would be interesting if the event could be accessed outside the map it is on, and it would also greatly expand the event system, being able to do an EVENT, which follows you on any map .
