### ISSUE TITLE
Clickable links

### ISSUE THREAD

**Issue by ghost** [AscensionGameDev/Intersect-Engine#250]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Detect HTTP(S) URLs and make them clickable in interfaces

**Additional context**
N/A

![Screenshot_9](https://user-images.githubusercontent.com/21990960/83959617-621d5f00-a855-11ea-9304-acdc10f3f6de.png)

**Comment by lodicolo** [comment]
Restored issue.

**Comment by Azurebeats** [comment]
Would a solution to this be to regex the label contents on the on click event and launching a browser from that?

Wouldn't really work for multiple links in one label but might also be a cheap way to have links in the chat window.

**Comment by lodicolo** [comment]
This isn't being done at least not with the current GWEN client UI implementation.

Ideally we would prefer if our future UI dependency would have this implemented.
