### ISSUE TITLE
 error when stepping on the event.

### ISSUE THREAD

**Issue by Moscano** [AscensionGameDev/Intersect-Engine#254]
**Describe the bug**

the error happens when I talk to the craft npc and pass the sprite exchange event.

**Version Encountered**
6.2.417

**To Reproduce**

**Expected behavior**

**Screenshots**

https://www.youtube.com/watch?v=amHfiVs8Ufk

**Logs**
If there are error logs please attach them below.

**Operating System:**
Windows

**Additional context**

**Comment by Azurebeats** [comment]
I'm sorry, but could you actually fill in the report instead of directing us to a YouTube video?

Also an example of the event (as short as possible)that can be used to reproduce this would help.

**Comment by jcsnider** [comment]
Invalid report Can't tell what's going on in the video, the report isn't filled out. Closing.
