### ISSUE TITLE
Player offline, but visible on the map.

### ISSUE THREAD

**Issue by ghost** [AscensionGameDev/Intersect-Engine#256]
**Describe the bug**
I noticed that some players when logging out, they still have the doll in the game, but offline on the entire server, it may be something related to the logout system in combat, but there is a time for the player to disappear? So, the player stays forever.

**Version Encountered**
Version 0.6.2.0

**To Reproduce**
idk

**Screenshots**
![Screenshot_1](https://user-images.githubusercontent.com/21990960/84717836-6a5c5500-af4d-11ea-99d5-77459549b71e.png)
![Screenshot_2](https://user-images.githubusercontent.com/21990960/84717839-6defdc00-af4d-11ea-86c5-bbb2637fffdc.png)

**Operating System:**
Windows

**Comment by lodicolo** [comment]
@ThousandX You already opened this bug: #177
