### ISSUE TITLE
Local (map) event can create global variables.

### ISSUE THREAD

**Issue by ThousandX** [AscensionGameDev/Intersect-Engine#261]
**Is your feature request related to a problem? Please describe.**
I was thinking of an easy way for the engine to create a clan system, and I came up with an idea, and whether to enable the creation of events, global variables, through a local event, or a common event?

**Describe the solution you'd like**
Can the player CREATE a global variable, defined by the creator, with a guild system, instead of the game owner, create 1 global variable, for each guild to be created, he can define an event where he can create himself freely?

**Additional context**
When clicking on the npc, it will ask for the name of the Clan, it will type the name, and the event will create a global variable like Clan_Player (PLayer = Nick of the player), with other variables Clan_Owner = \pn

Importantly, the creation of global variables will only be done if it does not exist. This will prevent substitutions of variables created by other events

**Comment by lodicolo** [comment]
This is too niche and limited, any form of membership system is better done written in code with proper integration.

This would additionally add on-the-fly manipulation to the game database, which is meant to be static in a live server scenario.

Any sort of "guild" or "clan" data would need to be strictly contained within the player database, which variable definitions (metadata) are not, only variable data is.
