### ISSUE TITLE
When you open the list of friends, and use the mouse scroll, the game simply closes.

### ISSUE THREAD

**Issue by ghost** [AscensionGameDev/Intersect-Engine#264]
**Describe the bug**
When you open the list of friends, and use the mouse scroll, the game simply closes.

**Version Encountered**
0.6.2

**To Reproduce**
Open the list of characters, have at least 1 friend in it, use the mouse scroll.

**Logs**
`2020-06-29 22:39:23.050 [Error] 
  Message: Referência de objeto não definida para uma instância de um objeto.
    Stack:    em Intersect.Client.Framework.Gwen.Input.InputHandler.OnMouseScroll(Base canvas, Int32 deltaX, Int32 deltaY) na E:\Celtos Online\Intersect-Engine\Intersect.Client.Framework\Gwen\Input\InputHandler.cs:linha 411
   em Intersect.Client.Framework.Gwen.Control.Canvas.Input_MouseScroll(Int32 deltaX, Int32 deltaY) na E:\Celtos Online\Intersect-Engine\Intersect.Client.Framework\Gwen\Control\Canvas.cs:linha 306
   em Intersect.Client.Framework.Gwen.Input.IntersectInput.ProcessMessage(Object message) na E:\Celtos Online\Intersect-Engine\Intersect.Client.Framework\Gwen\Input\IntersectInput.cs:linha 138
   em Intersect.Client.MonoGame.Input.MonoInput.CheckMouseScrollWheel(Int32 scrlVValue, Int32 scrlHValue)
   em Intersect.Client.MonoGame.Input.MonoInput.Update()
   em Intersect.Client.Core.Main.Update()
   em Intersect.Client.MonoGame.IntersectGame.Update(GameTime gameTime)
   em Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   em Microsoft.Xna.Framework.Game.Tick()
   em Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   em Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)`

**Operating System:**
Windows, Mac, Or Linux

**Comment by ThousandX** [comment]
Sorry to report, this bug is from a mouse scroll patch

Line code

[new 1.txt](https://github.com/AscensionGameDev/Intersect-Engine/files/4848445/new.1.txt)

**Comment by jcsnider** [comment]
If we ever bring the mouse scrolling into the official engine we may tackle this. But seeing that it is a non-issue with our official branches this is gonna be closed.
