### ISSUE TITLE
Players are able to speed hack with (projectile) attacks

### ISSUE THREAD

**Issue by ghost** [AscensionGameDev/Intersect-Engine#265]
**Describe the bug**
Players are able to use speed hack for attacks.
For movement speed they can't use it, but they can for normal E attacks

**Version Encountered**
0.6.2.0

**To Reproduce**
Just use Cheat Engine and activate Speed Hacking

**Video**
https://youtu.be/IwfGfU23H7E

**Operating System:**
Windows, Mac, Or Linux

**Comment by PotatoBlood** [comment]
speed hack does not work on my game, attacks appear to be faster clientside, but the attacks registered on the server are still the same. My attack speed is percentage based on a stat though, not disabled or static.

Image: https://floor100.com/uploads/chrome_BJmy2wcZ8H.png
Video: https://streamable.com/vtj8bf

**Comment by ThousandX** [comment]
As I demonstrated in my video, the attack is not only client side, the monster also dies with the rapid attacks.

**Comment by ThousandX** [comment]
When used with projectiles, the hack works, I just tested it.
If you use simple melee attack, it is only client side, but when used with arrows the attack is fast

**Comment by PotatoBlood** [comment]
> When used with projectiles, the hack works, I just tested it.
> If you use simple melee attack, it is only client side, but when used with arrows the attack is fast

can confirm this

**Comment by lodicolo** [comment]
Restored issue.

**Comment by jcsnider** [comment]
#339 will fix this.
