### ISSUE TITLE
NPCs won't cast AoE Spells

### ISSUE THREAD

**Issue by ghost** [AscensionGameDev/Intersect-Engine#271]
Describe the bug
This is bad, NPCs don't cast spells when the spell is in the area, AOE.

Version Encountered
0.6.2.0

To Reproduce
Create 1 area spell,
make an npc
put the skill on the Npc to be cast.
He just never casts the skill.

Operating System:
Windows, Mac, Or Linux

Note: Restored. See edit history.

**Comment by TheCeltos** [comment]
I just tested a clean version of the engine, and the problem persists.

**Comment by TheCeltos** [comment]
Se virem para descobrir o BUG :)

**Comment by jcsnider** [comment]
My npcs are casting AoE spells fine. Probably a configuration error. Not gonna pursue further.
