### ISSUE TITLE
Magic with taunt effect, players cannot use Spell that is Event

### ISSUE THREAD

**Issue by ghost** [AscensionGameDev/Intersect-Engine#272]
**Describe the bug**
For example, I made some potions, which are activated by event, when using with taunt effect, it is impossible

**Version Encountered**
0.6.2.0

**Expected behavior**
She should just keep the npc focused on you while Taunt's effect is alive.

**Operating System:**
Windows, Mac, Or Linux

**Comment by Azurebeats** [comment]
I don't follow the exact issue described here, anyone able to pitch in?

**Comment by jcsnider** [comment]
I /think/ what they're saying is that when taunted via a spell the player should not be able to use items (like potions). But tbf I really don't know. We need Gibby.

**Comment by jcsnider** [comment]
Actually closing this, as we are not going to get a better description (submitter is banned). If this is actually a bug, someone else will post it again later and hopefully with more info.
