### ISSUE TITLE
NRE in CharacterNameInUse

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#274]
**Describe the bug**
When I try to create a char, I get disconnected, and don't connect anymore unless I close and reopen the client.
I tried to create with the current adm account, tried with a non-adm account, and tried to create an account (which leads straight to the char selection), and yet the character is not created. The disconnect happens.

The client does not have a log, only the server.
**Version Encountered**
0.6.2.421

**To Reproduce**
Try to make a new char

**Expected behavior**
make a new char

**Logs**
[IntersectServer-2020_07_13-17_14_25_139.log](https://github.com/AscensionGameDev/Intersect-Engine/files/4915728/IntersectServer-2020_07_13-17_14_25_139.log)

**Operating System:**
Windows

**Comment by jcsnider** [comment]
If you open the Characters table in your Player Database you will find that you have a player with a NULL or no name. Deleting that character from the DB and then restarting the server will resolve the character creation bug.

As to why that happens.. I'm not sure yet. Has happened to moscano as well I think. Maybe players entering names with foreign characters that the database can't handle? Will have to look into this more.

**Comment by lodicolo** [comment]
Opened a separate issue (#293) for introducing a more user friendly response
