### ISSUE TITLE
Consumable events option

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#276]
**Is your feature request related to a problem? Please describe.**
When we create a magic item it has this option
![image](https://user-images.githubusercontent.com/63019821/87612915-373eea00-c6e2-11ea-8aa6-c16df9d9b63c.png)
The problem is with event items. Most of the time we use them to activate an event and that's it. However, we often have items that are permanent, such as a map {event showing image}, or book {event showing dialogues} and etc. So every script end of these events we have to return the item again.
![image](https://user-images.githubusercontent.com/63019821/87613050-8e44bf00-c6e2-11ea-88ce-e00e5518005f.png)

**Describe the solution you'd like**
Just like magic items, where there is a choice, they may or may not be consumable. A small improvement in the quality of life of some creators is to have this same option for event items. This way we can activate these repetitive events without the item disappearing from the inventory. A check box like the spell's would solve that.

**Additional context**

**Comment by lodicolo** [comment]
So this is already possible, it's just an extra step.

@WeylonSantana 

Since spells can start events:
- you can create an item that triggers a spell that starts the event
**or**
- you can just give the player the spell directly

**Comment by WeylonSantana** [comment]
@lodicolo Yes, that extra connection didn't cross my mind. It's a really good idea. I see that you marked it as an enhancement, it may be a good idea even if you also have the option directly avoiding extra steps. Thank you for considering.
