### ISSUE TITLE
Multiline textbox not working properly

### ISSUE THREAD

**Issue by RedBandana** [AscensionGameDev/Intersect-Engine#278]
**Describe the bug**
Actually, the current multiline text box is not usable as we cannot type multiple lines or create a json file with it. In fact, it is like a textbox.

**Version Encountered**
Version 0.6.2.421

**To Reproduce**
1. Go to an Interface class like the party window and instantiate a multiline textbox.
2. Open the client and use that Interface.
3. See error

**Expected behavior**
The multiline textbox should appear like a basic textbox and in the json file of the interface there will be nothing related to that textbox.

**Media**
![](https://s3.us-east-2.amazonaws.com/ascensiongamedev/filehost/ffa6c928a3f248a4cfbf03d5e2d573d5.gif)

**Operating System:**
Windows

**Comment by lodicolo** [comment]
Will not be addressed while we depend on GWEN.
