### ISSUE TITLE
Impossible to define left mouse click for any shortcut on the shortcut bar.

### ISSUE THREAD

**Issue by ghost** [AscensionGameDev/Intersect-Engine#279]
**Describe the bug**
Impossible to define left mouse click for any shortcut on the shortcut bar. Only the right click works if configured.

**Version Encountered**
0.6.2.421

**To Reproduce**
Go to the shortcut settings in the menu, set the attack to E, and E on both sides. Go to a shortcut from 1 to 9 or 0, define as the left mouse click, it defines, however when trying to use, it does not work.

**Expected behavior**
It was possible to remove the attack from the left mouse click, making it possible to link it to the use of a spell or item on the shortcut bar.

**Screenshots**
Attack config: https://prnt.sc/tpm70h
Mouse binded as skill or item uses: https://prnt.sc/tpm7cl

**Operating System:**
Windows

**Comment by lodicolo** [comment]
Restored issue.
