### ISSUE TITLE
Error showing more than 4 group members.

### ISSUE THREAD

**Issue by TheCeltos** [AscensionGameDev/Intersect-Engine#281]
**Describe the bug**
I was, changing the json of PartyWindow, when I arrived at member 5, which is actually called Member4, I noticed that he does not appear, even though defining the right coordinates, and the Kick button of member 5, appears, however for everyone, and not just for the leader.

**Version Encountered**
0.6.2.*

**To Reproduce**
I will be sending my group json to the developers for testing.
PartyWindow.json

https://ascensiongamedev.com/resources/filehost/eec2f23b45396908abf4bd2447255965.json

**Expected behavior**
That it was modular, the engine would take the max members configuration, and not bug when adding the remaining 6 members.

**Screenshots**
I can't send a print, but I sent the json file for testing

**Operating System:**
Windows

**Comment by lodicolo** [comment]
Currently the engine only supports 4 party members, so this is not a valid bug.

**Comment by TheCeltos** [comment]
But if it is possible to change the maximum member in the server configuration, why this limitation in the client?

**Comment by jcsnider** [comment]
Someone.. I think Joyce.. pulled PartyMembers out and moved it to the server config instead of a hardcoded constant.

That gives the implication that the party size is readily dynamic but it's not and nor is it intended to be.

**Comment by jcsnider** [comment]
The reason it was pulled out is because I accidentally committed 10 instead of 4 when fixing bugs in your source @TheCeltos and while resolving that Joyce added it to the config.

At best this is an enhancement idea (one that we won't do for now) but definitely not a bug.

**Comment by TheCeltos** [comment]
Damn this is dismal, games with only 4 members in the group, this is very strange

**Comment by jcsnider** [comment]
[Unfortunately it's a real game killer.](https://www.ascensiongamedev.com/resources/filehost/088ef35e6bc892305f1d5fb9979b6f04.png)

**Comment by TheCeltos** [comment]
Yes, but 5 people is better than 4.is too little

 :( sad
