### ISSUE TITLE
CastSpell(Guid, int) tried adding duplicate key

### ISSUE THREAD

**Issue by Andical** [AscensionGameDev/Intersect-Engine#284]
Version 6.2.421

No idea what happened, just logged in, walked 3-4 sqm and then suddenly I logged out and crashed.

Windows
![error1](https://user-images.githubusercontent.com/14881655/89077736-30230780-d383-11ea-9c6a-a3b4a47ad342.PNG)

[Intersect Server-2020_07_31-23_04_24_418.log](https://github.com/AscensionGameDev/Intersect-Engine/files/5009063/Intersect.Server-2020_07_31-23_04_24_418.log)
[errors-Intersect Server.log](https://github.com/AscensionGameDev/Intersect-Engine/files/5009064/errors-Intersect.Server.log)
[Intersect Client-2020_07_31-23_04_30_489.log](https://github.com/AscensionGameDev/Intersect-Engine/files/5009066/Intersect.Client-2020_07_31-23_04_30_489.log)

**Comment by lodicolo** [comment]
Opened a separate issue (#293) for introducing a more user friendly response
