### ISSUE TITLE
enhancement: notice prompt for network error

### ISSUE THREAD

**Issue by lodicolo** [AscensionGameDev/Intersect-Engine#293]
**Is your feature request related to a problem? Please describe.**
When network errors occur on the server, client connections are terminated and the client closes silently.

**Describe the solution you'd like**
Instead of silently closing to desktop. the client should be prompted with a message informing the user of a network error, and the user should be given an opportunity to reconnect.

**Comment by jcsnider** [comment]
So if the server simply closes then the client will present the following [notice](https://www.ascensiongamedev.com/resources/filehost/848245f601383cf1f02dfa8a3329fc08.png).

I wonder if it has something to do with client packets that error and then make the server boot the client...

**Comment by lodicolo** [comment]
Not sure if there is an issue anymore besides crashes, closing this (any crashes should be opened as bugs)
