### ISSUE TITLE
Movement Behave and Radius for monster.

### ISSUE THREAD

**Issue by Spectreye** [AscensionGameDev/Intersect-Engine#302]
**Hello !**

**As discussed with Joyce, the movement behaving of monster can be quite problematic, i quote here "@Mapyo" from the forum who explain it clearly why it can be a problem :** 

_I am working on guards and other NPC's for questing areas in my game, and I came to realize something... NPC's will follow you to the end of the god damn earth!_

_Seriously though, this can be abused to get new players killed by kiting high level mobs to lower level areas and then dropping your aggro by entering a new area or just logging, now I know this sounds like a simple little flaw with how NPC's currrently work but it can really mess with a game._

_Imagine walking into a dungeon to see that players have already been through and has kited all enemies to the end of the dungeon. Not only are you now screwed over because you have tons of enemies on you (which are supposed to be spread out across the dungeon) but you also don't get the experience the developers intended for you to have. _

_This problem also affects guards who stop hostiles from entering city/town/village gates! Sure you could just use an NPC block but having a guard that will defend you and prevent enemies from entering the kingdom is more immersive and really gives the game a nice touch. The problem you ask? Those guards will run after anything they see and will not return to their post ever!_

 

_Theres a solution here that I think we can all agree this engine needs, and that is more NPC Behaviour settings!_

_Here are a few settings I think should be added!_

https://s3.us-east-2.amazonaws.com/ascensiongamedev/filehost/8c4f4e7791658021bf94784abb89106d.png

 

_Roam - This is currently in the engine already, the option is called "Move Randomly". This mode is for when you want the Original style of NPC movement, no changes to what is currently in the engine._

_Guard - This behaviour setting will have the NPC stand still (or rotate randomly) and will attack (if attacked) enemies it sees withing its sight range (or when it gets hit) and will chase it until it the enemy leaves its guarding radius. If the enemy leaves the guarding radius then the guard will return to the spot it was set to spawn at._

_Radius - This behaviour setting will have the NPC roam around within its "Roam Radius" and will attack (if attacked) enemies it sees withing its sight range (or when it gets hit) if the enemy leaves the "Roam Radius" then it would stop attacking the enemy._

_Original idea belongs to @Aesthetic I just wanted to add to it! Find the original post below:_
https://www.ascensiongamedev.com/bug_tracker/suggestions/npc-quality-of-life-r1829/

**Comment by Azurebeats** [comment]
Part of this was added in 6.2.

Enhancement for this would be to make it configurable per NPC and set a maximum walk radius for npcs so they can't wander too far off from their spawn location.

**Comment by jcsnider** [comment]
Mostly resolved via options provided in #303 

Leaving this open as it would be beneficial to have a configurable radius option per NPC which would be another PR :P

**Comment by Spectreye** [comment]
Closing since fully enhanced in last build (Configurable radius per npc)
