### ISSUE TITLE
Editor crash when i open

### ISSUE THREAD

**Issue by Kamusvalenzuela** [AscensionGameDev/Intersect-Engine#313]
**Describe the bug**
i've updated my engine from 0.6.2.420 to 0.6.2.432
and my editor when i login crashed

**Version Encountered**
 0.6.2.432

**To Reproduce**
1. Take a versión 0.6.2.420
2. try to apply the patch for update to 0.6.2.432
3. open the editor

**Expected behavior**
I expected to open normally but this don't do that

**Screenshots**
![Screenshot_21](https://user-images.githubusercontent.com/51339474/92864769-e5f66280-f3d3-11ea-90b5-9d916d9a2a91.png)

**Logs**
2020-09-11 05:08:13.125 [Info] Connecting to 127.0.0.1:5451...

--------------------------------------------------------------------------------
2020-09-11 05:08:26.596 [Info] Connection approved [00000000-0000-0000-0000-000000000000].

--------------------------------------------------------------------------------
2020-09-11 05:08:26.629 [Debug] Connection established to remote [00000000-0000-0000-0000-000000000000/127.0.0.1:5451].

--------------------------------------------------------------------------------
2020-09-11 05:08:26.630 [Info] Connected [00000000-0000-0000-0000-000000000000].

--------------------------------------------------------------------------------

**Operating System:**
Windows 10 Pro 64 bits
[Editor-2020_09_11-02_08_11_214.log](https://github.com/AscensionGameDev/Intersect-Engine/files/5206007/Editor-2020_09_11-02_08_11_214.log)

**Comment by Azurebeats** [comment]
Did you replace the shaders folder while updating?

The new build may have different shaders.

**Comment by Kamusvalenzuela** [comment]
i've downloaded the client full 0.6.2.432 and only replace the shaders folders from that client to my updated client and that solved the problem Thx ♥
![Screenshot_22](https://user-images.githubusercontent.com/51339474/92868651-556e5100-f3d8-11ea-973b-becd4525eaaf.png)

**Comment by Kamusvalenzuela** [comment]
Closed and solved!
