### ISSUE TITLE
Client Close [Crash] - Event Inspector Issue

### ISSUE THREAD

**Issue by Kamusvalenzuela** [AscensionGameDev/Intersect-Engine#326]
**Describe the bug**
Basicly the client close when you enable the inspector on an event but you dont have any face on that
If you put a face, the inspector works well

**Version Encountered**

0.6.2.432

**To Reproduce**
1. Make a event and enable the inspector check
2. Introduce any text inside
3. Dont put a face to the inspector
4. Login in your game and try to click the event, your client will close

**Expected behavior**
When the player click the event for check the info of that event, show the text without a image

**Screenshots**
No screenshot, only crash

**Logs**
**--------------------------------------------------------------------------------**
**2020-09-22 22:40:06.818 [Error]**
  **Message: Referencia a objeto no establecida como instancia de un objeto.**
    **Stack:    en Intersect.Client.Interface.Game.EntityPanel.EntityBox.UpdateImage()**
   **en Intersect.Client.Interface.Game.EntityPanel.EntityBox.Update()**
   **en Intersect.Client.Entities.Player.Update()**
   **en Intersect.Client.Core.Main.ProcessGame()**
   **en Intersect.Client.Core.Main.Update()**
   **en Intersect.Client.MonoGame.IntersectGame.Update(GameTime gameTime)**
   **en Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)**
   **en Microsoft.Xna.Framework.Game.Tick()**
   **en Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()**
   **en Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)**

**--------------------------------------------------------------------------------**

**Operating System:**
Windows 10 64 bits

**Additional context**
No more

**Comment by jcsnider** [comment]
@Kamusvalenzuela can you download 0.6.2.432 again and copy over the Intersect Client.exe and Intersect Client.pdb files (both are important, and without renaming) and get the error logs again?

Doing so will provide us a line number which will help isolate the issue for debugging.

**Comment by Kamusvalenzuela** [comment]
i've tested again and the error only appears when a tileset is used as a sprite and the inspector is enabled with a NO FACE
This is with face  (Using a sprite and face on the inspector)
![Screenshot_30](https://user-images.githubusercontent.com/51339474/94157015-1cfa5880-fe57-11ea-986c-6974583399ef.png)

This is without face (Using a sprite without face on the inspector)
![Screenshot_31](https://user-images.githubusercontent.com/51339474/94157145-42876200-fe57-11ea-98df-963ed117a0cb.png)

This is without face (Using a tileset like a sprite and withou face on the inspector)
[errors-Intersect Client.log](https://github.com/AscensionGameDev/Intersect-Engine/files/5276750/errors-Intersect.Client.log)

So the bugged part its only when you use a inspector without face and a tileset like a sprite on "X" event
The server tries to load the sprite of the tileset as it does not have a face and he stop into the tileset, closing the client

![Screenshot_33](https://user-images.githubusercontent.com/51339474/94158583-f1786d80-fe58-11ea-943a-4d794d0798a1.png)

**Comment by Azurebeats** [comment]
@Kamusvalenzuela  I am unable to reproduce this with a clean 6.2 build by your given description, either I am misunderstanding something or you're not providing all the details.

Are you doing anything other than this?
![Image](https://s3.us-east-2.amazonaws.com/ascensiongamedev/filehost/aa9c52db1ea42f07dbb3c32b0a8d1b6e.png)

Do you have any custom paperdoll settings past the base Intersect ones?

**Comment by Kamusvalenzuela** [comment]
https://youtu.be/zx-L1HsNNFc 
There's an example
Maybe i'll need to fully download the last version and migrate my db

**Comment by Azurebeats** [comment]
Do you have any source modifications installed?

**Comment by Kamusvalenzuela** [comment]
![image](https://user-images.githubusercontent.com/51339474/94343958-4996a780-fff2-11ea-9757-ea1ee0fda347.png)
With clean version works well
and nope, i dont have any source modifications, only upgrades since 4.7 aprox

**Comment by Azurebeats** [comment]
Strange, anyone else have a game that's been upgraded that can produce a similar crash?

**Comment by Kamusvalenzuela** [comment]
Everyone on my game (36 players)
now i've downloaded a full clean version and i've tested it
The client doesn't the problem
The server (Config.json) its the problem
i'll search more closely the issue

**Comment by Kamusvalenzuela** [comment]
I just puted the default things on the config.json and compare with my config.json for test it and the config.json of the server have the error
The bug appears when you change the equipement slots
adjunt my config files and the default files
[config.zip](https://github.com/AscensionGameDev/Intersect-Engine/files/5287023/config.zip)
And the default config files
[config.zip](https://github.com/AscensionGameDev/Intersect-Engine/files/5287024/config.zip)
The issue appears when you add Custom equippements
(lane 21 to 94 of my config files)

**Comment by Azurebeats** [comment]
You have 12 equipment slots, but only 9 paperdoll slots defined.

That's what is causing your crash. This is not an engine bug.

**Comment by Kamusvalenzuela** [comment]
Ok i'll check it now
