### ISSUE TITLE
Chat channel tabs

### ISSUE THREAD

**Issue by da-rulez** [AscensionGameDev/Intersect-Engine#329]
**Is your feature request related to a problem? Please describe.**

There are no chat tabs

**Describe the solution you'd like**

Change the chat channel dropbox into tabs on top of / below the chatbox and add a System tab. Have it so that you can set messages as a system message. For example in events, xp drops, level up messages, etc. 

**Additional context**

Above is a basic system but you can expand by adding filters to the tabs so players can choose which messages they see in each tab.

**Comment by Azurebeats** [comment]
I don't think we'd need to get rid of the dropdown at the bottom, but having tabs like the following to filter chat with would probably help long term:

* All
* Global
* Party
* System
* Admin

Does mean we'd have to start tagging each chat message and retroactively go through each chat message being sent to add the appropriate tag however, and add the ability to add a tag to a chat message through the appropriate event command.

Sounds like a good feature request, but also a bit of a chore. Will see if I can get a draft for it when I have some time.

**Comment by WeylonSantana** [comment]
![image](https://user-images.githubusercontent.com/63019821/94201237-1ccb7e80-fe92-11ea-989c-af2ba1f00261.png)
@da-rulez would it be something more or less as you say?

@Azurebeats if it was more or less like this image above, how would the gui configuration look in the json files?

**Comment by da-rulez** [comment]
Yeah @WeylonSantana, something similar to that is what I had in mind. 

@Azurebeats Would it really have to be tagged? Can't you just add event and xp messages in the system tab?

Maybe Im missing some use cases for tagging it, but that seems like unnecessary extra work at first glance

**Comment by Azurebeats** [comment]
Yes, because right now every message is just that. A message. The client can't distinguish between what says what.

**Comment by WeylonSantana** [comment]
@Azurebeats events then you could have the option of sending a message to the chat system in addition to the chat player (all), local and global.  If your pros enter the base code of the intersecr you could think about it.

**Comment by Azurebeats** [comment]
I've done a first rough draft for this in #331 , please take a look at it .

There's some future room for making the tabs configurable as the channels displayed in each are currently hardcoded (but fairly easily changed around in code ) as well as the ability to send event messages to specific channels.

**Comment by Richy1111** [comment]
> 
> 
> I've done a first rough draft for this in #331 , please take a look at it .
> 
> There's some future room for making the tabs configurable as the channels displayed in each are currently hardcoded (but fairly easily changed around in code ) as well as the ability to send event messages to specific channels.

Just wondering if you're going to add a 'system' option in 'Add Chatbox Text' event command? Most events that would use the Chatbox command would probably be used for system messaging as well.

**Comment by Cheshire92** [comment]
The idea is that I might add a dropdown box in the future that allows for selecting a specific tag for your message. 
But right now it's just treated as a system (info) message I believe.

**Comment by Richy1111** [comment]
It only has 3 options for the Add Chatbox Text command. Player, Local and Global. I would have assumed the Player option would have went to 'system' tab but it doesn't.
But if you're going to revisit it in the future, thanks. 👍
