### ISSUE TITLE
Issue with Party UI

### ISSUE THREAD

**Issue by Kamusvalenzuela** [AscensionGameDev/Intersect-Engine#342]
**Describe the bug**
When you add more party members to limits and you try to edit the Party UI
Some errors appears
Like misterious Mana/Hp bars and missing bars from other members (up to 4 members)
![Screenshot_38](https://user-images.githubusercontent.com/51339474/94613742-74dff780-027b-11eb-9309-8c6e42d9446a.png)

**Version Encountered**

0.6.2.438

**To Reproduce**
1. Just edit your UI or change it for this file 
[PartyWindow.zip](https://github.com/AscensionGameDev/Intersect-Engine/files/5301771/PartyWindow.zip)
2. enter in your game and add more than 4 members to a party
3. See the issue

NOTE: The config have only settings to 5 members (Bcause when i was working on it i see the error and i can't continue)

**Screenshots**
![Screenshot_39](https://user-images.githubusercontent.com/51339474/94614214-326aea80-027c-11eb-9980-7c34b71bb543.png)

**Operating System:**
Windows 10 64 bits

**Comment by jcsnider** [comment]
Adding more party members doesn't automatically configure the UI json file for you.  When the party window was designed it was never meant to be used for more than 4 members.

You need to go and fix all of the options for Member5, 6, 7, 8, etc yourself which is mostly just cloning the options that are already there, making sure the names are correct, and then fixing the bounds (locations.)

I don't think this is a bug.

**Comment by Kamusvalenzuela** [comment]
i've fixed all of options for members 5,6 and i've stoped right here bcause the party window doesn't apply the changes propertly
here is my PartyWindow.json
[https://cdn.discordapp.com/attachments/615622475954520067/760961513375924284/PartyWindow.json](url)
i've posted right here the issue bcause Joyce mencioned it the "broken thing" about this system
![Screenshot_42](https://user-images.githubusercontent.com/51339474/94736856-475e8100-0343-11eb-897c-25416b1cd993.png)
And more info are posted right there:
https://www.ascensiongamedev.com/topic/5543-party-ui-issue/

**Comment by jcsnider** [comment]
Apologies for assuming it was user error. Got this fixed in #345 .

![party](https://www.ascensiongamedev.com/resources/filehost/53cfae6142fc24f0869ff9e3c1517d32.png)
