### ISSUE TITLE
Visual bug in the class editor.

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#352]
**Describe the bug**
I have a class in the class editor that its rebirth point changes if I change the order in chronological order.
It is only in this class, the other is normal.

I tried to copy this normal class, to the one that is defective and continues. Apparently the bug is visual only. I don't know if it's just me.

**Version Encountered**
0.6.2.439

**To Reproduce**
I just had the class in the editor, I don't know when it started or how to reproduce it.

**Expected behavior**
May the rebirth point not change when I change the order to chronological.

**Screenshots**
[001.zip](https://github.com/AscensionGameDev/Intersect-Engine/files/5312124/001.zip)

**Logs**
There is not

**Operating System:**
Window

**Comment by Azurebeats** [comment]
Could you please embed the pictures in the issue?

**Comment by WeylonSantana** [comment]
@Azurebeats I don't know how to do that. I didn't send images, I sent a video. And I don't know how to put the video too, in the other bug I put links from filehost because they were too big to upload here.

**Comment by Azurebeats** [comment]
Ah, sorry. I saw you put it under a header called Screenshots so I figured it was a zip file of pictures.
