### ISSUE TITLE
Client/Editor triggering speedhacking protection during normal use

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#353]
**Describe the bug**
I upgraded to version 0.6.2.439 and so any character in my game, new or old, doesn't walk. They are always teleported to where they were.

I know it's not a common event (because I have several) for 2 reasons:
1 - I turned them off, to see if it was up to them.
2 - Events teleport to a specific place, I used shift + right click to teleport, and this new location becomes the place where I cannot leave.

The customer log adds a new line to each attempt to walk the game, which consists of "received epp: 2100641", I don't know if it affects anything.

In the second video, I asked a friend of mine to join the game and for him to try to walk, the same thing happens. In my view, the character remains stationary, but he is there, walking and returning to the same place.

Remember that this is for an online server. Accessed via public ip and not locally.
I can't say if it has to do with the internet, but when the internet here is slow, messages sent by chat take time to appear in the game, I sent messages and everything was ok.

**Version Encountered**
0.6.2.439

**To Reproduce**
walk

**Expected behavior**
walk

**Screenshots**
[Video 1](https://www.ascensiongamedev.com/resources/filehost/eb82b4ab29d60309ba9acb0d3f5b97d6.mp4)
[Video 2](https://www.ascensiongamedev.com/resources/filehost/717409ea17574ec6720efdab0dac5677.mp4)

**Logs**
[logs.zip](https://github.com/AscensionGameDev/Intersect-Engine/files/5312247/logs.zip)

**Operating System:**
Windows

**Comment by Azurebeats** [comment]
There's some new packet options regarding latency and accepted delays, could you try raising these values and starting the server again to see if this makes a difference?

**Comment by jcsnider** [comment]
Please send us server logs.

**Comment by WeylonSantana** [comment]
[error.zip](https://github.com/AscensionGameDev/Intersect-Engine/files/5312897/error.zip)

**Comment by jcsnider** [comment]
Added more logging. Please try 0.6.2.440 and give us server logs when that one breaks. @WeylonSantana

**Comment by WeylonSantana** [comment]
[logs.zip](https://github.com/AscensionGameDev/Intersect-Engine/files/5313508/logs.zip)
@jcsnider

**Comment by jcsnider** [comment]
@WeylonSantana can you please try this build for me and let me know if the same error occurs?
https://www.ascensiongamedev.com/resources/filehost/d8554892e06f466d9ab0d1f8f554ef61.zip

**Comment by WeylonSantana** [comment]
@jcsnider Should I replace the files as if it were an update patch?

**Comment by jcsnider** [comment]
Yes

**Comment by WeylonSantana** [comment]
Okay, I'll answer you in a few minutes. If the same error occurs, will you want to log again?

**Comment by WeylonSantana** [comment]
@jcsnider I'm sorry for the delay, I had problems with the server, part of the night. So, there it is. I cannot say that the problem is 100% solved, but it is 99%.
Every time I start with the character only in the first step, I return back, as has happened, but after the first step, I can walk in the game normally, leave and enter the game a few times and every time only the first step happens. to return back, it is almost imperceptible.

[logs (1).zip](https://github.com/AscensionGameDev/Intersect-Engine/files/5315266/logs.1.zip)

**Comment by jcsnider** [comment]
Thanks Weylon. I saw that a few times in my testing and thought I had it resolved. At least we're close.

I will fix that tomorrow and we can wrap this one up.

**Comment by WeylonSantana** [comment]
Okay then. Thanks for your time and attention to this.

**Comment by jcsnider** [comment]
@WeylonSantana can you try this build for me?

When your character stutters on the first step can you send me whatever is logged in the server console?
https://www.ascensiongamedev.com/resources/filehost/532108d51c9c9ca670ec313e6c5d192d.zip

**Comment by WeylonSantana** [comment]
@jcsnider here's what we got
I would like to make a special comment: I tested walking and attacking simultaneously, and I tested gaining levels and walking simultaneously. He is retreating as he walks to the end of the attack sprite, or the level up message goes away, trying to force the player to retreat. I do not know if you came to testing, but happened to me, but no log is generated. Only on the first step does a message appear on the server and log.

[logs.zip](https://github.com/AscensionGameDev/Intersect-Engine/files/5320171/logs.zip)

**Comment by WeylonSantana** [comment]
This latest version that you sent is much better. The error in the first step still happens, but not always. I logged in about 5 times and it happened 2 times. My ping was at 93 (if that information is relevant). The same is true for my friend (whose ping was around 45), the first step in his error happened with the first step, but when I left and logged in again it didn't happen anymore. He made 3 attempts.

There is something relevant about attacking and walking as I mentioned.
In the view of those who attack and walk: the client or server is forcing him to go back, but nothing appears on the server side.
In the view of a third observer: the player attacks, remains stationary while the animation of the attack occurs, and then walks again.
In the video you will see these two perspectives.

Finally, when opening the client, the server reports the same error with a final "client.pingpacket" different from "client.movepacket"

Attached: video + log.

[logs.zip](https://github.com/AscensionGameDev/Intersect-Engine/files/5340521/logs.zip)
https://www.ascensiongamedev.com/resources/filehost/a797c11b9af49d24fc0e514c5f5a6eae.mp4

**Comment by jcsnider** [comment]
Okay, how about this one?
https://www.ascensiongamedev.com/resources/filehost/0445cc00d2931c32be5fe6e9e6dc2c37.zip

**Comment by WeylonSantana** [comment]
@jcsnider Sorry for the delay.

In my report for that version you sent it is:

For me, it's much better, it's getting better and better, I tested it 6 times, closing and opening the client every time and only once did the bug in the first step happen. At other times it happened to return back (sending debug on the server), but it didn't happen very often, it is more and more rare, I walked large amounts of maps.

For my friend (who has better internet than mine), the first step bug also happened 1 time, and not often happened to return back while walking.

We are not yet able to attack the npcs in the game with normal or armed attack, or each other (maybe all entities?).

The server always appears debug with ending "Packet [Intersect.Network.Packets.Client.PingPacket]" when we open the client.

For this version I have only 2 special notes to comment.
1 - The client generated a "silent error" in one of the tests, generated an error log, but nothing happened in the game, I was able to walk and talk in the game normally, but the error is there.
2 - The server crashed at some point, I don't remember which one, the log is together [[Error] Received unhandled exception from Thread Pool Worker], you'll see.

> but the default values might need some tweaking

I agree with you. I liked to stop when attacking, but I believe that many people will not.


Attached: my client's logs (so you can see if the "silent error" interferes with something. And the server's (the image shows the point where it crashed)

[logs client.zip](https://github.com/AscensionGameDev/Intersect-Engine/files/5351223/logs.client.zip)
[logs server.zip](https://github.com/AscensionGameDev/Intersect-Engine/files/5351224/logs.server.zip)

**Comment by jcsnider** [comment]
@WeylonSantana how about this one?
https://www.ascensiongamedev.com/resources/filehost/28eb28e66c014fb45858c30e89c360e6.zip

**Comment by WeylonSantana** [comment]
@jcsnider this time it got much worse. I have no words to explain the situation why I didn't understand what happened or what was happening, so I recorded my screen and asked my friend to record his screen.

my screen: https://www.ascensiongamedev.com/resources/filehost/ae808cf3ade8b66375a48e6e8fcfd0e3.mp4
his screen: https://www.ascensiongamedev.com/resources/filehost/1a3575e38dee55db64a01fa19353e928.mp4

logs: [logs.zip](https://github.com/AscensionGameDev/Intersect-Engine/files/5371087/logs.zip)


From what I understand, there is no bug in the first step, but we are not walking in the game, I do not see him walking and he does not see me walking, and in our clients we have the illusion of walking. Events that teleport what is played in touch do not work. (like the one in the house), maybe because the server doesn't recognize that we are there. attacking monsters still doesn't work.

**Comment by jcsnider** [comment]
@WeylonSantana got a few lines of code out of order. Here's another if you don't mind giving it a try:
https://www.ascensiongamedev.com/resources/filehost/1c6d06906ff7e667d2257c9e320a857c.zip

**Comment by WeylonSantana** [comment]
@jcsnider this version is 99% ok. There are only 2 current problems. I believe there are two small problems.

1 - Remember the setback when taking the first step? Well, it still happens, but it happens only on a very specific occasion: **when opening the client**. When the client is opened, when logging in, in the first step there is a step back to the place where it was originally. After that, there are no setbacks, even logging out and logging in several times. But always, when opening the client and logging in for the first time, the first step goes backwards and it is almost impeccable.
2 - I can attack monsters again, they recognize my place in the world and attacking them works again. However, for every 10 consecutive uninterrupted attacks (approximately), one attack does not work (the damage does not appear or decreases the monster's health). This is approximately the chance that the attacks are failing, 1 attack fails every 10 consecutive attacks.

I am giving my report now, because I have no access to the server logs, I will only have it at night or maybe tomorrow.

**Comment by WeylonSantana** [comment]
[logs.zip](https://github.com/AscensionGameDev/Intersect-Engine/files/5374874/logs.zip)

Server logs

**Comment by jcsnider** [comment]
@WeylonSantana see how 0.6.2.445 works for ya:
https://www.ascensiongamedev.com/topic/4232-prerelease-builds/?do=findComment&comment=48738

**Comment by WeylonSantana** [comment]
@jcsnider I really liked this version. I am going to give two opinions at this point.
1 - For me, speaking for myself, the bug is 100% fixed. This is the point. It's okay with me. I tried to walk in several places, there was barely even a setback and if there was one I didn't notice. No attacks were lost, I killed several npcs and all attacks resulted in damage and the monster's health decreased. Yes, everything is 100% ok for me.

2 - Now judge for yourself:
a - As I told you, the attack bug is 100% fixed and that is a fact. But as for walking, I realized the following:
Try to log into the game, after loading the map (around 5-10 seconds), walk. You will notice that everything is normal. Do this several times.

b - Try to log into the game again, several times, and before any map is loaded starts to move (while the screen is still black), the server will force the player to stay at the point of origin until the maps are 100% loaded (after 5-10 seconds). Only then does he walk normally in the game.

I'm sending a video for you to analyze.
https://www.ascensiongamedev.com/resources/filehost/e30afce1acc3c1094f47198d9fc5516b.mp4
In the log in at 00:08 and 00:32 of the video, I hope to load the map within the time I mentioned. Everything happens normal. At 00:50 in the video you will notice that it happens again (in my opinion the map was being loaded). At the log in at 01:15 and 01:35 of the video I am holding the floor button while on the black screen. At 2:00 in the video I wait again to test if the theory is still right. 2:20 happens the same as in 00:50. At the end of the video, the client closes because of that "queue empty" error that I reported once here.

Everything I explained above, for me is normal, since always when I make Heroes, there were always these little chokes when loading the map and it was something that never bothered me. Maybe it's even because of my machine that it's [not powerful](https://prnt.sc/uzgvsx). So in my opinion it is 100% and you can close the bug. But this is something that you decide.

**Comment by jcsnider** [comment]
Just released one more update to this which is in 0.6.2.447. Might not be absolutely perfect but it should be close. Gonna close this chain for now. If we have a lot of unacceptable stutters we can do more checks on login to make sure times are synced up before showing the world or something.
