### ISSUE TITLE
NPC Level

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#356]
**Is your feature request related to a problem? Please describe.**
The NPC level goes up to 100 and this is a problem.

**Describe the solution you'd like**
If we set a maximum level for the player, above or below 100, the npc editor should take that level configured on the server as max as well.

**Additional context**
I know that the level of the npc in the editor is purely demonstrative and useless, but it would be good if the npc (monsters) had the ability to match the level of the player when he exceeds more than 100 levels.

**Comment by Azurebeats** [comment]
I don't think this is an intentional limitation?
The input box is just hard limited by its settings to 100, nothing else in the engine seems to stop it from going above this..
I'll see about setting the limit to the max Int32 value. (2147483647)

**Comment by WeylonSantana** [comment]
@Azurebeats Okay for me, thank you very much.
