### ISSUE TITLE
feature: focus event dialogues to allow return submits

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#357]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I press Enter to continue an event dialog, on the login screen to login, on the registration screen, to choose options when there is only one option and the like.

**Describe the solution you'd like**
Pressing enter should work for any of the things mentioned above. It is only a small improvement in the quality of life, without main use and critical in the general functioning.

**Comment by Azurebeats** [comment]
I've managed to make some changes so this works for the login and registration window (already existed, just wasn't focussed properly).
Also for event user input dialogs, but not yet for events that ask you to press a button.. Not entirely sure Gwen has a handler for this.

**Comment by Azurebeats** [comment]
Mostly resolved with the merging of #359 
Leaving open for future enhancement on event dialogs.
