### ISSUE TITLE
"Reset radius for NPCs Bugs"

### ISSUE THREAD

**Issue by Spectreye** [AscensionGameDev/Intersect-Engine#364]
**Describe the bug**

A)The Reset Radius doesn't work in this particular case : The mob is a new spawn, he get taunted by a spell (for like 20 sec), if so he will follow the player regardless of the distance set. If the mob is triggered normally and go back one time, even if taunted by a spell after he will behave normally. 

B) When a monster get a damage on duration type (Ex: Dot duration 15sec) and the "ResetVitalsAndStatusses": true  is on, when he get to the radius limit and go back, he still take the damage (Even if the dot icon is gone)

C)When a monster have an high aggressive range or superior to the radius limit, he will go the limit and try to go back to his position, but due to the sight range he can't and will go back and forth until the player is outside of his aggressive radius.

**Version Encountered**
0.6.2.434 

**To Reproduce**

A)
1. Set in server config :
    "AllowResetRadius": true,
    "ResetRadius": 20,
    "AllowNewResetLocationBeforeFinish": false,
    "ResetVitalsAndStatusses": true

2. Make a spell who taunt mob on Aoe or single effect (Better results with Aoe) and taunt some freshly spawn mobs
3. Run (Futher than the radius limit)
4. See the mobs still chasing you.

B)
1. Set in server config :
    "AllowResetRadius": true,
    "ResetRadius": 20,
    "AllowNewResetLocationBeforeFinish": false,
    "ResetVitalsAndStatusses": true
2. Make an infinite dot spell who do little dmg
3. Test on a monster and go to the radius limit.
4.See the monster going back and still taking dmg from the dot.

C)
1. Set in server config :
    "AllowResetRadius": true,
    "ResetRadius": 20,
    "AllowNewResetLocationBeforeFinish": false,
    "ResetVitalsAndStatusses": true
2. Set a monster with an high aggressive range (Like 15 or 20)
3. Approach the monster and go a little behind his aggro radius, he will still want to kill you, your moma and her bridge friends.

**Expected behavior**
A) The taunted mob should return back to their position (Even if it's their first apparition)

B)The mobs should be cleansed of everything and go back to his position. (Maybe invincible during this time)

C)When hitting his radius limit the mob should drop his aggro and go back to his place before being able to be aggressive anew.

**Screenshots**

**Logs**

**Operating System:**
Windows

**Additional context**

Also, if you set a too low radius and do boss room, you may have boss who reset themselves : Give the capacity on editor to make a personnal radius for every monster is a must have someday.

**Comment by Azurebeats** [comment]
C is just how the system works, aggressive mobs will try and chase a player once they get in their sights again. 

The others are definitely bugs.

**Comment by Spectreye** [comment]
For C, maybe but that make it strangely comical sometimes or stupid (Depend of the point of view) xD
