### ISSUE TITLE
[Error] Dropping packet. Client Speedhacking?

### ISSUE THREAD

**Issue by Andical** [AscensionGameDev/Intersect-Engine#376]
![1](https://user-images.githubusercontent.com/14881655/95023001-d092f200-067a-11eb-96de-df9d18175e2f.PNG)
![2](https://user-images.githubusercontent.com/14881655/95023003-d12b8880-067a-11eb-8597-6592ddf1a66b.PNG)

1 guy and me are working together in a project, we returned after a few months of standby and with the new updates the editor is crashing for him. Its not a network problem since we had never had this issue and server has 500/500 mb and 2 ping.

Version - 0.6.2.442 WINDOWS
We have same client, same editor, same server version. He is getting disconnections and I get the following message in Server.Exe

 2020-10-04 17:24:34.929 [Error] Dropping Packet. Client Speedhacking?
        Ping[Connection=152, NetConnection=152, Error=0]
        Server Time[Ticks=259867946690, AdjustedMs=25986793, TicksUTC=637374290749265595, Offset=637374030881318905]
        Client Time[Ticks=259823004750, AdjustedMs=25982300, TicksUTC=637374290725961899, Offset=637374030902957149]
        Error[G=4493, R=2328, O=2164]
        Delta[Adjusted=4493, AWP=4341, AWEN=4379, AWEX=4303]
        Natural[A=False WP=False, WEN=False, WEX=False]
        Time Desync[True]
        Packet[Intersect.Network.Packets.Client.MovePacket]
2020-10-04 17:24:34.933 [Error] Dropping Packet. Client Speedhacking?
        Ping[Connection=152, NetConnection=152, Error=0]
        Server Time[Ticks=259868016616, AdjustedMs=25986801, TicksUTC=637374290749335521, Offset=637374030881318905]
        Client Time[Ticks=259825697288, AdjustedMs=25982569, TicksUTC=637374290728654437, Offset=637374030902957149]
        Error[G=4232, R=2067, O=2164]
        Delta[Adjusted=4232, AWP=4080, AWEN=4118, AWEX=4042]
        Natural[A=False WP=False, WEN=False, WEX=False]
        Time Desync[True]
        Packet[Intersect.Network.Packets.Client.MovePacket]
2020-10-04 17:24:35.057 [Error] Dropping Packet. Client Speedhacking?
        Ping[Connection=152, NetConnection=152, Error=0]
        Server Time[Ticks=259869255362, AdjustedMs=25986925, TicksUTC=637374290750574267, Offset=637374030881318905]
        Client Time[Ticks=259828407700, AdjustedMs=25982840, TicksUTC=637374290731364849, Offset=637374030902957149]
        Error[G=4085, R=1920, O=2164]
        Delta[Adjusted=4085, AWP=3933, AWEN=3971, AWEX=3895]
        Natural[A=False WP=False, WEN=False, WEX=False]
        Time Desync[True]
        Packet[Intersect.Network.Packets.Client.MovePacket]
2020-10-04 17:24:37.406 [Error] Dropping Packet. Client Speedhacking?
        Ping[Connection=144, NetConnection=144, Error=0]
        Server Time[Ticks=259892743494, AdjustedMs=25989274, TicksUTC=637374290774062399, Offset=637374030881318905]
        Client Time[Ticks=259883237940, AdjustedMs=25988323, TicksUTC=637374290750950788, Offset=637374030867712848]
        Error[G=951, R=2310, O=1360]
        Delta[Adjusted=951, AWP=807, AWEN=843, AWEX=771]
        Natural[A=False WP=False, WEN=False, WEX=False]
        Time Desync[True]
        Packet[Intersect.Network.Packets.Client.MovePacket]
2020-10-04 17:24:37.669 [Error] Dropping Packet. Client Speedhacking?
        Ping[Connection=144, NetConnection=144, Error=0]
        Server Time[Ticks=259895380793, AdjustedMs=25989538, TicksUTC=637374290776699698, Offset=637374030881318905]
        Client Time[Ticks=259885941623, AdjustedMs=25988594, TicksUTC=637374290753654471, Offset=637374030867712848]
        Error[G=944, R=2304, O=1360]
        Delta[Adjusted=944, AWP=800, AWEN=836, AWEX=764]
        Natural[A=False WP=False, WEN=False, WEX=False]
        Time Desync[True]
        Packet[Intersect.Network.Packets.Client.MovePacket]
2020-10-04 17:24:40.020 [Error] Dropping Packet. Client Speedhacking?
        Ping[Connection=144, NetConnection=144, Error=0]
        Server Time[Ticks=259918882513, AdjustedMs=25991888, TicksUTC=637374290800201418, Offset=637374030881318905]
        Client Time[Ticks=259904848714, AdjustedMs=25990484, TicksUTC=637374290772618391, Offset=637374030867769677]
        Error[G=1404, R=2758, O=1355]
        Delta[Adjusted=1404, AWP=1260, AWEN=1296, AWEX=1224]
        Natural[A=False WP=False, WEN=False, WEX=False]
        Time Desync[True]
        Packet[Intersect.Network.Packets.Client.MovePacket]
2020-10-04 17:24:40.813 [Error] Dropping Packet. Client Speedhacking?
        Ping[Connection=144, NetConnection=144, Error=0]
        Server Time[Ticks=259926811648, AdjustedMs=25992681, TicksUTC=637374290808130553, Offset=637374030881318905]
        Client Time[Ticks=259907552800, AdjustedMs=25990755, TicksUTC=637374290775322477, Offset=637374030867769677]
        Error[G=1926, R=3280, O=1355]
        Delta[Adjusted=1926, AWP=1782, AWEN=1818, AWEX=1746]
        Natural[A=False WP=False, WEN=False, WEX=False]
        Time Desync[True]
        Packet[Intersect.Network.Packets.Client.MovePacket]
2020-10-04 17:24:40.815 [Error] Dropping Packet. Client Speedhacking?
        Ping[Connection=144, NetConnection=144, Error=0]
        Server Time[Ticks=259926831519, AdjustedMs=25992683, TicksUTC=637374290808150424, Offset=637374030881318905]
        Client Time[Ticks=259910266099, AdjustedMs=25991026, TicksUTC=637374290778035776, Offset=637374030867769677]
        Error[G=1657, R=3011, O=1355]
        Delta[Adjusted=1657, AWP=1513, AWEN=1549, AWEX=1477]
        Natural[A=False WP=False, WEN=False, WEX=False]
        Time Desync[True]
        Packet[Intersect.Network.Packets.Client.MovePacket]
2020-10-04 17:24:40.816 [Error] Dropping Packet. Client Speedhacking?
        Ping[Connection=144, NetConnection=144, Error=0]
        Server Time[Ticks=259926841493, AdjustedMs=25992684, TicksUTC=637374290808160398, Offset=637374030881318905]
        Client Time[Ticks=259912968891, AdjustedMs=25991296, TicksUTC=637374290780738568, Offset=637374030867769677]
        Error[G=1388, R=2742, O=1355]
        Delta[Adjusted=1388, AWP=1244, AWEN=1280, AWEX=1208]
        Natural[A=False WP=False, WEN=False, WEX=False]
        Time Desync[True]
        Packet[Intersect.Network.Packets.Client.MovePacket]
2020-10-04 17:24:40.817 [Error] Dropping Packet. Client Speedhacking?
        Ping[Connection=144, NetConnection=144, Error=0]
        Server Time[Ticks=259926851488, AdjustedMs=25992685, TicksUTC=637374290808170393, Offset=637374030881318905]
        Client Time[Ticks=259915682434, AdjustedMs=25991568, TicksUTC=637374290783452111, Offset=637374030867769677]
        Error[G=1117, R=2471, O=1355]
        Delta[Adjusted=1117, AWP=973, AWEN=1009, AWEX=937]
        Natural[A=False WP=False, WEN=False, WEX=False]
        Time Desync[True]
        Packet[Intersect.Network.Packets.Client.MovePacket]
2020-10-04 17:24:41.496 [Error] Dropping Packet. Client Speedhacking?
        Ping[Connection=144, NetConnection=144, Error=0]
        Server Time[Ticks=259933644714, AdjustedMs=25993364, TicksUTC=637374290814963619, Offset=637374030881318905]
        Client Time[Ticks=259918384969, AdjustedMs=25991838, TicksUTC=637374290786154646, Offset=637374030867769677]
        Error[G=1526, R=2880, O=1355]
        Delta[Adjusted=1526, AWP=1382, AWEN=1418, AWEX=1346]
        Natural[A=False WP=False, WEN=False, WEX=False]
        Time Desync[True]
        Packet[Intersect.Network.Packets.Client.MovePacket]
2020-10-04 17:24:41.498 [Error] Dropping Packet. Client Speedhacking?
        Ping[Connection=144, NetConnection=144, Error=0]
        Server Time[Ticks=259933664698, AdjustedMs=25993366, TicksUTC=637374290814983603, Offset=637374030881318905]
        Client Time[Ticks=259921190785, AdjustedMs=25992119, TicksUTC=637374290788861085, Offset=637374030867670300]
        Error[G=1247, R=2611, O=1364]
        Delta[Adjusted=1247, AWP=1103, AWEN=1139, AWEX=1067]
        Natural[A=False WP=False, WEN=False, WEX=False]
        Time Desync[True]
        Packet[Intersect.Network.Packets.Client.MovePacket]
2020-10-04 17:24:41.500 [Error] Dropping Packet. Client Speedhacking?
        Ping[Connection=144, NetConnection=144, Error=0]
        Server Time[Ticks=259933684672, AdjustedMs=25993368, TicksUTC=637374290815003577, Offset=637374030881318905]
        Client Time[Ticks=259923903464, AdjustedMs=25992390, TicksUTC=637374290791573764, Offset=637374030867670300]
        Error[G=978, R=2342, O=1364]
        Delta[Adjusted=978, AWP=834, AWEN=870, AWEX=798]
        Natural[A=False WP=False, WEN=False, WEX=False]
        Time Desync[True]
        Packet[Intersect.Network.Packets.Client.MovePacket]
2020-10-04 17:24:41.501 [Error] Dropping Packet. Client Speedhacking?
        Ping[Connection=144, NetConnection=144, Error=0]
        Server Time[Ticks=259933694662, AdjustedMs=25993369, TicksUTC=637374290815013567, Offset=637374030881318905]
        Client Time[Ticks=259926605752, AdjustedMs=25992660, TicksUTC=637374290794276052, Offset=637374030867670300]
        Error[G=709, R=2073, O=1364]
        Delta[Adjusted=709, AWP=565, AWEN=601, AWEX=529]
        Natural[A=False WP=False, WEN=False, WEX=False]
        Time Desync[False]
        Packet[Intersect.Network.Packets.Client.MovePacket]
2020-10-04 17:24:43.692 [Error] Dropping Packet. Client Speedhacking?
        Ping[Connection=141, NetConnection=141, Error=0]
        Server Time[Ticks=259955601773, AdjustedMs=25995559, TicksUTC=637374290836920678, Offset=637374030881318905]
        Client Time[Ticks=259944715100, AdjustedMs=25994471, TicksUTC=637374290813445599, Offset=637374030868730499]
        Error[G=1088, R=2346, O=1258]
        Delta[Adjusted=1088, AWP=947, AWEN=982.25, AWEX=911.75]
        Natural[A=False WP=False, WEN=False, WEX=False]
        Time Desync[True]
        Packet[Intersect.Network.Packets.Client.MovePacket]
2020-10-04 17:25:22.109 [Error] Dropping Packet. Client Speedhacking?
        Ping[Connection=195, NetConnection=195, Error=0]
        Server Time[Ticks=260339776851, AdjustedMs=26033977, TicksUTC=637374291221095756, Offset=637374030881318905]
        Client Time[Ticks=260317493406, AdjustedMs=26031749, TicksUTC=637374291205771464, Offset=637374030888278058]
        Error[G=2228, R=1531, O=696]
        Delta[Adjusted=2228, AWP=2033, AWEN=2081.75, AWEX=1984.25]
        Natural[A=False WP=False, WEN=False, WEX=False]
        Time Desync[True]
        Packet[Intersect.Network.Packets.Client.AttackPacket]
2020-10-04 17:25:22.929 [Error] Dropping Packet. Client Speedhacking?
        Ping[Connection=191, NetConnection=191, Error=0]
        Server Time[Ticks=260347977166, AdjustedMs=26034797, TicksUTC=637374291229296071, Offset=637374030881318905]
        Client Time[Ticks=260322042575, AdjustedMs=26032204, TicksUTC=637374291210320633, Offset=637374030888278058]
        Error[G=2593, R=1896, O=696]
        Delta[Adjusted=2593, AWP=2402, AWEN=2449.75, AWEX=2354.25]
        Natural[A=False WP=False, WEN=False, WEX=False]
        Time Desync[True]
        Packet[Intersect.Network.Packets.Client.MovePacket]
2020-10-04 17:25:23.188 [Error] Dropping Packet. Client Speedhacking?
        Ping[Connection=191, NetConnection=191, Error=0]
        Server Time[Ticks=260350570295, AdjustedMs=26035057, TicksUTC=637374291231889200, Offset=637374030881318905]
        Client Time[Ticks=260324763186, AdjustedMs=26032476, TicksUTC=637374291213041244, Offset=637374030888278058]
        Error[G=2581, R=1884, O=696]
        Delta[Adjusted=2581, AWP=2390, AWEN=2437.75, AWEX=2342.25]
        Natural[A=False WP=False, WEN=False, WEX=False]
        Time Desync[True]
        Packet[Intersect.Network.Packets.Client.MovePacket]
2020-10-04 17:25:23.190 [Error] Dropping Packet. Client Speedhacking?
        Ping[Connection=191, NetConnection=191, Error=0]
        Server Time[Ticks=260350590153, AdjustedMs=26035059, TicksUTC=637374291231909058, Offset=637374030881318905]
        Client Time[Ticks=260327469046, AdjustedMs=26032746, TicksUTC=637374291215747104, Offset=637374030888278058]
        Error[G=2313, R=1616, O=696]
        Delta[Adjusted=2313, AWP=2122, AWEN=2169.75, AWEX=2074.25]
        Natural[A=False WP=False, WEN=False, WEX=False]
        Time Desync[True]
        Packet[Intersect.Network.Packets.Client.MovePacket]
2020-10-04 17:25:23.727 [Error] Dropping Packet. Client Speedhacking?
        Ping[Connection=191, NetConnection=191, Error=0]
        Server Time[Ticks=260355960919, AdjustedMs=26035596, TicksUTC=637374291237279824, Offset=637374030881318905]
        Client Time[Ticks=260330175709, AdjustedMs=26033017, TicksUTC=637374291218453767, Offset=637374030888278058]
        Error[G=2579, R=1882, O=696]
        Delta[Adjusted=2579, AWP=2388, AWEN=2435.75, AWEX=2340.25]
        Natural[A=False WP=False, WEN=False, WEX=False]
        Time Desync[True]
        Packet[Intersect.Network.Packets.Client.MovePacket]
2020-10-04 17:25:23.729 [Error] Dropping Packet. Client Speedhacking?
        Ping[Connection=191, NetConnection=191, Error=0]
        Server Time[Ticks=260355980770, AdjustedMs=26035598, TicksUTC=637374291237299675, Offset=637374030881318905]
        Client Time[Ticks=260332889704, AdjustedMs=26033288, TicksUTC=637374291221167762, Offset=637374030888278058]
        Error[G=2310, R=1613, O=696]
        Delta[Adjusted=2310, AWP=2119, AWEN=2166.75, AWEX=2071.25]
        Natural[A=False WP=False, WEN=False, WEX=False]
        Time Desync[True]
        Packet[Intersect.Network.Packets.Client.MovePacket]
2020-10-04 17:25:23.910 [Error] Dropping Packet. Client Speedhacking?
        Ping[Connection=191, NetConnection=191, Error=0]
        Server Time[Ticks=260357788919, AdjustedMs=26035778, TicksUTC=637374291239107824, Offset=637374030881318905]
        Client Time[Ticks=260335594294, AdjustedMs=26033559, TicksUTC=637374291223872352, Offset=637374030888278058]
        Error[G=2219, R=1522, O=696]
        Delta[Adjusted=2219, AWP=2028, AWEN=2075.75, AWEX=1980.25]
        Natural[A=False WP=False, WEN=False, WEX=False]
        Time Desync[True]
        Packet[Intersect.Network.Packets.Client.MovePacket]
2020-10-04 17:25:24.177 [Error] Dropping Packet. Client Speedhacking?
        Ping[Connection=191, NetConnection=191, Error=0]
        Server Time[Ticks=260360456325, AdjustedMs=26036045, TicksUTC=637374291241775230, Offset=637374030881318905]
        Client Time[Ticks=260338307476, AdjustedMs=26033830, TicksUTC=637374291226585534, Offset=637374030888278058]
        Error[G=2215, R=1518, O=696]
        Delta[Adjusted=2215, AWP=2024, AWEN=2071.75, AWEX=1976.25]
        Natural[A=False WP=False, WEN=False, WEX=False]
        Time Desync[True]
        Packet[Intersect.Network.Packets.Client.MovePacket]
2020-10-04 17:26:16.734 [Error] Dropping Packet. Client Speedhacking?
        Ping[Connection=167, NetConnection=167, Error=0]
        Server Time[Ticks=260886030576, AdjustedMs=26088603, TicksUTC=637374291767349481, Offset=637374030881318905]
        Client Time[Ticks=260719794695, AdjustedMs=26071979, TicksUTC=637374291744700811, Offset=637374031024906116]
        Error[G=16624, R=2264, O=14359]
        Delta[Adjusted=16624, AWP=16457, AWEN=16498.75, AWEX=16415.25]
        Natural[A=False WP=False, WEN=False, WEX=False]
        Time Desync[True]
        Packet[Intersect.Network.Packets.Client.MovePacket]
2020-10-04 17:32:29.912 [Error] Dropping Packet. Client Speedhacking?
        Ping[Connection=164, NetConnection=164, Error=0]
        Server Time[Ticks=264617804046, AdjustedMs=26461780, TicksUTC=637374295499122951, Offset=637374030881318905]
        Client Time[Ticks=264607488137, AdjustedMs=26460748, TicksUTC=637374295475353247, Offset=637374030867865110]
        Error[G=1032, R=2376, O=1345]
        Delta[Adjusted=1032, AWP=868, AWEN=909, AWEX=827]
        Natural[A=False WP=False, WEN=False, WEX=False]
        Time Desync[True]
        Packet[Intersect.Network.Packets.Client.MovePacket]
2020-10-04 17:32:30.452 [Error] Dropping Packet. Client Speedhacking?
        Ping[Connection=164, NetConnection=164, Error=0]
        Server Time[Ticks=264623204523, AdjustedMs=26462320, TicksUTC=637374295504523428, Offset=637374030881318905]
        Client Time[Ticks=264612898291, AdjustedMs=26461289, TicksUTC=637374295480763401, Offset=637374030867865110]
        Error[G=1031, R=2375, O=1345]
        Delta[Adjusted=1031, AWP=867, AWEN=908, AWEX=826]
        Natural[A=False WP=False, WEN=False, WEX=False]
        Time Desync[True]
        Packet[Intersect.Network.Packets.Client.MovePacket]
2020-10-04 17:34:15.611 [Error] Dropping Packet. Client Speedhacking?
        Ping[Connection=199, NetConnection=199, Error=0]
        Server Time[Ticks=265674792792, AdjustedMs=26567479, TicksUTC=637374296556111697, Offset=637374030881318905]
        Client Time[Ticks=265658912851, AdjustedMs=26565891, TicksUTC=637374296541062706, Offset=637374030882149855]
        Error[G=1588, R=1504, O=83]
        Delta[Adjusted=1588, AWP=1389, AWEN=1438.75, AWEX=1339.25]
        Natural[A=False WP=False, WEN=False, WEX=False]
        Time Desync[True]
        Packet[Intersect.Network.Packets.Client.PingPacket]

**Comment by Azurebeats** [comment]
Similar issue as #353 
Could you try the binary provided there? It's a work in progress.

And please attach the log file rather than pasting it in here.

**Comment by Azurebeats** [comment]
Actually, I'm going to sound stupid here.. but the speedhacking messages are about movement packets from a client. Not the editor.

Does he get a crash log from his editor?

**Comment by jcsnider** [comment]
As of 0.6.2.447 the speedhacking errors should be resolved. If editor disconnects persist please open another report.
