### ISSUE TITLE
Give or Take a "variable" item number to player.

### ISSUE THREAD

**Issue by Spectreye** [AscensionGameDev/Intersect-Engine#380]
**Is your feature request related to a problem? Please describe.**

In the process of my harvesting system, I wanted to player to gain experience in their harvest job and the ressources to give them more when they level up. So i set up a global event to do that.

I've been doing it with tier like this : 

Mining Roll 0 - 20 / 20 - 40 / 40 - 60 / 60 - 80 / 80 - 100 / 100 - 120 / 120 - 140 / 140 - 160 / 160 - 180 / 180 - 200
And the ressources going up with each roll.

But it require a fair amount of eventing, and at a point it become "useless" 
so i had the idea to make a formula, except there's a problem : 

_**you cannot give a "variable" item number to player.**_

**Describe the solution you'd like**

Make it possible to give an "Integer" Variable amount of item to a player.

It would be very efficient for a lot of event and open new easier way to make quest (Like Random number of ressources requested by npc).

**Comment by Azurebeats** [comment]
I like this idea, however it would also need to be implemented in various other item/inventory related commands at the same time or it would leave a very random implementation.

**Comment by Azurebeats** [comment]
Got it working on Change Item.

![Image](https://s3.us-east-2.amazonaws.com/ascensiongamedev/filehost/29c5dc7501b860922d6e65b5190693c3.png)

Probably needs to be on checking inventory slots as well. Possibly more?

**Comment by Azurebeats** [comment]
And some more progress..

![image1](https://s3.us-east-2.amazonaws.com/ascensiongamedev/filehost/fa65f054ffb9d6a855458a0c47c28ae1.png)
![Image2](https://s3.us-east-2.amazonaws.com/ascensiongamedev/filehost/2094584d7358ece3c29d8f08b5ec9927.png)
