### ISSUE TITLE
Addition to 'Give Experience' command

### ISSUE THREAD

**Issue by Richy1111** [AscensionGameDev/Intersect-Engine#381]
**Describe the solution you'd like**
Hello, I would like to request that the 'Give Experience' command in event editor also allows the use of variable integers. Since the variables have multiply/divide abilities, it would be nice to use them in such a way to formulate an experience gain equation in my mission ranking event.

Thanks <3

**Comment by Azurebeats** [comment]
Going to try and work this in alongside of #380
