### ISSUE TITLE
Option to draw NPC level?

### ISSUE THREAD

**Issue by Richy1111** [AscensionGameDev/Intersect-Engine#382]
I know targetting an NPC will show level and vitals, but I would like to request the NPC level being drawn on screen either above/below NPC name (or provide the option to). Sounds redundant but if a player chose to play without showing UI, targeting UI would be invisible as well.

Thanks <3

**Comment by jcsnider** [comment]
This might already be possible via the strings files. I'll have to double check.

**Comment by Richy1111** [comment]
And could we have option to draw map item names too, some items could be dropped behind a fringe or resource where a player would not otherwise see it there.

**Comment by Azurebeats** [comment]
@Richy1111 see #246 for that.

**Comment by Azurebeats** [comment]
Just checked by the way, the actual requested feature here is not yet possible.
