### ISSUE TITLE
Shared client (Without graphics only compressed on pack folder) crash

### ISSUE THREAD

**Issue by Kamusvalenzuela** [AscensionGameDev/Intersect-Engine#386]
**Describe the bug**
The shared clients can't loggin in the world bcause the client do a misterious crash with black window
The client with all graphics on their respective folders works well
But the compressed clients (With graphics only on the Pack folder, and nothing on the other graphic folder) doesn't work

**Version Encountered**

0.6.2.443

**To Reproduce**
1. Use the package textures on the editor
2. Clean the client deleting the graphics on:

- Animations
- Entities
- Faces
- Fogs
- Images
- Items
- Paperdolls
- Resources
- Spells
- Tilesets

3. check the "Packs" folder to see all compressed graphics
4. Run the client and try to loggin in the world

**Expected behavior**
Load normally the world after loggin

**Screenshots**
![Screenshot_52](https://user-images.githubusercontent.com/51339474/95508587-a185c480-0989-11eb-862f-897d81cd5677.png)
![Screenshot_53](https://user-images.githubusercontent.com/51339474/95508602-a5b1e200-0989-11eb-9899-f729aee4c810.png)

**And after blackscreen the client closes**

**Logs**
[errors-Inmortal Tower.log](https://github.com/AscensionGameDev/Intersect-Engine/files/5351118/errors-Inmortal.Tower.log)

**Operating System:**
Windows 10 64bits

**Comment by Cheshire92** [comment]
Fixed through #387
