### ISSUE TITLE
Walkable Ressources and Monster respawn on ressources

### ISSUE THREAD

**Issue by Spectreye** [AscensionGameDev/Intersect-Engine#388]
**Describe the bug**
Monster seems to be able to walk on Ressources( after it had respawned one time i think), player can also dash through those or inside but cannot "move" after. The problem is it can happen on the same ressources ( I mean a spot can bug and another of the same type don't). 

Also, monster can respawn on depleted ressources, leading to "trapped" monster inside ressources.

**Version Encountered**
0.6.2.434

**To Reproduce**
I'm not sure about what's affecting the ressources, my guess would be probably about the respawn mechanics,
Because when ressources spawn for the "first" time there's no problem, and after a respawn they become walkable by monster and dashable.

Also  : My ressources are "walkable after ressources removal" not before, and the dash do not ignore any collision.

**Expected behavior**
-Ressources shouldn't be dashable, or walkable by monster if the option hasn't been check

-Monster shouldn't be allowed to respawn on ressources (Depleted or not).

**Screenshots**
Not sure i could help but i tried to take screen of what happen : 
https://ascensiongamedev.com/resources/filehost/7ae706e9138a829a7bd07dc7cb6d805d.png

**Operating System:**
Windows

**Comment by Cheshire92** [comment]
@Spectreye Could you try this build to confirm it works?
https://www.ascensiongamedev.com/resources/filehost/1a8e97bd1c47694238872968872d3971.zip

**Comment by Spectreye** [comment]
Just finished the test, everything seems ok !
Projectile are ok too now.

**Comment by Cheshire92** [comment]
Fixed in #389
