### ISSUE TITLE
NPC's walking through 'impassable' events?

### ISSUE THREAD

**Issue by Richy1111** [AscensionGameDev/Intersect-Engine#393]
Not sure if this was intentional or if it could be passed as a bug.
But I just realized an NPC can walk through my locked door events...
We can use Npc Avoid attributes but, I thought events would have auto-blocked.

**Comment by Cheshire92** [comment]
Events are only processed for the relevant players and currently do not interact with npcs whatsoever.

**Comment by Richy1111** [comment]
Okay just making sure. Thanks for clarification, I'll use Npc Avoids where needed.
