### ISSUE TITLE
Attack doesn't launch when moving

### ISSUE THREAD

**Issue by Spectreye** [AscensionGameDev/Intersect-Engine#397]
**Describe the bug**
When you equip a weapon with a projectile and move forward then attack, the character stop for the duration of the attack speed set,  but no projectile is launched nor attack animation.

When you stand perfectly still, it works as intended.

**Version Encountered**
0.6.2.446

**To Reproduce**
1.  Make a weapon with a projectile, set the speed to 3000 ms (For a better view of the problem)
2.  Equip the item and start moving then try to attack while moving
3.  The character will stop, try to attack (nothing will came out)
4.  See error

**Expected behavior**
The player attack should be launched correctly (Even if he have to stand for the duration time)

**Video**
https://ascensiongamedev.com/resources/filehost/a751aa306f93c45530e87f6c489b3914.mp4

**Operating System:**
Windows

**Comment by Richy1111** [comment]
I still do like the idea of being stood still for the duration of the attack though. That brings more strategy to fighting in all class aspects instead of just shooting freely or running around auto-swinging at everything.

**Comment by jcsnider** [comment]
Should be fixed in 0.6.2.447 -- please confirm @Spectreye

**Comment by Spectreye** [comment]
Works perfectly ! Thanks a lot !
