### ISSUE TITLE
Client Crash (again)

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#405]
**Describe the bug**
See:
https://github.com/AscensionGameDev/Intersect-Engine/issues/266

**Version Encountered**
0.6.2.447

**To Reproduce**
I don't know.

**Expected behavior**
Don't crash

**Logs**
[errors-Intersect Client.log](https://github.com/AscensionGameDev/Intersect-Engine/files/5402341/errors-Intersect.Client.log)
[Intersect Client-2020_10_14-18_44_45_333.log](https://github.com/AscensionGameDev/Intersect-Engine/files/5402342/Intersect.Client-2020_10_14-18_44_45_333.log)
[Intersect Client-2020_10_14-18_47_02_307.log](https://github.com/AscensionGameDev/Intersect-Engine/files/5402343/Intersect.Client-2020_10_14-18_47_02_307.log)
[Intersect Client-2020_10_18-11_48_29_919.log](https://github.com/AscensionGameDev/Intersect-Engine/files/5402344/Intersect.Client-2020_10_18-11_48_29_919.log)
[Intersect Client-2020_10_18-11_48_55_917.log](https://github.com/AscensionGameDev/Intersect-Engine/files/5402345/Intersect.Client-2020_10_18-11_48_55_917.log)
[Intersect Client-2020_10_19-10_54_22_148.log](https://github.com/AscensionGameDev/Intersect-Engine/files/5402346/Intersect.Client-2020_10_19-10_54_22_148.log)

**Operating System:**
Windows

**Additional context**

**Comment by lodicolo** [comment]
Filed bug against Monogame: MonoGame/MonoGame#7402
Opened PR with fix: MonoGame/MonoGame#7403

Closing this since they have a tracking bug.
