### ISSUE TITLE
Warp to target spell : No "Target is out of range"

### ISSUE THREAD

**Issue by Spectreye** [AscensionGameDev/Intersect-Engine#407]
**Describe the bug**
When you make a warp to target spell with let's say, 5 range and if you use it on a monster, if you are out of range the spell is still "used", take the mana and get on cooldown. 

**Version Encountered**
0.6.2.448

**To Reproduce**
1. Make a warp to target spell with 5 range, a mana cost and a cooldown.
2. Use this spell on a monster being out of range.
3. ...

**Expected behavior**
The spell should warn you with a "Out of range" like other spell type

**Operating System:**
Windows

**Comment by Cheshire92** [comment]
Personally, instead of fixing this and calling it a day I'd prefer to just re-do how spell logic on the server works in the first place.
A spell should not be able to bypass a range check, ever. So this means there's a fundamental issue rather than a small one.

**Comment by FrSenpai** [comment]
I'll probably share a rev for the build n453 with logic edited server-side.

Have a good day
