### ISSUE TITLE
Events can't be inspected ingame (to show the message)

### ISSUE THREAD

**Issue by Andical** [AscensionGameDev/Intersect-Engine#408]
**Describe the bug**
When I create an event and enable inspector to show the message I write in it, I cant target ingame.

Windows, version 6.2.449

**To Reproduce**
1. Create an event.
2. Write something inside Inspector Description
3. Enable inspector
4. Targeting this event inside game doesnt pop the window with the message we wrote previously.
![event](https://user-images.githubusercontent.com/14881655/96652037-6181f280-1336-11eb-9e37-7c7c13ab01eb.PNG)
![event2](https://user-images.githubusercontent.com/14881655/96652163-a574f780-1336-11eb-92b9-b4ae92d57be6.PNG)

**Comment by Cheshire92** [comment]
I can't tell if you have it targeted in that screenshot, but it only works when you target an event, much like you would target an NPC.

**Comment by Andical** [comment]
I can't target it ingame, in previous 6.1 it was possible but now doesn't work

**Comment by Cheshire92** [comment]
Ah, it's because you don't have a graphic set for the event. The new target code is based on the graphic size I believe.
I'll look into fixing that.
