### ISSUE TITLE
Strange behavior in the "end mission" command

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#411]
**Describe the bug**
I am using the command "end mission" (executing end event). And strange behavior is happening. I'm not sure how to explain it so I'll show it in images in "To Reproduce"

**Version Encountered**
0.6.2.447

**To Reproduce**
1 - Event that ends the mission. (page without conditions).
![image](https://user-images.githubusercontent.com/63019821/96882886-2080ff80-1456-11eb-8d4e-77cfb5576283.png)

2 - Mission completion event
![image](https://user-images.githubusercontent.com/63019821/96883148-72c22080-1456-11eb-89cb-cfb1e5a15294.png)

3 - Result
[https://www.ascensiongamedev.com/resources/filehost/af2a5b8b8654927f8634caf7c53e7788.mp4](url)

Note¹:The chat command I use is to run common events when needed.
Note²:When the mission is finished, if you re-login, the log is updated and the mission disappears, but if you don’t do that, you can’t abandon it and if you accept the same mission it will still work even though the mission is already there.

**Expected behavior**
End mission correctly.

**Logs**
I don't know if it has to do, but this log was generated the first time it happened.
[Intersect Client-2020_10_22-09_57_36_295.log](https://github.com/AscensionGameDev/Intersect-Engine/files/5423388/Intersect.Client-2020_10_22-09_57_36_295.log)
(look at the error at the end of the log)

**Operating System:**
Windows

**Comment by Cheshire92** [comment]
Am I understanding this, but the quest stays in the questlog client-side but otherwise finishes correctly?

**Comment by WeylonSantana** [comment]
Exactly.  When an event ends the mission, the mission remains in the quest log, and it is not possible to abandon it.  If you relog it disappears.  If you do not relog, and accept the same mission again, the mission starts even though it is already in the mission log.

**Comment by jcsnider** [comment]
@WeylonSantana is this still an issue?

Does it happen if there are no events running upon quest completion? Wondering how to simplify the problem before I go and try to recreate.

**Comment by WeylonSantana** [comment]
@jcsnider yes, this is still a issue. See - https://www.ascensiongamedev.com/resources/filehost/7d539edbbc2b9a526199e9a7067ddfb3.mkv
