### ISSUE TITLE
Copying an event, copies the tiles underneath too.

### ISSUE THREAD

**Issue by lyimpike** [AscensionGameDev/Intersect-Engine#418]
**Describe the bug**
Copying an event, will copy tiles underneath even though you aren't in the _tiles_ tab

**Version Encountered**
0.6.1.261

**To Reproduce**
Copy a blank event (_or even a code-packed one_) with tiles underneath and paste it onto an empty (_void_) tile.
The tile will copy over too, even though you aren't in the _tiles_ tab.
(_This happens when you drag an event around the map too, taking the tile underneath with you._) 

**Operating System**
Client & Editor: Windows 10 Personal
Server: Windows Server 2016

**Comment by jcsnider** [comment]
Edit > Select > CurrentLayerOnly

**Comment by lyimpike** [comment]
> Edit > Select > CurrentLayerOnly

My apologies, thanks for the heads up.

**Comment by lyimpike** [comment]
> Edit > Select > CurrentLayerOnly

My bad, thanks for the heads up!
