### ISSUE TITLE
Editor Option to Resume From Where You Left Off

### ISSUE THREAD

**Issue by lyimpike** [AscensionGameDev/Intersect-Engine#422]
**Is your feature request related to a problem? Please describe.**
When you have many, many, many maps it can be annoying to have to go through folders to find the map you were last working on.

**Describe the solution you'd like**
I'd love to see an optional check-box that would make the editor open on the map you were last editing.

**Additional context**
![Screenshot_1](https://user-images.githubusercontent.com/25600834/97767603-65520980-1ada-11eb-93ca-707a5528205f.png)

**Comment by lodicolo** [comment]
The PR didn't add a checkbox to enable this (it's just always on), but I also don't see a good reason for this behavior to not be always on so I am closing this as completed.
