### ISSUE TITLE
Bug with weapon animation

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#423]
**Describe the bug**
I have 6 animations of 2 sprites.
![image](https://user-images.githubusercontent.com/63019821/97801740-9555f580-1c1d-11eb-818c-eab9515b576b.png)

The player.png have - 
1 - player_cast.png, 
2 - player_idle.png, 
3 - player_attack.png.

The player_sword.png have - 
1 - player_sword_cast.png,
2 - player_sword_idle.png, 
3 - player_sword_weapon.png.

That's the player.png:
https://www.ascensiongamedev.com/resources/filehost/312b8d2a3dcf3fbd92cb374679a67fd2.mp4

It performs attack animation (2 frames), the first frame of player.png (normal), then executes idle animation (2 frames). All OK.

That's the player_sword.png:
https://www.ascensiongamedev.com/resources/filehost/c6d987f72d91251bd092b607d80009e8.mp4

It performs weapon animation (1 frame randomly), the first frame of player.png (normal), then executes idle animation (2 frames).

my configs
![image](https://user-images.githubusercontent.com/63019821/97801813-4066af00-1c1e-11eb-817d-c36a2d8b305d.png)

**Essentially the problem is that weapon animations only execute 1 frame when they should be executed all (which in my case is 2)**
**Version Encountered**
0.6.2.447

**To Reproduce**
Repeat the steps above, perhaps using the settings I am using.

**Expected behavior**
Play all frames before changing to normal and finally idle.

**Logs**
no have

**Operating System:**
Windows

**Comment by jcsnider** [comment]
@WeylonSantana please zip up those graphics and share here so I can test locally.

**Comment by WeylonSantana** [comment]
@jcsnider 
[entities.zip](https://github.com/AscensionGameDev/Intersect-Engine/files/5505141/entities.zip)

**Comment by WeylonSantana** [comment]
@jcsnider Maybe I'm wrong, but as for the cast animation where I want it to be just 1 frame, no matter how fast the cast is(300ms or more), the player always disappears in the final half during the cast period. For example: a 300ms cast period, the frame appears from 0 - 150ms, and disappears from 150 - 300ms. I put 1 frame, because that's what I want to appear during the entire period of the cast animation.

**Comment by jcsnider** [comment]
@WeylonSantana please confirm this is fixed now

**Comment by WeylonSantana** [comment]
@jcsnider yes, in 108 is fixed!
