### ISSUE TITLE
[6.2] NPC's should return to place of aggro on target death.

### ISSUE THREAD

**Issue by lyimpike** [AscensionGameDev/Intersect-Engine#424]
**Is your feature request related to a problem? Please describe.**
Currently in latest 6.2, mobs will return to the place they originally saw / got aggro'd by the player. 
When the player leaves the radius set in the server config it returns to the position as intended, however this does not happen on player / npc target's death.

**Describe the solution you'd like**
I would like an option in the config to have the NPC return to its position after a player dies. 

**Additional context**
I understand this could possibly conflict with multiple people attacking an NPC, say the person who originally aggro'd the NPC dies and there were multiple others attacking it too. The NPC would just run away thinking combat was over, to solve this you could possibly add all attackers of the NPC to a table, and once the first player dies, remove it from the table (additionally removing an attacker from the table if they leave the radius set in server config) and focus on the next one until the NPC dies or all attackers are dead.

**Comment by Spectreye** [comment]
Also i would like to add that triggered monster continue to cast spell even after being de-aggroed.

**Comment by WeylonSantana** [comment]
Its Fixed on latest prerelease version (0.7.1.22)

https://www.ascensiongamedev.com/resources/filehost/38a88e436506ed66456989524276379a.mp4
