### ISSUE TITLE
Damage to mana crash the server.

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#426]
**Describe the bug**
I have (or had, why I removed at the moment) several spells with magic damage in order to be debuff spells (leaving the player weak too). So I recently realized that these spells crash the server.

**Version Encountered**
0.6.2.450

**To Reproduce**
Tests I did:
What causes the server to crash:

1 - Magic with mana damage only, monster with low defense = crash.
2 - Magic with life damage and mana simultaneously, but with the life damage value is much more than mana damage = crash.

What causes the server to NO crash:
1 - Magic with mana damage only, monster with high defense (that can defend all the damage) = no crash
2 - Magic with life damage and mana simultaneously, but with the life damage value is much less than mana damage = crash.

The same goes for other players as well.

**Expected behavior**
Cause mana damage to npcs or players.

**Screenshots**
![Screenshot_3](https://user-images.githubusercontent.com/63019821/98850905-391c7e00-2434-11eb-8847-47d1d6bcaf78.png)

**Logs**
If there are error logs please attach them below.

**Operating System:**
Windows 7

**Additional context**

**Comment by WeylonSantana** [comment]
This bug still remains until version 0.7.0.105

[Intersect Server-2021_02_08-13_51_01_346.log](https://github.com/AscensionGameDev/Intersect-Engine/files/5945478/Intersect.Server-2021_02_08-13_51_01_346.log)

**Comment by jcsnider** [comment]
@WeylonSantana this should be fixed in 0.7.0.106, can you confirm please?

**Comment by WeylonSantana** [comment]
@jcsnider sorry for the delay, I tested it today on version 106, it's really ok. You can close this topic, this bug has been fixed.
