### ISSUE TITLE
bug: cross platform build broken on mono (linux/mac)

### ISSUE THREAD

**Issue by lodicolo** [AscensionGameDev/Intersect-Engine#432]
**Describe the bug**
Building without Windows VS's MSBuild results in an incomplete/broken binary if the dependency file name matches `*.so.*`, rendering any client built using Mono broken on Linux.

**Expected behavior**
Build should include expected embedded resources in the client binary.

**Build System**
Mono

**Comment by Cheshire92** [comment]
Resolved with #431  merged.
