### ISSUE TITLE
Instancing

### ISSUE THREAD

**Issue by jcsnider** [AscensionGameDev/Intersect-Engine#449]
**Is your feature request related to a problem? Please describe.**
Allow instanced areas within Intersect which can be used for solo areas, or party raids, etc. This would be designed in such a way that the engine handles everything as an instance. The main world would be an instance with an identifier of Guid.Empty. All other instances would have Guids generated and players would have an instance property in which they reside in.

**Comment by Arufonsu** [comment]
solved by #1115
