### ISSUE TITLE
Projectiles Bug : Projectiles don't ignore resource

### ISSUE THREAD

**Issue by Spectreye** [AscensionGameDev/Intersect-Engine#454]
**Describe the bugs**
1) When you use a spell or weapon which use projectile that ignore collision with active and inactive ressources, the animation fade away on ressources who are not walkable before harvesting, however the damage are still done.

2) When you use a spell with projectiles and change map, the projectiles disappear from view, sometimes they even do not do any damage when fired from another map.

I've made a video where you can see each bug  individually (Look at the slime getting hit by projectiles but not getting any damage)

**Version Encountered**
0.6.2.453

**To Reproduce**
Missiles Animation Fading
1. Make a spell with projectile which ignore collision with active and inactive ressources.
2. Make a ressource which is not walkable before harvesting (and random skin)
3. Try to launch a projectile through it.

1. Make a spell with slow missiles and two map
2. Launch the projectiles and go on the other map
3. See error

**Expected behavior**
1)Projectiles animation should not end when passing through an active ressources if "Ignore collison with active ressources" is checked.

2) Projectiles should not disappear visually (And sometimes not doing damage at all) when moving to another map or shooting from another map.

**Video of bug**
https://ascensiongamedev.com/resources/filehost/107d0ffec3625212bf1079f5a76e4815.mp4

**Operating System:**
Windows

**Comment by blinkuz** [comment]
What disappearing when you move to another map happens between connected maps? Because this behavior is very strange unless what is done is to eliminate all the entities / objects that you are far away, have you tried placing a player on the other map and launching the projectile to confirm that the other player can see it?

**Comment by Spectreye** [comment]
Player on other map can see it, but if they change map, the projectiles will visually disappear too. I'm almost sure it has to do with the way the code deal with transition between map.

**Comment by blinkuz** [comment]
I just tried and I can confirm this error too, this has happened to me with my projectiles.

**Comment by Spectreye** [comment]
Update : The animation dysfonction seems to be corrected in 0.7.0.108.

Still, the Animation is still fading when colliding with a ressources, even if the "Ignore collision" with active ressources is checked.

**Comment by WeylonSantana** [comment]
The second bug is fixed, shooting projectiles and traversing the map doesn't make them disappear anymore.

but, the first bug still occurs, a projectile does not traverse a resource even when the checkbox is marked to ignore
