### ISSUE TITLE
On death abilities being casted.

### ISSUE THREAD

**Issue by UsagiEri** [AscensionGameDev/Intersect-Engine#456]
**Describe the bug**
On death of a character, the ability on cast time is casted while respawned back.

**Version Encountered**

0.6.2.453

**My Guesses. Because I don't know how to reproduce it.**
1. Went to **On Respawn** for my **Warp Player** on common events because I thought warping someone on death was the culprit however, disabling it still reproduces the result in the end.

**Expected behavior**
On death the skill should just be unused on death, or not having it casted when death occurs.

**Screenshots**
https://ascensiongamedev.com/resources/filehost/cd9aba65158961af3a7b6fb87ef18da6.gif

**Logs**
No logs availiable.

**Operating System:**
Windows

**Comment by jcsnider** [comment]
This should be fixed in the next Beta 7 build:
https://github.com/AscensionGameDev/Intersect-Engine/blob/170cc6aa286d4e95145291997f5c8a8a9c2bbf6e/Intersect.Server/Entities/Player.cs#L674
