### ISSUE TITLE
Buff & Debuff Effects Cannot Be Cleansed

### ISSUE THREAD

**Issue by Spectreye** [AscensionGameDev/Intersect-Engine#457]
**Describe the bug**
Cleanse is affected by several bugs, here's the list : 

-When you cast an on hit effect spell, then a self cleanse, or get cleansed by an ally (Or ennemy), the "on hit" effect is dispelled.

-When you get a stats buff/debuff and get cleansed (By ally or Ennemy) The buff/debuff is still there  : only the icons disappear. 

-Cleanse (Allied, Enemy or self) doesn't affect Dot/Hot, only the icons disappear.

-Cleanse, even when cast by yourself or an ally, dispell shield, invulnerability.

**Version Encountered**
0.6.2.45

**To Reproduce**
1. Make two cleanse spell that last 10 sec with single target range 5. One spell is friendly the other is not.
2. Make "Bad" spells with several effect such as dot,silence, stun, snare, etc.. and use them on an other character with the two cleasing spell, make him try to cleanse himself or cleanse him.
3. See error
4. Repeat with "Good effect" by partying with the other char and applying good effect spell on him such as H.o.t, Shield, invulnerabble, then cleanse him, you can make Aoe cleanse also it works the same.
5. See error

**Expected behavior**
Two solutions : 

1) Make Cleanse casted by you and ally dispell bad effects (Stun, silence, Damage on time, Stats debuff) on you but not the "good" effect such as heal on time, stats buff, shield, on hit, invulnerability. And make cleanse dispell "good" effects only when used enemy.

2) Separate the "cleanse" effect in two : 
-"Cleanse" : Only dispell "bad" effect (For ally and self usage)
-"Purge" : Dispell every buff and good effect (For enemy usage, or special spell as a cost maybe )

_Here's the list of "good" effect :_ 
-Heal on Time (Hot)
- Shield
- On hit (If friendly)
- Stealth
- Invulnerable
- Every kind of stats buffing.
- Cleanse (In the case of solution 2)

The list of "bad" effects:
- Damage on Time (Dot)
- Silence
- Stun
- Snare
- Blind
- Transform (May also be a "good effect")
- Sleep
- Taunt
- Every kind of stats debuffing
- Purge (In case of solution 2)

**Operating System:**
Windows

**Comment by Cheshire92** [comment]
This should be resolved in B7, I believe the Cleanse effect only dispels status effects of the opposite Friendly flag. (ie Friendly ones dispel Unfriendly effects and vice versa)

**Comment by jessidion** [comment]
> It should if the status is marked as a non friendly spell and the cleanse is marked as friendly. It will NOT however remove a Friendly marked status if the cleanse is also marked friendly. (For example, in PvP and both parties use a friendly spell)

0.7.0.129 I can confirm that friendly or not, cleanse just won't remove debuff/buff.

**Comment by WeylonSantana** [comment]
Basically this is the only bug here
--When you get a stats buff/debuff and get cleansed (By ally or Ennemy) The buff/debuff is still there : only the icons disappear.

Spells marked "friendly" are not cleaned, whether cast by the player himself, or allies, if the spell is friendly, it is not cleaned.

**Comment by jcsnider** [comment]
I don't think friendly buffs should be cleansed, or we need to add a new effect called total cleanse.

**Comment by WeylonSantana** [comment]
Currently friendly spells are not cleaned for buff or debuff too. Also currently cleanse, only clears status(like, snare, blind...) from spell with "friendly" not checked, and does not clean status(atk, def...) buff/debuff too

**Comment by Arufonsu** [comment]
"Total Cleanse" sounds appropiate for something like this. But this sounds like a discussion for a feature request, not a bug report, since cleanse is working as intended.
