### ISSUE TITLE
Editor : Visual : Group cooldown box retain the last input.

### ISSUE THREAD

**Issue by Spectreye** [AscensionGameDev/Intersect-Engine#463]
**Describe the bug**
When editing the group cooldown in the spell windows if you select a new group cooldown for a spell, then go on another spell, the group cooldown box will retain the last input visually.

Although it does not really "change" the input of the spell, it can lead to errors when modifying these.

**Version Encountered**
0.7.0.454

**To Reproduce**
1. Make a new spell, create a cooldown group "Skill1".
2.  Make another spell, go on it.
3. See error

**Expected behavior**
The correct visual should be displayed in the group cooldown box when changing to another spell after having inputted a group cooldown.

**Operating System:**
Windows

**Comment by Cheshire92** [comment]
I believe I fixed this on Leafling, just need to port it over still.
