### ISSUE TITLE
Invisible ennemies when using knockback spell/attack

### ISSUE THREAD

**Issue by Spectreye** [AscensionGameDev/Intersect-Engine#484]
**Describe the bug**
This bug appear very often when using spell/attack that knockback and when you are at the borders of two map. My guess is that when knockbacked on another map, the server doesn't always send back data to the player correctly about the monster position because when switching to another map the monster appear again;

**Version Encountered**
0.7.0.101 (And before)

**To Reproduce**
1. Create a spell that do very low damage and knockback on side. Create a monster and spawn them in a block of 4 map
2. Go to the center point of the 4 map and hit monster with the spell.
3. You may have to do a few try to see the error.

**Expected behavior**
Monster should not turn invisible when knockbacked to another map.

**Video**
https://ascensiongamedev.com/resources/filehost/acb65ac191054c496fb9039b562e0aa8.mp4

**Operating System:**
Windows

**Comment by MrPalladice** [comment]
I have the same problem on version B6.2.456.
Video link: https://ascensiongamedev.com/resources/filehost/dd532c2de61a45b8262aa80d77cf80c0.mp4
This situation happens when the npc is attacked with a spell. Or a bullet.
