### ISSUE TITLE
Option : Regeneration while in Battle.

### ISSUE THREAD

**Issue by Spectreye** [AscensionGameDev/Intersect-Engine#506]
**Is your feature request related to a problem? Please describe.**
Now due to how the reset radius of monster work, it's impossible to have Regen while In Combat, it would be very nice if the option to toggle the regen in fight was available.

**Describe the solution you'd like**

Add a new option line in server config here : 
  "Combat": {
    "BlockingSlow": 30,
    "CombatTime": 10000,
    "MaxAttackRate": 200,
    "MaxDashSpeed": 200,
    "MinAttackRate": 500,
    "RegenTime": 3000,
    **_"CombatRegen": True/False_**

It will allow game creator to choose if they want the regen or not.

**Additional context**
Jc provided me the part of the code where it's handled : 

//Regen Timers
                    if (timeMs > CombatTimer && timeMs > RegenTimer)
                    {
                        ProcessRegen();
                        RegenTimer = timeMs + Options.RegenTime;
                    
Removing  **timeMs > CombatTimer &&**  
would do the tricks, but it would be far better foreveryone to make it an option.

Thank you by advance to whoever can do this :-)

**Comment by blinkuz** [comment]
If I take a little time tomorrow I can make the change and send the PR it is something simple to make it optional and more than providing the condition that handles that part.

**Comment by jcsnider** [comment]
@blinkuz get to work :P

**Comment by blinkuz** [comment]
Hahaha and here we see my bad memory working, I completely forgot about this change, lately I am working on new programming in the engine for my project so most likely TODAY YES, I will fulfill the promise of doing this.
