### ISSUE TITLE
Ressources Editor : No animation played on collect.

### ISSUE THREAD

**Issue by Spectreye** [AscensionGameDev/Intersect-Engine#507]
**Describe the bug**

**Version Encountered**
0.7.0.106

**To Reproduce**
1. Create a new animation with whatever sound and whatever animation
2. Create a new ressources, set the precedently created animation
3. Put ressources in game and gather it.

**Expected behavior**
Animation should be played on gathering.

**Operating System:**
Windows

**Comment by jcsnider** [comment]
Caused by the removal of these 5 lines which will need to be added back
https://github.com/AscensionGameDev/Intersect-Engine/commit/9e3c5b026e0153af09efa295cbe51d3387d1231a#diff-f74066631bd400566222a8113d1d760f779fecd577a9ddba5dad4eb80f4f0204L60-L65
