### ISSUE TITLE
Event Speed

### ISSUE THREAD

**Issue by Xenogene83** [AscensionGameDev/Intersect-Engine#513]
**Describe the bug**
Events with speed set to "fastest" & frequency set to "Very Often" are moving incredibly slow.

**Version Encountered**
0.7.0.0

**To Reproduce**
Create an event with speed set to "fastest" & frequency set to "Very Often".

**Expected behavior**
The event should move fairly fast.

**Screenshots**

**Logs**
If there are error logs please attach them below.

**Operating System:**
Windows 7

**Additional context**

**Comment by jcsnider** [comment]
@Xenogene83 can you confirm this still exists in 0.7.0.106 official? Pretty sure it got fixed with #491

**Comment by jcsnider** [comment]
Closing because I'm pretty sure this is fixed. Please confirm that the bug exists in the latest official builds. If you can replicate this in 0.7.0.106+ please tag me and I'll reopen this issue.
