### ISSUE TITLE
Npc Battle & Event Lag

### ISSUE THREAD

**Issue by Xenogene83** [AscensionGameDev/Intersect-Engine#514]
**Describe the bug**
After latest update maps load faster, however events & battles seem to be lagging considerably. Events are also loading slower sometimes not appearing for several seconds after map loads.

**Version Encountered**
0.7.0.0

**To Reproduce**
Fight an npc or interact with event. For event loading simply walk onto a new map with events placed.

**Expected behavior**

**Screenshots**

**Logs**
If there are error logs please attach them below.

**Operating System:**
Windows 7

**Additional context**

**Comment by jcsnider** [comment]
@Xenogene83 can you confirm this still exists in 0.7.0.106 official? Pretty sure it got fixed with #491

**Comment by jcsnider** [comment]
Closing because I'm pretty sure this is fixed. Please confirm that the bug exists in the latest official builds. If you can replicate this in 0.7.0.106+ please tag me and I'll reopen this issue.
