### ISSUE TITLE
Visual bug in the class editor.

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#515]
**Describe the bug**
This bug again: #352 

**Version Encountered**

0.7.0.105

**To Reproduce**
1 - Create two classes and set the same respawn point for them.
2 - Open the editor and select a class
3 - with the selected class, change to chronological order.
4 - bug

**Expected behavior**
Spawn point not change when I change the order to chronological.

**Screenshots**
#352

**Logs**
If there are error logs please attach them below.

**Operating System:**
Windows 10

**Additional context**

**Comment by jcsnider** [comment]
@WeylonSantana I can't recreate this. Can you make a new video using 0.7.0.106?

**Comment by WeylonSantana** [comment]
@jcsnider 
https://www.ascensiongamedev.com/resources/filehost/81c25e545816e493f527ae34db0c68c6.mkv
