### ISSUE TITLE
Moving Cast cancel as an option rather than being mandatory.

### ISSUE THREAD

**Issue by Spectreye** [AscensionGameDev/Intersect-Engine#517]
**Is your feature request related to a problem? Please describe.**
Being able to cancel a casted ability only by moving a little, may be useful in some case but can lead to some big troubles for other, regarding to cast animation, sounds, mana not taken, No cooldown (No global cooldown too) it's also changing players tactics in a not necessary way as originally intended.

Also, It's a real hinder for melee classes (Even long range casting) that must now stop totally to be able to cast spell, and since it's quite easy to move away, even using very short cast time (0.25s) tend to be impossible, It's a total QoL changing.
(And since we cannot change the speed formula it restrain a lot of possibilities regarding to the speed stats).

As such, it shouldn't be forced and should be optional.

**Describe the solution you'd like**
Cast cancel by moving being an option rather than an obligation. 

Ideally, it would be a little box to check in spell editor : "Cancelable ?"

**Additional context**
Here's a short video showing some reasons why it should be an option :
https://ascensiongamedev.com/resources/filehost/f3df14296847408f6baf0be2c5b493e4.mp4

**Comment by da-rulez** [comment]
This seems like a leafling feature that leaked into Intersect. 

Would rather see this feature removed altogether. I imagine this would break the combat system of almost any Intersect game

**Comment by blinkuz** [comment]
> This seems like a leafling feature that leaked into Intersect.
> 
> Would rather see this feature removed altogether. I imagine this would break the combat system of almost any Intersect game

I do not think it is necessary to eliminate it completely, since the functionality exists, it would be best to make it optional, there are games in which this functionality is useful, in my case I think I can take advantage of it.

**Comment by jcsnider** [comment]
I did not to bring this in when merging the Leafling changes. Looking into both keeping it as an option and removing it entirely.
