### ISSUE TITLE
Spell Event type, Aoe radius not showing

### ISSUE THREAD

**Issue by Spectreye** [AscensionGameDev/Intersect-Engine#518]
**Describe the bug**
When trying to make a spell of Event type and selecting a Aoe Targeting type, the box of radius is not showed.

You can "trick" it by setting it as combat spell, aoe targetting and setting the radius there then go back to Event Type.

**Version Encountered**
0.7.0.106

**To Reproduce**
1. Go on spell editor
2. Make a new spell and select event type, then Aoe targetting.

**Expected behavior**
The radius box should be there.

**Screenshots**
https://ascensiongamedev.com/resources/filehost/a7cb733d0b3b4f1f035e691de6b02ad4.png

**Operating System:**
Windows

**Comment by jcsnider** [comment]
The original intention was to have event spells strictly be self-targeting.  If you try to use an AOE event spell in a party it will only fire for the caster. The real solution I think would be to hide that targeting window all together.

**Comment by Spectreye** [comment]
Actually the fact that it only launch for the caster is not a problem in itself.
Restricting event type it to only self target may hinder some real good use, like forcing player not to move for a few second, or gaining xp, taking item, after a "normal" attack etc... I've seen a good kamehameha made with the event system, that would break it all by example.
Please do not reduce it to only self targeting ^^"
