### ISSUE TITLE
Warp to target visual bug, Is self targeting intended ?

### ISSUE THREAD

**Issue by Spectreye** [AscensionGameDev/Intersect-Engine#519]
**Describe the bug**
When making warp to target spell, if you make special effect shield, and use the spell on yourself, the shield grey bar does not appear but the effect seems to be correctly applied. (Was ok in previous ver)

Also, even if the spell is "friendly"  if a player is not in your party you can still jump on him on arena/normal maps. 

Finally, is it intended for warp to target spell to be  self castable?

**Version Encountered**
0.7.0.106

**To Reproduce**
1. Make a warp to target spell, set it to friendly, radius 4; -50 damage, Shield effect 15000ms last.
2. Use the spell on another player while in party, then on yourself.
3. See error
4.  Leave the party, jump on another player in a normal map, then arena map, then safe map.
5. See error

**Expected behavior**
The grey bar should appear when used on yourself
Or
The warp to target spell shouldn't be useable or yourself.

Also :
You shouldn't be able to jump on a ennemy target if the spell is "Friendly" checked.

**Screenshots**
https://ascensiongamedev.com/resources/filehost/56977071f68344048d4a3781c3a4c9c4.mp4

**Operating System:**
Windows

**Comment by jcsnider** [comment]
The shielding part of this bug should be fixed by #555
