### ISSUE TITLE
Spell tooltips, sleep and maybe several effects bug.

### ISSUE THREAD

**Issue by Spectreye** [AscensionGameDev/Intersect-Engine#520]
**Describe the bug**
I've made three video that i strongly recommend watching to understand more easilly.

In my 1st exemple i've made two spell, one is a debuff that last 8 second an reduce speed by 100, the other one is a sleeping spell. 
As you can see, the effects are correctly applied but there is sometime a tooltip under ennemy char info, sometime not, it also randomly disapear when changing target, or reappear.

____________________________

In my 2nd exemple, there is a sleep spell that last 15 sec, the player use it on another player in Arena zone type. 

He's affected by the spell of sleep, but does not wake up when a spell is used on him, he should also have the tooltip of the tongue spell which reduce his speed. 
And as you can see the sleep spell end randomly
Then i reattack him, and he's instantly awake.
After waiting for the regen and being out of combat, i retry the sleep spell and several attack, not waking either, spell end early.

My guess is that it's linked to Combat time.

____________________________

In my 3rd exemple i use the same spells.

Doing the spell on a npc does make him sleep, attacking with the tongue spell does not put the tooltip (The effect is still here), and the tooltip of the sleep spell is still here even if the monster is awake.

__________________________

It's a lot a problems together and i'm not totally sure how to effciently reproduce them since they appear randomly and are affected differently depending on being in combat or not, or if fighting a player or a monster.

I also got case when the sleep spell didn't make ennemy player sleep at all and strange behaviour.

**Version Encountered**
0.7.0.106

**To Reproduce**
1. Create two spell, one who debuff speed for 10 sec and another one that make ennemy sleep.
2. Try them on monster and player
3. See error

**Expected behavior**
-Tooltips should be correctly displayed for every spells and be stacked.
-Sleep should always stop when the player is hurted (Tooltips should stop too)

**Video**
1st exemple :
https://ascensiongamedev.com/resources/filehost/3c714da97fea1abfae6f59ad3dab7f16.mp4
2nd exemple :
https://ascensiongamedev.com/resources/filehost/0285b947ab4756aba10cca15135bcef2.mp4
3rd exemple:
https://ascensiongamedev.com/resources/filehost/c61a8c874e1fef2cac2a2ef46b41917c.mp4

**Operating System:**
Windows

**Comment by jcsnider** [comment]
@Spectreye hopefully most of this will be fixed in 0.7.0.107 but please confirm once that is released before we officially close this issue.

**Comment by Spectreye** [comment]
Everything seems smooth so far from the test i've made, i reopen a ticket if i found something new
