### ISSUE TITLE
Client Crash in a random manner.

### ISSUE THREAD

**Issue by Spectreye** [AscensionGameDev/Intersect-Engine#522]
**Describe the bug**
It's hard to describe what happenned i wasn't able to isolate or reproduce the problem, i only have two logs, the only thing i'm sure is that it happened when conducting pvp test with a friend.

**Version Encountered**
0.7.0.106

**To Reproduce**
I don't know how to reproduce it :/

**Expected behavior**
Client not crashing.

**Logs**

2021-02-08 22:44:19.464 [Error] 
  Message: La clé donnée était absente du dictionnaire.
    Stack:    à System.ThrowHelper.ThrowKeyNotFoundException()
   à System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   à Intersect.Client.Maps.MapInstance.DrawItemNames() dans C:\TeamCity\buildAgent\work\40dc5d27074313da\Intersect.Client\Maps\MapInstance.cs:ligne 737
   à Intersect.Client.Core.Graphics.DrawInGame() dans C:\TeamCity\buildAgent\work\40dc5d27074313da\Intersect.Client\Core\Graphics.cs:ligne 344
   à Intersect.Client.Core.Graphics.Render() dans C:\TeamCity\buildAgent\work\40dc5d27074313da\Intersect.Client\Core\Graphics.cs:ligne 465
   à Intersect.Client.MonoGame.IntersectGame.Draw(GameTime gameTime) dans C:\TeamCity\buildAgent\work\40dc5d27074313da\Intersect.Client\MonoGame\IntersectGame.cs:ligne 280
   à Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime)
   à Microsoft.Xna.Framework.Game.Tick()
   à Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   à Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   à Intersect.Client.MonoGame.IntersectGame.MonoGameRunner.Start(IClientContext context, Action postStartupAction) dans C:\TeamCity\buildAgent\work\40dc5d27074313da\Intersect.Client\MonoGame\IntersectGame.cs:ligne 514
   à Intersect.Client.Core.ClientContext.InternalStart() dans C:\TeamCity\buildAgent\work\40dc5d27074313da\Intersect.Client\Core\ClientContext.cs:ligne 44
   à Intersect.Core.ApplicationContext`2.Start(Boolean lockUntilShutdown) dans C:\TeamCity\buildAgent\work\40dc5d27074313da\Intersect (Core)\Core\ApplicationContext`2.cs:ligne 221

--------------------------------------------------------------------------------
2021-02-08 23:53:15.709 [Error] 
  Message: La clé donnée était absente du dictionnaire.
    Stack:    à System.ThrowHelper.ThrowKeyNotFoundException()
   à System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   à Intersect.Client.Maps.MapInstance.DrawItemNames() dans C:\TeamCity\buildAgent\work\40dc5d27074313da\Intersect.Client\Maps\MapInstance.cs:ligne 737
   à Intersect.Client.Core.Graphics.DrawInGame() dans C:\TeamCity\buildAgent\work\40dc5d27074313da\Intersect.Client\Core\Graphics.cs:ligne 344
   à Intersect.Client.Core.Graphics.Render() dans C:\TeamCity\buildAgent\work\40dc5d27074313da\Intersect.Client\Core\Graphics.cs:ligne 465
   à Intersect.Client.MonoGame.IntersectGame.Draw(GameTime gameTime) dans C:\TeamCity\buildAgent\work\40dc5d27074313da\Intersect.Client\MonoGame\IntersectGame.cs:ligne 280
   à Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime)
   à Microsoft.Xna.Framework.Game.Tick()
   à Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   à Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   à Intersect.Client.MonoGame.IntersectGame.MonoGameRunner.Start(IClientContext context, Action postStartupAction) dans C:\TeamCity\buildAgent\work\40dc5d27074313da\Intersect.Client\MonoGame\IntersectGame.cs:ligne 514
   à Intersect.Client.Core.ClientContext.InternalStart() dans C:\TeamCity\buildAgent\work\40dc5d27074313da\Intersect.Client\Core\ClientContext.cs:ligne 44
   à Intersect.Core.ApplicationContext`2.Start(Boolean lockUntilShutdown) dans C:\TeamCity\buildAgent\work\40dc5d27074313da\Intersect (Core)\Core\ApplicationContext`2.cs:ligne 221

Edit : just got one more crash, here the log 
2021-02-09 17:50:41.096 [Error] 
  Message: La clé donnée était absente du dictionnaire.
    Stack:    à System.ThrowHelper.ThrowKeyNotFoundException()
   à System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   à Intersect.Client.Maps.MapInstance.DrawItemNames() dans C:\TeamCity\buildAgent\work\40dc5d27074313da\Intersect.Client\Maps\MapInstance.cs:ligne 737
   à Intersect.Client.Core.Graphics.DrawInGame() dans C:\TeamCity\buildAgent\work\40dc5d27074313da\Intersect.Client\Core\Graphics.cs:ligne 344
   à Intersect.Client.Core.Graphics.Render() dans C:\TeamCity\buildAgent\work\40dc5d27074313da\Intersect.Client\Core\Graphics.cs:ligne 465
   à Intersect.Client.MonoGame.IntersectGame.Draw(GameTime gameTime) dans C:\TeamCity\buildAgent\work\40dc5d27074313da\Intersect.Client\MonoGame\IntersectGame.cs:ligne 280
   à Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime)
   à Microsoft.Xna.Framework.Game.Tick()
   à Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   à Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   à Intersect.Client.MonoGame.IntersectGame.MonoGameRunner.Start(IClientContext context, Action postStartupAction) dans C:\TeamCity\buildAgent\work\40dc5d27074313da\Intersect.Client\MonoGame\IntersectGame.cs:ligne 514
   à Intersect.Client.Core.ClientContext.InternalStart() dans C:\TeamCity\buildAgent\work\40dc5d27074313da\Intersect.Client\Core\ClientContext.cs:ligne 44
   à Intersect.Core.ApplicationContext`2.Start(Boolean lockUntilShutdown) dans C:\TeamCity\buildAgent\work\40dc5d27074313da\Intersect (Core)\Core\ApplicationContext`2.cs:ligne 221

**Operating System:**
Windows

**Additional context**
Feel free to comment for more informations if i can provide them.

**Comment by jcsnider** [comment]
This is ultimately caused by not having a Map Rarity color defined in colors.json for the rarity of the item that is dropping.

That being said I am making it so it won't crash going forwards.
