### ISSUE TITLE
Chance to drop an item doesn't work.

### ISSUE THREAD

**Issue by MrPalladice** [AscensionGameDev/Intersect-Engine#544]
**Describe the bug**
Despite setting a % chance to drop an item, items still drop with npc with a 100% chance. Every time we kill an NPC.

**Version Encountered**
Version: V0.7.0.106

**Expected behavior**
Restore an item drop chance.

**Screenshots**
https://ascensiongamedev.com/resources/filehost/4c835a108b4be258812ce13516735c73.mp4

**Operating System:**
Windows 10

**Comment by blinkuz** [comment]
This problem has already been solved in the following PR: https://github.com/AscensionGameDev/Intersect-Engine/pull/530
