### ISSUE TITLE
3 Bugs in 0.7.0.106 full

### ISSUE THREAD

**Issue by dryamzord** [AscensionGameDev/Intersect-Engine#548]
Hello, I have come to report 3 full errors of 0.7.0.106. 
(1. The probability of falling items on enemies does not work, they always decrease even if you put 0%). (2. The Set Range in the items does not work, they appear as such but when equipping them they do not add or subtract from your statistics) (3. When you give yourself a buff this is not verified in the box on the screen below the target.) Thank you very much and I hope to get news when these bugs are fixed so that we can continue our projects with this fantastic version.

**Comment by jcsnider** [comment]
This bug is all kinds of wrong. Template not followed. Multiple bug reports. Duplicate reports... Closing this.
