### ISSUE TITLE
Target Bug?

### ISSUE THREAD

**Issue by Kamusvalenzuela** [AscensionGameDev/Intersect-Engine#551]
**Describe the bug**
When you click an target and do a new click for attack the target get loss
(Works fine if you use "TAB" for select it and attack with the "E" button)
This can gave some headaches if you are trying to attack with melee attacks and targeting spells

**Version Encountered**

0.7.0.106

**To Reproduce**
1. Fight vs an entity or player
2. Click on him and try to click for attack
3. See the "error"

**Expected behavior**
Only remove the target if you click on him

**Screenshots**
https://user-images.githubusercontent.com/51339474/108114414-846bab80-7077-11eb-802d-5037ab650a38.mp4

**Operating System:**
All

**Additional context**
I dont know if its a bug or a new feature, but i report it for if this is a bug

**Comment by jcsnider** [comment]
This will be fixed via a PR shortly... but the config is gonna be saved to your registry with other preferences. Easiest fix is to use a different port number after the 0.7.0.107 update.
