### ISSUE TITLE
Dying offline : On Respawn & PvP Death event not triggering

### ISSUE THREAD

**Issue by Spectreye** [AscensionGameDev/Intersect-Engine#572]
**Describe the bug**
When exiting the game while in battle and dying, any on respawn event will not be triggered. Breaking some respawn system and rendering possible for the player to be trapped in eventual limbo or not suffering a penalty he should have.

**Version Encountered**
0.7.0.108

**To Reproduce**

1. Create an item "Apple", then create a "on respawn" common event which take 10 apple
2. Give yourself 20 apple, get in a fight, quit the game.
3. Log in back after you're sure to be dead.

**Expected behavior**
On respawn event should be launched even if the player died offline.

**Operating System:**
Windows,

**Additional context**
Partially break system like this one : 
https://www.ascensiongamedev.com/topic/4459-aog-player-respawn-system/?tab=comments#comment-42076

**Comment by jcsnider** [comment]
That makes sense. Once the player dies he is 'out of combat' so he immediately gets logged out and events do not have time to execute.

The alternative to AOGs on Respawn Event would be to have a blank map that the class is set to spawn to with an autorun event that uses variables to determine if the player is new and should be warped to a tutorial or otherwise check the variables to determine where to send them.

**Comment by da-rulez** [comment]
Can't you make it so the player doesn't respawn until he logs in?

**Comment by jcsnider** [comment]
With extra code, yes, but that doesn't solve the problem. The player could still log out or dc as they are loading into the game and terminate that event before it completes. 

My suggestion above of the autorun event on the spawn map would always work.

**Comment by Spectreye** [comment]
yeah, i have another bad news, it's also not working with Pvp Death since the player can also disconnect the same way.

**Comment by jcsnider** [comment]
There's no way that I can force the player to stay logged in until the events complete.... Technically the events could throw up a message or options and never complete. 

We can add an option to keep the player online for an extra X seconds after respawning in hopes that the events complete, but that would be an additional enhancement/feature request.
