### ISSUE TITLE
Changing the resolution when the shop/bank window is open locks the character in the game.

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#573]
**Describe the bug**
When you interact with an event on the map that opens a shop or bank in the game, pressing ESC opens the in game menu, if you change the resolution the game closes all windows. As the shop/bank was not closed properly, the character is unable to interact with any other event on the map whatsoever.

**Version Encountered**
0.7.0.108

**To Reproduce**
1. Create an event on the map that opens a shop or trunk
2. Press ESC and change the resolution
3. Try to interact with events.

**Expected behavior**
When any window is open, pressing ESC should close the window. With no windows open, pressing ESC again is when the menu should open. Or it should happen at least when the store / bank is open.

**Screenshots**

**Logs**
If there are error logs please attach them below.

**Operating System:**
Windows 10

**Additional context**
The same bug occurs with an open crafting station window. This **does not** happen with text dialog windows

**Comment by Spectreye** [comment]
Pressing ESC does close the windows, actually, but you can still reproduce the bug :

1. Create an event on the map that open a shop or bank
2. Go on the menu button, then change resolution
3. Try to interract with event.
4. See error

**Comment by Arufonsu** [comment]
ah, i was about to PR for this, nvm..

at https://github.com/AscensionGameDev/Intersect-Engine/blob/b408676dd0ddf808b860391d8186c0c825f6a81c/Intersect.Client/Interface/Shared/OptionsWindow.cs#L582

```
            if (Globals.InShop)
            {
                Networking.PacketSender.SendCloseShop();
            }
            if (Globals.InShop)
            {
                Networking.PacketSender.SendCloseBank();
            }
```

fixes the issue.
