### ISSUE TITLE
Delayed damage on Missiles. Missiles Visual Range incorrect depending on speed.

### ISSUE THREAD

**Issue by Spectreye** [AscensionGameDev/Intersect-Engine#574]
**Describe the bug**
After a few test, i've seen that missiles have their damage retarded despite the animation hitting effectively monster and players.
Also the effective range of the missiles is not the same as the animations and also that depended of the missiles speed.

Also after more test i've got three conclusions :

-The faster the missiles, the farer the missiles go visually out of their initial range
-The slower the missiles, the closest they are to their visual range.
-Damage are delayed whatever the missiles speed, just a little faster or slower, it's particulary visible when using waves of missiles.

The tests have conducted with a 0 ping (Local host) and minimal server ping (10-15) but online, there is two videos to show the bugs.

**Version Encountered**
0.7.0.108

**To Reproduce**
1. Create two missiles types, one slower (2800 ms for 14 range, start on the player) and one fast (700 ms for 14 range, start on the player)
2. Create two spell using these missiles types and give them low damage.
3. Create a range ground with 14 tiles of space and place a standing npc on it.
4. Fire at the npc with the two spells.
5. You can also conduct test on moving npc.
6. See error

**Expected behavior**
Missiles damage should be more "Instant" and if not instant at last less slower when touching a monster/player.
The visual should stop when he reach his max range, otherwise it can wrong the player at how far he can effectively touch.

**Video**
https://ascensiongamedev.com/resources/filehost/934da64ed2e8dafcfe6b9146bf7ab0ac.mp4
https://ascensiongamedev.com/resources/filehost/42607f0e92a85a4edfa1f79d391fba22.mp4

**Operating System:**
Windows

**Comment by Arufonsu** [comment]
̷r̷e̷t̷a̷r̷d̷e̷d̷ ... **cough** maybe u meant "delayed" for the issue title._
 
confirmed, there's some relative delay beetwen them  ;-;

**Comment by Arufonsu** [comment]
̷r̷e̷t̷a̷r̷d̷e̷d̷ ... **cough** maybe u meant "delayed" for the issue title.
 
confirmed, there's some relative delay beetwen them  ;-;

**Comment by jcsnider** [comment]
Try adjusting ProjectileUpdateInterval in the server config to a smaller value, maybe 10ms and lemme know if that helps.

**Comment by Spectreye** [comment]
With 10 MS it's a little better. The visual range is still incorrect, even when lowering the  "MapUpdateInterval" to 10 too.

**Comment by Cheshire92** [comment]
I've noticed this as well. It's wildly inconsistent on how far off from its target it will be as well. 

Projectiles are also still not always disposed of after they should stop being processed sticking on the screen and seemingly never disappearing. Wonder if it's related? Is it not managing to remove them from the list of projectiles and dispose of them at the right time perhaps?

**Comment by blinkuz** [comment]
I am also noticing this in some projectiles despite adjusting the speed as mentioned above, after having collided with the target there is a delay when disappearing.

**Comment by jcsnider** [comment]
@blinkuz @Spectreye do you all by chance have any autorun events that are modifying global variables? Oddly specific, I know, but global variables are writing to the db on demand at this time. If that is happening a lot in your games it will kill performance. As seen here:
https://www.ascensiongamedev.com/topic/5928-beta-7-v111-lag/#comment-50782

**Comment by blinkuz** [comment]
@jcsnider Currently I do not have any events or variables created for my project, I am working 100% on skills and projectiles, I have adjusted ProjectileUpdateInterval to lower but the delay continues to occur.
