### ISSUE TITLE
Server error when logging in with client downloaded from the forum * Steam Version Outdated *.

### ISSUE THREAD

**Issue by dhmhc** [AscensionGameDev/Intersect-Engine#597]
**Describe the bug**
I downloaded the latest version 0.7.0.108, and sent the server to the VPS, and tried to open the client, the following error is shown on the server side, and on the client, it shows as Steam Outdated

**Version Encountered**
0.7.0.108

**To Reproduce**
Download the latest prerelease from the forum;
Send the server to a VPS
Try to connect them together.

**Expected behavior**
I tried to compile a version of my own, using the prerelease project, but the same problem happens.

**Screenshots**
https://prnt.sc/10j4may

**Logs**
`
**2021-03-11 21:37:31.370 [Error] 
  Message: Method not found: '!0 System.Linq.Expressions.Expression`1.Compile(Boolean)'.
    Stack:    at MessagePack.MessagePackSerializer.CompiledMethods..ctor(Type type)
   at MessagePack.MessagePackSerializer.<>c.<.cctor>b__45_0(Type t)
   at MessagePack.Internal.ThreadsafeTypeKeyHashTable`1.AddToBuckets(Entry[] buckets, Type newKey, Entry newEntryOrNull, Func`2 valueFactory, TValue& resultingValue)
   at MessagePack.Internal.ThreadsafeTypeKeyHashTable`1.TryAddInternal(Type key, Func`2 valueFactory, TValue& resultingValue)
   at MessagePack.Internal.ThreadsafeTypeKeyHashTable`1.GetOrAdd(Type key, Func`2 valueFactory)
   at MessagePack.MessagePackSerializer.Deserialize(Type type, ReadOnlyMemory`1 bytes, MessagePackSerializerOptions options, CancellationToken cancellationToken)
   at Intersect.Network.MessagePacker.Deserialize(Byte[] data) in C:\TeamCity\buildAgent\work\40dc5d27074313da\Intersect (Core)\Network\MessagePacker.cs:line 44**

`

**Operating System:**
Windows Server 2016

**Comment by Cheshire92** [comment]
It means your client and server keys are mismatched. You'll want to compile both at the same time.

The error displaying steam version mismatch is odd though, considering that's a leafling specific error message. Did this transfer over by accident? It should say Unknown on the client.

**Comment by dhmhc** [comment]
Ah yes, I noticed that I just threw the client into the leafling folder already had packages ready, yes the error is said between handshakes between client and server

**Comment by Cheshire92** [comment]
Closing this as it's user error. 
Please don't try to do funny stuff to other people's games.

As for your issue, make sure you compile both client and server at the same time yourself (as this generated the appropriate keys to connect) and use both of those to connect to eachother. Any other combinations are not possible.

**Comment by dhmhc** [comment]
*As for your issue, make sure you compile both client and server at the same time yourself (as this generates the appropriate keys to connect) and use both of those to connect to eachother. Any other combinations are not possible.*
Yes, I compiled both sides of the engine, you can close it, maybe there is a problem with my VPS.

As for the content, no, it was not * stolen * if you meant it, the Time Fantasy package is open for any game you want to use, as long as it is purchased, but unfortunately many use it without having paid for it.

**Comment by Cheshire92** [comment]
There's custom graphics mixed in as well and if you're copying files from another game we are done here and I'm putting you on my personal blacklist.

**Comment by dhmhc** [comment]
As I already said soon, the error has already been solved, it is a problem in the VPS that for some reason was not doing a squeeze between the client and server. As for the graphics, you are very toxic as to what is beginning to think of me, I don't know you, I don't know who you are, and you must think the same about me, so let's keep the respect right?

About breaking the encryption, if there was someone wanting to do this, do you really think you would come here to ask for help? It's an open-source, it's all explained how encryption works, * breaking * would be too advanced a word to do here.

I posted a problem, like any other report, you have already come with threats to put me on your * personal black list *, are we in middle school?


For me it ends here, the topic is already closed. it has already been resolved, thanks.

**Comment by Cheshire92** [comment]
You've copied files from another game and admitted to it then tried to defend yourself from it by claiming anyone can use it.

Whatever your issue may have been has become invalidated there.

**Comment by dhmhc** [comment]
ok
