### ISSUE TITLE
Npc bypass rangecheck when using spell.

### ISSUE THREAD

**Issue by Spectreye** [AscensionGameDev/Intersect-Engine#598]
**Describe the bug**
Actually, Npc who have single target offensive spell or warp to target spell use them even if they are totally out of range, resulting in a unintended deplete of their mana.

Aoe healing spell "miss" if the target is out of range.

**Version Encountered**
0.7.0.108

**To Reproduce**
1. Create a Npc with a single target spell (Range 1 ) and a short cooldown (3 or 4 sec) and a mana cost.
2. Attack the npc and get out of the range of his spell.
3. See error
4. Repeat with an Aoe healing spell

**Expected behavior**
Single target and warp to target Spell used by NPC should check the range of the target too.
 Aoe healing spell should not miss if the target is out of range. (How can it miss to begin with? )

**Operating System:**
Windows

**Comment by jcsnider** [comment]
Got a fix for the first half. AoE seems to work fine for me so I'm not sure what the AoE problem is.
