### ISSUE TITLE
Debuff icon not showing.

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#60]
**Describe the bug**
Monsters are using debuff spells on me, and the icon doesn't show below my status window, I deleted the gui folder and pasted the most recent gui folder to be sure.

**Version Encountered**
0.6.1.240

**To Reproduce**
![image](https://user-images.githubusercontent.com/63019821/78185809-09d77480-7442-11ea-9ff3-e905047aebf7.png)
![image](https://user-images.githubusercontent.com/63019821/78185955-460ad500-7442-11ea-974e-89c1cb119466.png)
The effect that is there "Benção", which causes the debuff, is "Shield" in English. I'm only using it with negative values to cause the debuff.

**Expected behavior**
When the player receives a debuff, the client should show the icon below the character status window. Showing how much time is left before the effect is lost.

**Screenshots**
![image](https://user-images.githubusercontent.com/63019821/78186691-874fb480-7443-11ea-814a-8314f4490edb.png)

![image](https://user-images.githubusercontent.com/63019821/78186787-b6febc80-7443-11ea-8f8c-b3094fd3a19a.png)

**Logs**
No Logs

**Operating System:**
Windows 7, 64x.

**Additional context**
Rarely, it happens from where the icon should be, blinking showing the icon, something very fast and difficult to happen, sometimes I have to receive several debuff at once.

**Comment by jcsnider** [comment]
@WeylonSantana: Shield statuses end as soon as the shield is destroyed. Because your should provides 0 hp it is immediately removed and the stats go back to normal.

EIther give the Shield some health by using the Hp Damage field or set the effect to None and then the debuff will persist.
