### ISSUE TITLE
Cooldown reduction affect all items cooldown

### ISSUE THREAD

**Issue by Spectreye** [AscensionGameDev/Intersect-Engine#607]
**Describe the bug**
Actually the stats of Cooldown reduction also reduce items cooldown. I've never seen a game where this is actually the norm (Except if it was an intentionnal features).

It can lead to a lot of unintended problems : 

- Consumable cdr
- Quest item cdr
- Stuff cdr
- Every kind of items cdr 

**Version Encountered**
0.7.0.108

**To Reproduce**
1. Make a potion with 30 sec cooldown and an armor that reduce by 50% the cooldown.
2. See error

**Expected behavior**
Items shouldn't be concerned by the CDR.
Or 
An option in items/spell would be welcome : "Ignore CDR"

**Operating System:**
Windows

**Additional context**
I've made a topic about it but nobody answered... 
https://www.ascensiongamedev.com/topic/5832-cooldown-reduction-stats/#comment-50215

**Comment by jcsnider** [comment]
Added options to ignore cooldown reduction for items & spells. (In their respective editors)

If ignore cdr is checked then cdr will not be applied for the group when that particular item/spell is used.
