### ISSUE TITLE
Pasting data into Experience table for classes does not work

### ISSUE THREAD

**Issue by helenatodev** [AscensionGameDev/Intersect-Engine#609]
**Is your feature request related to a problem? Please describe.**
I was trying to place a custom XP in the classes of my project, used in a simple Excel table, but when pasting into the XP table and leaving the program or editor screen, all values are reset.
It would be interesting, if we could put a personalized formula, an option below EXP INCREASE.
So that we can make more lightweight that does not exceed the limit of values of the engine that would be a gigantic number, however when using only percentage in the calculation, this number is easily reached.

**Describe the solution you'd like**
As mentioned above, it would be interesting where we could put a customizable formula for example **player.level * 2 / 0.10 (22).**

Ignore the formula, it's just an example, you could follow an excel standard to make it easier to paste in the * Custom box *

**Comment by dhmhc** [comment]
I ended up editing the XP table of each class by editing directly from the Database, in the column to overlay the xp

**Comment by blinkuz** [comment]
I was modifying it and it has worked correctly for me, can you share more details of the problem or screenshots? in my case the maximum level is 60 and when saving the exp tables in each class using the grid exp everything seems to work correctly, I am using a custom version of the engine based on prerelease 7

**Comment by dhmhc** [comment]
When you copy an entire column with the LEVEL - LEVEL, and paste it into the editor table, it copies, but when you try to save, clicking CLOSE, when the editor returns, it resets everything you defined, I tested it now, and it only works by putting value by value, manually and not using the paste system on top
