### ISSUE TITLE
Server is locking and lagging, just restarting to resolve.

### ISSUE THREAD

**Issue by ghost** [AscensionGameDev/Intersect-Engine#61]
**Describe the bug**
The server starts to press after a certain time, causing some rollbacks until it is impossible to play.

**Version Encountered**
0.6.2.401

**To Reproduce**
I don't know how to reproduce, just leaving the server on for 24 hours

**Expected behavior**
It seems when the server goes online for a long time

**Logs**
https://ascensiongamedev.com/resources/filehost/7f9ff432827c2569ee8930f7ef74616a.log

**Operating System:**
Windows Server 2016

**Additional context**

**Comment by jcsnider** [comment]
Lots of bugs that could have caused this have been fixed in the past week. Given that the logs here no longer apply and there are no actual repro steps this is being closed.
