### ISSUE TITLE
Traps not visible

### ISSUE THREAD

**Issue by froggytrav** [AscensionGameDev/Intersect-Engine#614]
Traps are not visible on the ground, hit/cast anim is working though
Version 0.7.0.109

**Comment by blinkuz** [comment]
This does not comply with the format of reporting bugs and the traps that do not have sprites is something by default, the functionality does not exist and there is already an issue created suggesting to add it.

**Comment by froggytrav** [comment]
How does it not comply with the format for reporting bugs? I listed the bug which in itself would be difficult to elaborate, other than what I described. And you are wrong that it does not exist. It did exist and was working with version 0.6.2.435, as I just now tested it with one of my backups. Which is why I reported it as a bug.

Anyway I do not want to clutter this, as this is a bug report, feel free to PM me on the forums instead.

**Comment by blinkuz** [comment]
https://www.ascensiongamedev.com/topic/5702-trap-visuals/ The only way to visualize cheats is by assigning a hit or cast animation, but there is no sprite as such to make them visual when cast.

https://github.com/AscensionGameDev/Intersect-Engine/issues/607 Here you can see the correct format to report bugs, the more information you can provide it will be easier to test and replicate it to find a solution.

**Comment by froggytrav** [comment]
Since you don't seem to understand and did not want to have this conversation privately, here is a video demonstrating that traps did in fact have a visual effect when placed, meaning they DID have a visual effect on the ground previously, but don't anymore.
https://www.youtube.com/watch?v=McpcNjvPQY4

And while I absolutely understand to write just like in the example you linked, I don't see the reason? Do I need to explain here to the creators of the engine how to create a trap spell? I doubt it, so instead I explained the bug (traps do not show on the ground) and what version i am using. All those other steps are completely irrelevant. If it was an event or a more complex part of the engine I absolutely would further explain the steps to reproduce the bug. But you know, just to humor you I'll do it.
