### ISSUE TITLE
Chat bar scroll does not work properly.

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#618]
**Describe the bug**
I downloaded the full 109 version to try it out. The scroll bar does not work when the chat has few messages

**Version Encountered**
0.7.0.109

**To Reproduce**
1. Download full 109 version
2. Log in in game
3. Chatting and try to use scroll bar

**Expected behavior**
scroll bar working

**Screenshots**
https://www.ascensiongamedev.com/resources/filehost/ed92554fd8efddd72c11448373db0224.mp4

**Logs**
If there are error logs please attach them below.

**Operating System:**
Windows, Mac, Or Linux

**Additional context**

**Comment by Cheshire92** [comment]
Yeah it's an oddity I created that fixed a much more annoying bug. Once there's 10+ lines in chat it'll behave properly.

The original issue was that scrolling at all would reset the scroll height you'd set it to as soon as someone sent a chat message. It's not perfect and definitely a bug of sorts but it worked as a quick hacky fix.

**Comment by WeylonSantana** [comment]
I didn't know about it, so if you can close this topic I would like to thank you

**Comment by jcsnider** [comment]
@Cheshire92 can you elaborate more on what the original annoying bug was? I might take a look at cleaning this up later.. but I don't want to end up back where we started.

**Comment by Cheshire92** [comment]
Original bug has the chatbox scroll all the way down every message that's received and doesn't retain the scroll distance the user has set. 

Makes it impossible to look back at old chat messages.

**Comment by Arufonsu** [comment]
Can confirm and can easily be reproduced in the latest dev 0.7B.

Bug#1 (described here by @WeylonSantana  )
The scroll bar doesn't work properly when the chat has **few** messages.
![chatbug2](https://user-images.githubusercontent.com/17498701/120934160-2ff24780-c6cb-11eb-8a55-b227f777c575.gif)

Bug#2 (described here by @Cheshire92 )
The chatbox doesn't retain the scroll distance the user has set / can't see the first messages in the chat log after a while.
(as you can see, i can't scroll up to the admin welcome message in the chat log)
![chatbug1](https://user-images.githubusercontent.com/17498701/120934226-79db2d80-c6cb-11eb-859e-f1e937bc562b.gif)

**Comment by Arufonsu** [comment]
Confirmed, this can be reproduced in the latest dev 0.7B.

The scroll bar doesn't work properly when the chat has **few** messages.
![chatbug2](https://user-images.githubusercontent.com/17498701/120934160-2ff24780-c6cb-11eb-8a55-b227f777c575.gif)

**Comment by Arufonsu** [comment]
Not sure if this is the best way to "fix" this issue, but in Chatbox.cs, L:240, changing the value 10:
`var scrollToBottom = mChatboxMessages.GetVerticalScrollBar().ScrollAmount == 1 || (mChatboxMessages.RowCount <= 10 && mChatboxMessages.GetVerticalScrollBar().ScrollAmount <= 1);`

to 1:
`var scrollToBottom = mChatboxMessages.GetVerticalScrollBar().ScrollAmount == 1 || (mChatboxMessages.RowCount <= 1 && mChatboxMessages.GetVerticalScrollBar().ScrollAmount <= 1);`


seems to fix it 👍🏽 
![recording](https://user-images.githubusercontent.com/17498701/123529181-edb19a00-d6bb-11eb-967f-d73864d260e5.gif)

**Comment by Cheshire92** [comment]
Yeah originally my thought for the hacky fix was that you probably wouldn't need to scroll until you'd reach 10 lines of chat messages. So i set that as the minimum where it would stop force snapping to the bottom.
