### ISSUE TITLE
Option to alphabetize lists

### ISSUE THREAD

**Issue by froggytrav** [AscensionGameDev/Intersect-Engine#621]
**Is your feature request related to a problem? Please describe.**
I have spells ranging from rank 1-11, and some parts of intersect is alphabetized and others are ordered by when they were created

**Describe the solution you'd like**
To be able to alphabetize lists for easier selection and sorting, arranging, or even be able to use search regardless of what list it is

**Additional context**
No other context

**Comment by jcsnider** [comment]
Dupe of #421
