### ISSUE TITLE
Drop Items in party

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#631]
**Is your feature request related to a problem? Please describe.**
The idea of a drop for each member of the party is cool, but this should be the creator’s choice, there should be a way to configure this, not every game may want to use this as a default.
but also, many creators may want to use, but not for all monsters. (avoid having a bool in the server config)

**Describe the solution you'd like**
By default the drop should be unique, and not for each party player, so in the npc editor there should have:

Checkbox: Party Loot? - If enabled it will give loot to each party member separately (how is it currently with this leafling code)
Checkbox: Party correction - If enabled it will divide to dropchance of an item over the party size (So 1% in a party of 2 will become 0.5%)

**Additional context**

**Comment by jcsnider** [comment]
Will add a checkbox in the NPC editor called Boss Loot which will trigger this behavior (where all attackers & their party members) are generated loot when the NPC dies.

If that checkbox is unchecked then the original behavior will take effect which is that loot only spawns for the killer.
