### ISSUE TITLE
API Endpoint Unban bug

### ISSUE THREAD

**Issue by Thomasfds** [AscensionGameDev/Intersect-Engine#632]
**Describe the bug**
I was doing the ban / unban system for a web interface, so I am using the API.

During the unban, the account remains banned.

API return success message.

**Version Encountered**
0.6.2.457-beta (v0.6.2.457)

**To Reproduce**

Send to api endpoint request for deban.

**Other**
When i have upgrade to v7.111 everything works fine.

**Comment by jcsnider** [comment]
If it works in v7 then it's been fixed. Use v7 if you need that endpoint.
