### ISSUE TITLE
Reset Vitals And Statusses in config.json is active every time

### ISSUE THREAD

**Issue by TalikanPDMO** [AscensionGameDev/Intersect-Engine#643]
**_I'm french. My english is bad ^^'_**

**Describe the bug**
In config.json (server) the option "ResetVitalsAndStatusses" is false but .... is alway actived (true)

**Version Encountered**
7.0.108

**To Reproduce**
1. Go to config.json
2. Change "ResetVitalsAndStatusses" to false
3. Create a NPC with reset range 4, 5 ... or anything
4. See the bug if NPC lose the aggro, HP and MP is restored

**Expected behavior**
/

**Screenshots**
/

**Logs**
/

**Operating System:**
Windows 10

**Additional context**
earlier this option work fine =/

**Comment by jcsnider** [comment]
English wasn't bad.

You said 'earlier' it worked fine. In which version specifically? @TalikanPDMO 

I'm thinking about adding another property called ContinuouslyResetVitalsAndStatuses which can be set to true/false.

If true the npc will reset its hp the entire time while walking back to the reset point, and if false it will only reset its hp one time when it turns around. Will that work as a solution?

**Comment by TalikanPDMO** [comment]
Hello,

In the 6.2 it's work fine.
I expressed myself badly I think ^^'

"ResetVitalsAndStatusses" in config.json is "false" but the NPC restore HP/MP
