### ISSUE TITLE
Server crash when projectiles collide with enemies.

### ISSUE THREAD

**Issue by blinkuz** [AscensionGameDev/Intersect-Engine#649]
**Describe the bug**
As the title mentions after having made a merged of the last changes in the prerelease branch in my project, the server is crashing every time I launch a projectile at the enemies, I thought that the error was related to a method that I have created to eliminate the shells spawns when 1 of them collides but i have removed all logic and left the shells file clean and i still have the problem.

**Version Encountered**
Prerelease 7 with the latest changes to date: https://github.com/AscensionGameDev/Intersect-Engine/pull/641

**To Reproduce**
Launch an existing projectile at an enemy npc.

**Expected behavior**
Correct functioning of the projectiles.

**Screenshots**
Screenshot of the server log when it crashes while in debug mode in the IDE Rider:
https://s3.us-east-2.amazonaws.com/ascensiongamedev/filehost/6cfccf36115ffdf31c6e01f18c067fb2.png

**Logs**
https://www.ascensiongamedev.com/resources/filehost/8d381c42f675b4395351241172e2875f.log

**Operating System:**
Windows.

**Additional context**
The problem is very strange since I have carried out tests after merging the last wave of PR, specifically all the changes before: https://github.com/AscensionGameDev/Intersect-Engine/pull/629 and everything works perfectly like this that doing an analysis of the changed files related to the projectiles after that point I have doubts regarding this PR: https://github.com/AscensionGameDev/Intersect-Engine/pull/633

**Comment by jcsnider** [comment]
Can you please confirm that this error occurs with a clean version of 0.7.0.112 and post those logs?

I have to assume that this is caused by custom code, especially since line 1064 in Entity.cs on the prerelease branch has no logic on it.

**Comment by blinkuz** [comment]
I will start to carry out tests in a completely clean environment, I understand that it would be difficult to follow up due to my custom changes but it is very strange that everything happens after the last merged related to the projectiles and the delay improvement, I will inform you with the new log from let him do the tests.

**Comment by blinkuz** [comment]
I confirm that the problem is happening due to some custom change in my project, I am sorry to have raised the false alarm, the changes in the projectiles made in the last PR are working perfectly as far as I have tried in a clean version, unfortunately I still cannot find what is the Specific problem whereby after PR # 633 my server crashes when impacting entities, feel free to close the issue.

**Comment by jcsnider** [comment]
Best of luck working it out!
