### ISSUE TITLE
feature: configurable party item drop logic

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#651]
**Is your feature request related to a problem? Please describe.**
is it intentional that party members cannot pick up items that are not yours? if it is, maybe that could change

**Describe the solution you'd like**
Party members can not pickup items when drop.
Whenever an item drops, does it belong to one owner, but when it's in a party, does the drop belong to everyone? This is the common behavior in games, here, the owner is the owner
It should have an option to allow members to obtain equipment, even if they are not the owner, IF the owner of the drop is a party member.
As well, there should be an option for only the owner to be able to take the item, regardless of being in a party or not

**Additional context**

**Comment by dhmhc** [comment]
I thought that this function was already in the engine in .112

    "IndividualizedLootAutoIncludePartyMembers": true

**Comment by WeylonSantana** [comment]
@dhmhc https://prnt.sc/123dgdd
"When killing an npc which spawns individualized loot for all of it's attackers, include loot for all their party members, even if they didn't participate (deal damage) to the npc"

https://github.com/AscensionGameDev/Intersect-Engine/pull/642/commits/a5cb57c883e9d4af654054e3e72c9d98465ae299

**Comment by WeylonSantana** [comment]
I'm closing this as not very useful, we had a lot of work to separate the loot and prevent people in the party from stealing the items from each other, that would be going backwards, I'm more mature than April 25, 2021.
