### ISSUE TITLE
Projectiles blocked by friendly targets

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#652]
**Is your feature request related to a problem? Please describe.**
Projectiles could have the ability to cross party members, on the contrary, in a narrow passages, whoever has projectiles style combat behind someone who fights hand-to-hand will never participate in the battle

**Describe the solution you'd like**
Projectiles pass through party members without causing damage or disappearing, this should happen without the need for piercing to be activated.

**Additional context**
1 - Open 2 clients
2 - Place two players on the same tile and face the same side
3 - shoot a projectile, the projectile does not hit the enemy ahead

**Comment by Cheshire92** [comment]
I am pretty sure I fixed this in Leafling at some point. So it's definitely doable.
