### ISSUE TITLE
Something wrong with the chance to drop items when you die

### ISSUE THREAD

**Issue by dhmhc** [AscensionGameDev/Intersect-Engine#670]
**Describe the bug**
I put 1 in the drop configuration when dying, and it seems that the percentage is very high, the whole inventory almost drops all when dying, if you put 0, nothing drops, if you put 1, half of the inventory drops.

**Version Encountered**
0.7.0.115

**To Reproduce**
1 - Set the drop in the server settings, to number 1,
2 - fill your inventory, and see almost all of it dropping.

**Expected behavior**
should 1 really be 1% or 10%? I think 1%, I tried to put a value of 0.1 to 1% but it seems that this is not how it works ... or it should work

**Operating System:**
Windows Server 2016

**Comment by WeylonSantana** [comment]
@dhmhc do a test, try to do the opposite
imagine so
1 = 99% of dropping items
99 = 1% of dropping items
Try to put 99 and see if it drops 1%

**Comment by dhmhc** [comment]
I did the test, and yes, exactly what you said, it's the opposite hahahah.

But this is strange, because in the configuration, it is called '' Item drop chance "'and no, chance of not dropping the item.

**Comment by WeylonSantana** [comment]
@dhmhc Indeed haha
