### ISSUE TITLE
Playerbox BUG

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#681]
**Describe the bug**
Duplicate HP in the playerbox

**Version Encountered**
0.7.0.117

**To Reproduce**
1 - Download the full version
2 - start the server and create the account
3 - log in
4 - see error

or

upgrade your current project, no need change any file on gui folder

**Expected behavior**
no bug or glitch

**Screenshots**
![image](https://user-images.githubusercontent.com/63019821/116933996-b930dd00-ac3a-11eb-92b0-de1ad44e18f5.png)

**Logs**
If there are error logs please attach them below.

**Operating System:**
Windows 10

**Additional context**

**Comment by dhmhc** [comment]
The same here, I noticed that there was something wrong in the character's life when taking damage, it had a gray bar, I thought it was just my interface that bugged after upgrading.

**Comment by Kamusvalenzuela** [comment]
same here
