### ISSUE TITLE
Spell with casting time do not work while walking

### ISSUE THREAD

**Issue by Sachiel353** [AscensionGameDev/Intersect-Engine#683]
**Describe the bug**
When trying to use a spell that has a casting time while walking it does not work most of the time.

**Version Encountered**

0.7.0.117

**To Reproduce**
1. Create a spell with casting time
2. Give it to the player
3. Try to cast it while walking

**Expected behavior**
When walking and trying to cast a spell with casting time the player stops automatically to cast it like it used to.

**Operating System:**
Windows 10

**Comment by da-rulez** [comment]
Can confirm this one. Tried with that cancel cast while walking option false and true. 

Thought it was custom code, but seems like that lefling feature is still blocking some spell casts
