### ISSUE TITLE
Non-dropable item property

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#684]
**Is your feature request related to a problem? Please describe.**
Rather than having a global bool in the server's config regarding dropping items upon dying, this could be an item editor configuration.

**Describe the solution you'd like**
Have area to enter the percentage of drop the item upon dying.

0% do not drop upon dying.

**Additional context**
The intersect would probably overcome some challenges if that were to happen :3

When we set up an item drop chance when dying, it’s global for all items and that’s annoying, I don't want all items to be dropable, so I'm forced to mark bound checkbox, but I don't want them to be bound, I just want it not to drop, so I'm left with no choice.

**Comment by da-rulez** [comment]
I think you are on the right track here.

My suggestion is for a couple of checkboxes for items: 

Drop on death?
Can drop?
Can trade?
Can sell? 
Can bank? 


I think that would cover any possibility.

**Comment by WeylonSantana** [comment]
I like that, @Cheshire92 talked about that months ago

**Comment by jcsnider** [comment]
I like this. Only big requirement is that these options need to default to true if bound is checked for existing items during the upgrade/migration.. don't want to break games with engine updates unless we have to. Marking as help wanted.

**Comment by blinkuz** [comment]
@jcsnider  Exactly which of the 2 ideas seems correct to you? the one in the main topic that mentions only adding a% drop per article or the one in the @da-rulez comment to add all the new options to verify the different cases and possibilities with the items?

**Comment by jcsnider** [comment]
All of the above.
