### ISSUE TITLE
Improved Quest Log

### ISSUE THREAD

**Issue by jcsnider** [AscensionGameDev/Intersect-Engine#687]
**Is your feature request related to a problem? Please describe.**
Quest log as it stands is very very basic. 

**Describe the solution you'd like**
Being able to set conditions for quests to show up would be nice.  

I'm thinking that we could define quest types and ordering in the server config like so
- Main Quests
- Daily Quests
- Party Quests
- Side Quests

Being able to optionally move completed quests into a specific section would be nice. as well

Finally being able to 'Track' quests so the current task and info shows up on screen would be awesome.

**Additional context**

**Comment by da-rulez** [comment]
Sounds great! 

Maybe an option to group quests in the menu?

So you have 'Western Provinces' and 'Chocolate Town' quests or something
