### ISSUE TITLE
bug:  SQLite Error 5: 'database is locked'

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#692]
**Describe the bug**
I don't know the cause, the server is online and crashes periodically

**Version Encountered**
0.7.112

**To Reproduce**
1. Online server for days
2. see error

**Expected behavior**
Do not crash

**Screenshots**

**Logs**
2021-05-08 15:45:22.678 [Error] Failed to save user: beelaw
2021-05-08 15:45:22.678 [Error] 
  Message: SQLite Error 5: 'database is locked'.
    Stack:    em Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   em Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   em Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   em Microsoft.Data.Sqlite.SqliteConnectionExtensions.ExecuteNonQuery(SqliteConnection connection, String commandText)
   em Microsoft.Data.Sqlite.SqliteConnection.BeginTransaction(IsolationLevel isolationLevel)
   em Microsoft.EntityFrameworkCore.Storage.RelationalConnection.BeginTransactionWithNoPreconditions(IsolationLevel isolationLevel)
   em Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(DbContext _, ValueTuple`2 parameters)
   em Microsoft.EntityFrameworkCore.Storage.Internal.NoopExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   em Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.Execute(IEnumerable`1 commandBatches, IRelationalConnection connection)
   em Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(IReadOnlyList`1 entriesToSave)
   em Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   em Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   em Intersect.Server.Database.IntersectDbContext`1.SaveChanges(Boolean acceptAllChangesOnSuccess) na C:\TeamCity\buildAgent\work\40dc5d27074313da\Intersect.Server\Database\IntersectDbContext.cs:linha 276
   em Intersect.Server.Database.IntersectDbContext`1.SaveChanges() na C:\TeamCity\buildAgent\work\40dc5d27074313da\Intersect.Server\Database\IntersectDbContext.cs:linha 268
   em Intersect.Server.Database.PlayerData.User.Save(Boolean force) na C:\TeamCity\buildAgent\work\40dc5d27074313da\Intersect.Server\Database\PlayerData\User.cs:linha 335

--------------------------------------------------------------------------------
2021-05-08 15:45:22.756 [Error] Received unhandled exception from System.Threading.Thread.

--------------------------------------------------------------------------------

--------------------------------------------------------------------------------
hread.
2021-05-08 15:45:22.756 [Error] Received unhandled exception from System.Threading.Thread.

--------------------------------------------------------------------------------
2021-05-08 15:45:22.756 [Error] 
  Message: Failed to save user, shutting down to prevent rollbacks!

--------------------------------------------------------------------------------
2021-05-08 15:45:22.756 [Error] 
  Message: Failed to save user, shutting down to prevent rollbacks!

**Operating System:**
Windows

**Additional context**

**Comment by WeylonSantana** [comment]
#841 And this problem are duplicates. As in the other there is more information, I will close

**Comment by Arufonsu** [comment]
Reopening since this is the original issue report for the (yet unable to reproduce) bug report.

**Comment by WeylonSantana** [comment]
As I don't know how to reproduce anymore, I'll close it, if it happens in the future, I'll create another
