### ISSUE TITLE
feature: expand character movement capabilities

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#694]
**Is your feature request related to a problem? Please describe.**
As the intersect engine thinks of something that should be good for everyone, the movement should be improved, but how?

**Describe the solution you'd like**
The intersect has a configuration for maps, the value 0 is a type of camera movement, the value 1 is another camera movement, the value 2 is another movement. The same could be applied to the movement of the character / npc / events

something like "CharacterMovement": 1,

0 = 4-sided movement (default)
1 = 8-sided movement (diagonal walking, which hundreds of people ask for)
2 = movement with mouse (if possible) (I [asked for it](https://www.ascensiongamedev.com/topic/4866-point-and-click/) the day the intersect became open source haha)

**Additional context**
if the intersect had at least the option 0 and 1, it would already cover many games, it could be a bool (false for 4 direction(defalt), true for 8)

**Comment by jcsnider** [comment]
If someone created a clean PR for diagonal movement that is optional we'd probably consider and accept it.

Mouse movement would require changing too much, and likely would be declined.

**Comment by RandemGamor** [comment]
Leafling has diagonal movement. Maybe approach the developer to see if shes willing to help with adding it as a permanent feature into intersect?

Mouse movement would just need to work similar to npc 'tracking' when chasing a player.
On click have it path to that position.

**Comment by WeylonSantana** [comment]
> Leafling has diagonal movement. Maybe approach the developer to see if shes willing to help with adding it as a permanent feature into intersect?
> 
> Mouse movement would just need to work similar to npc 'tracking' when chasing a player.
> On click have it path to that position.
> It would be a really nice feature that's for sure.

Jc knows how to make the move by clicking, he's done it on another project, and the diagonal walk any of them can do too, but they must have other priorities in their lives, so if someday a programmer shows up willing to help, they maybe can accepted the pr.

**Comment by Cheshire92** [comment]
> Leafling has diagonal movement. Maybe approach the developer to see if shes willing to help with adding it as a permanent feature into intersect?

The person that implemented it in Leafling is the same person that wrote the diagonal movement patch for the engine on the forums.

If someone is willing to clean it up a bit and make it a bit less messy alongside some configuration options I'm sure it'll be possible to accept it as a pr though.

**Comment by blinkuz** [comment]
I had some problems with the diagonal movement of the patch in the forum and with the help of Kibbelz I was able to clean it, if I can correctly track all the changes we make to make it work well I can try to share it as a PR.

**Comment by blinkuz** [comment]
I have found the code that I mentioned before, but I see that the same commit also worked on improving the target system to attack those that are diagonally if you have them targeted, do you think it would be correct to add that part as well? all OPTIONAL in case you decide to use the diagonal movement in the server configuration.

**Comment by blinkuz** [comment]
Many months passed and I had forgotten about this, but lol here is an initial idea of what the forum patch for the prerelease branch would be, it is still in work but I will try to add configuration options to keep the 4 directions movement intact.

#1229
