### ISSUE TITLE
Can't migrate to 118

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#699]
**Describe the bug**
I use mysql database in my game, so until version 117 the migration went well, but at 118 it didn't

**Version Encountered**
0.7.0.118

**To Reproduce**
1. replace exe files
2. start server
3. type READY

**Expected behavior**
not crash and start normally

**Screenshots**

**Logs**
[errors-Intersect Server.log](https://github.com/AscensionGameDev/Intersect-Engine/files/6451632/errors-Intersect.Server.log)
[Intersect Server-2021_05_10-08_18_17_194.log](https://github.com/AscensionGameDev/Intersect-Engine/files/6451633/Intersect.Server-2021_05_10-08_18_17_194.log)
[playerdbIntersect Server-2021_05_10-08_18_17_194.log](https://github.com/AscensionGameDev/Intersect-Engine/files/6451634/playerdbIntersect.Server-2021_05_10-08_18_17_194.log)

**Operating System:**
Windows 10

**Additional context**
I restored my backups and cleared all logs, the logs above were generated when I typed READY "as if it were the first time"

These logs below are generated if I try to type READY a second time
[errors-Intersect Server.log](https://github.com/AscensionGameDev/Intersect-Engine/files/6451648/errors-Intersect.Server.log)
[Intersect Server-2021_05_10-08_26_55_129.log](https://github.com/AscensionGameDev/Intersect-Engine/files/6451649/Intersect.Server-2021_05_10-08_26_55_129.log)
[playerdbIntersect Server-2021_05_10-08_26_55_129.log](https://github.com/AscensionGameDev/Intersect-Engine/files/6451650/playerdbIntersect.Server-2021_05_10-08_26_55_129.log)

the process went well in sqlite database

**Comment by jcsnider** [comment]
Probably need to use a newer version of MySql or better yet use MariaDB instead. I don't think there are changes to the engine that we can easily make to resolve this.

**Comment by WeylonSantana** [comment]
@jcsnider 
I downloaded the latest version of mariadb.
I uninstalled xampp (which I used in the past) and installed mariadb
and created two new databases and restored my backups (connected to the mariadb service)

I downloaded version 117, asked to update the database, updated it, it was ok.
![image](https://user-images.githubusercontent.com/63019821/117724128-b2b1e080-b1b9-11eb-9465-a847a996533b.png)

![image](https://user-images.githubusercontent.com/63019821/117724186-cd845500-b1b9-11eb-870e-8febe0dfc67e.png)

Still it is not possible to upgrade to 118

**Comment by jcsnider** [comment]
So from Googling it looks like it might be caused by database/table coalition issues....

Does a clean 0.7.0.118 work?

If so, can you try converting your player database back to a sqlite db using the 'migrate' command on the server console, and then delete all the tables in herospd and then use 'migrate' again which will allow the server to create all the tables and move the data in correctly?

**Comment by WeylonSantana** [comment]
@jcsnider about the clean version, it’s not even necessary, I have a version to create my gui, I upgraded there, and it worked well.
but my game, which does not upgrade

about the migration, I also tried, the server console says that the operation was successful, both for the migration of heroespd (player data) and heroesgd (game data), but the databases are clean, without any data. When changing the database in the config.json from MySql to sqlite, and starting the server, it creates a map of 0, class of 0.

but I just tried to convert and start the server. But I didn't try that last thing you said

Correct me if I'm wrong, (I think I got it wrong)
What I have to try is
1 - use the migrate function, and migrate the two databases.
2 - delete the tables in heroespd (while it is mysql?)
3 - after that, use the migrate function again and migrate the two databases again?

**Comment by WeylonSantana** [comment]
@jcsnider you can close this report
your solution was right

1 - use the function to migrate only to the player database
2 - in sqlite database delete all tables
3 - in the configuration files, change the player database from mysql to sqlite
4 - I started version 117 for the tables to be created
5 - replaces exes with version 118 and update
6 - update worked correctly and the server started
