### ISSUE TITLE
json update on 118

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#701]
**Describe the bug**
All versions before version 118, the json files of the gui update when we resize the screen for example.

I can make a modification to a json file, (change the size of a window for example), if I want to see this change in the game, just resize the game and the new settings are loaded.

In version 118 this does not happen anymore.
So we have to go back to the old method, close and open the game with every change made to the json files.

I'm trying to set up the guild tab chat, guild window to my gui, but I'm also modifying other elements like playerbox, hotbar, if I change a pixel in the json file I have to close and open the game.

Until version 117, it was enough to resize the window.

**Version Encountered**
0.7.0.118

**To Reproduce**
1. Open the game
2. modify a json file from any window
3. resize the game
4. See error (new settings not applied)

**Expected behavior**
new settings applied

**Screenshots**

**Logs**
If there are error logs please attach them below.

**Operating System:**
Windows

**Additional context**

**Comment by jcsnider** [comment]
Very much intentional. Jsons are cached in memory now on first load so that when opening the bank and other windows the game isn't waiting on disk reads and writes which will help performance. 

https://github.com/AscensionGameDev/Intersect-Engine/pull/673
