### ISSUE TITLE
Guild bank window crashes

### ISSUE THREAD

**Issue by helenatodev** [AscensionGameDev/Intersect-Engine#703]
**Describe the bug**
I made an NPC that opens the guild bank, but when you do that the game simply closes.

**Version Encountered**
0.7.0.118

**To Reproduce**
1. Create a guild.
2. Try to open the Guild Bank
3. See the error

**Expected behavior**
Open the guild bank with 50 slots as specified in the server settings.

**Logs**
https://pastebin.ubuntu.com/p/6Jff63QG7Z/

**Operating System:**
Windows

**Comment by WeylonSantana** [comment]
@dhmhc Could you test the set guild bank slots? It doesn't seem to work here I think.

I set an int variable to 10
defined guild bank slots for this var int
opened guild bank

did not work

about your bug, I tested it here and it opened and it worked normally

**Comment by jcsnider** [comment]
It's not really mentioned but guild bank slots can only increase and not decrease at this time.

**Comment by WeylonSantana** [comment]
@jcsnider got it.

**Comment by jcsnider** [comment]
@dhmhc can you try replacing your client/resources/gui/layouts/game/bankitem.json with a clean one from here and see if it works?

https://raw.githubusercontent.com/AscensionGameDev/Intersect-Assets/b7_full/resources/gui/layouts/game/BankItem.json

**Comment by dhmhc** [comment]
> @dhmhc can you try replacing your client/resources/gui/layouts/game/bankitem.json with a clean one from here and see if it works?
> 
> https://raw.githubusercontent.com/AscensionGameDev/Intersect-Assets/b7_full/resources/gui/layouts/game/BankItem.json

i tried but no :(

`2021-05-10 23:48:53.741 [Error] 
  Message: Tentativa de divisão por zero.
    Stack:    em Intersect.Client.Interface.Game.Bank.BankWindow.InitItemContainer() na C:\TeamCity\buildAgent\work\40dc5d27074313da\Intersect.Client\Interface\Game\Bank\BankWindow.cs:linha 124
   em Intersect.Client.Interface.Game.Bank.BankWindow..ctor(Canvas gameCanvas) na C:\TeamCity\buildAgent\work\40dc5d27074313da\Intersect.Client\Interface\Game\Bank\BankWindow.cs:linha 47
   em Intersect.Client.Interface.Game.GameInterface.OpenBank() na C:\TeamCity\buildAgent\work\40dc5d27074313da\Intersect.Client\Interface\Game\GameInterface.cs:linha 211
   em Intersect.Client.Interface.Game.GameInterface.Draw() na C:\TeamCity\buildAgent\work\40dc5d27074313da\Intersect.Client\Interface\Game\GameInterface.cs:linha 401
   em Intersect.Client.Interface.Interface.DrawGui() na C:\TeamCity\buildAgent\work\40dc5d27074313da\Intersect.Client\Interface\Interface.cs:linha 183
   em Intersect.Client.Core.Graphics.Render() na C:\TeamCity\buildAgent\work\40dc5d27074313da\Intersect.Client\Core\Graphics.cs:linha 474
   em Intersect.Client.MonoGame.IntersectGame.Draw(GameTime gameTime) na C:\TeamCity\buildAgent\work\40dc5d27074313da\Intersect.Client\MonoGame\IntersectGame.cs:linha 280
   em Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime)
   em Microsoft.Xna.Framework.Game.Tick()
   em Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   em Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   em Intersect.Client.MonoGame.IntersectGame.MonoGameRunner.Start(IClientContext context, Action postStartupAction) na C:\TeamCity\buildAgent\work\40dc5d27074313da\Intersect.Client\MonoGame\IntersectGame.cs:linha 514
   em Intersect.Client.Core.ClientContext.InternalStart() na C:\TeamCity\buildAgent\work\40dc5d27074313da\Intersect.Client\Core\ClientContext.cs:linha 44
   em Intersect.Core.ApplicationContext`2.Start(Boolean lockUntilShutdown) na C:\TeamCity\buildAgent\work\40dc5d27074313da\Intersect (Core)\Core\ApplicationContext`2.cs:linha 221`

**Comment by jcsnider** [comment]
How about bankwindow.json?
https://raw.githubusercontent.com/AscensionGameDev/Intersect-Assets/b7_full/resources/gui/layouts/game/BankWindow.json

**Comment by dhmhc** [comment]
> How about bankwindow.json?
> https://raw.githubusercontent.com/AscensionGameDev/Intersect-Assets/b7_full/resources/gui/layouts/game/BankWindow.json

Yaaaaa! its Works 👯‍♀️ 

I downloaded this .json from the forum upgrade package

**Comment by jcsnider** [comment]
Sweet, I'm gonna chalk this one up to a bad config :)
