### ISSUE TITLE
Editor crash when open the Resource Editor.

### ISSUE THREAD

**Issue by naziozeno** [AscensionGameDev/Intersect-Engine#715]
Occurs at full version.

**Describe the bug**
When open the resoucer editor it's crash.

**Version Encountered**
0.7.0.108

**To Reproduce**
1. Open the editor
2. Click on Resource editor
3.  The editor crashes

**Screenshots**
[https://ibb.co/jVyPsCZ](url)

**Logs**
2021-05-10 23:21:30.471 [Error] 
  Message: InvalidArgument=Value '0' não é um valor válido para 'SelectedIndex'.
Nome do parâmetro: SelectedIndex
    Stack:    em System.Windows.Forms.ComboBox.set_SelectedIndex(Int32 value)
   em Intersect.Editor.Forms.Editors.FrmResource.UpdateEditor() na C:\TeamCity\buildAgent\work\40dc5d27074313da\Intersect.Editor\Forms\Editors\frmResource.cs:linha 236
   em Intersect.Editor.Forms.Editors.FrmResource.AssignEditorItem(Guid id) na C:\TeamCity\buildAgent\work\40dc5d27074313da\Intersect.Editor\Forms\Editors\frmResource.cs:linha 56
   em Intersect.Editor.Forms.Controls.GameObjectList.GameObjectList_AfterSelect(Object sender, TreeViewEventArgs e) na C:\TeamCity\buildAgent\work\40dc5d27074313da\Intersect.Editor\Forms\Controls\GameObjectList.cs:linha 140
   em System.Windows.Forms.TreeView.OnAfterSelect(TreeViewEventArgs e)
   em System.Windows.Forms.TreeView.TvnSelected(NMTREEVIEW* nmtv)
   em System.Windows.Forms.TreeView.WmNotify(Message& m)
   em System.Windows.Forms.TreeView.WndProc(Message& m)
   em System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Operating System:**
Windows 10

**Comment by jcsnider** [comment]
Much better @naziozeno! The logs help a ton.

Fixed by #712
