### ISSUE TITLE
Option to lose XP when dying

### ISSUE THREAD

**Issue by dhmhc** [AscensionGameDev/Intersect-Engine#722]
**Is your feature request related to a problem? Please describe.**
I saw that the engine is getting quite modular and for all audiences, games, and it is always possible to do more with this engine due to its ability to serve various types of projects.

**Describe the solution you'd like**
And here is my suggestion, what if it was possible to set a percentage of XP loss on the server when dying?

Loses XP when dying: true / false
Percentage of loss on death: int%
It can regress level when dying when there is no more XP: true / false

Some important points if you return to the level when you have no more XP to lose.

1 - Remove the point that was used in the attribute. Or remove the attribute that was upgraded when gaining the distribution point
2 - Check equipment when losing the level, in this case, if the equipment is not at the same level as the character, he will automatically unequip.
I think these are the most important points so that there is no glitch when dying, as a character dying and losing xp on purpose to gain infinite points of attributes.
**Additional context**
I think it will make some projects more difficult, and many people may like this option in their game

**Comment by da-rulez** [comment]
We made a patch for a previous Intersect version:
https://kasplant.itch.io/kash-shop-exp-loss-on-death

This could serve as a base for a PR. I imagine it's not too hard to make. 

This does not include leveling down. Which strikes me as way too game specific and bad game design / asking for trouble in 99% of cases.

**Comment by Cheshire92** [comment]
Levelling down would require the game to start tracking what points were spent on for each level which it simply doesn't right now.. And wouldn't work when someone decides to save all their points for five levels and then spend them.

Losing experience isn't a hard ask, neither is levelling down technically.. But removing the points the user spent themselves last level might be tricky. I think the current system for it simply tears points away one by one until it reaches a valid threshold again.

**Comment by dhmhc** [comment]
> Levelling down would require the game to start tracking what points were spent on for each level which it simply doesn't right now.. And wouldn't work when someone decides to save all their points for five levels and then spend them.
> 
> Losing experience isn't a hard ask, neither is levelling down technically.. But removing the points the user spent themselves last level might be tricky. I think the current system for it simply tears points away one by one until it reaches a valid threshold again.

In fact, this is almost impossible to do and it would not be worth the effort ...

**Comment by WeylonSantana** [comment]
@dhmhc There is a "rudimentary" way to make the player lose XP when dying, create a variable and assign a negative value to that variable, then give the player exp and give exp by choosing this variable with a negative value, it will work.

Then you would have to change the value of this variable, according to the player's level or level range, for example losing 10exp when level is greater than 1 and less than 10, and so on.

Rudimentary, as I mentioned, but it works

And I think this topic can be more or less a clone of my topic, where I ask for practically the same thing

**Comment by dhmhc** [comment]
I think that just losing XP then, it would be a good size, I think the rest would be almost impossible to do, and it wouldn't even be worth it.

I even know how to make the code, but I don't know how to put it in the server settings, the options ..

**Comment by jcsnider** [comment]
Just add a line in the Core/Config/Player Settings or whatever file for % to lose. Looking forward to a PR :)
