### ISSUE TITLE
organize chronologically

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#725]
**Describe the bug**
I don't know if it was intended but I am reporting, the button to organize chronologically, organizes in alphabetical order

**Version Encountered**
0.7.0.120

**To Reproduce**
1. Click on organize chronologically
2. See error

**Expected behavior**
organize chronologically

**Screenshots**

**Logs**
If there are error logs please attach them below.

**Operating System:**
Windows

**Additional context**
By default (when folders appear) it is already alphabetically organized, so I believe it is a bug

**Comment by WeylonSantana** [comment]
@jcsnider After some time using the variable editor as it is, I believe it is better that way.
When opening the editor, if there are no folders, the variables are already organized by chronologically order. The button is now used to arrange alphabetically.
The created folders (when the editor is not organized alphabetically) are still organized alphabetically and show the added variables in the order they were created/added. It's much better than before.

If no one else complains about it, You could close it and remove it from the to-do list.

The solution would be to change the text of the button from "arrange chronologically" to "arrange alphabetically"

Another problem that could be avoided would be this:
When creating many variables at the same time, they all come with the name "new x variable", so we rename them all.
When organizing chronologically it would look something like this:

![image](https://user-images.githubusercontent.com/63019821/120325275-e0bca900-c2bd-11eb-89d1-3df6d087c70b.png)

This bug may be the solution to this problem.
(I know it's something very irrelevant, but I believe it's a comfort for us)
So here is my request.

**Comment by Arufonsu** [comment]
i personally think it would be nice to be able to arrange alphabetically even with folders up 🔡  ~

**Comment by jcsnider** [comment]
Yeah chronological is being tossed for alphabetical asap, and then later we will replace the dropdowns with something that does folders too.
