### ISSUE TITLE
Option to not show player names and monsters on the map.

### ISSUE THREAD

**Issue by helenatodev** [AscensionGameDev/Intersect-Engine#740]
**Is your feature request related to a problem? Please describe.**
I was here thinking, if you have the option to show level next to the name, why is there not an option to not show the name of the player / monster on the screen?

**Describe the solution you'd like**
It would be interesting, an option to render the nickname of the monster or player, only when hovering over the entity, consecutively showing the level as well, if activated in the server settings.

**Additional context**
This would leave the game in preference, to make it less polluted on maps with many monsters, or player on a map.

**Comment by Cheshire92** [comment]
I'd say this is a pretty game specific option since some people would want to control this globally and some would like to control this from the client settings.

**Comment by Uyarrr** [comment]
I think it should be in client settings.

**Comment by Arufonsu** [comment]
Many games allow users to basically set it up in the game options, to whether display the names all the time, or when hovering the mouse on players/monsters. in the other hand, i would personally like to have it locked and specifically configured so the HP bars are always displayed for players only (except for invisibility), while hiding monsters names and hp bards until mouse hovered or attacked 😆

**Comment by dhmhc** [comment]
> Many games allow users to basically set it up in the game options, to whether display the names all the time, or when hovering the mouse on players/monsters. in the other hand, i would personally like to have it locked and specifically configured so the HP bars are always displayed for players only (except for invisibility), while hiding monsters names and hp bars until mouse hovered or attacked 😆

same here hahaha

I would like to just when the mouse hovers over, show names, tags and clan...
