### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Uyarrr** [AscensionGameDev/Intersect-Engine#741]
**Describe the bug**
Server crashes randomly.

**Version Encountered**
0.7.0.116

**Logs**
2021-05-21 04:23:18.056 [Error] 
  Message: Error 718: ConflictInMappingEntry
    Stack:    konum: Open.Nat.SoapClient.GetXmlDocument(String response)
   konum: Open.Nat.SoapClient.<InvokeAsync>d__3.MoveNext()

UPnP Service Initialization Failed. You might not have a router, or UPnP on your router might be disabled.
  Message: 'Open.Nat.NatDeviceNotFoundException' türünde özel durum oluşturuldu.
    Stack:    konum: Open.Nat.NatDiscoverer.<DiscoverDeviceAsync>d__5.MoveNext()
--- Özel durumun oluşturulduğu önceki konumdan başlayan yığın izlemesinin sonu ---
   konum: System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   konum: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   konum: System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   konum: Intersect.Server.Networking.Helpers.UpnP.<ConnectNatDevice>d__4.MoveNext() C:\TeamCity\buildAgent\work\40dc5d27074313da\Intersect.Server\Networking\Helpers\UPnP.cs içinde: satır 31

**Operating System:**
Windows

**Comment by Cheshire92** [comment]
After a while, right away or when something specific happens?

Can you try to disable UPnP in the server config so we can get rid of that bogus error from the logs?

**Comment by Uyarrr** [comment]
As I've noticed when both client and editor is open, but I'm not 100% sure thats why I didn't add reproduction steps. It's also instantly crashed when I opened the server.

**Comment by jcsnider** [comment]
Related: https://github.com/AscensionGameDev/Intersect-Engine/issues/224#issuecomment-781783405
