### ISSUE TITLE
Option to use sprite animations on spells

### ISSUE THREAD

**Issue by Sachiel353** [AscensionGameDev/Intersect-Engine#745]
**Is your feature request related to a problem? Please describe.**
Having a option that allows to use a sprite animation from the existing ones (_attack, _weapon, _shoot) when using a spell.

**Describe the solution you'd like**
A dropdown menu in the spell editor that allows to choose which of the three animations to use.

**Additional context**
This would allow to have a more immersive game with sprite animations for spells and not only for weapons.

**Comment by jcsnider** [comment]
_cast exists which will pay while casting spells

**Comment by Sachiel353** [comment]
Yes, but it would be nice to have something after that, for example if i make projectile spell, with _shoot i can show the player shooting the projectile, if i make a "magic sword" spell i could use _weapon to show it swinging the sword. Right now this kind of thing is only possible with weapons, so spells with those characteristics look a bit weird just appearing in front of the player.
