### ISSUE TITLE
Papperdoll BUG in the Character tab

### ISSUE THREAD

**Issue by ThousandX** [AscensionGameDev/Intersect-Engine#75]
**Describe the bug**
It seems to me a disorganization of clothes.

**Version Encountered**
Source Version 0.6.1.0

**To Reproduce**
Just put a equips with papperdoll.

**Expected behavior**
To be normal as it appears in the character

**Screenshots**
http://prntscr.com/rsh61i

**Logs**
NO

**Operating System:**
Windows Server 2016

**Additional context**
--

**Comment by jcsnider** [comment]
Happy to look into it...

In order to save time if I sent you my login info for your game could you give my character the armor and equipment to make this bug happen?

**Comment by ThousandX** [comment]
These items any new character gets when starting the quest, can do it with a beginner char, and talk to the first NPC

**Comment by jcsnider** [comment]
Fixes have been merged into master and dev branches
