### ISSUE TITLE
'Guild System' Bug #3 - Can deposit bags with items inside (v.0.7.0.120)

### ISSUE THREAD

**Issue by RandemGamor** [AscensionGameDev/Intersect-Engine#755]
**Describe the bug**
Players can place items inside of bags and then into the guild stash. I believe this should not be possible as there is the option to expand space.

**Version Encountered**

v.0.7.0.120

**To Reproduce**
Put items inside a bag.
Put bag inside guild bank.
Withdraw bag with other player, see items inside.

**Expected behavior**
I expected not to be able to store bags inside the guild stash.
Either we should not be able to store them full stop, or it should be optional in a server config file.

**Screenshots**
n/a

**Logs**
n/a

**Operating System:**
n/a

**Additional context**
n/a

**Comment by Arufonsu** [comment]
i played a game where this was possible. either way, this could be implemented.
such a restriction shouldn't be default tho, but toggable and up to the game designer that's using the engine.

**Comment by jcsnider** [comment]
You can configure items in the item editor on whether they can be banked (or not).
https://www.ascensiongamedev.com/resources/filehost/694b143525bc240f6ea654636fad55b4.png

That way you can define whether banks should be bankable on an item by item basis. The logic does not check if bags are full though, that only happens on trading/selling so players don't get scammed.
