### ISSUE TITLE
'Guild System' Bug #4 (v.0.7.0.120)

### ISSUE THREAD

**Issue by RandemGamor** [AscensionGameDev/Intersect-Engine#756]
**Describe the bug**
When you create a guild if you try and type more than the maximum allowed characters it acts as if you just clicked 'Cancel' and doesn't display the same messages (popup and in-chat) that it does if it doesn't meet the minimum requirement.

**Version Encountered**

v.0.7.0.120

**To Reproduce**
Try to create a guild with more than the maximum number of characters allowed.

**Expected behavior**
I expected the same chat popup and text chat to appear that appears when the variable input is less than the minimum amount.

**Screenshots**
n/a

**Logs**
n/a

**Operating System:**
n/a

**Additional context**
n/a

**Comment by jcsnider** [comment]
The variable input does not provide errors if the input is invalid, instead you are given a different chain of event commands that you can run to tell the player your own custom error message.

![invalid](https://www.ascensiongamedev.com/resources/filehost/f97c67002d7a079a04291185de80a500.png)
