### ISSUE TITLE
Global Boosts such as EXP, Drop Rate, etc

### ISSUE THREAD

**Issue by RandemGamor** [AscensionGameDev/Intersect-Engine#757]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
I would like to be able to have global boosts such as *1.5 experience across the whole server for a limited amount of time. Should be able to attach this to events.
As well as other boosts like drop rate (Luck) and so on.

**Additional context**

**Comment by blinkuz** [comment]
I think it is related to this PR: https://github.com/AscensionGameDev/Intersect-Engine/pull/592

**Comment by Kamusvalenzuela** [comment]
> I think it is related to this PR: #592

Its like u say, this is a duplicate in part of a Feature request
Duplicate of #589

**Comment by RandemGamor** [comment]
Ah I didn't see that sorry :) Thanks
