### ISSUE TITLE
Event Command - Reset Stat Point Allocations

### ISSUE THREAD

**Issue by jcsnider** [AscensionGameDev/Intersect-Engine#761]
**Is your feature request related to a problem? Please describe.**
There is currently no way for to give players an option to reset their stat point allocations and re spec-out their builds.

**Describe the solution you'd like**
An event command which will reset stat point allocations.

**Additional context**
NA

**Comment by AisenGaming** [comment]
This is a great addition!

**Comment by blinkuz** [comment]
This will save the lives of many, it is something very useful.

**Comment by Arufonsu** [comment]
Yiasss!! 🎲 🎮
