### ISSUE TITLE
Additional Crafting Features - '+ .value to p.var' for example.

### ISSUE THREAD

**Issue by RandemGamor** [AscensionGameDev/Intersect-Engine#763]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
So, I want to be able to give 'crafting' experience to a player when they craft specific items.
Now I know I can create a player variable like "smithingEXP".
But there's no way to + to the player variable value when they craft that I can see?
Like we need options to give even player exp, and value to a variable upon successful completion of the craft.

This also brings me to another feature that will be a real nice addition;
Crafting Requirement. This could be set like player level, or a variable requirement/condition.
like "if smithingLVL => 1" for example.

If they are able to craft it the item picture would be full colour.
If it wasn't able to be crafted, it would be faded out or black and white or have a little image overlaid to show it's not yet craftable and they don't meet the requirements.
We should have a way to state to the player what the requirements are.
So maybe a little 'optional description' box. we could write in say;
"Smithing Level 1 required" as an example.

**Additional context**
n/a

**Comment by WeylonSantana** [comment]
A "run common event" after each crafting performed would solve this.

**Comment by AisenGaming** [comment]
This is something I'm looking into already, will let you know when I have something

**Comment by AisenGaming** [comment]
Adding to this real quick:
I have finished the code to trigger common events after a successful craft, I am currently in the middle of working out the database migration for it to be done. Once that's done I will be making a PR for it :)

**Comment by worldofjimmy** [comment]
Could currently be made by:
Craft a "-Sword".
Common event: If player has a "-Sword" give X points to Variable X and give a "Sword" to the player.

But would love to have an option to run common event after a craft has been made.
