### ISSUE TITLE
Shortcut to add several stats point at once

### ISSUE THREAD

**Issue by Spectreye** [AscensionGameDev/Intersect-Engine#774]
**Is your feature request related to a problem? Please describe.**
You use a lot of stats allocation or you have the possibilites to change classe as will ? Well you have the same problems as me ! (And reallocate 200+ stats point each time you change class is a chore for players)

**Describe the solution you'd like**
A Simple shortcut to add several point at once (Exemple : Shift + Clic = 10 points, like in diablo 2)

**Comment by Arufonsu** [comment]
Not sure if this is what you mean, but here's an example on how MapleStory does it. 
(for skills, but same logic could be applied to stats?)
![imagen](https://user-images.githubusercontent.com/17498701/121086202-dbc19300-c7b0-11eb-99b9-1fdc41744bf5.png)

**Comment by jcsnider** [comment]
You either need an extra ui window, or extra buttons. Both add clutter for something that I still argue is a niche issue. An addition like #775 provides would be best as a source mod (or someday a plugin) but this isn't a change that I want to bring into the base engine. Marking as won't fix.
