### ISSUE TITLE
bug: MaximumLootWindowDistance > map's size

### ISSUE THREAD

**Issue by Guite-Emortal** [AscensionGameDev/Intersect-Engine#778]
**Describe the bug**
Loot in the Loot Window duplicates when you move from one map to another. 
However, when the Loot button is clicked the correct amount of loot is distributed. So not game break but obnoxious.

**Version Encountered**

0.7.0.120 & 0.7.0.121 BETA-PreRelease
**To Reproduce**
1. Create an item and monster.
2. Set item drop rate from your monster to 100%
3. Kill monster close to map border.
4. See Loot in the Loot Window duplicate

**Expected behavior**

**Screenshots**
Not a Screenshot but a short 22 second video of the issue described.
https://youtu.be/25dAiMEYnCg

**Operating System:**
Windows 10

**Additional context**
None

**Comment by Xenepherth** [comment]
Its not bug i think... if you in range loot radius, you can see items in loot bag

**Comment by Guite-Emortal** [comment]
Yea but that isn't the problem. The problem is that the loot in the window visibly multiplies when you move from one map to another. There is only 1 iron plate available to loot, I am within range of the single plate the entire time, the only difference is that I crossed the border into another map.

**Comment by Xenepherth** [comment]
> Yea but that isn't the problem. The problem is that the loot in the window visibly multiplies when you move from one map to another. There is only 1 iron plate available to loot, I am within range of the single plate the entire time, the only difference is that I crossed the border into another map.

ahhh okay i'm undersand now...

**Comment by jcsnider** [comment]
[Cannot immediately recreate.](https://www.ascensiongamedev.com/resources/filehost/1b3ad7e3c60ab73a04dca4e13ba9e4c2.mp4)

Gonna need more info.

Are you using 0.7.0.121 or a version with source modifications? Any more information that might help with recreating?

**Comment by Cheshire92** [comment]
Not ever seen this behaviour in Leafling either, where the code for the AoE loot window was taken from.

**Comment by Guite-Emortal** [comment]
No modifications. Currently using 0.7.0.121., the bug is currently present. Originally saw the bug in 0.7.0.120.

**Comment by WeylonSantana** [comment]
@Guite-Emortal I always have a clean version to test for bugs when I'm not sure if they are bugs or not
I reproduced from step 1 to 4 you mentioned, and it didn't happen
I watched your video too, and I tried to do it the same way as it is there, and it didn't happen
I believe that around here a bug is considered a bug when it happens to everyone and/or in a clean version (no changes)
So I'm leaving this comment of mine, I tried to replicate it and I also couldn't

**Comment by jcsnider** [comment]
@Guite-Emortal that second video was interesting because your loot distance was like 20 tiles away. Can you share your server config, or at least the looting section of it?

**Comment by Guite-Emortal** [comment]
"Loot": {
    "ItemDespawnTime": 15000,
    "ItemOwnershipTime": 5000,
    "ShowUnownedItems": false,
    "ConsolidateMapDrops": false,
    "EnableLootWindow": true,
    "MaximumLootWindowItems": 30,
    "MaximumLootWindowDistance": 75,
    "IndividualizedLootAutoIncludePartyMembers": false

**Comment by Cheshire92** [comment]
Isn't 75 above the amount of tiles the client would normally even be aware of?

**Comment by jcsnider** [comment]
For sure. It's enough to get across the adjacent map, and then try to get across again. Maybe it searches recursively and comes back again.... I definitely think that distance is why he's having the issue and we are not.

**Comment by Guite-Emortal** [comment]
Alright so I took what you both said and changed my:
"MaximumLootWindowDistance":  from 75 to 35 and it fixed the problem
[Bug Fixed](https://ascensiongamedev.com/resources/filehost/27b79107d3358adac4b928c36f758369.mp4)

**Comment by WeylonSantana** [comment]
This is not a bug, but it will be left open so an extra check can be done to prevent it from happening again.

**Comment by Arufonsu** [comment]
we should probably make it so if MaximumLootWindowDistance > map's size, then MaximumLootWindowDistance = map's size
