### ISSUE TITLE
Transform don't return to original form after "Effect duration"

### ISSUE THREAD

**Issue by Andical** [AscensionGameDev/Intersect-Engine#782]
**Describe the bug**
Create a spell to transform yourself or other people into another sprite. Doesnt matter how many seconds you enter inside effect duration you just dont return to original form after that time.
I am sure last week when I was usign 6.2.458 it was working, because I did 2 spells with it and today I tested them back ...

**Version Encountered**
Fresh install 0.7.0.121

**To Reproduce**
1- Download full 0.7.0.121
2- Create spell with target type Self or Target.
3- Enter an Effect duration, for example 3000ms
4- After 3 seconds when you transform someone with this spell they dont return to original sprite. Its an infinite transform.
Bug for both, self and target
5- Inside Client, you see the skill being used and the icon in dots under your character portrait but after it expires you stay in this form....

**Expected behavior**
Transform your sprite for the amount selected and return to original.

**Screenshots**
![transform](https://user-images.githubusercontent.com/14881655/122297311-aaa53900-cefb-11eb-9bdd-d30fe8c02ac7.png)

**Operating System:**
Windows 10

**Additional context**
As menctioned up, I created this spell in version 6.2 and it was working as intended returning to original and today after I saw it wasnt working I downloaded fresh install and confirmed its bug in new patch

**Comment by Andical** [comment]
![transform](https://user-images.githubusercontent.com/14881655/122297743-2f905280-cefc-11eb-9be3-f4598b2697a2.png)
Another example in the fresh install I just downloaded

**Comment by helenatodev** [comment]
I went to test this bug, and also noticed that paperdoll does not hide when you are transformed. It seems to me that this did not happen in previous versions

**Comment by Xenepherth** [comment]
Confirmed that bug need to fix

**Comment by Kamusvalenzuela** [comment]
Confirmed x3
