### ISSUE TITLE
Adjust Player HP - Event

### ISSUE THREAD

**Issue by Andical** [AscensionGameDev/Intersect-Engine#784]
Adjust Player HP ignores values and always heal 50. Item cooldown is ignored too and is always 10s.

**Version Encountered**
7.0.121

1. Create an item called Food, Fish, Meat anything you want and set a cooldown for it (In my example I did 5min - 300000).
2. Create a Common Event Called Fish and Adjust Player HP in a quantity, 1, 5, 20... anything you want. Or even nevative numbers.
3. Inside the config of fish item you previously created, select type Event and load the event we just made.

**Expected behavior**
Doesn't matter if you enter 1 hp, 5, -5 or any other value it will always heal you for 50.
Also ignored the cooldown you wrote inside item properties.

**Screenshots**
![image](https://user-images.githubusercontent.com/14881655/122652035-e2e78a00-d13c-11eb-9b18-dc6d30ad7b6d.png)
![image](https://user-images.githubusercontent.com/14881655/122652061-014d8580-d13d-11eb-8086-1a5cae62ef81.png)
![image](https://user-images.githubusercontent.com/14881655/122652134-85a00880-d13d-11eb-8e05-a2badeafb773.png)

**Operating System:**
Windows 10

**Additional context**
Is there any other way of creating a heal buff for clicking a food better than this? ( I wanted to add label and wait time to make  small heal tics over time with wait and go to label start)

**Comment by Andical** [comment]
Related to previous: I created a spell called fish and it works well with the heal I set.
But when in the item "Fish" I link it to a spell it heals 50 (ignoring the heal I set), same as the bug in this topic with events.
![related](https://user-images.githubusercontent.com/14881655/122823473-b28c2100-d2df-11eb-8662-6616012c0913.png)

**Comment by jcsnider** [comment]
First off, for items you can use a consumable type instead.

For spells you can make them friendly and put a negative damage to restore hp.

Secondly with the same config I am able to restore 100 hp... so marking this as blocked.

**Comment by lodicolo** [comment]
This can be reopened if a complete minimal reproduction scenario is provided for the latest prerelease build.
