### ISSUE TITLE
Max "Item Stack" ignored inside bags

### ISSUE THREAD

**Issue by Andical** [AscensionGameDev/Intersect-Engine#786]
**Describe the bug**
I don't know if this is intended but I will explain how I think it should work.
In item editor when you set an inventory stack limit, this limit is ignored when you move items inside bags. There is only limit for bank and inventory, I think inventory and bag should be the same or add a 3º stack for items inside bags.
Would be cool to have this function to force players carry bags and not having 1 bag with infinite storing space...

**Version Encountered**
7.0.121

**To Reproduce**
1. Go to items
2. Create an item called arrows and set max stack 100.
3. Add it to any shop ingame and buy it
4. In your inventory the item stays in the stack you previously selected
5. Move the item to a bag and it ignores any stack limit

**Expected behavior**
Since there is only inventory stack limit and bank stack limit, I think we need to set inventory stack limit same as bags or create a new stack limit for bags (3º option in item editor creator).

**Screenshots**
In this example arrows max stack is 100 and rune 5, but inside bags there is no limit.
![bug](https://user-images.githubusercontent.com/14881655/122682319-f9ebb200-d1f8-11eb-9ef1-75028c1e5b01.PNG)

**Operating System:**
Windows 10

**Additional context**
Would be cool to have this function to force players carry bags and not having 1 bag with infinite storing space...

**Comment by Cheshire92** [comment]
Ah, right I forgot bags were a thing. 
Rewrote the banking logic to be a copy of the inventory logic but I guess the same should apply to bags.

Rather than copying or again I think we're better off making the way storage slots are handled a generic handler for.. well storage slots.. rather than more copy work.

**Comment by Andical** [comment]
I noticed that If I have 5 runes in my inventory and 5 runes inside my bag and I add the rune to hotbar, for example skill 1, I can only use it 5 times (the 5 from inventory), I think it would be cool if I have a consumable or rune like this in both places they share quantity when we use them. In this case it should use the 10 runes (5inventory+5bag) when I press the rune binded in hotbar

**Comment by Cheshire92** [comment]
That's an entirely different conversation and unrelated to this issue though.

**Comment by Andical** [comment]
You right, should I create a new post with feature request or bug? I don't pretend to be a bore

**Comment by Cheshire92** [comment]
I'd say being able to use items from bags would be a feature request. 
Not sure how feasible it is though.. considering bags are entirely different entities separate from players and inventories however.

**Comment by Arufonsu** [comment]
Fixed by #1285
