### ISSUE TITLE
Database modified since loaded + invalid handle to path

### ISSUE THREAD

**Issue by Andical** [AscensionGameDev/Intersect-Engine#797]
**Describe the bug**
Everyday I work in my game project 10hours+ (open and close editor, clients etc) and I NEVER get a single error, everything clean and smooth. When I go to sleep the console is empty but EVERY morning, the day after when I wake up, I have the same errors. Noone is connected to server, no client, no editor, nothing.

**Version Encountered**
7.0.121

**To Reproduce**
1. Run server
2. Go to sleep (all good)
3. Wake up (this bugs appear in colsole)

**Expected behavior**
Empty console, noone is interacting with server.

**Screenshots**
Always when I go to sleep console is like this:
![server](https://user-images.githubusercontent.com/14881655/123048350-97fc9980-d3fe-11eb-9884-7dc54624a41b.PNG)

And when I wake up I have this errors:
![error](https://user-images.githubusercontent.com/14881655/123048463-b9f61c00-d3fe-11eb-9cf7-bd35061557a7.PNG)

**Logs**
If there are error logs please attach them below.
[errors-mono-sgen.log](https://github.com/AscensionGameDev/Intersect-Engine/files/6699555/errors-mono-sgen.log)
[mono-sgen-2021_06_23-02_30_30_457.log](https://github.com/AscensionGameDev/Intersect-Engine/files/6699556/mono-sgen-2021_06_23-02_30_30_457.log)
[playerdbmono-sgen-2021_06_23-02_30_30_457.log](https://github.com/AscensionGameDev/Intersect-Engine/files/6699557/playerdbmono-sgen-2021_06_23-02_30_30_457.log)

**Operating System:**
Server in Ubuntu (20.04.2 LTS)

**Additional context**
Folder and files always have FULL permissions.
![permissions](https://user-images.githubusercontent.com/14881655/123049208-9a132800-d3ff-11eb-9fd8-2195d2797583.PNG)

**Comment by Andical** [comment]
I forgot to mention I haven't edit players or server databses. All is by default.

**Comment by Andical** [comment]
Maybe related with this other issue? #120
https://github.com/AscensionGameDev/Intersect-Engine/issues/120

**Comment by jcsnider** [comment]
Do you have any services talking to your server via the API?

**Comment by Andical** [comment]
website intersect CMS port 5402

**Comment by WeylonSantana** [comment]
Please create a new issue if this occurs in the future.
