### ISSUE TITLE
[Linux ARM + Mono] Server Issues.

### ISSUE THREAD

**Issue by Arufonsu** [AscensionGameDev/Intersect-Engine#799]
### **Describe the bug**
Intersect Server can't properly start at all in ARM Linux enviorments with the latest version of Mono.

Tested device:
- Raspberry pi Zero W with Raspbian OS Lite (headless).
- Raspberry pi Zero W with latest Ubuntu LTS OS (headless).

### **Version Encountered**
Latest dev branch to the date of this report.

### **To Reproduce**
1. Install the latest stable version of mono.
2. Run Intersect Server though mono.
3. See Errors/Warnings
-
4. Tested with Mono 6.8, no more warnings.
5. But server is unable to go further than "Loading, Please wait." and exits back to terminal command input.

### **Expected behavior**
Intersect Server starts and runs without an issue on ARM Linux enviorments with the latest version of Mono.

### **Screenshots**
![raspberrypiZero](https://user-images.githubusercontent.com/17498701/123180692-bf348480-d459-11eb-9665-22575309a09e.png)

### **Logs**
No logs got generated by the server.

### **Operating System:**
So far, any ARM Linux distro (?)

**Comment by jcsnider** [comment]
If the server isn't crashing then it's fine. The gpath assertions are warnings and not really an issue.

**Comment by Arufonsu** [comment]
did you saw the screenshots? the server doesn't seems to be running / showing anything in the console afterwards 😢 
it never reaches the point where it sucessfully loads up, or you say its still running in the background (??)

![2021-06-23 19_49_18-Intersect Server - CPS_ 60, Players_ 0, Active Maps_ 0, Logic Threads_ 2 (0 In U](https://user-images.githubusercontent.com/17498701/123181826-18051c80-d45c-11eb-9beb-fe34402310f9.png)

**Comment by Arufonsu** [comment]
Another test with NoFoody / Debug, but this time no error output, the server simply wont finish to start at all and it exits to the system's default console input. Server clearly isn't running in the background, as i checked all the PIDs.

![2021-06-23 21_18_04-pi@raspberrypi_ ~](https://user-images.githubusercontent.com/17498701/123187738-b26b5d00-d468-11eb-87cb-2d3a1ec23695.png)

sadly, i get no logs nor anything to tell what's the issue here.
if there's a specific version of mono i should try, i would love to know which, as we should probably mention this in the documentation.

**Comment by jcsnider** [comment]
Not sure what's up. The gpath lines are non-issues for us. Without any other explicit crash logs/errors I don't have any insight as to what's going on.

**Comment by Arufonsu** [comment]
> 
> 
> Not sure what's up. The gpath lines are non-issues for us. Without any other explicit crash logs/errors I don't have any insight as to what's going on.

yeah.. sorry about that, would provide logs if i had any.
my guess is that its an issue with ARM arch and Mono perhaps? the gpath errors aren't present on Mono versions from 6.9 and below, its only an error warning from that version ahead. What's worrying here is that the server won't load any further than the "Loading, Please wait." strings on console. 

We should probably point out in the how to docs about these issues though:
- Intersect Server works fine with Mono versions 6.0 to 6.9 ish ~
- Intersect Server has issues with ARM Linux distros or headless distros (?)..

Regards, hope this can help at least to document this silly trial and error experiment i did with the Rasp Pi Zeros.

**Comment by Arufonsu** [comment]
To confirm the previous comment, i just tested today with an Amazon's EC2 ubuntu-focal-20.04 machine and its working fine and without any warning by using mono 6.8.

![2021-06-24 16_34_36-Configuración](https://user-images.githubusercontent.com/17498701/123329391-bf408d00-d50a-11eb-9491-412643c8b9d6.png)

Regards.

**Comment by Arufonsu** [comment]
Well, at last i managed to turn the game server as whole into a service for ubuntu, which works amazing !
![intersect_service](https://user-images.githubusercontent.com/17498701/123486302-c4204200-d5d9-11eb-985e-709f1c1900c4.png)
Closing this as its not really an issue, but for documentation porpouses it may help for anyone who eventually decides to search up about Intersect and ARM Linux.

Regards !
