### ISSUE TITLE
Critical nud

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#803]
**Describe the bug**
I don't know if it's a bug, but I'll report it as such
The numerical up down of the critical, everywhere allows to add 0.1 times per click
But in decimal places it is 0, never allowing us to see the value of the decimal place
Causing to make several clicks to editor changes from 0 to another value for example
The default value is 1.5 for example
In editors we will only be allowed to see changes when changing to 1 or 2

**Version Encountered**
0.7.0.121

**Expected behavior**
Show in critical nud editors at least one decimal place, as numerical increments allow for this

**Screenshots**
![image](https://user-images.githubusercontent.com/63019821/123494384-05264f80-d5f6-11eb-8da7-cd0e5e187a83.png)

**Operating System:**
Windows

**Additional context**

**Comment by helenatodev** [comment]
I had noticed it a long time ago, but I never got to investigate in depth whether it works or not
