### ISSUE TITLE
An item with a type of "None" should have a configurable type name for use in the Item's description

### ISSUE THREAD

**Issue by AlexVild** [AscensionGameDev/Intersect-Engine#806]
**Is your feature request related to a problem? Please describe.**
The use case of this would be a rare crafting material - the user may want to set the crafting material's rarity to something like "Rare", but the item is an `ItemType.None`. In the UI, when a player highlights the item, they see something like `None - Rare` underneath it. I find this to be a bit odd - as a player, I'd be confused about what the "None" means.

**Describe the solution you'd like**
It would be nice if, in the server config, we defined what "None" should be read as in-game.

**Additional context**
I have found the `none` server string - but changing it did not change the display of an item with item type "None". What is this used for? Should this be the configuration setting, as opposed to something on the server's config?

**Comment by Cheshire92** [comment]
This should be an option in the client strings file already.

**Comment by AlexVild** [comment]
@Cheshire92 Ah, _client_ strings, okay.

Question about the client config files: doesn't that mean anyone that plays the game can edit those strings?

**Comment by Cheshire92** [comment]
In theory yes but it would only affect their local client.

**Comment by AlexVild** [comment]
I'm gonna close this, then. Thank you!
