### ISSUE TITLE
Crafting Tables do not show item icons with their in-editor RGBA values

### ISSUE THREAD

**Issue by AlexVild** [AscensionGameDev/Intersect-Engine#807]
**Describe the bug**
When in a crafting table in the client, the item icons displayed do not use their respective RGBA values as defined in the editor for that item.

**Version Encountered**

0.7.0.121

**To Reproduce**
1. Create an item in the item editor
2. Change the RGBA values of its sprite
3. Add that item as a ingredient to some crafting recipe
4. Add that recipe to a crafting table
5. Open that crafting table in-client
6. The icon will not display with the RGBA values specified in the crafting table window. Only when highlighted (and thus, displaying the item display window) will the correct RGBA values be shown.

**Expected behavior**
It is expected that the sprite's RGBA values are always displayed consistently to match what they are set to in the editor.

**Screenshots**
![image](https://user-images.githubusercontent.com/8580915/123584243-00f16200-d7af-11eb-9b79-f456ae8c1b2c.png)

Here you can see that in the item's popup description menu, the alpha is lowered. However, in the crafting table, it is not changed.

**Operating System:**
Windows

**Comment by Cheshire92** [comment]
Oopsie. 🤣
