### ISSUE TITLE
feature: ability to toggle fading effects when warping

### ISSUE THREAD

**Issue by AlexVild** [AscensionGameDev/Intersect-Engine#810]
**Is your feature request related to a problem? Please describe.**
The base-game "warp" functionality can be a bit jarring. Additionally, if you do a work around by making your own fade out system with the event editor (something like displaying increasingly opaque images), you then have to deal with fading back _in_ on any map that the user could have came from via fade out. It's not impossible, but kind of a pain.

**Describe the solution you'd like**
The engine already has a built-in fade system, but the editor is not aware of it. It would be nice to have a toggle option for "fade between warp" or something, like what RPG Maker has, **that we could check for both map warp tiles and the event editor "warp player" option.**

**Comment by WeylonSantana** [comment]
I believe fade should be a command from the special effects area like play sound, show image, it should fade in and fade out, that way it would encompass much more than just teleports like cutscenes and so on.

**Comment by WeylonSantana** [comment]
Closing this out, we have the common fade event, so we can fade, then warp, and then fade again.
