### ISSUE TITLE
Ability to add a crafting sound to a crafting table

### ISSUE THREAD

**Issue by AlexVild** [AscensionGameDev/Intersect-Engine#812]
**Is your feature request related to a problem? Please describe.**
Crafting feels a little strange without auditory feedback.

**Describe the solution you'd like**
Being able to play a sound for each item that's crafted would be cool. I imagine a simple first-step implementation is just to allow the user to set a sound on a crafting table - this sound would play for the client every time it crafts an item while within that crafting table.

**Comment by jcsnider** [comment]
I think Aisen was gonna make it so common events could be set to execute on crafting as well which can lead to the same result. I'm fine with both being discreet options but providing the fyi.

**Comment by AisenGaming** [comment]
I have indeed already made it and now working on the DB Migration for it work. Should be done soon

**Comment by AlexVild** [comment]
> 
> 
> I have indeed already made it and now working on the DB Migration for it work. Should be done soon

Awesome! I'll close this then.
