### ISSUE TITLE
Negating a conditional "Has Item" check does not work.

### ISSUE THREAD

**Issue by AlexVild** [AscensionGameDev/Intersect-Engine#814]
**Describe the bug**
Something like the following:
![image](https://user-images.githubusercontent.com/8580915/124038876-ddf1c880-d9cf-11eb-83d7-125904357019.png)
Simply does not work. It does not get negated - it is still checking, in this example, that the player has 5 chicken legs, and not that they DON'T.

**Version Encountered**

0.7.0.121
**To Reproduce**
1. Make some event with a negated "Has Item" condition
2. It does not work as expected.

**Expected behavior**
I expect that the event will only go inside the conditional IF the logic holds up - negating meaning the opposite of having 5 chicken legs, in that example.

**Operating System:**
Windows

**Additional context**
Maybe this is a problem since the recent change to stackable objects? Additionally, I wonder how many of the other conditionals don't work when negated.

**Comment by AisenGaming** [comment]
Can confirm this bug.

**Comment by Arufonsu** [comment]
Can confirm too, i though it was me not setting up the event script properly, but i have tried countless times by now.

**Comment by Arufonsu** [comment]
Can confirm too, i though it was me not setting up the event script properly, but i have tried countless times with conditional branches by now and somehow and the condition always outputs as true somehow.
