### ISSUE TITLE
SQLite Error 5: 'database is locked'.

### ISSUE THREAD

**Issue by TalikanPDMO** [AscensionGameDev/Intersect-Engine#841]
Hello,

**Describe the bug**
The server crash with this error, i don't know why ... it's randomly
_[Error] Received unhandled exception from System.Threading.Thread.
Message: SQLite Error 5: 'database is locked'._

**Version Encountered**
7.0.121 "Vanilla" no edit source

**To Reproduce**
1. Run Server.exe
2. Wait and ...
3. See error

**Expected behavior**
/

**Screenshots**
/

**Logs**
[errors-Intersect Server.log](https://github.com/AscensionGameDev/Intersect-Engine/files/6765143/errors-Intersect.Server.log)

**Operating System:**
Windows 

**Additional context**
/

**Comment by Cheshire92** [comment]
Are you using any tools to write data to the database outside of the server?

**Comment by TalikanPDMO** [comment]
Hello,

Yes but just for look, no write

**Comment by Cheshire92** [comment]
Don't run those tools at the time the server is running, this will lock it causing an error like this.

**Comment by TalikanPDMO** [comment]
:O ! Uups ^^'

How ... unlocked the database ?

**Comment by Cheshire92** [comment]
Close the tools you use to read it properly. Sqlite does not deal with multiple sessions to the same file well. (It was never really meant to do that)

If you need live data from the server try using the API.

**Comment by TalikanPDMO** [comment]
Hum, the tool is not run =/

The last execution was early June

**Comment by jcsnider** [comment]
Maybe restart your computer as well if the file remains locked while everything is closed.

**Comment by TalikanPDMO** [comment]
> Maybe restart your computer as well if the file remains locked while everything is closed.

Is the first

**Comment by TalikanPDMO** [comment]
Arf, sorry.



> Maybe restart your computer as well if the file remains locked while everything is closed.

I thought I had already tried, I test

**Comment by TalikanPDMO** [comment]
Hello,

After several tests the bug always comes back and randomly =/

**Comment by TalikanPDMO** [comment]
[playerdbIntersect Server-2021_07_08-17_33_08_659.log](https://github.com/AscensionGameDev/Intersect-Engine/files/6786093/playerdbIntersect.Server-2021_07_08-17_33_08_659.log)
[errors-Intersect Server.log](https://github.com/AscensionGameDev/Intersect-Engine/files/6786094/errors-Intersect.Server.log)
[Intersect Server-2021_07_08-17_33_08_659.log](https://github.com/AscensionGameDev/Intersect-Engine/files/6786095/Intersect.Server-2021_07_08-17_33_08_659.log)

Last log

**Comment by Cheshire92** [comment]
I'd suggest figuring out what process on your machine keeps locking the file.

**Comment by jcsnider** [comment]
Disable the API and let me know if it keeps happening.

**Comment by TalikanPDMO** [comment]
> Disable the API and let me know if it keeps happening.

It's disable.
"  "Enabled": false," in api.config.json


> I'd suggest figuring out what process on your machine keeps locking the file.
> I don't think it's the server doing it on a clean build.
I reset the VPS so ...

**Comment by TalikanPDMO** [comment]
Hi,

The last log have a new errors

[errors-Intersect Server.log](https://github.com/AscensionGameDev/Intersect-Engine/files/6796939/errors-Intersect.Server.log)

**Comment by Arufonsu** [comment]
Considering the date of the report (it was made afterwards #692) and inactivity of the author, i'm closing this as not planned and duplicate.
