### ISSUE TITLE
"PVP Death" event trigger should happen before respawn

### ISSUE THREAD

**Issue by Xyseer764** [AscensionGameDev/Intersect-Engine#846]
**Is your feature request related to a problem? Please describe.**
I've tried making a PvP system where a hostile NPC spawns after a player dies, but I'm unable to spawn the NPC in a proper position, as events triggered from the "PVP Death" trigger happen after respawn.

**Describe the solution you'd like**
Simply make events triggered by PVP Death happen before the player is spawned - it gives us the access to the death location and doesn't remove any functionality.

**Comment by Cheshire92** [comment]
It happens whenever it wants to happen.
Even if we trigger it before the Respawn (which I'm pretty sure it does?) That doesn't mean the entire event processes before that.

**Comment by Xyseer764** [comment]
Well, that's unfortunate then. I'm new to this engine and I'm impressed with how much work has been put into it, but every second thing I try to implement through variable manipulation is impossible without changing the source code. The engine obfuscates its data and doesn't allow the developer to read game variables, which means that small and basic things like reading a player's item count require recompiling the source code.

**Comment by Cheshire92** [comment]
Don't touch the DB ever while the server runs. 
If you need live data externally use the API, the data is hardly obfuscated in locations you're meant to be able to see and manipulate it from.
Unless I'm misunderstanding what you mean by reading item counts?

And unfortunately, not every idea or feature is going to work or for in their game for everyone. We try to get a reasonable middle ground between what we think is a basic feature and what we can feasibly implement but if you need something outside of that you'll either need to hope we agree with your idea or make it yourself if the event system can't do it.

**Comment by Xyseer764** [comment]
"use the API" - have I not read something in the documentation? Is there a way for the editor to access variables such as the item count of a specific item in the inventory without having to recompile it and just making some addon?

By obfuscation I meant that the engine hard-codes pretty much every major structure, making it very inflexible for just about ANY game. Not being able to access things such as player health/item count/position, ect., by default is a strange choice to me, as that's functionality that's useful to pretty much any project. The fact that guilds were impossible to add through the event system (now they're implemented by being hard-coded) imo exposes a the massive limitations of the engine (I'm not talking about guild UI ect., just about functionality). Any system more complex than the complete fundamentals can't be implemented through the Event System, because you run into scalability issues. We don't even have access to _arrays_ for god's sake! Even adding just that one thing would multiply the number of possibilities by ten-fold, as it'd allow you to cross-access player variables between different clients, if you gave us access to player IDs. The engine draws on a lot of inspiration from the RPG Maker series, which means it's easy to work in and understand, but I think the engine is shooting itself in the foot if RPG Maker is as far as it cares about functionality. For single-player games having no arrays and not being able to talk between different save-files (in Intersect that instead would be different players) might be fine, but in an engine that wants to be scalable enough to run MMOs I'd consider it basic functionality.

I want to tamper what I wrote above, as I still consider Intersect a great project and I have a lot of respect for the people that maintain and develop it. I'm making these criticisms, because I want this engine to be at its best. Ultimately though, my opinions are just that, opinions and ya'll have a lot more experience working with the project. Still, I'm putting my thoughts out here, because I'm dreading actually having to program those changes myself - I've tried looking over the project and adding a single event command and oh, boy do I have no clue how long it'll take me - one command requires me to go edit 10~ files at a few different spots, learn what the hell those edits even mean, create the .design and .cs file for the command and probably much more I've not thought about yet. Getting a grasp on the source code will take me months and I'd be much more at ease if I didn't have to go there to make every small little system. Hell, I'm using the engine, because I vowed to myself to never write netcode again (a lot of time and headaches in the past...) and my project's almost a perfect fit for what the engine wants to provide. It's lacking only a few features that'd reduce my need to mess with the source code by 95% (and I'm guessing would reduce that need by about the same amount for most users of this engine).

I really hope I'm missing some button that just allows you to easily pop on small addons to the game and that everything I brought up above are moot points.

**Comment by da-rulez** [comment]
Should write the functionality you're missing in a suggestion.

What would an array be/do?

**Comment by Xyseer764** [comment]
Alright, I'll write this in suggestions.

**Comment by Cheshire92** [comment]
I feel this discussion has more or less reached the conclusion it can on a technical level. (This is just not possible with the way events work and if it were and you slap 10 minutes worth of events what's the client doing before warping?)

Going to close this. Feel free to continue the discussion on the forums or another relevant issue though.
