### ISSUE TITLE
Icon RGB values do not apply to dragged items

### ISSUE THREAD

**Issue by Xyseer764** [AscensionGameDev/Intersect-Engine#847]
**Describe the bug**
When dragging an item, the icon/pic always displays the default 255,255,255,255 color.

**Version Encountered**
0.7.0.123

**To Reproduce**
1. Create an item with any icon
2. Change RGB values from the default
3. Drag the item in the inventory

**Expected behavior**
The dragged item should maintain the specified RGB colors.

**Screenshots**
[ScreenShots](https://imgur.com/a/HV0252z)

**Operating System:**
Windows

**Comment by Cheshire92** [comment]
Should already be fixed in the development build.
https://github.com/AscensionGameDev/Intersect-Engine/pull/831

Closing this because it'll eventually come down to prerelease.
