### ISSUE TITLE
Isometric maps and characters 

### ISSUE THREAD

**Issue by HeadClot** [AscensionGameDev/Intersect-Engine#85]
**Is your feature request related to a problem? Please describe.**
Currently in Intersect engine there is no support for isometric styled maps or characters in the map editor or in play mode.

**Describe the solution you'd like**
Support for isometric tile sets added to the map editor and the option to switch between an isometric grid and a standard top down grid in the editor.  An Isometric character with eight directional movement and depth sorting would also be desirable. 

**Additional context**
Isometric maps

![Diablo 1](http://i.imgur.com/yq3mKXK.jpg)

![Hades](https://assets.rockpapershotgun.com/images/2019/01/hades-i.jpg)

Isometric Characters

![Diablo 2 Secret Cow level](https://i.stack.imgur.com/2NslT.jpg)

**Comment by jcsnider** [comment]
Sorry, but this is well beyond the scope of the base engine and will not be worked on.
