### ISSUE TITLE
In combat + exit game (window mode) = client not responding

### ISSUE THREAD

**Issue by Andical** [AscensionGameDev/Intersect-Engine#857]
**Describe the bug**
One a monster attacks you or you get in combat casting something, once you press exit button of the window (top right), the game becomes frozen, sometimes it backs after a few seconds but most of the time not.

**Version Encountered**
7.0.123

**To Reproduce**
1. Attack a monster, cast a spell or eat a food, anything that gets you in combat.
2. Instead of exiting through game options, press windows exit in top right
3. The game becomes frozen and most of the times it doesnt unfrozen, it stops responding
4. Sometimes it backs from frozen when the monster kills you and you respawn :D

**Expected behavior**
The Combat Warning window should pop normally instead of freezing client

**Screenshots**
![combat](https://user-images.githubusercontent.com/14881655/125231051-56169300-e2da-11eb-9de2-7d6d690cd7e9.png)

**Logs**
This is the log when I exit and game crash
[Intersect Client-2021_07_12-06_29_03_779.log](https://github.com/AscensionGameDev/Intersect-Engine/files/6798583/Intersect.Client-2021_07_12-06_29_03_779.log)

**Operating System:**
Windows client, ubuntu server

**Comment by lodicolo** [comment]
@Andical Is there any error log for this?

**Comment by Cheshire92** [comment]
There isn't, I've seen this happen a few times as well but can't seem to reliably recreate it myself to debug where it gets stuck.

**Comment by jcsnider** [comment]
Can confirm this bug exists, no errors. It eventually unfeezes and closes the game or shows the combat warning box.

**Comment by helenatodev** [comment]
With me, I just attack a monster, and try to exit the game through the logout menu, it gives warning and crashes.
To unlock, just ALT + TAB, then go back to the game, and there it is... unlocked, you can click OK button on the logout prompt in combat

**Comment by WeylonSantana** [comment]
@Arufonsu I was testing this bug, and it no longer freezes as described above, currently in the latest version (pre-release .22), there is a slight freeze of 1 second when the prompt opens. I would consider it corrected and you?
