### ISSUE TITLE
Stack Limit doesn't seem to apply when directly giving items

### ISSUE THREAD

**Issue by Xyseer764** [AscensionGameDev/Intersect-Engine#860]
**Describe the bug**
When giving the player items through an event, the game bypasses the item stack limit (normal option, not overflow or up to amount).

**Version Encountered**

0.7.0.123

**To Reproduce**
The item has a stack limit of 10 in inventory and 10000 in the bank.
It's very inconsistent, so it's very hard for me to say how to reproduce it, but my event is essentially this:
1. Give the player 4-5 planks (giving through variable, not static value)
2. Take away the player's wood
3. Go back to the start of the event
4. If the player has wood GOTO 1

Sometimes I end up with stacking working fine, sometimes I end up with stacks over 10.

**Expected behavior**
The item stacks should never exceed 10.

**Screenshots**
https://imgur.com/a/DMu3IQG

**Operating System:**
Windows

**Comment by Cheshire92** [comment]
Does this only happen using the event system or also when you pick quantities of it up from the map?

**Comment by Xyseer764** [comment]
I experienced two behaviors:
1. I dropped the 12 stack, picked it up and then it added itself on top of a stack of 4 and made a whole stack of 16 planks (6 above the limit).
2. I then dropped the 16 stack and picked it up - then it split itself up correctly.

I repeated it and a hunch I had was right. When you already have a stack of the item between (1)-(x-1) where x is the stack limit, then the game seems to ignore the stack limit, as you simply add to that stack. When you have no empty stack (you have no item in the inventory at all, or you have only full stacks of the item) the game seems to behave properly.

**Comment by Cheshire92** [comment]
That's strange as I'm pretty sure I tested for this specifically.
But I must have missed some bit of logic somewhere.

**Comment by Xyseer764** [comment]
Might be something with specifically this version, or maybe somehow it's just bugging out on my machine. Would love it if someone reproduced it.

**Comment by Cheshire92** [comment]
If no one manages to look into this before then I've got some time off soon that should let me take a look.

**Comment by WeylonSantana** [comment]
@Arufonsu I can't reproduce the error, give items, through variable or normal methods, it's always respecting the stack limit on latest prerelease version, or I'm doing it wrong, or the bug is fixed, could you give me a hand in testing this one?

**Comment by Arufonsu** [comment]
there's been some changes and fixes on how stackables work around inventory, bank and bags, cound't reproduce it either as 0.7.1.22
