### ISSUE TITLE
Crafting recipe Ingredient tooltips disappear

### ISSUE THREAD

**Issue by Xyseer764** [AscensionGameDev/Intersect-Engine#861]
**Describe the bug**
When hovering over an ingredient it disappears after a second-two, even though you're still hovering over it. This doesn't happen in the inventory and is overall very infuriating as it doesn't allow the player to read the name of the ingredient as it disappears almost instantly.

This issue also applies to the item being crafted.

**Version Encountered**
0.7.0.123

**To Reproduce**
1. Create a crafting menu item with an any ingredient
2. Hover over the ingredient

**Expected behavior**
The RGB should match the set RGB and the hover-over tooltip should last as long as the player's hovering over the ingredient.

**Operating System:**
Windows

**Comment by Cheshire92** [comment]
> The item RGB values do not apply in the crafting menu. If an item has custom RGB values, it'll just appear with the default color (this might be related to the dragging bug that's already being fixed).

This particular issue should already be resolved in the development branch.

**Comment by Cheshire92** [comment]
I've removed the bug that's already been fixed from the issue to make referencing and searching for this one easier in the future.

**Comment by WeylonSantana** [comment]
This bug doesn't exist anymore, hovering over an ingredient in the craft window keeps the tooltip open, the same happens while crafting, the tooltip only disappears after the end of crafting.
