### ISSUE TITLE
Add a flag for regen ticks

### ISSUE THREAD

**Issue by Xyseer764** [AscensionGameDev/Intersect-Engine#865]
**Is your feature request related to a problem? Please describe.**
Currently regeneration ticks happen only outside of combat. I'd be helpful if there was a flag in the config of the server to switch between the current behavior and allowing regeneration to happen during combat.

**Describe the solution you'd like**
Add a flag in the server config that does what I described above.

**Comment by jcsnider** [comment]
Pretty sure that exists in the servers config.json. If not there is another open request for it.

**Comment by Cheshire92** [comment]
I don't recall seeing anything like this?
Might be wrong though.

**Comment by Xyseer764** [comment]
Yep, sorry for not searching the issues - I was told from the forum to open one. There indeed is one already open https://github.com/AscensionGameDev/Intersect-Engine/issues/506
