### ISSUE TITLE
Quality of life: Update tool only include necessary files

### ISSUE THREAD

**Issue by Andical** [AscensionGameDev/Intersect-Engine#869]
**Is your feature request related to a problem? Please describe.**
I would like to use base Autoupdater, it works well and only downloads new or modified files. But the client I distribute to users must get rid of most folders and in the end it only has: Fonts, Gui, Packs, Shaders and txt config files. The rest must be deleted, but update package tool generates a list of hundreds of items and in large projects I just cant remove file by file (for example remove tileset folder, animations etc) and everything is listed inside update.json, used or not.

**Describe the solution you'd like**
I would like that when I press Package Update tools and generate an update to send it to users it doesnt include the UNencrypted files, only the .assets one and the minimum required to launch the game (and only this listed inside update.json).
![image](https://user-images.githubusercontent.com/14881655/125741881-77776260-fb2f-4f4a-83c5-a50be22dd430.png)
![image](https://user-images.githubusercontent.com/14881655/125742060-1bda68fa-7232-402c-a67d-fbbe329c8666.png)

**Comment by Cheshire92** [comment]
Have you read what you crossed out?
ClientIgnore: true

This update file also counts for the editor and thus includes every file, with a flag whether the client should ignore downloading the file or not.

**Comment by Andical** [comment]
oh, so I just set to false the folders I deleted? forgive my ignorance lol

**Comment by Cheshire92** [comment]
No? You just ignore that those are generated and the client should ignore downloading them through the built in updater.

**Comment by Andical** [comment]
but update.json is generated after, when all files and folders are already created no? I feel lost

**Comment by Cheshire92** [comment]
The client looks at that file to determine what it has to download. It doesn't start downloading everything randomly.

**Comment by Andical** [comment]
okay I will do some testing, thanks a lot!

**Comment by Cheshire92** [comment]
That file is basically a definition file for the updater that's build into the client and editor.

Both will look at it to determine what they need to download. The editor will download everything (because it can't read asset packs) and the client will only download the relevant asset packs.

**Comment by helenatodev** [comment]
I think it should have a file that determines what it will update before generating the update. as some projects may use other update launchers. like steam. this will make it easier to manipulate the files that really matter for the player to download. currently it copies everything in the current folder to a new one. only with the generated packs folder. it would be interesting to generate only the ones you defined in the editor or in some configuration file
