### ISSUE TITLE
Self healing spells missing randomly

### ISSUE THREAD

**Issue by Andical** [AscensionGameDev/Intersect-Engine#877]
**Describe the bug**
Healing spells sometimes spend the mana needed and show animation but doesn't heal with cast on self.
https://streamable.com/e2rd65
You can see at second 3 and 17 that the healing animation is applied (red +) and mana taken but health didn't go up.

**Version Encountered**
I have seen this previously, not only in 7.0.124.

**To Reproduce**
1. Create a spell targeting WITH self type
2. Fill a healing amount and mana required
3. Take damage ingame and every 20 spells at least 2 are missed.
My spell config:
![1](https://user-images.githubusercontent.com/14881655/126035241-739fb9ea-9594-4fd9-a3b8-31463223e79e.PNG)
![2](https://user-images.githubusercontent.com/14881655/126035242-c9985ccd-f579-4d35-a97f-61afaa9e2173.PNG)

**Expected behavior**
Take the mana but heal my life.

**Operating System:**
Windows client, Linux server

**Additional context**
I haven't seen any other spell miss so far, only healings applied to self.

**Comment by WeylonSantana** [comment]
You must have the Friendly checkbox marked to heal yourself.

**Comment by Andical** [comment]
You say @WeylonSantana ?  :) Second 22 and 26.
https://streamable.com/dmmpfg
Here you can see with it activated too and now it even misses 2 consecutive heals (unlucky but it can happen). I don't know people didn't notice this earlier, I saw for a long time.

**Comment by Arufonsu** [comment]
has anyone managed to reproduce this yet?

so far, i couldn't:
https://user-images.githubusercontent.com/17498701/174466801-c4c41dcf-0ff2-4e25-b39f-4965ba6c8feb.mp4

**Comment by Arufonsu** [comment]
has anyone managed to reproduce this yet?

so far, i couldn't:

https://user-images.githubusercontent.com/17498701/174466801-c4c41dcf-0ff2-4e25-b39f-4965ba6c8feb.mp4

**Comment by WeylonSantana** [comment]
It's not a bug anymore.
