### ISSUE TITLE
Players with buffs press logout but characters stay ingame

### ISSUE THREAD

**Issue by Andical** [AscensionGameDev/Intersect-Engine#883]
Hello folks, it's me again :D

**Describe the bug**
When a character use a healing over time, a food, or anything benefitial that leaves him a buff after pressing Escape> Characters/logout/desktop or close, they leave the game without a warning but character stays ingame until the end of duration.
A noob player would logout thinking he is safe but his character stays there :D

**Version Encountered**
7.0.124

**To Reproduce**
1. Go to Spells and create something that is applied to your character with any duration
2. Exit game
2. Log in other account
3. See previous player standing there until his buff is out even if he logged out without warnings or notifications

**Expected behavior**
Character should logout if the buff is friendly or leave a warning that he must stay ingame until duration is over.

**Screenshots**
![off](https://user-images.githubusercontent.com/14881655/126445178-8f4c6e30-48ed-4b38-9740-a0bb4db83e0e.png)

**Operating System:**
Windows client, ubuntu server

**Comment by Cheshire92** [comment]
This is related to how the combat timer works, friendly spells still keep you in combat and being in combat keeps you online.

**Comment by Arufonsu** [comment]
weird, iirc they changed it so you can't logout/exit while in combat

reference: https://github.com/AscensionGameDev/Intersect-Engine/issues/543#issuecomment-780879989

**Comment by Arufonsu** [comment]
weird, iirc @jcsnider changed it in the dev branch so you can't directly logout/exit while in combat, even giving a warning about it.
healing should count as a combat state, so this shouldn't be happening (right? unless they decide to ignore the warning and logout anyways)

reference: #543 (comment)

**Comment by Cheshire92** [comment]
Considering there has been no communication or status changes on this after mentioning it's likely an intended effect I'll be closing this.
