### ISSUE TITLE
Commentary on events

### ISSUE THREAD

**Issue by genitr** [AscensionGameDev/Intersect-Engine#884]
**Is your feature request related to a problem? Please describe.**
Sometimes, in the process of creating an event, you have to add many different conditions, checks, commands.  And then the event becomes cumbersome and not always easy to read.  In addition, if a project is created not by one person, but by a team, then it is extremely difficult to disassemble what the other has done.

**Describe the solution you'd like**
I suggest adding the "Comment" command to the events.  This command has only one function - to inform the developer about how the event is arranged.

**Additional context**

**Comment by jcsnider** [comment]
Checkout the Label command.

**Comment by Cheshire92** [comment]
Possible enhancement for label would be rendering the line or text in a different colour.

**Comment by jcsnider** [comment]
Think I made it green... If not I did so for Ambardia and can move that over here.

**Comment by genitr** [comment]
> Think I made it green... If not I did so for Ambardia and can move that over here.

It would be great!  If it is also a different color, then even better.  Thank you!

**Comment by WeylonSantana** [comment]
This feature was resolved in #1328
