### ISSUE TITLE
Items attained via 'Resources' don't stack

### ISSUE THREAD

**Issue by TeppyTV** [AscensionGameDev/Intersect-Engine#887]
**Describe the bug**
When successfully harvesting a 'resource' the items it drop do not stack, and can only be added to a "stack" by dropping them and picking them back up as a stack. Becomes incredibly annoying if you have a resource that has various percentage rates of dropping multiples of the same item.

**Version Encountered**

0.7.0.125

**To Reproduce**
1. Go to 'Resource Editor'.
2. Create several drop chances for the same stackable item.
3. Gather from the resource.
4. If multiples of the same stackable item drop, they don't stack and each dropped item takes up an inventory slot.

**Expected behavior**
If a resource drops a stackable item, the item should stack instead of each taking a separate inventory slot.

**Comment by Cheshire92** [comment]
Unable to reproduce on development branch.

![Image1](https://www.ascensiongamedev.com/resources/filehost/c4be29f50c6f3cfcdd3499bac8d4a504.gif)
![Image2](https://www.ascensiongamedev.com/resources/filehost/a223d0e4551254cb3680a328aae2a29d.png)

**Comment by TeppyTV** [comment]
Maybe it's by giving them different percent chance to drop that creates seperate ID's for them or something causing the stacking issue? Let me record it

**Comment by TeppyTV** [comment]
Suddenly it's fixed. Maybe when I updated to the nightly build it fixed it and I hadn't even noticed...IDK. Sorry for wasting your time with this issue. Closing it, sorry about that.
