### ISSUE TITLE
Moving 'MaxHotBar' into server config

### ISSUE THREAD

**Issue by froggytrav** [AscensionGameDev/Intersect-Engine#896]
According to JC: "It's actually not in the config. Instead it's hard coded in the source. https://github.com/AscensionGameDev/Intersect-Engine/blob/b48cea53f5e757b7f4961373e01fa777f768d0e6/Intersect%20(Core)/Config/Options.cs#L299"

**Describe the solution you'd like**
Moving the option into config.json or client config

**Comment by blinkuz** [comment]
I can do a PR for this if no one else is doing it, it doesn't look like a complex task to do.

**Comment by Arufonsu** [comment]
Opened a PR that solves this issue.
Should consider to close #895 as well, in order to avoid redundancy in the topic.
