### ISSUE TITLE
Editor Shortcut Keys

### ISSUE THREAD

**Issue by whispwhill** [AscensionGameDev/Intersect-Engine#913]
**Is your feature request related to a problem? Please describe.**
I have a hard time navigating the editor with the mouse, would be better with just keyboard shortcuts.

**Describe the solution you'd like**
Use keyboard shortcuts, B for brush F for flood fill, etc.

**Comment by Cheshire92** [comment]
I'd agree with this being a good idea for the overall user experience.

Any suggestions on which shortcuts should exist?
Might as well compile a list to discuss before someone goes ham with their preferences.

**Comment by aerayth** [comment]
Just the first letter of each tooltip name.

**Comment by oomstdev** [comment]
Agreed would be awesome
