### ISSUE TITLE
[BUG] Task Completion event

### ISSUE THREAD

**Issue by Kamusvalenzuela** [AscensionGameDev/Intersect-Engine#914]
**Describe the bug**
When you save a task (By event, gather items, kill npcs) a lot of times will get error when you save it and re-open it

**Version Encountered**

0.7.0.126

**To Reproduce**
1. Go to quest editor
2. Make a new quest or edit one
3. Make a new task without touching the "Edit task completion event"
4. save it, Close the editor, restart the server
5. Open the editor, open the quest editor
6. And try to touch the "Edit task completion event"
7. See the error

**Expected behavior**
Normally function of the event

**Screenshots**
https://cdn.discordapp.com/attachments/782922670077509632/876836118484643840/unknown.png

**Logs**
--------------------------------------------------------------------------------
2021-08-16 14:32:52.843 [Warn] EditingEvent is null.

--------------------------------------------------------------------------------
2021-08-16 14:32:57.523 [Error] 
  Message: Referencia a objeto no establecida como instancia de un objeto.
    Stack:    en Intersect.Editor.Forms.Editors.Quest.QuestTaskEditor.btnEditTaskEvent_Click(Object sender, EventArgs e) en C:\TeamCity\buildAgent\work\40dc5d27074313da\Intersect.Editor\Forms\Editors\Quest\Quest_TaskEditor.cs:línea 171
   en System.Windows.Forms.Control.OnClick(EventArgs e)
   en System.Windows.Forms.Button.OnClick(EventArgs e)
   en System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   en DarkUI.Controls.DarkButton.OnMouseUp(MouseEventArgs e)
   en System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   en System.Windows.Forms.Control.WndProc(Message& m)
   en System.Windows.Forms.ButtonBase.WndProc(Message& m)
   en System.Windows.Forms.Button.WndProc(Message& m)
   en System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

--------------------------------------------------------------------------------

**Operating System:**
Windows 10 64 bits

**Additional context**

**Comment by Kamusvalenzuela** [comment]
Extra: If you touch the "Edit task completion event" button and save the event window totally clean works fine after
But if you never touch the "Edit task completion event" button when you add the task and close it, the error will appear ever

**Comment by Cheshire92** [comment]
Yeah, see #915 as there is some discussion regarding the cause and fix there.
