### ISSUE TITLE
Dash Type Skill won't show tiles quantity

### ISSUE THREAD

**Issue by pedroolyntho** [AscensionGameDev/Intersect-Engine#921]
**Describe the bug**
"Dash" skill type won't show up how many tiles I want it to dash, but the skill works (it says "DASH" when I use it, just doesn't go anywhere, he stays at the same place)

**Version Encountered**

0.7.0.126-beta-prerelease

**To Reproduce**

**Expected behavior**
I wish the quantity of dash tiles would appear.

**Screenshots**
https://s3.us-east-2.amazonaws.com/ascensiongamedev/filehost/72dd501bb79368312266d0cd252843b7.png

**Logs**
If there are error logs please attach them below.

**Operating System:**
Windows

**Additional context**

**Comment by pedroolyntho** [comment]
Well, forgot to say.
If someone finds the same issue, just go to frmSpell.Designer.cs (Editor), and change "lblRange" and "scrlRange" Ys. 
They are up but behind Collision group. You should higher the number of the Y for them to appear.

**Comment by Cheshire92** [comment]
Since this isn't ACTUALLY resolved and you just fixed it for yourself I'm re-opening this.
