### ISSUE TITLE
Target influencing projectile

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#940]
**Describe the bug**
If the map is safe, you cannot fire projectiles if you click on a player (put the player on target)

**Version Encountered**
0.7.0.126

**To Reproduce**
1. Make a projectile and safe map
2. put other player in map
3. select that player and try fire a projectile

**Expected behavior**
![image](https://user-images.githubusercontent.com/63019821/133623445-4c04a11c-57bf-45da-b275-32741a6ec54a.png)
Target should not influence projectile shooting, on the safe map just do not cause damage

**Screenshots**

**Logs**
If there are error logs please attach them below.

**Operating System:**
Windows

**Additional context**

**Comment by Arufonsu** [comment]
There's a way to do this, it involves to move the "isSafe" check that's present around the targeting code, down to the part where you actually *attack*. if the map is not safe, only then there will be a damage output. This would allow the ability to even shot to targets (while still avoiding stealthed ones), while preventing the damage output when required.
i can try opening up a PR for this one in the following weeks, unless someone else tackles it down.
may be worth to mention that, moving the check over to the attack handler, may not be what everyone actually wants as behaviour? we may need more opinions on this one, in the other hand, we could simply create an option that toggles whether the dev wants to check for safe areas when targeting, or when attacking is about to do it's thing (attack).
