### ISSUE TITLE
[Development Build] Spell editor does not save spells

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#948]
**Describe the bug**
Spell editor does not save spells on this area
![image](https://user-images.githubusercontent.com/63019821/136830540-b89133a4-30c0-4724-a48d-0e466730d371.png)
above this area, works fine.

**Version Encountered**
Latest development version? I don't know the number

**To Reproduce**
Clone to source from 0
Compile the pre-release version and the dev too
Make spells and put values on combat area, any area
In the pre-release version it works, in the dev it doesn't

**Expected behavior**
Save all correctly

**Screenshots**

**Logs**
If there are error logs please attach them below.

**Operating System:**
Windows

**Additional context**

**Comment by Cheshire92** [comment]
Strange, assuming this is somehow related to #942
I don't remember doing anything that would cause this but perhaps the methods behind the inputs have become unlinked somehow?
