### ISSUE TITLE
Remove Party Invite Range

### ISSUE THREAD

**Issue by Cheshire92** [AscensionGameDev/Intersect-Engine#962]
**Is your feature request related to a problem? Please describe.**
I honestly find the limitation on party invites baffling, why would it matter whether someone is nearby or not?
In most games you can simply invite people to a party whenever and wherever you are.

**Describe the solution you'd like**
Remove the distance limitation to party invites, it does not fit in a modern game.

**Comment by WeylonSantana** [comment]
@Cheshire92 What about the maximum number of members in the party?  This value can already be changed to be able to change the amount of members?
I remember you had an implementation like that, and there was a revert.

**Comment by Arufonsu** [comment]
i agree with you but, what about devs that wish to keep it restricted?
they could still refer to this PR to see what's been changed, and in the other hand, the restriction could be changed to work with a server side boolean that toggles it on/off perhaps (?), something like "RestrictPartyInviteRange: true/false".

**Comment by Cheshire92** [comment]
Sorry, normally I agree with options but anyone that wants this is detached from reality and probably shouldn't be making a multiplayer game. You'd want to keep playing together with other people easy and convenient, this option is the exact opposite of that. 

It'll also make no sense to have this limit when you can invite people by typing in their name or clicking them in the chatbox like I'm planning to do.

**Comment by WeylonSantana** [comment]
@Arufonsu Usually parties are formed with your friends, so instinctively you will want to open the friends window and invite them there, this option would restrict that and in addition, people who don't know each other and met in the game and then ask to party. In this case the distance limit would not influence either, as they would be close to each other. Then, it is an option that has no function and restricts real friends to being on the same map.

I know a game that even looks for all parties formed on the server and if there is space in them and where map most of the members are, so if it's a public party you can join, no matter where you are, as long as you are on the same server, then I think removing this option here is a good step.

**Comment by Arufonsu** [comment]
> 
> It'll also make no sense to have this limit when you can invite people by typing in their name or clicking them in the chatbox like I'm planning to do.

Loving this concept already, and yeah, removing the restriction in such cases makes sense.

> 
> You'd want to keep playing together with other people easy and convenient, this option is the exact opposite of that.

Like i said, **i do agree with you on removing this restriction**, but then, i dunno if we can judge what a dev wants and not on their project, anyway, if anyone wants this restriction back to their repo for some reason, they may check up this conversation and the commits from this PR.

> 
> @Arufonsu Usually parties are formed with your friends, so instinctively you will want to open the friends window and invite them there, this option would restrict that and in addition, people who don't know each other and met in the game and then ask to party. In this case the distance limit would not influence either, as they would be close to each other. Then, it is an option that has no function and restricts real friends to being on the same map.

Yeah, makes sense.

> I know a game that even looks for all parties formed on the server and if there is space in them and where map most of the members are, so if it's a public party you can join, no matter where you are, as long as you are on the same server, then I think removing this option here is a good step.

This feels like something interesting to have one day tbh, a "Party Search" function, which looks up for formed parties.
For something like this, we might need to store parties with IDs in a db, and allow users to name them after something, who knows, to eventully expand such thing with password restricted private parties and more!
