### ISSUE TITLE
Standardization of DescWindows

### ISSUE THREAD

**Issue by WeylonSantana** [AscensionGameDev/Intersect-Engine#965]
**Is your feature request related to a problem? Please describe.**
They're not standardized, and they don't show everything a developer might want
**good points** - ItemDescWindow
1. When you have a value in status + a value of % shows in the window like "5 + 10%" for example.

**bad points** - ItemDescWindow
1. When an item is not buffed or debuffed, it shows everything the same way.

**good points** - SpellDescWindow
1. When a spell doesn't buff or debuff a status, it doesn't show for example
"attack: +10"
"speed: -5"
(does not show the other statuses)

**bad points** - SpellDescWindow
1. When an item buffs or debuffs the % + stattus, it doesn't show the same way as in ItemDescWindow.

**bad points** of both
1. When item/spell gives ONLY percentage it does not show, (in spell still show 0 in status)
2. It doesn't show values that we might want to show like status scaling, amount scaling, and critical
(we often have to type in the item description the status that scale, the percentage, or percentage of critical)

**Describe the solution you'd like**
We need something that standardizes both windows, I think server options like:

DescWindowOptions: {
   ShowEmptyStatus: false,
   ShowCriticalChance: true,
   ShowCriticalMultiplier: false,
   ShowScalingStatus: true,
   ShowScalingAmount: true,
}

**Additional context**
so far i did this:

items
![image](https://user-images.githubusercontent.com/63019821/137624637-c59b18cd-f9a9-4e74-908c-69b7cbc98e46.png)
![image](https://user-images.githubusercontent.com/63019821/137624641-3859c103-a2a3-4231-88e8-c1c99db2e730.png)

spells
![image](https://user-images.githubusercontent.com/63019821/137624662-27f025c1-53e6-4ad1-b270-6c4031093488.png)
![image](https://user-images.githubusercontent.com/63019821/137624668-7a02e14b-a3cd-406c-844a-d3a7b10b7a69.png)

but I did it in a non-optional way, I'm going to learn a little about strings and server configuration to create this pr
I accept any thoughts and considerations

**Comment by WeylonSantana** [comment]
@Cheshire92 All these ideas are incredible, I hadn't thought about it yet.

> They're not very informative because of the amount of garbage information and could use some new formatting as there is a lot of wasted space.

I also agree with that, I'm going to use this base that you sent for the item that doesn't have the expanded desc window
In the way you put it in your draft image, would it be a good idea to continue using two windows? (descwindow and descwindowexpanded) Or would just one solve everything?

> Also to potentially include the options like CanDrop, CanBank etc.

good one, I believe it should be entered as text, so it can be multi-language.

> Along with this, I would like to propose adding the spell tooltip of the spell taught by an item alongside the item tooltip if the item teaches the player a spell.

About this I don't know if it's within the scope of my knowledge, but I'll try to find it, if I can't, I'll ask for help with it, As for the rest I believe I can do it.

Should I continue with the server options idea so that it's the dev's option to choose what to show or not?

**Comment by Cheshire92** [comment]
Oh, I'm not sure this is something easy to do at all and will likely require a complete rewrite of how the tooltip is constructed I fear.

I drew up this as a quick concept for what I was thinking about:
![Image](https://s3.us-east-2.amazonaws.com/ascensiongamedev/filehost/dc1f55ef746ade5aefc39f32f13f3718.png)

**Comment by WeylonSantana** [comment]
Okay haha, but what did you think of the idea of just changing the name color instead of adding a new element?

**Comment by Arufonsu** [comment]
> 
> **bad points** - ItemDescWindow
> 
>     1. When an item is not buffed or debuffed, it shows everything the same way.
> 

So you decided to open an issue for this one 😄 
going to leave these here, since we previously chatted about this in discord, and i believe that this is worth to mention:

- A patch with a small change, that allows it to hide stats that aren't buffed or debuffed (skips when stats Equals(0) ), if there's plans to change the item's tooltip, this should probably be considered as well.
[Skips_0_stats_strings_onItems.zip](https://github.com/AscensionGameDev/Intersect-Engine/files/7360439/Skips_0_stats_strings_onItems.zip)
![imagen](https://user-images.githubusercontent.com/17498701/137636885-58c10aef-6a92-42fa-90e6-f0cf530bf463.png)
- Something related to this has already been requested before, might be good to have it linked here as well. 
( #886 )

**Comment by WeylonSantana** [comment]
I think this would be a lot more complicated, but not impossible, but cheshire decided to take this one, luckily for us, you will have to be good at persuasion there haha

I would prefer there to be a change in the status color, but thinking that this would make the window very colorful, and also the colors would have to be placed in the server config aand etc., very laborious, your option is much better, if not entered, after this update you could put
